### ISSUE TITLE
Install bug

### ISSUE THREAD

**Issue by sreekrishnapandi** [intrig-unicamp/mininet-wifi#1]
Hi! Cheers on the good work!
I just wanted to bring it to your attention that commits on Aug 21 seem to introduce errors in the installation. 
> cd: iw: No such directory 
in line 147: util/install.sh

**Comment by ramonfontes** [comment]
Hi,

Thank you for contacting us. Which version do you have? Could you clone the latest version 1.0rc1? I guess it is working.

**Comment by sreekrishnapandi** [comment]
Yes. I am using the latest version. I am trying to install it in a vanilla ubuntu VM. The installation works fine for the versions upto v0.98. 
However for the latest ones, it seems that the install script is in a different directory while it does `cd` . 
I get the following error thrown:
>libnl-dev is already the newest version.
>0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
>util/install.sh: line 552: cd: iw: No such file or directory

**Comment by sreekrishnapandi** [comment]
Note: I am not using the VM image provided in the README.

**Comment by ramonfontes** [comment]
Very very strange. I've implemented a new feature from this latest version which allows you set up position of nodes also using iw, but iw directory is there. Did you use util/install.sh -Wnfv? I pushed some new changes. I hope you can succeed right now.

**Comment by sreekrishnapandi** [comment]
I figured the problem. It was a result of using a Virtual machine manager (vagrant) to automate the process by installing the miinet-wifi as a part of the init script. It confuses with the `cd` command. 
Sorry for the false alarm.

**Comment by ramonfontes** [comment]
No problem. In fact there was a problem if you tried util/install.sh instead of util/install.sh -Wnvf which was fixed. Thank you so much!
