### ISSUE TITLE
MAC addresses are being overriden when using adhoc networks

### ISSUE THREAD

**Issue by patgrosse** [intrig-unicamp/mininet-wifi#10]
I used this simple example to set the MAC addresses of two stations. The MAC address is replaced by a generated one, and no `hw ether` command is executed.

```python
#!/usr/bin/python

from mininet.net import Mininet
from mininet.cli import CLI
from mininet.log import setLogLevel
from mininet.node import Node


def topology():
  print "*** Creating network"
  net = Mininet()
  print "*** Creating stationms"
  sta1 = net.addStation('sta1', mac='00:00:00:00:00:02')
  sta2 = net.addStation('sta2', mac='00:00:00:00:00:03')
  print "*** Adding stations to adhoc"
  net.addHoc(sta1)
  net.addHoc(sta2)
  print "*** Starting network"
  net.start()
  print "*** Running CLI"
  CLI(net)
  print "*** Stopping network"
  net.stop()

if(__name__ == "__main__"):
  setLogLevel("debug")
  topology()
```

After the network creation I used `iw dev staX-wlan0 info` to inspect the MAC address. Even in the `staX.params` I can see the generated one.

**Comment by ramonfontes** [comment]
Fixed in https://github.com/intrig-unicamp/mininet-wifi/commit/84afbb2c06b84694a1ca4ed1a8ff444d36510591

**Comment by ramonfontes** [comment]
I just improved the code in https://github.com/intrig-unicamp/mininet-wifi/commit/972a0c382509cb0630b230cfa901f20615b5134f

**Comment by patgrosse** [comment]
Works perfectly, thanks!
