### ISSUE TITLE
A problem of node mobility!

### ISSUE THREAD

**Issue by iamxg** [intrig-unicamp/mininet-wifi#100]
Hi, Ramon
Nodes still can communication even if a node isn't in communication range of other nodes, when I ran examples adhoc.py and position.py. I don't know why and how to resolve.
![image](https://user-images.githubusercontent.com/30093996/29618951-4aafe0ac-87df-11e7-9752-832dc2c2ab00.png)

Best Regards,
Xian

**Comment by ramonfontes** [comment]
Hi Guo,

Could you share your code?

**Comment by iamxg** [comment]
I don't modify any code in examples. I only specify new location by using 'py sta3.setPosition()'.

**Comment by ramonfontes** [comment]
I just tried examples/position.py setting up the position of sta1 to '80,20,0' and it worked as expected. I couldn't observe any problem.

**Comment by iamxg** [comment]
sta1 = net.addStation('sta1', mac='00:00:00:00:00:02', ip='10.0.0.1/8', position='10,20,0')
    sta2 = net.addStation('sta2', mac='00:00:00:00:00:03', ip='10.0.0.2/8', position='10,30,0')
    sta3 = net.addStation('sta3', mac='00:00:00:00:00:04', ip='10.0.0.3/8', position='80,10,0')

**Comment by iamxg** [comment]
I am very sorry, I forget that I added sta3 in position.py.

**Comment by ramonfontes** [comment]
What about h3?? Did you change its ip address??

**Comment by iamxg** [comment]
Do you mean that ip of "sta3"? sta3's ip is ip='10.0.0.3/8'

**Comment by ramonfontes** [comment]
I meant h3. If you're using position.py, you can see h3 there.

**Comment by ramonfontes** [comment]
Oops.. h1!

Sent from my android

On 23 Aug 2017 11:45, "Ramon Fontes" <ramonreisfontes@gmail.com> wrote:

I meant h3. If you're using position.py, you can see h3 there.

**Comment by iamxg** [comment]
I understand. h1's ip is the same as sta3'ip. So, there is erro

**Comment by iamxg** [comment]
Thanks a lot! I am very sorry!

**Comment by iamxg** [comment]
Thank you very much! Have a good day!
