### ISSUE TITLE
Stations in ad hoc mode can ping each other even if they are out of range

### ISSUE THREAD

**Issue by iamxg** [intrig-unicamp/mininet-wifi#103]
I have added stations in ad hoc mode. (No access points).
And then I added a mobility model. But I discover that stations can still ping each other when they are out of range.

        for station in net.stations:
            net.addHoc(station, ssid='adhocNet', mode='g')

        #Xian: add the following lines for adhoc network
        net.plotGraph(max_x=100, max_y=100)
        net.propagationModel('friisPropagationLossModel', sL=2)
        net.seed(random.randint(0, 100))
        net.startMobility(startTime=0, model='RandomWayPoint', max_x=100, max_y=100, min_v=0.5, max_v=0.8)

How can I resolve this?

Thank you for your help.

**Comment by ramonfontes** [comment]
Is wmediumd enabled? Please enable wmediumd and interference.

**Comment by iamxg** [comment]
Okay I will try to do that. Is this the relevant example: https://github.com/intrig-unicamp/mininet-wifi/blob/8c43db940081d35cb57bfcbad5058324a674df2d/examples/wmediumd_mobility.py?

**Comment by ramonfontes** [comment]
That code isn't about adhoc. You just have to enable wmediumd and
interference in your code.

**Comment by iamxg** [comment]
Hi Ramon,
I'd like to simulate a mobile ad hoc network. I enable wmediumd and interference. But stations can still ping each other when they are out of range. Please you help me check the code. Thanks a lot.
def topology():
    "Create a network."
    net = Mininet(controller=Controller, enable_wmediumd=True, enable_interference=True)
    print "*** Creating nodes"
    sta1 = net.addStation('sta1', mac='02:00:00:00:00:01', range='20')
    sta2 = net.addStation('sta2', mac='02:00:00:00:00:02', range='20')
    sta3 = net.addStation('sta3', mac='02:00:00:00:00:03', range='20')
    print "*** Configuring wifi nodes"
    net.configureWifiNodes()

    print "*** Creating links"
    net.addHoc(sta1, ssid='adhocNet', mode='g')
    net.addHoc(sta2, ssid='adhocNet', mode='g')
    net.addHoc(sta3, ssid='adhocNet', mode='g')

    print "*** Starting network"
    net.build()
    net.plotGraph(max_x=100, max_y=100)
    net.propagationModel('friisPropagationLossModel', sL=2)
    net.seed(random.randint(0, 100))
    net.startMobility(startTime=0, model='RandomWayPoint', max_x=100, max_y=100, min_v=0.5, max_v=0.8)

    print "*** Running CLI"
    CLI(net)

    print "*** Stopping network"
    net.stop()

**Comment by iamxg** [comment]
![image](https://user-images.githubusercontent.com/30093996/29745196-ea84f30a-8a79-11e7-8d5c-bd3122bcaab9.png)

**Comment by ramonfontes** [comment]
Hi,

Please don't set the range when wmediumd is enabled. It's calculated by the
propagation model. Also, you have to set the propagation model just before
net.configureWifiNodes().

2017-08-26 18:15 GMT-03:00 Xian Guo <notifications@github.com>:

**Comment by iamxg** [comment]
def topology():
    "Create a network."
    net = Mininet(controller=Controller, enable_wmediumd=True, enable_interference=True)
    print "*** Creating nodes"
    sta1 = net.addStation('sta1', mac='02:00:00:00:00:01')
    sta2 = net.addStation('sta2', mac='02:00:00:00:00:02')
    sta3 = net.addStation('sta3', mac='02:00:00:00:00:03')
    print "*** Configuring wifi nodes"
    net.propagationModel('friisPropagationLossModel', sL=2)
    net.configureWifiNodes()

    print "*** Creating links"
    net.addHoc(sta1, ssid='adhocNet', mode='g')
    net.addHoc(sta2, ssid='adhocNet', mode='g')
    net.addHoc(sta3, ssid='adhocNet', mode='g')

    print "*** Starting network"
    net.build()
    net.plotGraph(max_x=100, max_y=100)
    net.seed(random.randint(0, 100))
    net.startMobility(startTime=0, model='RandomWayPoint', max_x=100, max_y=100, min_v=0.5, max_v=0.8)

    print "*** Running CLI"
    CLI(net)

    print "*** Stopping network"
    net.stop()

**Comment by iamxg** [comment]
I modify the codes, but the result is same.

**Comment by ramonfontes** [comment]
Please try logdistance instead of friss
(e.g. net.propagationModel("logDistancePropagationLossModel", exp=4.5)).

I just found a problem with friss.

2017-08-26 18:26 GMT-03:00 Xian Guo <notifications@github.com>:

**Comment by iamxg** [comment]
do this problem is relative with the propagation model? The running result is expected when I replaced the propagation model.

    net.propagationModel("logDistancePropagationLossModel", exp=5)

 
![screenshot from 2017-08-26 16-54-58](https://user-images.githubusercontent.com/30093996/29745411-56a9beb2-8a7f-11e7-9c86-f7f0817de2a3.png)

**Comment by iamxg** [comment]
Ok, Thank you very much for your hard work!

**Comment by iamxg** [comment]
Hi Ramon,
Good afternoon!
In ad hoc mode, will the middle nodes automatically relay the received packet? Do it need to configure?

**Comment by ramonfontes** [comment]
No. You have to configure a routing protocol. Whatever you want (even
static routing).

**Comment by iamxg** [comment]
Ok, thank you for replying timely. I will try to do it.

**Comment by ramonfontes** [comment]
You can find further information in the mailing list and you can use it for
doubts/questions.

**Comment by iamxg** [comment]
Ok, Thank you!

**Comment by Varadarajreddy** [comment]
Hi, 

I am trying to ping the stations and UDPS server but I am unable to ping them. When I try to ping the stations I am getting the message like Destination Host is Unreachable. can anyone help me to achieve the ping between the stations? 
Below is my code for your reference. Thanks.

#!/usr/bin/python
import sys
from mininet.node import Controller
from mininet.log import setLogLevel, info
from mn_wifi.cli import CLI_wifi
from mn_wifi.net import Mininet_wifi

def topology(plot):
	"Create a network."
	net=Mininet_wifi(controller=Controller)
	
	info("*** Creating nodes\n")
    	#TODO add stations and  access points
    	STA1 = net.addStation('STA1', passwd='19056149', encrypt='wpa2', mac='00:00:00:10:11:08', ip='147.192.10.2/24', position ='50,25,0', range=30, min_v=5, max_v=5, antennaheight='3', antennagain='7', ipv6='fe80::10')
    	STA2 = net.addStation('STA2', passwd='19056149', encrypt='wpa2', mac='00:00:00:10:11:09', ip='147.192.10.3/24', position ='50,25,0', range=30, min_v=5, max_v=10, antennaheight='3', antennagain='7', ipv6='fe80::11')
    	STA3 = net.addStation('STA3', passwd='19056149', encrypt='wpa2', mac='00:00:00:10:11:10', ip='147.192.10.4/24', position ='50,140,0', range=30, min_v=2, max_v=7, antennaheight='3', antennagain='7', ipv6='fe80::12')
	UDPS = net.addStation('UDPS', mac='00:00:00:10:01:01', ip='147.192.10.1/24', position ='50,140,0', range='30', antennaheight='3', antennagain='7',) 

	AP1 = net.addAccessPoint('AP1', mac='00:00:00:00:10:02', ssid='ssid-ap1', passwd='19056149', encrypt='wpa2', mode='a', channel='1', failMode="standalone", position='50,75,0',  range=25, Model='DI524')
    	AP2 = net.addAccessPoint('AP2', mac='00:00:00:00:10:03', ssid='ssid-ap2', passwd='19056149', encrypt='wpa2', mode='g', channel='6', failMode="standalone", position='50,125,0', range=25, Model='DI524')
    	AP3 = net.addAccessPoint('AP3', mac='00:00:00:00:10:04', ssid='ssid-ap3', passwd='19056149', encrypt='wpa2', mode='b', channel='2', failMode="standalone", position='100,125,0', range=25, Model='DI524')
    	AP4 = net.addAccessPoint('AP4', mac='00:00:00:00:10:05', ssid='ssid-ap4', passwd='19056149', encrypt='wpa2', mode='g', channel='3', failMode="standalone", position='150,125,0', range=25, Model='DI524')
    	AP5 = net.addAccessPoint('AP5', mac='00:00:00:00:10:06', ssid='ssid-ap5', passwd='19056149', encrypt='wpa2', mode='b', channel='3', failMode="standalone", position='150,75,0',  range=25, Model='DI524')
    	AP6 = net.addAccessPoint('AP6', mac='00:00:00:00:10:07', ssid='ssid-ap6', passwd='19056149', encrypt='wpa2', mode='g', channel='3', failMode="standalone", position='200,75,0', range=25, Model='DI524')

	c1=net.addController('c1')

	net.setPropagationModel(model="longDistance", exp=5)

	info("*** Configuring wifi nodes\n")
	net.configureWifiNodes()

	net.addLink(AP1,AP2, bw=100, delay='3ms', loss=5)
	net.addLink(AP2,AP3, bw=100, delay='3ms', loss=5)
        net.addLink(AP3,AP4, bw=100, delay='3ms', loss=5)
        net.addLink(AP3,AP5, bw=100, delay='3ms', loss=5)
        net.addLink(AP5,AP6, bw=100, delay='3ms', loss=5)
		
	
	net.plotGraph(max_x=600, max_y=600)

	net.startMobility(time=0)
        net.mobility(STA1,'start', time=10,  position='50,25,0')
        net.mobility(STA2,'start', time=15,  position='50,25,0')
        net.mobility(STA1,'stop',  time=20,  position='200,75,0')
        net.mobility(STA2,'stop',  time=21,  position='150,125,0')
        net.mobility(STA3,'start', time=16,  position='50,25,0')
        net.mobility(STA3,'stop',  time=22,  position='100,125,0')
        net.stopMobility(time=30)
	
	info("*** Starting network\n")
   	net.build()
    	#TODO start ap1
	c1.start()
    	AP1.start([c1])
    	AP2.start([c1])
    	AP3.start([c1])
    	AP4.start([c1])
    	AP5.start([c1])
    	AP6.start([c1])

	info("*** Running CLI\n")
    	CLI_wifi(net)

    	info("*** Stopping network\n")
    	net.stop()


if __name__ == '__main__':
    setLogLevel('info')
    plot = False if '-p' in sys.argv else True 
    topology(plot)

**Comment by ramonfontes** [comment]
Which troubleshooting steps did you try? Can you elaborate your question with technical details in terms of network aspects? By the way, you are working with adhoc and without wmediumd? Did you calibrate the propagation model in order to meet the signal range requirements?

**Comment by Varadarajreddy** [comment]
Actually, i am a student and I am absolutely new to new mininet. To answer your question I just tried with ping command and traceroute(however it did not work in mininet it was showing that command was not found) and I tried iwconfig(When I run this command it showed that ESSID: off/any, access point: is not associated. 

mininet-wifi> STA1 iwconfig
STA1-wlan0  IEEE 802.11  ESSID:off/any  
          Mode:Managed  Access Point: Not-Associated   Tx-Power=20 dBm   
          Retry short limit:7   RTS thr:off   Fragment thr:off
          Encryption key:off
          Power Management:on
          
lo        no wireless extensions.

**Comment by Varadarajreddy** [comment]
![Screenshot from 2021-12-02 18-51-28](https://user-images.githubusercontent.com/86453166/144484873-1d937a07-03c5-41a7-b804-3d309089d1c1.png)

**Comment by Varadarajreddy** [comment]
I have not configured the Adhoc nodes here. I just configured the  mobile nodes.

**Comment by ramonfontes** [comment]
Arw you new computer networking too?? You may want to know that iwconfig does not work with adhoc. Anyway, you must enable wmediumd and make sure that the signal range you have set work well with the propagation model.

**Comment by ramonfontes** [comment]
What??? What is the relationship between your question and this thread???

**Comment by Varadarajreddy** [comment]
oh, I am very sorry actually I should have raised a new question instead of posting in this thread. I sincerely apologise for any inconvenience.
