### ISSUE TITLE
Support for CPULimitedHost

### ISSUE THREAD

**Issue by floppydrive6** [intrig-unicamp/mininet-wifi#104]
Hi,
I have noticed when running sample script w/ CPULimitedHost from: [mininet](https://raw.githubusercontent.com/mininet/mininet/master/examples/cpu.py) I get an error: `  File "cpu.py", line 105, in <module>
    out = bwtest(limits)
  File "cpu.py", line 76, in bwtest
    net.stop()
  File "/usr/local/lib/python2.7/dist-packages/mininet-2.1.post2-py2.7.egg/mininet/net.py", line 1039, in stop
    host.terminate()
  File "/usr/local/lib/python2.7/dist-packages/mininet-2.1.post2-py2.7.egg/mininet/node.py", line 450, in terminate
    self.cleanup()
  File "/usr/local/lib/python2.7/dist-packages/mininet-2.1.post2-py2.7.egg/mininet/node.py", line 937, in cleanup
    retry(retries=3, delaySecs=1, fn=self.cgroupDel)
  File "/usr/local/lib/python2.7/dist-packages/mininet-2.1.post2-py2.7.egg/mininet/util.py", line 209, in retry
    if args[1].type != 'accessPoint':
IndexError: tuple index out of range
`
I have look into mininet-wifi source code and there is a class CPULimitedHost with its cleanup method: [here](https://github.com/intrig-unicamp/mininet-wifi/blob/1ebe5afc407d70d104aed5be0986c1ba33fa8234/mininet/node.py#L867)
Is mininet-wifi supporting CPULimitedHost?
I am asking because I am playing with my configured mptcp kernel w/ several topologies and I want to use some CPULimited hosts in them.
Regards,
Grzegorz

**Comment by floppydrive6** [comment]
I've just checked it the same example in `mininet-vm`and it works fine, so I suppose there could be a problem with cleanup CPULimitedHost in `mininet-wifi`.
Regards,
Grzegorz

**Comment by ramonfontes** [comment]
Hi,

I think that line isn't necessary anymore. Could you try it again after this
commit
<https://github.com/intrig-unicamp/mininet-wifi/commit/e60bb5749aad0f66776d1834e509a8f11d92cfc7#diff-261a6a76f3216f4d7e4d7cdacb43820d>
?

2017-08-28 21:18 GMT-03:00 floppydrive6 <notifications@github.com>:

**Comment by floppydrive6** [comment]
Hi, sure, give me a moment

**Comment by floppydrive6** [comment]
@ramonfontes as expected, it seems to work now.
Thanks!
Grzegorz

**Comment by ramonfontes** [comment]
Cool! Thanks!

**Comment by ramonfontes** [comment]
I have noticed a problem with UserAP after the last commit. Could you try this [other one](https://github.com/intrig-unicamp/mininet-wifi/commit/30eb5ad85f2387d2169601b96280876d8ceffd0b)?
