### ISSUE TITLE
Throughput drastic decreasing

### ISSUE THREAD

**Issue by ines-s-santos** [intrig-unicamp/mininet-wifi#106]
Hi!

I am measuring the TCP throughput in wireless network with iperf with a access point range of 250 m, and testing the dependency with the distance to the access point. And I don't understand why the throughput decreases until range/2 (in this position the throughput is drastically low) , then increases and starts to decrease with distance again. Can anyone help me with this? Can I solve this ?

**Comment by ramonfontes** [comment]
Hi Ines,

Is wmediumd enabled? Have u checked the signal table? Which behaviour did
you expect? And why?

Sent from my android

On 4 Sep 2017 06:52, "ines-s-santos" <notifications@github.com> wrote:

Hi!

I am measuring the TCP throughput in wireless network with iperf with a
access point range of 250 m, and testing the dependency with the distance
to the access point. And I don't understand why the throughput decreases
until range/2 (in this position the throughput is drastically low) , then
increases and starts to decrease with distance again. Can anyone help me
with this? Can I solve this ?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/intrig-unicamp/mininet-wifi/issues/106>, or mute the
thread

**Comment by ines-s-santos** [comment]
I did not used wmediumd before, but I tested with it now and the values are now different but still weird, does not has the drastic decrease but the throughput value is almost constant in each position of the station. 
I was expecting a decrease of throughput with distance.Because is what happens in typical mobile networks that also uses TCP and UDP protocols.

**Comment by ramonfontes** [comment]
Do you mean, linear? Could you point me any reference?

**Comment by ines-s-santos** [comment]
Not linearly I think.
Is presented in this paper: 
https://www.researchgate.net/publication/309327770_Transport_protocols_behaviour_study_in_evolving_mobile_networks

**Comment by ramonfontes** [comment]
I think you should compare with wifi, not LTE. We didn't designed a model
for LTE.

**Comment by ramonfontes** [comment]
Btw, as I told you before, the formulas are public and you can do whatever
you want in order to reproduce LTE.

Ps. I will appreciate if u send this type of questions to our mailing list
instead of mark them as issues on github.

**Comment by ines-s-santos** [comment]
But even for Wi-Fi, searching in Google photos for Wi-Fi throughput vs distance, the graphs present a decreasing behavior. 

Like : http://wi-fi.na.by/mimodraft.files/image011.jpg.

**Comment by ines-s-santos** [comment]
Okay, I am sorry. I thought this was the right place to make my questions. I'll use the mailing list next time.

Sorry again.

**Comment by ramonfontes** [comment]
Those formulas are results of experiments we conducted in an anechoic
wireless testbed, called R2lab. We didn't have a good enough and feasible
environment to do the same in larger distances.

You can find more information at
https://academic.oup.com/comjnl/article/3093135

**Comment by ines-s-santos** [comment]
The formula that you are talking about is this one: rate = costumbw*(1.1** -dist) ? Is this formula that influences the iperf values ?

Because this is the behavior that I am expecting.

**Comment by ramonfontes** [comment]
Yes.

2017-09-04 10:26 GMT-03:00 ines-s-santos <notifications@github.com>:

**Comment by ines-s-santos** [comment]
So how can I get a lower throughput when my station is 75 m away from the ap, than when it is at 100 m or more ? Can I send you by email my code to see if I have a mistake or why does this happen?

The test is running the iperf between the server (h1) and the clients (ue1, ue3...=sta1, sta3).

**Comment by ramonfontes** [comment]
There are many possibilities. You can change setBW() in
https://github.com/intrig-unicamp/mininet-wifi/blob/master/mininet/wifiLink.py#L88
and based on the distance you can use a different formula.

2017-09-04 11:06 GMT-03:00 ines-s-santos <notifications@github.com>:
