### ISSUE TITLE
Unable to detect RSSI change on radio interface in monitor mode

### ISSUE THREAD

**Issue by capablegh** [intrig-unicamp/mininet-wifi#11]
I have described the issue on [this Stackexchange post](http://stackoverflow.com/questions/40767703/mininet-wifi-radiotap-captured-rssi-not-varying-when-station-mobility-is-simula).  Are my expectations incorrect? I do not know if the Mininet-wifi authors watch any issues posted there. If you need I can duplicate it here.

**Comment by ramonfontes** [comment]
Answer available at http://stackoverflow.com/questions/40767703/mininet-wifi-radiotap-captured-rssi-not-varying-when-station-mobility-is-simula

**Comment by capablegh** [comment]
Thank you, the comments there were helpful!

**Comment by ramonfontes** [comment]
You're welcome! ;)
