### ISSUE TITLE
Multiple virtual ssid

### ISSUE THREAD

**Issue by shreyakupadhyay** [intrig-unicamp/mininet-wifi#117]
Referring to the [commit](https://github.com/intrig-unicamp/mininet-wifi/commit/e842ed733ee748bcb61cfac1e205f7fa345cb8d7), the code changed in the file forwardingBySSID.py is not allowing the network connections between stations and access point.

## Issue:
While scanning available SSIDs using the command on the station(sta1): 
```sh
$sudo iw dev sta1-wlan0 scan | grep ssid
```
The output below is displayed:
![Output](https://user-images.githubusercontent.com/9116745/31253200-91a46e5e-aa41-11e7-806d-c20df07b6deb.png)
There are extra characters that are getting added in each ssid name. Because of the format changed in the referred [commit](https://github.com/intrig-unicamp/mininet-wifi/commit/e842ed733ee748bcb61cfac1e205f7fa345cb8d7). While:
```sh
$ iwconfig | grep ESSID
```
shows that SSID assigned to sta1 is "ssid1" instead of any one of the ssid which is being displayed in the image. This issue is with the other stations too.

I tried changing the code for addAccessPoint inside net.py but it didn't work for me.  How can I go forward with this?

**Comment by ramonfontes** [comment]
Hi,

I think something is wrong here. Please see:

root@alpha-Inspiron:/home/alpha/mininet-wifi# iw dev sta1-wlan0 scan | grep
ssid
SSID: ssid
SSID: ssid1
SSID: ssid2
SSID: ssid3
SSID: ssid4


2017-10-05 18:52 GMT-03:00 Shreyak Upadhyay <notifications@github.com>:

**Comment by shreyakupadhyay** [comment]
I cloned the code again and compiled it. Running the script one more time, it worked. Thanks for your quick response.

**Comment by ramonfontes** [comment]
You're welcome.
