### ISSUE TITLE
interference between 2 or many APs in same frequency

### ISSUE THREAD

**Issue by hendrojio** [intrig-unicamp/mininet-wifi#134]
Hi, Mr. Ramon
I am in new with mininet-wifi, my research about interference of 2 or more AP in same frequency/channel  while their area/range was tangent (same area). An examples I built WLAN based _**wmediumd_interference.py**_ with 2 AP (APa & APb) with 2 STAs associated to each AP,  in the same time using _**iperf**_  I make traffic between 2 STAs in APa and 2 STAs in APb, I wish there will be an interference in WLAN known with a decrease traffic between STAs in each AP, but why each traffic do NOT change compared with 2 AP in non-overlapping channel? Can mininet-wifi simulate my WLAN topology?
Of course, wmediumd and interference and they work well in WLAN with 1 AP, but why not in 2 AP same channel.
![topowifi2](https://user-images.githubusercontent.com/30153509/32697033-5966e324-c7b9-11e7-9223-f0cae5f5f184.png)
STA1 n STA2 associated with AP1, STA11 n STA12 associated with AP2
  Could you give me some suggestion? Thanks a lot!

Best Regards,
Hendrojio

**Comment by ramonfontes** [comment]
Answered in the mailing list.

**Comment by hendrojio** [comment]
Yes, I do understand.
Thank you

**Comment by isilbolatbas** [comment]
Hi, Mr. Roman
can you send me the answer to this question, please?

**Comment by ramonfontes** [comment]
*Ramon :)

Well, Mininet-WiFi supports the _interference method_ provided by wmediumd - that is based on [CCA Threshold](https://github.com/ramonfontes/wmediumd/blob/mininet-wifi/wmediumd/wmediumd.c#L234). However, we [haven't implemented](https://github.com/intrig-unicamp/mininet-wifi/blob/master/TODO.md) any interference model yet.

**Comment by alic-antunez** [comment]
Hello Mr Ramon. Has an interference model or something similar been developed in which I can emulate interference from two APs by having the same channel?

**Comment by ramonfontes** [comment]
There is an interference model implemented in Wmediumd. I suggest you to take a look on that.

**Comment by Vedant0616** [comment]
Hello Mr Ramon. I have tried creating interference in same channel but still there is no packet drop. Can you suggest any changes that need to be done for introducing packet dropping?

**Comment by ramonfontes** [comment]
Closing due to no new interactions.
