### ISSUE TITLE
problem in Vanet 

### ISSUE THREAD

**Issue by iamxg** [intrig-unicamp/mininet-wifi#139]
Hi Ramon,
Good morning. 
I modified the codes according to [this commit](https://github.com/intrig-unicamp/mininet-wifi/commit/dd5adfb9b7786bba763f4c091f95466feec4d5d7) , But I find that car can associate with AP only if it is in AP's range when this program just starts. Car can't associate with AP when it enters an AP's range during running process. I don't know why. For example, car9 in the below figure.
![image](https://user-images.githubusercontent.com/30093996/33673778-60f0d5e2-da73-11e7-8457-f8644aa6a8d3.png)
 Xian Guo

**Comment by ramonfontes** [comment]
Could you run it in debug mode and send the output to me?

2017-12-06 14:05 GMT-03:00 Xian Guo <notifications@github.com>:

**Comment by iamxg** [comment]
Hi Ramon,
I am sorry that I am not familiar with debug. I copy part of output and email to you.
I still found that V2V and V2I both can work if I set AP's range=100 and car's range=50.
Thank you!
Xian Guo

**Comment by iamxg** [comment]
Hi Ramon,
I am sorry that I am not familiar with debug. I copied part of output and email to you.
I still found that V2V and V2I can both work if I set AP's range=50 and car's range=100.
Thank you!
Xian Guo

**Comment by ramonfontes** [comment]
What if you don't set the signal range?

2017-12-06 19:54 GMT-03:00 Xian Guo <notifications@github.com>:

**Comment by iamxg** [comment]
It seam that it can work if don't set the signal range.
![image](https://user-images.githubusercontent.com/30093996/33697566-39d2ee14-dacd-11e7-8d78-8f32431b486c.png)

**Comment by iamxg** [comment]
Besides, I hope that V2V communication can achieve by using carxSTA's wlan0 interface. It will occur the following error when I added function addHoc() on carsta. I check wlan=1 not 0. Could you let me know how to modify codes so that I can use ad hoc mode?
Thanks a lot!
Xian Guo

**Comment by iamxg** [comment]
Besides, I hope that V2V communication can achieve by using carxSTA's wlan0 interface. It will occur the following error when I added function addHoc() on carsta. I check wlan=1 not 0. Could you let me know how to modify codes so that I can use ad hoc mode?
Thanks a lot!
Xian Guo
![image](https://user-images.githubusercontent.com/30093996/33698195-95c08c9c-dad0-11e7-8a24-9ff1ecaf6504.png)

**Comment by ramonfontes** [comment]
It's already implemented
https://github.com/intrig-unicamp/mininet-wifi/blob/master/mininet/wifiNet.py#L1095

2017-12-07 0:58 GMT-03:00 Xian Guo <notifications@github.com>:

**Comment by iamxg** [comment]
Ok, Thank you very much. Just In this afternoon, I found that you update many codes. I download and compile it. But now, some codes before I tested can't run. I will test it further.
Best Regards,
Xian Guo

**Comment by ramonfontes** [comment]
Dear, was the problem resolved?

**Comment by iamxg** [comment]
Hi Ramon,
Sorry, I just saw your message. It still can't be resolved now. So, I set car's range=100 and AP's range=50. Such V2V and V2I both can work. 
Best Regards,
Xian

**Comment by iamxg** [comment]
Hi Ramon,
I'd like to test my codes. So I install my codes on another computer. System environment: Virtual Box, 16.4. But my modules always occur the following error. I don't know why. Could you help me?
Best Regards,
Xian Guo.
![image](https://user-images.githubusercontent.com/30093996/34699812-132e275a-f4a5-11e7-8011-690760e5f37f.png)

**Comment by ramonfontes** [comment]
Doesn't sudo mn -c solve the problem?

**Comment by iamxg** [comment]
Hi,

I tried this command but it didn't work. 


Xian G




-----Original Message-----

**Comment by ramonfontes** [comment]
Guo,

Are you using mininet-wifi?
