### ISSUE TITLE
Two network interfaces

### ISSUE THREAD

**Issue by tonetto** [intrig-unicamp/mininet-wifi#14]
Hi, first of all thanks for this great tool.

I am trying to simulate an offloading environment, where one station having two wireless interfaces is able to reach a single host from both paths. This station must be able to move following any of the already implemented mobility models, therefore there will be this intermittent connectivity from both interfaces. One access point could have a short range but good link quality, while a second ap a long range but poor quality connection.

So something like:
- host h1, running an http server, probably with two network interfaces
- station sta1, having two wireless interfaces
- ap1, connected to h1 with good quality, but short wifi range
- ap2, connected to h1 with poor quality, but long wifi range
- sta1 must move freely and as soon as any of the APs are in range, connect to them and be able to reach h1

For that I edited the wifiMobilityModel.py example, setting up two network interfaces on each node, each of them on a different subnet. (The main part of) My script looks like the following:

    print "*** Creating nodes"
    h1 = net.addHost( 'h1', ip='10.0.0.1/24' )
    sta1 = net.addStation( 'sta1', wlans=2, ip='10.0.0.2/24')
    ap1 = net.addAccessPoint( 'ap1', ssid= 'slow-ssid', mode= 'g', channel= '1', position='50,50,0', range=40 )
    ap2 = net.addAccessPoint( 'ap2', ssid= 'fast-ssid', mode= 'g', channel= '4', position='20,80,0', range=20 )
    c1 = net.addController( 'c1', controller=Controller )
    c2 = net.addController( 'c2', controller=Controller )

    print "*** Configuring wifi nodes"
    net.configureWifiNodes()

    print "*** Associating and Creating links"
    net.addLink(ap1, sta1)
    net.addLink(ap2, sta1)

    net.addLink(ap1, h1)
    net.addLink(ap2, h1)
    
    sta1.setIP('10.1.0.2/24', intf="sta1-wlan1")
    h1.setIP('10.1.0.1/24', intf="h1-eth1")

    print "*** Starting HTTP server on H1"
    h1.cmdPrint('python -m SimpleHTTPServer 80 &')

    print "*** Starting network"
    net.build()
    c1.start()
    c2.start()
    ap1.start( [c1] )
    ap2.start( [c2] )
    
    """uncomment to plot graph"""
    net.plotGraph(max_x=100, max_y=100)

    """association control"""
    net.associationControl('ssf')

    """Seed"""
    net.seed(20) 

    "*** Available models: RandomWalk, TruncatedLevyWalk, RandomDirection, RandomWayPoint, GaussMarkov, ReferencePoint, TimeVariantCommunity ***"
    net.startMobility(startTime=0, model='RandomDirection', max_x=100, max_y=100, min_v=0.5, max_v=0.8)

The issue I'm having is that once the station starts moving it often does not connect to any of the APs, even if they are in range. Another problem, but that's maybe not a real issue of the simulator, as the node moves around, I can't get it to always connect with the same interface to the same single AP. For example, as it moves, sta1-wlan0 can connect to ap1 or ap2, this way it would be tricky to always get connectivity between the station and the host through both paths (the good and the poor one).

Starting with a simple example, where the node sits in the overlapping area between the two APs, without moving, it works. As soon as I try to get it moving things get out of control. I would like to know if that's possible what can I do to have this scenario working.

Thanks in advance.

-- Leonardo

**Comment by tonetto** [comment]
Maybe an easy workaround would be to run a DHCP server connected to both APs, and as soon as the station would get a connection it would request a correct IP. It wouldn't matter which interface it would be using.

But I am not quite sure if this is possible at the moment and how to do that if so.

**Comment by ramonfontes** [comment]
Hi Leonardo,

2016-12-06 12:51 GMT-03:00 Leonardo Tonetto <notifications@github.com>:

> Hi, first of all thanks for this great tool.
>
> I am trying to simulate an offloading environment, where one station
> having two wireless interfaces is able to reach a single host from both
> paths. This station must be able to move following any of the already
> implemented mobility models, therefore there will be this intermittent
> connectivity from both interfaces. One access point could have a short
> range but good link quality, while a second ap a long range but poor
> quality connection.
>
> So something like:
>
>    - host h1, running an http server, probably with two network
>    interfaces You can use only one interface as well (why not?). Thus,
>    you have to change the topology to:
>
> h1 - s1 - ap2
        -         |
       ap3 --- sta1

>
>    -
>
>
>    - station sta1, having two wireless interfaces
>    - ap1, connected to h1 with good quality, but short wifi range
>    - ap2, connected to h1 with poor quality, but long wifi range
>    - sta1 must move freely and as soon as any of the APs are in range,
>    connect to them and be able to reach h1
>
> For that I edited the wifiMobilityModel.py example, setting up two network
> interfaces on each node, each of them on a different subnet. (The main part
> of) My script looks like the following:
>
> print "*** Creating nodes"
> h1 = net.addHost( 'h1', ip='10.0.0.1/24' )
> sta1 = net.addStation( 'sta1', wlans=2, ip='10.0.0.2/24')
> ap1 = net.addAccessPoint( 'ap1', ssid= 'slow-ssid', mode= 'g', channel= '1', position='50,50,0', range=40 )
> ap2 = net.addAccessPoint( 'ap2', ssid= 'fast-ssid', mode= 'g', channel= '4', position='20,80,0', range=20 )
> c1 = net.addController( 'c1', controller=Controller )
> c2 = net.addController( 'c2', controller=Controller )
>
> print "*** Configuring wifi nodes"
> net.configureWifiNodes()
>
> print "*** Associating and Creating links"
> net.addLink(ap1, sta1)
> net.addLink(ap2, sta1)
>
> net.addLink(ap1, h1)
> net.addLink(ap2, h1)
>
> sta1.setIP('10.1.0.2/24', intf="sta1-wlan1")
> h1.setIP('10.1.0.1/24', intf="h1-eth1")
>
> print "*** Starting HTTP server on H1"
> h1.cmdPrint('python -m SimpleHTTPServer 80 &')
>
> print "*** Starting network"
> net.build()
> c1.start()
> c2.start()
> ap1.start( [c1] )
> ap2.start( [c2] )
>
> """uncomment to plot graph"""
> net.plotGraph(max_x=100, max_y=100)
>
> """association control"""
> net.associationControl('ssf')
>
> """Seed"""
> net.seed(20)
>
> "*** Available models: RandomWalk, TruncatedLevyWalk, RandomDirection, RandomWayPoint, GaussMarkov, ReferencePoint, TimeVariantCommunity ***"
> net.startMobility(startTime=0, model='RandomDirection', max_x=100, max_y=100, min_v=0.5, max_v=0.8)
>
> The issue I'm having is that once the station starts moving it often does
> not connect to any of the APs, even if they are in range.
>
Could you share the full code? This is weird.


> Another problem, but that's maybe not a real issue with the simulator, as
> the node moves around, I can't get it to always connect with the same
> interface to the one single AP. For example sta1-wlan0 can connect to ap1
> or ap2, this way it would be tricky to get always get connectivity between
> the station and the host through both paths (the good and the poor one).
>
> Starting with a simple example, where the node sits in the overlapping
> area between the two APs, without moving, it works. As soon as I try to get
> it moving things get out of control. I would like to know if that's
> possible what can I do to have this scenario working.
>
Why don't you use bond interfaces? Please see a particular demo in demos/
allWirelessNetworksAroundUs.py

**Comment by ramonfontes** [comment]
Hello Leonardo,

Did you solve the problem? Did that demo worked for your purpose?

**Comment by tonetto** [comment]
Hi Ramon,

I didn't want to use bond. The idea behind this was that students would implement a protocol to use both interfaces and not use any existing solution (this was missing in my explanation).

The idea of using a switch and then have only one network interface in the host was also good. Thanks for that.

The issue I mentioned about not being able to associate was wrong. But I still see a behavior I believe is not correct with ping.

So, assuming the station has 2 interfaces and 2 IPs (10.0.0.1/24, 10.1.0.1/24), 4 APs (ap1-4) and one host also with 2 interfaces and 2 IPs (10.0.0.2/24, 10.1.0.2/24). Having:

ap1 --- (10.0.0.2/24) [h1] (10.1.0.2/24) ---- ap2 --- ap3 --- ap4

When the station moves around and connects freely to these APs, ping (at least on my test) only works with the first AP the station connects to with a given interface. For example:

* if sta1 starts with wlan0 connected to ap1 and IP 10.0.0.1/24 and wlan1 connected to ap2 with IP 10.1.0.1/24, if I ping h1 from sta1 (sta1 ping 10.1.0.2), it works;
* as sta1 moves around, while keeping the connectivity with ap1, and it eventually associates wlan1 with ap3 or ap4 (keeping the same IP addresses), if I try to ping with the same command (sta1 ping 10.1.0.2) it does **not** work.

In my example h1 runs a simple HTTP server, running wget from sta1 works tho.

Maybe I am doing something wrong and that's the expected behavior of ping, but that's the reason why I said it wasn't connecting to the access points (instead of trying iw or iwconfig to verify that).

Hope I could explain it well, if not, please let me know.

**Comment by ramonfontes** [comment]
Hi Leonardo,

Just one question: Have you checked out the flow table of the APs? Probably
the AP is learning that to reach h1 the packet has to go to a specific path
and when sta1 moves around, the AP still has the previous table installed
on it.

**Comment by NadiaMOUAWAD** [comment]
Hello, I am facing the same problem concerning the ping> I have implemented the controller in a way to delete the previous flow tables, however, when sta1 connects to AP2 with sta1-wlan1 the ping stops because ap2 is not sending a packet_in message to the controller about the new connection in order to install new flows. Do you have any idea about this?

**Comment by ramonfontes** [comment]
Could you provide more details about your setup?

**Comment by NadiaMOUAWAD** [comment]
okay, in my topology I have :
    sta1=net.addStation('sta1',wlans=2,mac='00:00:00:00:00:02', ip='
10.0.0.2/8')
    h1 = net.addHost('h1', mac='00:00:00:00:00:10', ip='10.0.0.1/8')
sta1 is moving its is connected to AP1 with sta1-wlan0 .

If I xterm h1 and ping 10.0.0.2 everything is okay until sta1 disconnect
with AP2 and connects to AP2 with sta1-wlan1 , h1 cannot reach sta1 anymore
even though , I am pre-installing flow rules with Ryu controller and
deleting rules in AP2.

If I try to add     sta1.setIP('10.1.0.2/8', intf="sta1-wlan1")

and  make h1 ping 10.0.0.2 ( since sta1 is first connected with sta1-wlan0)
the ping does not work from the beginning because sta1 is taken with IP
address 10.1.0.2.

**Comment by ramonfontes** [comment]
So, both interfaces are on the same subnet and sta1-wlan0 is up after
handover? I think you have problems at L2/L3.

Moreover, you said that "ap2 is not sending a packet_in message to the
controller". Isn't h1 sending icmp packets to ap2?? Which node is h1
connected? Could you clarify the issue? Is really difficult to make some
assumption without a complete overview of the topology.

**Comment by NadiaMOUAWAD** [comment]
#!/usr/bin/python

'Setting mechanism to optimize the use of APs'

from mininet.node import RemoteController
from mininet.log import setLogLevel, info
from mininet.wifi.node import OVSKernelAP
from mininet.wifi.cli import CLI_wifi
from mininet.wifi.net import Mininet_wifi
from time import sleep

from mininet.wifi.node import UserAP

from mininet.wifi.link import wmediumd

from mininet.wifi.wmediumdConnector import interference
import random


def topology():
    "Create a network."
    net = Mininet_wifi(controller=RemoteController,link=wmediumd,
accessPoint=OVSKernelAP, wmediumd_mode=interference)
    #net = Mininet_wifi(controller=RemoteController,
accessPoint=OVSKernelAP)
    info("*** Creating nodes\n")
    sta1=net.addStation('sta1',wlans=2,mac='00:00:00:00:00:02', ip='
10.0.0.2/8')
    h1 = net.addHost('h1', mac='00:00:00:00:00:10', ip='10.0.0.1/8')

    ap1 = net.addAccessPoint('ap1', ssid='ssid-ap1', mode='g', channel='1',

position='40,50,0',dpid='1',protocols='OpenFlow13')
    ap2 = net.addAccessPoint('ap2', ssid='ssid-ap2', mode='g', channel='6',
                             position='90,50,0',
dpid='2',protocols='OpenFlow13')
    #ap3 = net.addAccessPoint('ap3', ssid='ssid-ap3', mode='g', channel='1',
    #
position='130,50,0',dpid='3',protocols='OpenFlow13')
    c1 = net.addController('c1',
controller=RemoteController,ip='192.168.191.152')

    net.propagationModel(model="logDistance", exp=5)
    #net.plotGraph(max_x=200, max_y=200)
    net.seed(10)
    info("*** Configuring wifi nodes\n")
    net.configureWifiNodes()

    info("*** Associating and Creating links\n")
    net.addLink(ap1, ap2)
    #net.addLink(ap1, sta1)
    net.addLink(h1, ap2)
    #net.setBgscan(signal=-45, s_inverval=5, l_interval=10)
    #net.associationControl('ssf')

This is my mininet topology.
    sta1.setIP('10.1.0.2/8', intf="sta1-wlan1")
    #sta1.cmd('ip link set sta1-wlan1 address 00:00:00:00:00:33')

    #sta1.cmd('ifconfig sta1-wlan0 200.0.10.150 up')

    #sta1.cmd('sudo wireshark -i mon0 &')
    #sta1.cmd('python myClient.py -i %s -m "hello world"' % c1.IP())

    net.startMobility(time=10)
    net.mobility(sta1, 'start', time=10, position='35,50,0')
    net.mobility(sta1, 'stop', time=200, position='180,50,0')
    net.stopMobility(time=200)

    info("*** Starting network\n")
    net.build()
    c1.start()
    ap1.start([c1])
    ap2.start([c1])
    #ap3.start([c1])

    info("*** Running CLI\n")
    CLI_wifi(net)
    info("*** Stopping network\n")
    net.stop()


if __name__ == '__main__':
    setLogLevel('info')
    topology()

First, I am using xterm h1 to ping sta1. sta1 starts mobility and it is
connected to AP1 with sta1-wlan0. Before the handover occurs, I am
implementing some methods to delete flows and install new flows in AP2 in
order to try to reach sta1 when it connects to AP2 with sta1-wlan1. So I am
installing a rule in AP2 with matching fields eth_src=h1 mac address and
eth_dst= sta1 mac address. and specifying the output port (knowing that
sta1 will connect to AP2 with port 1).  However, when sta1 disconnects with
AP1, I cannot reach sta1 no more.

I tried to rewrite the IP destination to redirect the packets sent to
10.0.0.2 to 10.1.0.2, but I still cannot reach sta1 when it looses
connection with sta1.

**Comment by NadiaMOUAWAD** [comment]
Hello,

I am trying to take your advice into account.This is my topology:
#!/usr/bin/python

'Setting mechanism to optimize the use of APs'

from mininet.node import RemoteController
from mininet.log import setLogLevel, info
from mininet.wifi.node import OVSKernelAP
from mininet.wifi.cli import CLI_wifi
from mininet.wifi.net import Mininet_wifi
from time import sleep
from mininet.wifi.node import UserAP
from mininet.wifi.link import wmediumd
from mininet.wifi.wmediumdConnector import interference
import random


def topology():
    "Create a network."
    net = Mininet_wifi(controller=RemoteController,link=wmediumd,
accessPoint=OVSKernelAP, wmediumd_mode=interference)
    #net = Mininet_wifi(controller=RemoteController,
accessPoint=OVSKernelAP)
    info("*** Creating nodes\n")
    sta1=net.addStation('sta1',wlans=2,mac='00:00:00:00:00:02', ip='
10.0.0.2/8')
    h1 = net.addHost('h1', mac='00:00:00:00:00:10', ip='10.0.0.1/8')

    ap1 = net.addAccessPoint('ap1', ssid='ssid-ap1', mode='g', channel='1',

position='40,50,0',dpid='1',protocols='OpenFlow13')
    ap2 = net.addAccessPoint('ap2', ssid='ssid-ap2', mode='g', channel='6',
                             position='80,50,0',
dpid='2',protocols='OpenFlow13')
    s5 = net.addSwitch( 's5'
,mac='00:00:00:00:00:02',protocols='OpenFlow13',dpid='5')
    #ap3 = net.addAccessPoint('ap3', ssid='ssid-ap3', mode='g', channel='1',
    #
position='130,50,0',dpid='3',protocols='OpenFlow13')
    c1 = net.addController('c1',
controller=RemoteController,ip='192.168.191.152')

    net.propagationModel(model="logDistance", exp=5)
    #net.plotGraph(max_x=200, max_y=200)
    net.seed(10)
    info("*** Configuring wifi nodes\n")
    net.configureWifiNodes()

    info("*** Associating and Creating links\n")
    net.addLink(ap1, sta1)
    net.addLink(ap1, s5,3,1)
    net.addLink(ap2, s5,3,2)
    net.addLink(h1, s5,1,3)
    #net.setBgscan(signal=-45, s_inverval=5, l_interval=10)
    #net.associationControl('ssf')

    #net.startMobility(time=0, model='RandomWayPoint', max_x=120, max_y=50,
    #                  min_v=0.2, max_v=0.4)
    #sta1.setIP('10.0.0.8', intf='sta1-wlan0')
    ap1.cmd('iw dev %s interface add mon0 type monitor'
%ap1.params['wlan'][0])
    #sta1.cmd('ip link set mon0 address 00:00:00:00:00:15')
    ap1.cmd('ifconfig mon0 up')
    #sta1.cmd("ifconfig sta1-wlan1 10.1.0.2/8 up")
    sta1.setIP('10.1.0.2/8', intf="sta1-wlan1")
    #sta1.cmd('ip link set sta1-wlan1 address 00:00:00:00:00:33')


    net.startMobility(time=10)
    net.mobility(sta1, 'start', time=10, position='35,50,0')
    net.mobility(sta1, 'stop', time=50, position='80,50,0')
    net.stopMobility(time=100)

    info("*** Starting network\n")
    net.build()
    c1.start()
    ap1.start([c1])
    ap2.start([c1])
    s5.start([c1])
    """
    for i in range(30):
        output = sta1.cmd('iw dev sta1-wlan0 scan -u freq 2412 passive')
        print "["+str(i)+"] iw output: "+output
        sleep(3)
    """


    info("*** Running CLI\n")
    CLI_wifi(net)
    info("*** Stopping network\n")
    net.stop()


if __name__ == '__main__':
    setLogLevel('info')
    topology()

 The problem that I have is when I ping 10.0.0.2 the host is not reachable
until sta1 connects with AP2 . In other words, the address 10.0.0.2 is not
recognizable, however when I comment  this code line sta1.setIP('10.1.0.2/8',
intf="sta1-wlan1" ) every thing works normally.

Do you know what is the problem?

**Comment by ramonfontes** [comment]
Dear,

You have configured both interfaces on the same subnet. Which interface
will the station use??

This is a basic concept of networking. :(

Sent from my android.

>

**Comment by ramonfontes** [comment]
This isn't about using two interfaces simultaneously. This is about using
two interfaces simultaneously with 2 interfaces on the same subnet.
