### ISSUE TITLE
install problem

### ISSUE THREAD

**Issue by cheungi** [intrig-unicamp/mininet-wifi#141]
Hello,

I'm trying to put a fresh load of mininet and mininet-wifi on my new MacBook Pro.  I am using Virtualbox to run the VMs.  VBox is Version 5.2.2 r119230 (Qt5.6.3).  Mininet is version 2.2.2 running over Ubuntu version 16.04.3 LTS.  Everything has been updated and upgraded.  Mininet is working fine on it's own.  

I then followed the 4-step instruction on this GitHub page to install mininet-wifi over the mininet install.  Now mininet no longer works and I keep getting the error below when I try to start it.  What am I doing wrong?  I have gotten this to work before on an older MacBook Pro but I don't recall if I am missing something to get everything to work.  Please help!

Error returned:
mininet@mininet-vm:$ sudo mn --test pingall
[sudo] password for mininet: 
Traceback (most recent call last):
  File "/usr/local/bin/mn", line 4, in <module>
    __import__('pkg_resources').run_script('mininet-wifi===2.2.0d1', 'mn')
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 719, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 1504, in run_script
    exec(code, namespace, namespace)
  File "/usr/local/lib/python2.7/dist-packages/mininet_wifi-2.2.0d1-py2.7.egg/EGG-INFO/scripts/mn", line 27, in <module>
    from mininet.node import (Host, CPULimitedHost, Controller, OVSController,
ImportError: cannot import name UserAP
mininet@mininet-vm:~$

**Comment by ramonfontes** [comment]
Hello,

Please remove this directory (/usr/local/lib/python2.7/
dist-packages/mininet_wifi-2.2.0d1-py2.7.egg) and then run sudo make
install.

**Comment by cheungi** [comment]
Thanks for your reply.  I did what you advised and it allowed me to use mininet again.  I was able to do a quick pingall test to confirm.  However after removing the directory you mentioned, it does not recognize the wifi as being installed.  When I try to reinstall the wifi, it reverts back to the same original error as stated above.  Please advise.  Thank you.

after removing directory and running sudo make install in mininet directory
>mininet@mininet-vm:/mininet-wifi$ sudo mn --test pingall
*** Creating network
*** Adding controller
*** Adding hosts:
h1 h2 
*** Adding switches:
s1 
*** Adding links:
(h1, s1) (h2, s1) 
*** Configuring hosts
h1 h2 
*** Starting controller
c0 
*** Starting 1 switches
s1 ...
*** Waiting for switches to connect
s1 
*** Ping: testing ping reachability
h1 -> h2 
h2 -> h1 
*** Results: 0% dropped (2/2 received)
*** Stopping 1 controllers
c0 
*** Stopping 2 links
..
*** Stopping 1 switches
s1 
*** Stopping 2 hosts
h1 h2 
*** Done
completed in 5.207 seconds
mininet@mininet-vm:/mininet-wifi$ sudo mn --wifi
Usage: mn [options]
(type mn -h for details)
mn: error: no such option: --wifi
mininet@mininet-vm:~/mininet-wifi$

after reinstalling mininet-wifi
> mininet@mininet-vm:/mininet-wifi$ sudo mn --test pingall
Traceback (most recent call last):
  File "/usr/local/bin/mn", line 4, in <module>
    __import__('pkg_resources').run_script('mininet-wifi===2.2.0d1', 'mn')
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 719, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 1504, in run_script
    exec(code, namespace, namespace)
  File "/usr/local/lib/python2.7/dist-packages/mininet_wifi-2.2.0d1-py2.7.egg/EGG-INFO/scripts/mn", line 27, in <module>
    from mininet.node import (Host, CPULimitedHost, Controller, OVSController,
ImportError: cannot import name UserAP
mininet@mininet-vm:/mininet-wifi$ sudo mn --wifi
Traceback (most recent call last):
  File "/usr/local/bin/mn", line 4, in <module>
    __import__('pkg_resources').run_script('mininet-wifi===2.2.0d1', 'mn')
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 719, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 1504, in run_script
    exec(code, namespace, namespace)
  File "/usr/local/lib/python2.7/dist-packages/mininet_wifi-2.2.0d1-py2.7.egg/EGG-INFO/scripts/mn", line 27, in <module>
    from mininet.node import (Host, CPULimitedHost, Controller, OVSController,
ImportError: cannot import name UserAP
mininet@mininet-vm:/mininet-wifi$

**Comment by cheungi** [comment]
strange... I don't have mn inside the /usr/bin folder.

**Comment by ramonfontes** [comment]
Please find mn and remove it.
