### ISSUE TITLE
start error

### ISSUE THREAD

**Issue by whiteysy** [intrig-unicamp/mininet-wifi#142]
Hello
Some error occurred when i started the simulator today. I have not met this error before. Then I reinstalled mininet-wifi. The error still exist. Please help me, thank you!

Error returned:
--------------------------------------------------------------------------------
Caught exception. Cleaning up...

ValueError: invalid literal for int() with base 10: 'fi'
--------------------------------------------------------------------------------
*** Removing excess controllers/ofprotocols/ofdatapaths/pings/noxes
killall controller ofprotocol ofdatapath ping nox_core lt-nox_core ovs-openflowd ovs-controller udpbwtest mnexec ivs ryu-manager 2> /dev/null
killall -9 controller ofprotocol ofdatapath ping nox_core lt-nox_core ovs-openflowd ovs-controller udpbwtest mnexec ivs ryu-manager 2> /dev/null
pkill -9 -f "sudo mnexec"
*** Removing junk from /tmp
rm -f /tmp/vconn* /tmp/vlogs* /tmp/*.out /tmp/*.log
*** Removing old X11 tunnels
*** Removing excess kernel datapaths
ps ax | egrep -o 'dp[0-9]+' | sed 's/dp/nl:/'
***  Removing WiFi module and Configurations
pkill -9 -f hostapd
***  Removing OVS datapaths
ovs-vsctl --timeout=1 list-br
ovs-vsctl --timeout=1 list-br
*** Removing all links of the pattern foo-ethX
ip link show | egrep -o '([-_.[:alnum:]]+-eth[[:digit:]]+)'
ip link show
*** Killing stale mininet node processes
pkill -9 -f mininet:
*** Shutting down stale tunnels
pkill -9 -f Tunnel=Ethernet
pkill -9 -f .ssh/mn
rm -f ~/.ssh/mn/*
*** Killing wmediumd
pkill wmediumd
*** Cleanup complete.

**Comment by ramonfontes** [comment]
Hi,

What is the installed version? I cannot observe such error. Tests from
Travis say that everything is ok with sudo mn --wifi. What is the output
for *sudo mn --wifi -v debug*?

2017-12-14 11:09 GMT-03:00 whiteysy <notifications@github.com>:

**Comment by whiteysy** [comment]
It is my fault because of my carelessness. I started the simulator by the command "sudo mn -wifi" instead of "sudo mn --wifi". Thanks for you reply timely!
