### ISSUE TITLE
Problems about APs

### ISSUE THREAD

**Issue by Ericzhang1127** [intrig-unicamp/mininet-wifi#143]
Hello!

Is it possible to use POX controller to controller flows among APs wirelessly?
For example:
                                                Sta1---- AP1 ----AP3 -----AP2----Sta2
                                                            
Flow Path : sta1--AP1--AP3--AP2--sta2                                                               
I used the command net.addMesh(ap1) , but the  output is Flood.As a result,AP2 and AP3 all receive the flow.
How can I set AP1(wlan2)----(waln2)AP3(wlan3)-----(wlan2)AP2? 
Thank you very much

**Comment by ramonfontes** [comment]
Hello,

Although the OpenFlow Spec 1.5 defines the behavior of sending out the incoming port [_see B.6.3 IN PORT Virtual Port_](https://www.opennetworking.org/wp-content/uploads/2014/10/openflow-switch-v1.5.1.pdf), I don't know whether this feature is already implemented in OVS. I tried this unsuccessfully one year ago and I really don't know whether it is already implemented. 

Regarding the last question, you can do something like:

`...`
`ap1 = net.addAccessPoint('ap1', wlans=2, ssid='ssid1,', position='10,10,0')`
`ap2 = net.addAccessPoint('ap2', wlans=2, ssid='ssid2,', position='30,10,0')`
`ap3 = net.addAccessPoint('ap3', wlans=2, ssid='ssid3,', position='50,10,0')`
`...`

`net.addMesh(ap1, intf='ap1-wlan2', ssid='mesh-ssid1')`
`net.addMesh(ap2, intf='ap2-wlan1', ssid='mesh-ssid1')`
`net.addMesh(ap2, intf='ap2-wlan2', ssid='mesh-ssid2')`
`net.addMesh(ap3, intf='ap3-wlan2', ssid='mesh-ssid2')`

**Comment by Ericzhang1127** [comment]
Thank you very much!
I tried your advice and here is my code:
#!/usr/bin/python

'This example shows how to create wireless link between two APs'

from mininet.net import Mininet
from mininet.node import Controller, OVSKernelAP,RemoteController
from mininet.cli import CLI
from mininet.log import setLogLevel
from mininet.link import TCLink

def topology():
    "Create a network."
    net = Mininet(controller=Controller, link=TCLink, accessPoint=OVSKernelAP,
                  enable_wmediumd=True, enable_interference=True)

    print "*** Creating nodes"
    sta1 = net.addStation('sta1', mac='00:00:00:00:00:11',ip="192.168.0.1/24")
    sta2 = net.addStation('sta2', mac='00:00:00:00:00:12',ip="192.168.0.2/24")
    sta3 = net.addStation('sta3', mac='00:00:00:00:00:13',ip="192.168.0.3/24")
    sta4 = net.addStation('sta4', mac='00:00:00:00:00:14',ip="192.168.0.4/24")
    ap1 = net.addAccessPoint('ap1', wlans=2, ssid='ssid1,', position='10,10,0')
    ap2 = net.addAccessPoint('ap2', wlans=2, ssid='ssid2,', position='30,10,0')
    ap3 = net.addAccessPoint('ap3', wlans=2, ssid='ssid3,', position='50,10,0')
    c0 = net.addController('c0', controller=Controller)

    print "*** Configuring wifi nodes"
    net.configureWifiNodes()

    print "*** Associating Stations"
    #net.addLink(sta4, ap1)
    net.addLink(sta1, ap1)
    net.addLink(sta2, ap2)
    net.addLink(sta3, ap3)
    net.addMesh(ap1, intf='ap1-wlan2', ssid='mesh-ssid1')
    net.addMesh(ap2, intf='ap2-wlan1', ssid='mesh-ssid1')
    net.addMesh(ap2, intf='ap2-wlan2', ssid='mesh-ssid2')
    net.addMesh(ap3, intf='ap3-wlan2', ssid='mesh-ssid2')

    print "*** Starting network"
    net.build()
    c0.start()
    ap1.start([c0])
    ap2.start([c0])
    ap3.start([c0])

    print "*** Running CLI"
    CLI(net)

    print "*** Stopping network"
    net.stop()


if __name__ == '__main__':
    setLogLevel('info')
    topology()

**Comment by ramonfontes** [comment]
Please note that ap2 has 2 interfaces and these 2 interfaces are working in mesh mode. That said,  sta2 cannot connect with ap2.

Intf is the interface name and mesh-ssid1 the ssid of the wireless mesh.

**Comment by Ericzhang1127** [comment]
Thanks !
I set 3 wlans to AP2, but sta1 still cannot ping sta2.
ap2 = net.addAccessPoint('ap2', wlans=3, ssid='ssid2,ssid4,ssid5', position='30,10,0')
Is there any methods that sta2 can connect with ap2?

**Comment by Ericzhang1127** [comment]
Thanks a lot !
I set 3wlans for AP2 , and it worked!
I want to konw the connection ports between APs.Is there any command to show the connection between APs? I used to use "links ", but it doesn't work.

**Comment by ramonfontes** [comment]
Hi,

Have you ever tried ovs-ofctl (e.g. ovs-ofctl show ap1)? Another
alternative is dpctl.
