### ISSUE TITLE
getRange doesn't return any range anything

### ISSUE THREAD

**Issue by bharaththiruveedula** [intrig-unicamp/mininet-wifi#144]
I am trying to see what all properties we can get  from wifi node, I tried to see the range of access point using https://github.com/intrig-unicamp/mininet-wifi/blob/master/mininet/node.py#L288. But the method doesn't return anything. Moreover it updates the graph. may I know why we are updating graph and why not returning the range value?

**Comment by ramonfontes** [comment]
Fixed with this commit
<https://github.com/intrig-unicamp/mininet-wifi/commit/bf9ddab9c587eea54621030c4912763f53185f93>.
You may want to work on branch dev. The branch dev includes support to
python3 as well.

Thanks!

2017-12-31 17:01 GMT-03:00 Bharath <notifications@github.com>:
