### ISSUE TITLE
“IndexError: list index out of range“ when I run the SBRC.py in the demos

### ISSUE THREAD

**Issue by topspeedbell** [intrig-unicamp/mininet-wifi#145]
Hi, Ramon,
the name of phywlan has been changed to the name of my USB dongle wifi .
I stopped the NetworkManager, and ran the SBRC.py, but I got the error as below:

*** Configuring wifi nodes
Traceback (most recent call last):
  File "SBRC.py", line 80, in <module>
    topology()
  File "SBRC.py", line 42, in topology
    net.configureWifiNodes()
  File "/usr/local/lib/python2.7/dist-packages/mininet_wifi-2.2.0d1-py2.7.egg/mininet/net.py", line 780, in configureWifiNodes
    self.stations, self.aps = mininetWiFi.configureWifiNodes(self)
  File "/usr/local/lib/python2.7/dist-packages/mininet_wifi-2.2.0d1-py2.7.egg/mininet/wifiNet.py", line 1076, in configureWifiNodes
    cls.configureAPs(mininet.aps, mininet.driver)
  File "/usr/local/lib/python2.7/dist-packages/mininet_wifi-2.2.0d1-py2.7.egg/mininet/wifiNet.py", line 868, in configureAPs
    cls.configureAP(ap, aplist=aps)
  File "/usr/local/lib/python2.7/dist-packages/mininet_wifi-2.2.0d1-py2.7.egg/mininet/wifiNet.py", line 780, in configureAP
    if ap.params['ssid'][wlan] != '':
IndexError: list index out of range

My os is Ubuntu 16.04,  and I have run sudo mn -c each time. 
Could you help me ?
thanks!

BR
Top

**Comment by ramonfontes** [comment]
Hi,

I just updated sbrc.py. Please try the new code.

**Comment by topspeedbell** [comment]
Hi，
Thanks for you reply!

Is the sbrc.py in https://github.com/ramonfontes/reproducible-research/tree/master/mininet-wifi/SBRC-2016 ?
I downloaded the sbrc,py last week. 

BR
Top

**Comment by ramonfontes** [comment]
Yes. It was updated 10min ago.

2018-01-09 9:42 GMT-03:00 topspeedbell <notifications@github.com>:

**Comment by topspeedbell** [comment]
thanks.
I downloaded the sbrc.py again, but there is still the same error. 
I find the latest update time  is " on 30 Nov 2017".

**Comment by topspeedbell** [comment]
sorry, it's caused  by network delay. Now I can find the new version. I will try it! thank!

**Comment by topspeedbell** [comment]
It works. Thanks!

I notice you also updated the sigcomm 2016, so I tested the sigcomm.py. It works, also. But when i run “sh ./rule.hybridVirtualPhysical”, it shows “ permission denied ”.  How can I get the permission in the mininet-wifi cli?
Thanks!

**Comment by ramonfontes** [comment]
You can run such code from any terminal.

Sent from my android

On 9 Jan 2018 13:10, "topspeedbell" <notifications@github.com> wrote:

It works. Thanks!

I notice you also updated the sigcomm 2016, so I tested the sigcomm.py. It
works, also. But when i run “sh ./rule.hybridVirtualPhysical”, it shows “
permission denied ”. How can I get the permission in the mininet-wifi cli?
Thanks!

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/intrig-unicamp/mininet-wifi/issues/145#issuecomment-356330492>,
or mute the thread
