### ISSUE TITLE
Running errors: 

### ISSUE THREAD

**Issue by iamxg** [intrig-unicamp/mininet-wifi#146]
Hi Ramon,
I'd like to test my codes. So I install my codes on another computer. System environment: Virtual Box, ubuntu 16.4. But all of my modules always occur the following error. I don't know why. Could you help me?
Best Regards,
Xian Guo.
image
![image](https://user-images.githubusercontent.com/30093996/34724489-9ba9cecc-f513-11e7-8a40-a73235c2866c.png)

**Comment by ramonfontes** [comment]
Dear Guo,

I suppose you're using mini-ndn and I cannot answer for such error.

**Comment by iamxg** [comment]
Hi Ramon，
Ok， thanks a lot. I will continue to find this reason.
Best Regards,
Xian Guo
