### ISSUE TITLE
Mininet-wifi and mininet No module named wifi.clean

### ISSUE THREAD

**Issue by sahilabro** [intrig-unicamp/mininet-wifi#149]
I am working on a database design for monitoring both WiFi, and layer 2 networks.

After installing mininet-wifi on the same machine (followed your instructions), mininet does not work anymore. However if i remove mininet-wifi and reinstall standard mininet it works. I need to simulate a WiFi network but it won't let me.

Here is the Error I get

$ sudo mn --test
Traceback (most recent call last):
  File "/usr/local/bin/mn", line 4, in <module>
    __import__('pkg_resources').run_script('mininet-wifi===2.2.0d1', 'mn')
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 719, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 1504, in run_script
    exec(code, namespace, namespace)
  File "/usr/local/lib/python2.7/dist-packages/mininet_wifi-2.2.0d1-py2.7.egg/EGG-INFO/scripts/mn", line 24, in <module>
    from mininet.wifi.clean import cleanup_wifi
ImportError: No module named wifi.clean

Any idea how to solve this?

**Comment by ramonfontes** [comment]
Hi,

Please remove mininet-wifi dir from /usr/local/lib/python2.7/
dist-packages/mininet_wifi with sudo rm -r
/usr/local/lib/python2.7/dist-packages/mininet_wifi*,
then clone the code again and run sudo make install. Finally, let me know
if it solves the issue.

**Comment by sahilabro** [comment]
Hi, it still gives me the same error unfortunately.

**Comment by ramonfontes** [comment]
Can you see the file `mininet/wifi/clean.py`?

**Comment by ramonfontes** [comment]
Please try:
`sudo rm -r /usr/local/lib/python2.7/dist-packages/mininet*`,

Then run:
`sudo make install`

**Comment by sahilabro** [comment]
It still gives me the same issue.

**Comment by ramonfontes** [comment]
The same issue?

File "/usr/lib/python2.7/dist-packages/pkg_resources/init.py", line **719**, in run_script
and
File "/usr/lib/python2.7/dist-packages/pkg_resources/init.py", line **1504**, in run_script

?

**Comment by sahilabro** [comment]
Yes it still gives me that:

Traceback (most recent call last):
File "/usr/local/bin/mn", line 4, in 
import('pkg_resources').run_script('mininet-wifi===2.2.0d1', 'mn')
File "/usr/lib/python2.7/dist-packages/pkg_resources/init.py", line 719, in run_script
self.require(requires)[0].run_script(script_name, ns)
File "/usr/lib/python2.7/dist-packages/pkg_resources/init.py", line 1504, in run_script
exec(code, namespace, namespace)
File "/usr/local/lib/python2.7/dist-packages/mininet_wifi-2.2.0d1-py2.7.egg/EGG-INFO/scripts/mn", line 24, in 
from mininet.wifi.clean import cleanup_wifi
ImportError: No module named wifi.clean

**Comment by heav1811** [comment]
Do "pip unistall mininet".

**Comment by heav1811** [comment]
Do "pip unistall mininet".

**Comment by amirbyo** [comment]
Hi
how to i can remove mininet-wifi from my ubuntu ?

**Comment by ramonfontes** [comment]
sudo rm -rf /usr/local/bin/mn /usr/local/bin/mnexec \
         /usr/local/lib/python2.7/dist-packages/mininet*

**Comment by reubenct** [comment]
Hi,
I was also facing same issue. @ramonfontes first comment helped me out.
Now I am able to run 'sudo mn' and 'sudo mn -c'.
But when I run 'sudo mn --wifi', it shows an error that 'insmod' module is not found and Mininet does not start.
![image](https://user-images.githubusercontent.com/23528484/41214618-e68db254-6d69-11e8-9d28-f08698f4b87e.png)
This error shows up even after I did clean (with -c option).
Please help me out, and what is the correct way to start mininet-wifi ?
Thanks

**Comment by ramonfontes** [comment]
Hi,

I don't know what is going wrong there. Tests from Travis show that
everything is ok:
https://travis-ci.org/intrig-unicamp/mininet-wifi/jobs/390172438#L2953

**Comment by ramonfontes** [comment]
I suggest you either install Ubuntu in a new VM from scratch or use our VM.

**Comment by M-Hadi-T** [comment]
hi dear I faced to this problems, haw can I solve this problems?

hadi@ubuntu:~$ sudo mn --wifi
Traceback (most recent call last):
  File "/usr/local/bin/mn", line 4, in <module>
    __import__('pkg_resources').run_script('mininet-wifi==2.5', 'mn')
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 3243, in <module>
    def _initialize_master_working_set():
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 3226, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 3255, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 568, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 886, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 772, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'mininet-wifi==2.5' distribution was not found and is required by the application

**Comment by ramonfontes** [comment]
I see no problem here. The error means that you haven't installed mn-wifi.

**Comment by ramonfontes** [comment]
I see no problem here. The error means that you haven't installed mn-wifi.

**Comment by M-Hadi-T** [comment]
previously I installed the mn-wifi.

hadi@ubuntu:~$ ls
certificate  enter                Music     Pictures  ssl        xterm
Desktop      mac80211_hwsim_mgmt  oflops    pox       Templates
Documents    mininet              oftest    Public    Videos
Downloads    mininet-wifi

**Comment by ramonfontes** [comment]
You listed directories :(. This doesn't mean that you have installed mn-wifi.

**Comment by M-Hadi-T** [comment]
hadi@ubuntu:~$ git clone git://github.com/intrig-unicamp/mininet-wifi
fatal: destination path 'mininet-wifi' already exists and is not an empty directory.

**Comment by ramonfontes** [comment]
I could avoid commenting.. :( :( Are you new to computing? What does the message say? "DESTINATION PATH ALREADY EXISTS!" Do you really want to clone a repository called mininet-wifi?? How many options do we have to solve this "problem"?? This is not an issue related to mn-wifi at all!
