### ISSUE TITLE
Wifi-Direct Destination host unreachable

### ISSUE THREAD

**Issue by NandanMaj** [intrig-unicamp/mininet-wifi#150]
Below given is the code of mininet_wifi/examples/wifiDirect.py

#!/usr/bin/python

'Example for WiFi Direct'

from time import sleep

from mininet.log import setLogLevel, info
from mininet.wifi.link import wmediumd
from mininet.wifi.cli import CLI_wifi
from mininet.wifi.net import Mininet_wifi

def topology():
    "Create a network."
    net = Mininet_wifi(link=wmediumd, enable_interference=True,
                  configureWiFiDirect=True, disableAutoAssociation=True)

    info("*** Creating nodes\n")
    sta1 = net.addStation('sta1', ip='10.0.0.1/8', position='10,10,0')
    sta2 = net.addStation('sta2', ip='10.0.0.2/8', position='20,20,0')

    info("*** Configuring Propagation Model\n")
    net.propagationModel(model="logDistance", exp=3.5)

    info("*** Configuring wifi nodes\n")
    net.configureWifiNodes()

    net.plotGraph(max_x=200, max_y=200)

    info("*** Starting WiFi Direct\n")
    net.wifiDirect(sta1)
    net.wifiDirect(sta2)

    info("*** Starting network\n")
    net.build()

    sta1.cmd('wpa_cli -ista1-wlan0 p2p_find')
    sta2.cmd('wpa_cli -ista2-wlan0 p2p_find')
    sta2.cmd('wpa_cli -ista2-wlan0 p2p_peers')
    sleep(3)
    sta1.cmd('wpa_cli -ista1-wlan0 p2p_peers')
    sleep(3)
    pin = sta1.cmd('wpa_cli -ista1-wlan0 p2p_connect %s pin auth'
                   % sta2.params['mac'][1])
    sleep(3)
    sta2.cmd('wpa_cli -ista2-wlan0 p2p_connect %s %s'
             % (sta1.params['mac'][1], pin))

    info("*** Running CLI\n")
    CLI_wifi(net)

    info("*** Stopping network\n")
    net.stop()

if __name__ == '__main__':
    setLogLevel('info')
    topology()

When in run it in shell it gives error like : 

*** Creating nodes
*** Configuring Propagation Model
*** Configuring wifi nodes
command failed: No such file or directory (-2)
command failed: No such file or directory (-2)
Traceback (most recent call last):
  File "./examples/wifiDirect.py", line 58, in <module>
    topology()
  File "./examples/wifiDirect.py", line 26, in topology
    net.configureWifiNodes()
  File "/usr/local/lib/python2.7/dist-packages/mininet_wifi-2.2.0d1-py2.7.egg/mininet/wifi/net.py", line 2174, in configureWifiNodes
    self.configureWirelessLink(self.stations, self.aps, self.cars)
  File "/usr/local/lib/python2.7/dist-packages/mininet_wifi-2.2.0d1-py2.7.egg/mininet/wifi/net.py", line 2012, in configureWirelessLink
    self.configureMacAddr(node)
  File "/usr/local/lib/python2.7/dist-packages/mininet_wifi-2.2.0d1-py2.7.egg/mininet/wifi/net.py", line 2159, in configureMacAddr
    node.params['mac'][wlan] = node.getMAC(iface)
  File "/usr/local/lib/python2.7/dist-packages/mininet_wifi-2.2.0d1-py2.7.egg/mininet/wifi/node.py", line 255, in getMAC
    debug('%s\n' % mac[0])
IndexError: list index out of range

**Comment by ramonfontes** [comment]
Please run sudo mn -c.

**Comment by NandanMaj** [comment]
Okay thanks for replying. Sir can I contact you through this email for
Mininet-wifi related queries/guidance?

**Comment by ramonfontes** [comment]
Dear,

Join our mailing list for questions/doubts on Mininet-WiFi.

**Comment by vkeeegupt** [comment]
Sir,
It show destination host unreachable,
When vlc-streaming from station to host,
While vlc-streaming from station to station,it's ok

**Comment by vkeeegupt** [comment]
In handover.py

**Comment by ramonfontes** [comment]
Do you have any comments about the flow timeout??

**Comment by vkeeegupt** [comment]
sir, 
actually i am unable to ping sta1 to sta2/h1 when i use mobility.
please help me sir,
i am working on bgscan-handover

**Comment by ramonfontes** [comment]
There is no problem with handover-bgscan. BTW, this issue isn't about handover-bgscan.

**Comment by vkeeegupt** [comment]
Sir,
Where is the problem?
And how should I handle it?

**Comment by ramonfontes** [comment]
Which problem?? Where did you find h1 in handover-bgscan??

**Comment by vkeeegupt** [comment]
sir,
i added it myself,anyways its not necessary,even while trying to ping sta1 and sta2, the error i am getting is:
connect:network is unreachable
i have mailed you with screenshots attached

**Comment by ramonfontes** [comment]
APs have different ssids. Why? You not only added one host, you have
changed all the code.

**Comment by Arupkarbabu** [comment]
Sir i have doubt regarding mininet-wifi
it is possible or not sir ? two AP AND multiple station connect with one controller
station---AP1---ovsSwitch---ryucontroller
station---AP2---ovsSwitch---ryucontroller

**Comment by Arupkarbabu** [comment]
import sys
from mn_wifi.net import Mininet_wifi
from mn_wifi.cli import CLI
from mininet.log import setLogLevel, info
from mn_wifi.link import adhoc
from mn_wifi.link import wmediumd
from mininet.node import RemoteController
from mn_wifi.wmediumdConnector import interference

def topology():
"Create a network."
net = Mininet_wifi(controller=RemoteController ,link=wmediumd, wmediumd_mode=interference)

info("*** Creating nodes\n")
sta1 = net.addStation('sta1',mac='00:00:00:00:00:02', ip='10.0.0.2/8') 
sta2 = net.addStation('sta2',mac='00:00:00:00:00:03', ip='10.0.0.3/8')  
sta3 = net.addStation('sta3')
sta4 = net.addStation('sta4')
sta5 = net.addStation('sta5')
sta6 = net.addStation('sta6')

net.setPropagationModel(model="logDistance", exp=4)

ap1 = net.addAccessPoint('ap1', ssid="simplewifi",mode="g", channel="5")
ap2 = net.addAccessPoint('ap2', ssid="simplewifi2",mode="g", channel="5")


c0 = net.addController('c0', controller=RemoteController, ip='127.0.0.1',port=6633)


info("*** Configuring wifi nodes\n")
net.configureWifiNodes()
info("*** Associating...\n")
net.addLink(ap1, sta1)
net.addLink(ap1, sta2)
net.addLink(ap1, sta3)
net.addLink(sta1, intf='sta1-wlan0', cls=adhoc, ssid='adhocNet')
net.addLink(sta2, intf='sta2-wlan0', cls=adhoc, ssid='adhocNet')
net.addLink(sta3, intf='sta3-wlan0', cls=adhoc, ssid='adhocNet')
net.addLink(ap2, sta4)
net.addLink(ap2, sta5)
net.addLink(ap2, sta6)
net.addLink(sta4, intf='sta4-wlan0', cls=adhoc, ssid='adhocNet1')
net.addLink(sta5, intf='sta5-wlan0', cls=adhoc, ssid='adhocNet1')
net.addLink(sta6, intf='sta6-wlan0', cls=adhoc, ssid='adhocNet1')
net.addLink(ap1, ap2)

info("*** Starting network\n")
net.build()
c0.start()
ap1.start([c0])
ap2.start([c0])
info("*** Addressing...\n")
sta1.setIP('192.168.10.1/24', intf="sta1-wlan0")
sta2.setIP('192.168.10.2/24', intf="sta2-wlan0")
sta3.setIP('192.168.10.2/24', intf="sta3-wlan0")

sta4.setIP('192.168.20.1/24', intf="sta4-wlan0")
sta5.setIP('192.168.20.2/24', intf="sta5-wlan0")
sta6.setIP('192.168.20.3/24', intf="sta6-wlan0")





info("*** Running CLI\n")
CLI(net)

info("*** Stopping network\n")
net.stop()

**Comment by Arupkarbabu** [comment]
sta1 ping sta2

sta1 ping sta2
PING 10.0.0.2 (10.0.0.2) 56(84) bytes of data.
From 10.0.0.1 icmp_seq=1 Destination Host Unreachable
From 10.0.0.1 icmp_seq=2 Destination Host Unreachable
From 10.0.0.1 icmp_seq=3 Destination Host Unreachable
From 10.0.0.1 icmp_seq=4 Destination Host Unreachable
From 10.0.0.1 icmp_seq=5 Destination Host Unreachable
From 10.0.0.1 icmp_seq=6 Destination Host Unreachable
From 10.0.0.1 icmp_seq=7 Destination Host Unreachable
From 10.0.0.1 icmp_seq=8 Destination Host Unreachable
From 10.0.0.1 icmp_seq=9 Destination Host Unreachable
From 10.0.0.1 icmp_seq=10 Destination Host Unreachable
From 10.0.0.1 icmp_seq=11 Destination Host Unreachable
From 10.0.0.1 icmp_seq=12 Destination Host Unreachable
From 10.0.0.1 icmp_seq=13 Destination Host Unreachable
From 10.0.0.1 icmp_seq=14 Destination Host Unreachable
From 10.0.0.1 icmp_seq=15 Destination Host Unreachable
From 10.0.0.1 icmp_seq=16 Destination Host Unreachable
From 10.0.0.1 icmp_seq=17 Destination Host Unreachable
From 10.0.0.1 icmp_seq=18 Destination Host Unreachable
From 10.0.0.1 icmp_seq=19 Destination Host Unreachable
From 10.0.0.1 icmp_seq=20 Destination Host Unreachable
From 10.0.0.1 icmp_seq=21 Destination Host Unreachable
From 10.0.0.1 icmp_seq=22 Destination Host Unreachable
From 10.0.0.1 icmp_seq=23 Destination Host Unreachable
From 10.0.0.1 icmp_seq=24 Destination Host Unreachable
From 10.0.0.1 icmp_seq=25 Destination Host Unreachable
From 10.0.0.1 icmp_seq=26 Destination Host Unreachable
From 10.0.0.1 icmp_seq=27 Destination Host Unreachable

**Comment by Arupkarbabu** [comment]
have a example regarding this implementation part .two Ap and multiple adhoc network .
help me ?

**Comment by ZAHID188** [comment]
@Arupkarbabu I will recommend use args and try to understand the range of the ap and stas it's covering or not mostly destination unreachable it's because of the position of the stas and aps.
![image](https://github.com/user-attachments/assets/858773a0-c741-43c9-9a16-774d4bf3eebe)
