### ISSUE TITLE
How to set the protocol using Python API

### ISSUE THREAD

**Issue by sahilabro** [intrig-unicamp/mininet-wifi#151]
Hi all,

I want to create a custom topology such that it includes both Layer 2 and WiFi devices, both enabled under SDN OpenFlow Protocol 1.3. I cannot create such a network through the command-line as it only gives me the option to create either layer 2, or WiFi.

I want all my switches and access-points to be OpenFlow1.3 enabled ie --switch ovsk, protocols=OpenFlow13

I want something like,

STA1 -- > AP1

AP1 --> S1 --> S2 --> S3 --> AP2 

AP2 --> STA2

S2 --> H1 [wired host]

I found this:
http://mininet.org/api/classmininet_1_1node_1_1OVSSwitch.html

But I have no idea how to go about setting these devices as OpenFlow1.3 enabled using Pythong API..

net = Mininet_wifi(accessPoint=OVSKernalAP)
ap1 = net.AddAccessPoint('Ap1')
S2 = net.AddSwitch('S1')
net.addLink(ap1,S2)
... etc

**Comment by ramonfontes** [comment]
ap1 = net.addAccessPoint('Ap1', protocols='OpenFlow13')

2018-02-19 15:16 GMT-03:00 sahilabro <notifications@github.com>:

**Comment by sahilabro** [comment]
Many thanks,

Would i do the same to set a remote controller (ie I'd be running Ryu from another terminal so..)

net = Mininet_wifi(controller=remote, accessPoint=OVSKernalAP)
c1 = net.addController('c1', protocols='OpenFlow13', controller=remote)


As the above gives me an error..

**Comment by ramonfontes** [comment]
Please try RemoteController and consider to read the manual, scripts
availabe at /examples and comments in our mailing list for further
information on how to use Mininet-WiFi.
