### ISSUE TITLE
Unify the Py2 and Py3 codes

### ISSUE THREAD

**Issue by hildogjr** [intrig-unicamp/mininet-wifi#152]
Unify the Python 2 and Python 3 codes.
Python 2 may be decrepit in the next few year, so it is important to think in migration.
A middle phase is create a code the run in both, for this use the `pasteurize` and `future` and also the code bellow to run one part or other:

    from sys import version_info as py_version_info
    
    if py_version_info < (3,0):
        # Code for Py 2
    else:
        # Code for Py 3

**Comment by hildogjr** [comment]
I fix this, but I am not able to create a pull-request because repository restrictions.

**Comment by ramonfontes** [comment]
Hi, thank you.

There is no repository restrictions.

**Comment by hildogjr** [comment]
When I click in Upload appear the message:

    Uploads are disabled.
    File uploads require push access to this repository.

Also I can not create a (my) branch.

There is other branch (by other own Git account) where I can contribute / merge my code?

**Comment by ramonfontes** [comment]
Upload? Why don't you use pull request? You cannot create branches/neither
make changes directly to my repo.

2018-02-23 8:22 GMT-03:00 Hildo Guillardi Júnior <notifications@github.com>:

**Comment by hildogjr** [comment]
Ok.
Now I forked. I don't why, but I remember that the last repository that I branch created the fork automatically when I try to upload.

Now I can upload to my account and after give a "pull request".
