### ISSUE TITLE
help first run of  mininet-wifi

### ISSUE THREAD

**Issue by dkalog** [intrig-unicamp/mininet-wifi#156]
Hi *,
Congrats for the nice work.

I am trying to replicate the basic setup either importing the ova or compiling from a clear ubuntu/xenial64. 
In both case the initial-first execution fails (Everything works fine with the import of  ova in virtualbox.) When I open a terminal   sudo mn --wifi    I receive... 

~$ sudo mn --wifi
*** Creating network
*** Adding controller
--------------------------------------------------------------------------------
Caught exception. Cleaning up...

Exception: Please shut down the controller which is running on port 6653:
Active Internet connections (servers and established)
tcp        0      0 0.0.0.0:6653            0.0.0.0:*               LISTEN      17579/ovs-testcontr
tcp        0      0 127.0.0.1:36456         127.0.0.1:6653          TIME_WAIT   -
--------------------------------------------------------------------------------
*** Removing excess controllers/ofprotocols/ofdatapaths/pings/noxes
killall controller ofprotocol ofdatapath ping nox_corelt-nox_core ovs-openflowd ovs-controllerovs-testcontroller udpbwtest mnexec ivs ryu-manager 2> /dev/null
killall -9 controller ofprotocol ofdatapath ping nox_corelt-nox_core ovs-openflowd ovs-controllerovs-testcontroller udpbwtest mnexec ivs ryu-manager 2> /dev/null
pkill -9 -f "sudo mnexec"
*** Removing junk from /tmp
rm -f /tmp/vconn* /tmp/vlogs* /tmp/*.out /tmp/*.log
*** Removing old X11 tunnels
*** Removing excess kernel datapaths
ps ax | egrep -o 'dp[0-9]+' | sed 's/dp/nl:/'
***  Removing OVS datapaths
ovs-vsctl --timeout=1 list-br
ovs-vsctl --timeout=1 list-br
*** Removing all links of the pattern foo-ethX
ip link show | egrep -o '([-_.[:alnum:]]+-eth[[:digit:]]+)'
ip link show
*** Killing stale mininet node processes
pkill -9 -f mininet:
*** Shutting down stale tunnels
pkill -9 -f Tunnel=Ethernet
pkill -9 -f .ssh/mn
rm -f ~/.ssh/mn/*
*** Cleanup complete.
***  Removing WiFi module and Configurations
pkill -9 -f hostapd
*** Killing wmediumd
pkill wmediumd

What do you suggest ?

**Comment by ramonfontes** [comment]
The message says: "please shutdown the controller which is running on port 6653".

Have you ever tried to kill its process (e.g. sudo fuser -k 6653/tcp)?

**Comment by dkalog** [comment]
Thank a lot. 
Each time the VM reboots there is a process ovs-testcontrol connected to this port :-/  .. I don't know if it is possible to disable ovs-testcontrol  .. ( I would suggest somehow to incorporate this in you install/check script...)
