### ISSUE TITLE
Packet Loss Rate

### ISSUE THREAD

**Issue by iamxg** [intrig-unicamp/mininet-wifi#160]
Hi Ramon,
How are you? 
I hope to analysis packet loss rate caused by collision in MANET. Could you give me some advices?
Thanks a lot!
Xian Guo.

**Comment by ramonfontes** [comment]
Hi Xian,

Is there any problem are you facing with any code?

**Comment by iamxg** [comment]
Hi Ramon,
Ok, Thank you very much. I am reading codes about this module.
Best Regards,
Xian Guo

**Comment by iamxg** [comment]
Hi Ramon,
I read codes in link.py. But I don't make sense which functions call functions setLoss(), tc() or when these codes will be executed. Can you give me a simple explain?  Thanks a lot!
Best Regards,
Xian Guo

**Comment by ramonfontes** [comment]
Dear,

This is not an issue! Please use the mainling list for such questions.
