### ISSUE TITLE
Mininet_wifi Warnings!!--AttributeError: 'Mininet' object has no attribute 'addBaseStation'

### ISSUE THREAD

**Issue by ozgrcglr** [intrig-unicamp/mininet-wifi#161]
when I wanted to create my own topoly, I saw an error code; 

AttributeError: 'Mininet' object has no attribute 'addBaseStation'

I tried a lot of different ways for solving the problem but It didn't work..

**Comment by ramonfontes** [comment]
addBaseStation is deprecated. Use addAccessPoint() instead. Please refer to
the sample files at /examples.

**Comment by ozgrcglr** [comment]
I tried all the things..But it doesnt work
AttributeError: 'Mininet' object has no attribute 'addAccessPoint'

**Comment by ramonfontes** [comment]
Are you sure you have installed Mininet-WiFi? Isn't Mininet? Is sudo mn
--wifi working?

**Comment by ozgrcglr** [comment]
it works like that..I have installed..

ubuntu@ubuntu:~/mininet-wifi$ sudo mn --wifi
[sudo] password for ubuntu: 
*** Creating network
*** Adding controller
*** Adding hosts and stations:
sta1 sta2 
*** Adding switches and access point(s):
ap1 
*** Configuring wifi nodes...

*** Adding link(s):
(sta1, ap1) (sta2, ap1) 
*** Configuring nodes
*** Starting controller(s)
c0 
*** Starting switches and/or access points
ap1 ...
*** Starting CLI:

**Comment by ramonfontes** [comment]
So, when is the problem occurring?

**Comment by ozgrcglr** [comment]
when I tried to write my own topology it occurs..

firstly I copied the example code which name is position-test.py  this site:

http://www.brianlinkletter.com/mininet-wifi-software-defined-network-emulator-supports-wifi-networks/


after I saved it, I moved it in /home/ubuntu/mininet-wifi/examples
and I wrote sudo python position-test.py
and BUMMM.. ERROR

**Comment by ramonfontes** [comment]
Did you update your script? I suppose that changes in your code are
required. That's why I told you to take scripts at /examples as reference
to make your script work.

**Comment by ozgrcglr** [comment]
ok.. I start to try it..

**Comment by ramonfontes** [comment]
IMPORTANT NOTE

(Updated October 20, 2017) Since I wrote this post two years ago, the
Mininet-WiFi developers have continued to add a lot of functionality to
Mininet-WiFi. Some of the information in this post may be outdated and no
longer accurate. *Please refer to the Mininet-WiFi documentation
<https://github.com/intrig-unicamp/mininet-wifi> for up-to-date information
about this project.* At the top of that page is a link to the Mininet-WiFi
manual, which is currently hosted at:
https://github.com/ramonfontes/manual-mininet-wifi/raw/master/mininet-wifi-draft-manual.pdf
.

Source:
http://www.brianlinkletter.com/mininet-wifi-software-defined-network-emulator-supports-wifi-networks/

**Comment by ozgrcglr** [comment]
I did all things..
This is errors:
u

```
buntu@ubuntu:~/mininet-wifi/examples$ sudo python position-test2.py 
*** Creating nodes
Traceback (most recent call last):
  File "position-test2.py", line 52, in <module>
    topology()
  File "position-test2.py", line 17, in topology
    ap1 = net.AccessPoint( 'ap1', ssid='new-ssid', mode= 'g', channel= '1', position='10,30,0', range='20' )
AttributeError: 'Mininet_wifi' object has no attribute 'AccessPoint'
```

**this is my codes... It does not work..** 

#!/usr/bin/python

import sys

from mininet.node import Controller
from mininet.log import setLogLevel, info
from mininet.wifi.node import OVSKernelAP
from mininet.wifi.cli import CLI_wifi
from mininet.wifi.net import Mininet_wifi


def topology():

    net = Mininet_wifi(controller=Controller, accessPoint=OVSKernelAP)

    print "*** Creating nodes"
    ap1 = net.AccessPoint( 'ap1', ssid='new-ssid', mode= 'g', channel= '1', position='10,30,0', range='20' )
    ap2 = net.AccessPoint( 'ap2', ssid='new-ssid', mode= 'g', channel= '6', position='50,30,0', range='20' )
    sta1 = net.addStation( 'sta1', mac='00:00:00:00:00:01', ip='10.0.0.1/8', position='10,20,0' )
    sta2 = net.addStation( 'sta2', mac='00:00:00:00:00:02', ip='10.0.0.2/8', position='50,20,0' )
    c1 = net.addController( 'c1', controller=Controller )

    print"*** configuring wifi noders"
    net.configureWifiNodes()

    """plot graph"""
    net.plotGraph(max_x=60, max_y=60)

    # Comment out the following two lines to disable AP
    print "*** Enabling association control (AP)"
    net.associationControl( 'ssf' )

    print "*** Creating links and associations"
    net.addLink( ap1, ap2 )
    net.addLink( ap1, sta1 )
    net.addLink( ap2, sta2 )

    print "*** Starting network"
    net.build()
    c1.start()
    ap1.start( [c1] )
    ap2.start( [c1] )

    print "*** Running CLI"
    CLI_wifi( net )

    print "*** Stopping network"
    net.stop()

if __name__ == '__main__':
    setLogLevel( 'info' )
    topology()

**Comment by ramonfontes** [comment]
Dear,

There is no AccessPoint() :(. Have you ever tried addAccessPoint(), instead?
