### ISSUE TITLE
Controller installation mininet wifi

### ISSUE THREAD

**Issue by ozgrcglr** [intrig-unicamp/mininet-wifi#163]
Hello;

I want to try different controller (pox-opendaylight etc) on mininet-wifi..

I read the mininet wifi-draft-manual but they havent written anything about  how to different controller run and installation  on mininet-wifi.

**Comment by ramonfontes** [comment]
Hello,

You can install/use any controller you want. There is no specific step on
how  to install them with Mininet-WiFi. Once you have the controller you
want, configure a remote controller in Mininet-WiFi and connect to your
controller by means of its port.


2018-04-09 10:21 GMT-03:00 ozgrcglr <notifications@github.com>:

**Comment by ozgrcglr** [comment]
Thank you ramon..It works..
