### ISSUE TITLE
transfer openflow data to controller

### ISSUE THREAD

**Issue by gash9118787** [intrig-unicamp/mininet-wifi#164]
I use ryu as my controller. When open vswitch ap transfers openflow data to the controller, how can I modify the flow_stat_reply or port_stat_reply that the ap can transmit?

**Comment by ramonfontes** [comment]
Please refer the OpenFlow specification.

**Comment by gash9118787** [comment]
I have already known the openflow protocol, so can I modify the data that open vswitch ap sends to the controller in mininet-wifi? Or what program is related to openflow in mininet-wifi?

**Comment by ramonfontes** [comment]
Yes, you can. Please refer to the openflow specification.
