### ISSUE TITLE
SDN based cellular network support in Mininet Wifi

### ISSUE THREAD

**Issue by memran2** [intrig-unicamp/mininet-wifi#166]
I would like to know that does Mininet Wifi Provide support for SDN based Cellular Network if not then with which simulator Mininet Wifi should be integrated so that we can study the Hand over between SDN based Wifi and SDN based Cellular networks.

**Comment by ramonfontes** [comment]
This is not an issue. I suggest you to get into our mailing. You will find
the answer for your question there.

**Comment by ramonfontes** [comment]
I think I already sent it privately to you, no?

https://github.com/intrig-unicamp/mininet-wifi#mailing-list

2018-04-28 14:24 GMT-03:00 memran2 <notifications@github.com>:

**Comment by memran2** [comment]
subscribed many thanks dear
