### ISSUE TITLE
ping problem in mininet-wifi

### ISSUE THREAD

**Issue by as74150** [intrig-unicamp/mininet-wifi#167]
Please help me Sir:
I am emulating a shortest path use Ryu in this emulator, but it dosen't work well. So I printed my log and found in Mininet-wifi sta1 ping sta2, the packet-in message was sta1 to ff:ff:ff:ff:ff:ff(broadcast), but in Mininet was sta1 to sta2. Please give me some suggestion. Thanks a lot!

Best wishes,
Qin

**Comment by ramonfontes** [comment]
Could you provide more details about the issue?

**Comment by as74150** [comment]
First， I'm thanks for you to reply my question.
I used mininet-wifi emulating two APs and two STAs with Ryu controller,the simple topology is： 
              ________C0________
              |                           |
           AP1----------------AP2
             |                            |
          STA1                     STA2
STA1(mac=00:00:00:00:00:02)  STA2(mac=00:00:00:00:00:03)
the Ryu controller runs an shortest path app witch use networkx. The problem is that When I run mininet-wifi to create a network，in CIL input： sta1 ping sta2 ，the packet-in message is just：
packet in 1 00:00:00:00:00:02 ff:ff:ff:ff:ff:ff 1
but in mininet，the packet-in message has：packet in 1 00:00:00:00:00:02 00:00:00:00:00:03 1
I don't kown why it happens and I help to get some suggestions. thanks a lot！

PS:the code of the topology:
#!/usr/bin/python

'Setting the position of Nodes and providing mobility using mobility models'

from mininet.node import RemoteController
from mininet.log import setLogLevel, info
from mininet.wifi.node import OVSKernelAP
from mininet.wifi.cli import CLI_wifi
from mininet.wifi.net import Mininet_wifi

def topology():
    "Create a network."
    net = Mininet_wifi(controller=RemoteController, accessPoint=OVSKernelAP)

    info("*** Creating nodes\n")
    sta1 = net.addStation('sta1', mac='00:00:00:00:00:02', ip='10.0.0.2/8',
                   min_x=10, max_x=30, min_y=50, max_y=70, min_v=5, max_v=10, range=10)
    sta2 = net.addStation('sta2', mac='00:00:00:00:00:03', ip='10.0.0.3/8',
                   min_x=10, max_x=30, min_y=50, max_y=70, min_v=5, max_v=10, position='160,72,0', range=10)
    ap1 = net.addAccessPoint('s1', ssid='ssid1', mode='g', channel='1', range=60,
                             position='50,50,0', protocols='OpenFlow13')
    ap2= net.addAccessPoint('s2', ssid='ssid2', mode='g', channel='6', range=60,
                             position='180,65,0', protocols='OpenFlow13')
    c1 = net.addController('c1', controller=RemoteController, ip='172.23.22.113')
    #, ip = '172.23.22.99'

    net.addLink(ap1, ap2)
    net.addLink(ap1, sta1)
    net.addLink(ap1, sta2)

    info("*** Configuring wifi nodes\n")
    net.configureWifiNodes()

    net.plotGraph(max_x=300, max_y=300)

    net.startMobility(time=0, model='RandomDirection', max_x=100, max_y=100,
                      seed=20)

    info("*** Starting network\n")
    net.build()
    c1.start()
    ap1.start([c1])
    ap2.start([c1])

    info("*** Running CLI\n")
    CLI_wifi(net)

    info("*** Stopping network\n")
    net.stop()


if __name__ == '__main__':
    setLogLevel('info')
    topology()

**Comment by ramonfontes** [comment]
Could you share the pcap file?

**Comment by as74150** [comment]
OK,I'll send the result to you via your gmail, thanks a lot.

**Comment by JohnnyQuach95** [comment]
I have a problem. When I type " h1 ping h1" in mininet. It Ping and Ping nonstop. I don't know why and I cannot stop it. I can only shutdown mininet.
