### ISSUE TITLE
error in loading mac80211_hwsim

### ISSUE THREAD

**Issue by Mwdan123** [intrig-unicamp/mininet-wifi#169]
Sir, please help me, this kind of error(mentioned below) is always showing after installing the latest mininet-wifi, even after I run "sudo mn -c", it shows like that... but it works findly when I run "sudo mn ". I tried many times by installing again and again.... pls help me Sir, Thank you.

#sudo mn --wifi
[sudo] password for sdn: 
*** Creating network
*** Adding controller
*** Adding hosts/stations:
sta1 sta2 
*** Adding switches/access points:
ap1 
*** Configuring wifi nodes...
insmod: ERROR: could not load module None: No such file or directory
Warning! Error when loading mac80211_hwsim. Please run sudo 'mn -c' before running your code.
Further information available at /tmp/mininetwifi-mac80211_hwsim.log.

content of the "/tmp/mininetwifi-mac80211_hwsim.log." like below-

2018-05-09 21:44:55,006 - ERROR - Warning:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/mininet_wifi-2.2.1d1-py2.7.egg/mininet/wifi/module.py", line 247, in assign_iface
    '| tr -d ":"' % phys[0], shell=True).split('\n')
IndexError: list index out of range

**Comment by Mwdan123** [comment]
Sir I am using ubuntu 14.04 LTS

**Comment by Mwdan123** [comment]
Actually, the older version of mininet-wifi was working perfectly. Is that ubuntu 14.04 LTS not compatible for latest mininet-wifi ?

**Comment by ramonfontes** [comment]
Yes, it is. However, it seems that you have problem with mac80211_hwsim.

**Comment by Mwdan123** [comment]
Is there any way to compile mac80211_hwsim  natively as you said ?.

**Comment by ramonfontes** [comment]
Please try `sudo modprobe mac80211_hwsim radios=2` and also `sudo mn --wifi -v debug`.

**Comment by Mwdan123** [comment]
$ sudo mn --wifi -v debug 
*** errRun: ['which', 'controller'] 
/usr/local/bin/controller
  0*** Setting resource limits
*** Creating network
*** Adding controller
*** errRun: ['which', 'mnexec'] 
/usr/bin/mnexec
  0*** errRun: ['which', 'ip', 'addr'] 
/sbin/ip
  1*** c0 : ('unset HISTFILE; stty -echo; set +m',)
unset HISTFILE; stty -echo; set +m
*** errRun: ['which', 'telnet'] 
/usr/bin/telnet
  0*** c0 : ('echo A | telnet -e A 127.0.0.1 6653',)
Telnet escape character is 'A'.
Trying 127.0.0.1...
telnet: Unable to connect to remote host: Connection refused
*** Adding hosts/stations:
*** errRun: ['which', 'mnexec'] 
/usr/bin/mnexec
  0*** errRun: ['which', 'ip', 'addr'] 
/sbin/ip
  1*** sta1 : ('unset HISTFILE; stty -echo; set +m',)
unset HISTFILE; stty -echo; set +m
sta1 *** sta2 : ('unset HISTFILE; stty -echo; set +m',)
unset HISTFILE; stty -echo; set +m
sta2 
*** Adding switches/access points:
*** errRun: ['which', 'ovs-vsctl'] 
/usr/bin/ovs-vsctl
  0*** errRun: ['ovs-vsctl', '-t', '1', 'show'] 
08534505-a353-48fc-b9d8-2a49ebfe7110
    ovs_version: "2.0.2"
  0*** errRun: ['ovs-vsctl', '--version'] 
ovs-vsctl (Open vSwitch) 2.0.2
Compiled Dec  9 2015 14:08:08
  0*** ap1 : ('unset HISTFILE; stty -echo; set +m',)
unset HISTFILE; stty -echo; set +m

added intf lo (0) to node ap1
*** ap1 : ('ip link set', 'lo', 'up')
ap1 
*** Configuring wifi nodes...
Loading 3 virtual wifi interfaces
insmod: ERROR: could not load module None: No such file or directory
find: `/sys/kernel/debug/ieee80211': No such file or directory

*** Configuring interfaces with appropriated network-namespaces...
Warning! Error when loading mac80211_hwsim. Please run sudo 'mn -c' before running your code.
Further information available at /tmp/mininetwifi-mac80211_hwsim.log.

$ sudo modprobe mac80211_hwsim radios=2
[sudo] password for ubuntu14: 
modprobe: ERROR: ../libkmod/libkmod.c:556 kmod_search_moddep() could not open moddep file '/lib/modules/3.13.0-32-generic/modules.dep.bin'

**Comment by ramonfontes** [comment]
According the msg you don't have ieee80211:
`find: /sys/kernel/debug/ieee80211': No such file or directory`

If you don't have ieee80211, you don't have mac80211_hwsim.

**Comment by Mwdan123** [comment]
ok sir, Actually its running on oracle virtualbox and the host machine is Windows 7 ultimte(Laptop). Is this very necessary to have ieee80211 device physically??

**Comment by ramonfontes** [comment]
As I mentioned earlier it is compiled by default. I really don't know why you don't have it.

**Comment by Mwdan123** [comment]
yes sir, It should be compiled by default as I used earlier.

**Comment by Mwdan123** [comment]
I think my issue may have some relation with following--

**** Consider update on your install.sh script #157**** which is third issue from top..!!!
