### ISSUE TITLE
Undefined reference to self.stations causes crash when using vanilla Mininet

### ISSUE THREAD

**Issue by AndrewC-B** [intrig-unicamp/mininet-wifi#172]
`self.stations` is initialised in the `Mininet_Wifi` class but not in the `Mininet` class. Thus, this line causes a crash when using vanilla Mininet (`AttributeError: 'Mininet' object has no attribute 'stations'`). 

https://github.com/intrig-unicamp/mininet-wifi/blob/ba085b026c50877ab717baa96ffc3064f760a599/mininet/net.py#L654

I'm curious to know why the `self.stations` reference is even there, as `Mininet_Wifi` overrides `ping()`. I suggest removing this reference, and I'm happy to submit a pull request which does this.

**Comment by ramonfontes** [comment]
Yep. `Mininet_Wifi` overrides `ping()` and that reference can be removed. :)

**Comment by AndrewC-B** [comment]
Great! 

https://github.com/intrig-unicamp/mininet-wifi/pull/173
