### ISSUE TITLE
airodump-ng does not detect all available wireless networks

### ISSUE THREAD

**Issue by SvetlomirPetrov** [intrig-unicamp/mininet-wifi#176]
Hi,

I use your platform to emulate wireless network for an Ethical Hacking course. I managed to do that but the level of realism is low so I tried to improve it by adding more networks but have an issue. Here is the setup:

1. The students login to a station created by mininet-wifi - Sta3.
2. Scan the air for available networks and see two SSIDs: a hackable and unhackable one.
3. Capture some traffic into a dump file which contains WPA handshake from the hackable network.
4. Crack the password with a dictionary attack.

The setup works great, they can capture the WPA handshake and perform the hack but the issue is that one cannot see the two networks with:
```
airmon-ng start sta3-wlan0
airodump-ng mon0
```
but is able to do it with:
`iw dev sta3-wlan0 scan`

Do you have any ideas why this does happen?

Here is the python script:
[hack.py.zip](https://github.com/intrig-unicamp/mininet-wifi/files/2108168/hack.py.zip)

**Comment by ramonfontes** [comment]
Hi,

Could you provide more detail about _why the level of realism is low_? Regarding your code, I have some suggestions:

- (i) Only aps have position. I suggest you to do the same with stations.
- (ii) If I were you, I'd use wmediumd.
- (iii) If sta1 can reach ap1, net.addLink(sta1, ap1), etc. isn't required.
- (iv) you didn't start s1 with any controller.

**Comment by SvetlomirPetrov** [comment]
In the initial version, only one AP was available with a dummy password. One of its stations disconnects every 5-10 secs so one is able to capture the handshake fastly. Then I decided to add more AP's in the same fashion but with stronger passwords otherwise, it is obvious which network has to be cracked so the students can feel the frustration :)

Thanks for the suggestions! I have no idea what is wmediumd and how to useit, just followed one of your examples - authentication.py where you use net.addLink(). I tried to add positions to the stations but this had no effect on the issue, the same is with starting s1 with a controller.

This is a simplified logical setup that I want to achieve:
![setup](https://user-images.githubusercontent.com/2814912/41499463-d44d16be-7180-11e8-8dbd-09c4589d9f32.png)
So the student can see more than 1 networks with airodump-ng.

**Comment by ramonfontes** [comment]
Cool! 

I just tested airmon-ng and airodump-ng and it worked with wmediumd_interference.py. There you can see how you can enable wmediumd. You have to basically set the link as wmediumd.

**Comment by SvetlomirPetrov** [comment]
As far as I understoond, I added the below line:

`from mininet.wifi.link import wmediumd`

and appended link=wmediumd:

`net = Mininet_wifi(controller=Controller, accessPoint=UserAP, link=wmediumd)`

But now I see nothing both with iw and airodump.

**Comment by ramonfontes** [comment]
Dear,

How are you doing this? You're going to the node you want and there you type `airmon-ng start sta3-wlan0` and `airodump-ng mon0`, right?

**Comment by SvetlomirPetrov** [comment]
Yep.

**Comment by ramonfontes** [comment]
Is [this](https://intrig.dca.fee.unicamp.br:8840/owncloud/index.php/s/JJuZcokw1cFDja0) the behavior you want?

**Comment by SvetlomirPetrov** [comment]
Exactly this one :)

**Comment by ramonfontes** [comment]
So, It's working.. :)

**Comment by SvetlomirPetrov** [comment]
I tried to build my setup on top of wmediumd_interference.py as I did with authentication.py. Unfortunately, I cannot run any of the wmediumd examples but the rest examples work as expected. Obviously, there is something wrong. I will try with a clean install of mininet-wifi in the next days.

Thanks for the help!
