### ISSUE TITLE
Make "ugly way to check if wired/wireless topo" not case sensitive

### ISSUE THREAD

**Issue by zephyrmoth** [intrig-unicamp/mininet-wifi#178]
[The check for whether a topology is wired or wireless](https://github.com/intrig-unicamp/mininet-wifi/blob/8b9c2b7237e754f7ec177e947d58466cf03d533d/mininet/wifi/net.py#L644) will break on any topology which imports from WifiTopo but does not share the same path, which can lead to unexpected behavior in derivative code.

**Comment by ramonfontes** [comment]
I think this [commit](https://github.com/intrig-unicamp/mininet-wifi/commit/ee754348d370df29fd742996354e37b7ab80f5bc) will work better after applying more changes from #177 .
