### ISSUE TITLE
Promblem:Exception: Please shut down the controller which is running on port 6653:

### ISSUE THREAD

**Issue by benaicode** [intrig-unicamp/mininet-wifi#180]
Hello,I am a new guy of mininet-wifi. I have tried many ways to solve this problem---"Exception: Please shut down the controller which is running on port 6653". And below,it's my output after enter 'sudo mn'.

cheng@ChengMininet:~/mininet-wifi$ sudo mn
*** Creating network
*** Adding controller
--------------------------------------------------------------------------------
Caught exception. Cleaning up...

Exception: Please shut down the controller which is running on port 6653:
激活Internet连接 (服务器和已建立连接的)
tcp        0      0 0.0.0.0:6653            0.0.0.0:*               LISTEN      19623/ovs-testcontr 
tcp        0      0 127.0.0.1:36716         127.0.0.1:6653          TIME_WAIT   -                   
--------------------------------------------------------------------------------
*** Removing excess controllers/ofprotocols/ofdatapaths/pings/noxes
killall controller ofprotocol ofdatapath ping nox_corelt-nox_core ovs-openflowd ovs-controllerovs-testcontroller udpbwtest mnexec ivs ryu-manager 2> /dev/null
killall -9 controller ofprotocol ofdatapath ping nox_corelt-nox_core ovs-openflowd ovs-controllerovs-testcontroller udpbwtest mnexec ivs ryu-manager 2> /dev/null
pkill -9 -f "sudo mnexec"
*** Removing junk from /tmp
rm -f /tmp/vconn* /tmp/vlogs* /tmp/*.out /tmp/*.log
*** Removing old X11 tunnels
*** Removing excess kernel datapaths
ps ax | egrep -o 'dp[0-9]+' | sed 's/dp/nl:/'
***  Removing OVS datapaths
ovs-vsctl --timeout=1 list-br
ovs-vsctl --timeout=1 list-br
*** Removing all links of the pattern foo-ethX
ip link show | egrep -o '([-_.[:alnum:]]+-eth[[:digit:]]+)'
ip link show
*** Killing stale mininet node processes
pkill -9 -f mininet:
*** Shutting down stale tunnels
pkill -9 -f Tunnel=Ethernet
pkill -9 -f .ssh/mn
rm -f ~/.ssh/mn/*
*** Cleanup complete.
***  Removing WiFi module and Configurations
pkill -9 -f hostapd
*** Killing wmediumd
pkill wmediumd
***  Removing fakelb module and Configurations

I'm very upset now.I hope a guy can help me.

**Comment by ramonfontes** [comment]
I suggest you to go through the mailing list or even the user manual. That's not an issue.

**Comment by benaicode** [comment]
thank you so much
