### ISSUE TITLE
how to use info commend to get received signal strength

### ISSUE THREAD

**Issue by sunminming** [intrig-unicamp/mininet-wifi#182]
when i use"sta1 iw sta1 dev sta1-wlan0 info",i can only find "txpower"

**Comment by ramonfontes** [comment]
Is sta1 associated with any ap?

**Comment by sunminming** [comment]
yes.i use “mn --wifi" to create this network
```
mininet-wifi> py sta1.params['associatedTo']
[<OVSAP ap1: lo:127.0.0.1,ap1-wlan1:None pid=7704> ]
mininet-wifi> sta1 iw dev sta1-wlan0 info
Interface sta1-wlan0
	ifindex 5
	wdev 0x1
	addr 02:00:00:00:00:00
	ssid my-ssid
	type managed
	wiphy 0
	channel 1 (2412 MHz), width: 20 MHz (no HT), center1: 2412 MHz
	txpower 14.00 dBm
```

**Comment by ramonfontes** [comment]
You may want to use `link` instead of `info`.

**Comment by ramonfontes** [comment]
Are you using wmediumd as a link?

**Comment by sunminming** [comment]
This problem is solved, thank you for your help.I did miss the "link" parameter.I have another question, i run `position-test.py` in section 4.5 of manual,there is an error:Error: `tx power is negative! (-21)`.Only when i delete the range of ap or set propagation model ,it can run.And i can't set range of ap by using python api :`py ap1.setRange(100,intf='ap1-wlan1')`

**Comment by ramonfontes** [comment]
Actually, this is not a problem, right? Considering that these questions aren't an issue at all, I will suggest you to get into our mailing list. You can find answers for all the questions you have there.

**Comment by sunminming** [comment]
ok,thank you again for your help
