### ISSUE TITLE
Python 3 module location

### ISSUE THREAD

**Issue by tterranigma** [intrig-unicamp/mininet-wifi#184]
I am installing mininet with the `-P` flag. When I try to run a python3 script with the line: 

```python
from mininet.node import Controller
```

I get an error that the `mininet` module was not found. Indeed the mininet module is installed under `/usr/lib/local/python.2.7`. This is on Ubuntu 17.10.

I am doing sth wrong?

**Comment by ramonfontes** [comment]
Hi,

Which Python version you are using (python -v)?

**Comment by tterranigma** [comment]
It is `Python 3.6.3`. I have set the script as executable and the shebang line reads:

```
#!/usr/bin/env python3
```

**Comment by tterranigma** [comment]
I am also using the master branch of mininet-wifi.

**Comment by ramonfontes** [comment]
Can you run sudo mn --wifi? (you don't need to make changes in scripts).

alpha@alpha-Inspiron:~$ `python --version`
Python 3.5.2

alpha@alpha-Inspiron:~$ `sudo mn --wifi`
*** Creating network
*** Adding controller
*** Adding stations:
sta1 sta2 
*** Adding access points:
ap1 
*** Configuring wifi nodes...

*** Adding link(s):
(sta1, ap1) (sta2, ap1) 
*** Configuring nodes
*** Starting controller(s)
c0 
*** Starting switches and/or access points
ap1 ...
*** Starting CLI:
mininet-wifi> exit
*** Stopping 1 controllers
c0 
*** Stopping 2 links
..
*** Stopping switches/access points
ap1 
*** Stopping nodes
sta1 sta2 
*** Killing hostapd
*** Killing mac80211_hwsim

*** Done
completed in 2.969 seconds
alpha@alpha-Inspiron:~$ `sudo python examples/position.py `
*** Creating nodes
*** Configuring wifi nodes
*** Creating links
*** Starting network
*** Configuring nodes
*** Running CLI
*** Starting CLI:
mininet-wifi> exit
*** Stopping network
*** Stopping 1 controllers
c1 
*** Stopping 3 links
...
*** Stopping switches/access points
ap1 
*** Stopping nodes
h1 sta1 sta2 
*** Killing hostapd
*** Killing mac80211_hwsim

*** Done

**Comment by tterranigma** [comment]
I am getting different results. Below I always use the `-P` flag.

First, I spinned a new Ubuntu 17.10. vm. There, I set the the `/usr/bin/python` symlink to point to `/usr/bin/python3`. Then, I tried to compile using `sudo util/install.sh -WlnfvP`. But I get the following error:

```
Setting up python-pexpect (4.2.1-1) ...
Traceback (most recent call last):
  File "/usr/bin/pip2", line 9, in <module>
    from pip import main
ModuleNotFoundError: No module named 'pip'
```

Next try, I install mininet on a clean install of Ubuntu 17.10 without messing with the python symlink. Installation completes and then I change the symlink. I get this:

```
printer@qqq-main-honeyd:~$ sudo mn --wifi
Traceback (most recent call last):
  File "/usr/local/bin/mn", line 4, in <module>
    __import__('pkg_resources').run_script('mininet-wifi===2.2.1d1', 'mn')
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 3049, in <module>
    @_call_aside
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 3033, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 3062, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 658, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 972, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 858, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'mininet-wifi===2.2.1d1' distribution was not found and is required by the application
```

Finally, I install and run without messing with the python symlink at all. `mn --wifi` runs fine (I suppose using python2.)

**Comment by ramonfontes** [comment]
Can you install `pip` manually?

**Comment by ramonfontes** [comment]
You can try "sudo make install" as well.

**Comment by tterranigma** [comment]
OK, this is what I tried next. On a fresh install of Ubuntu 17.10 I installed pip3 and set the `/usr/bin/python` and `/usr/bin/pip` symlinks to point to python 3 versions. Then, I installed the mininet-wifi with:

```
sudo util/install.sh -WlnfvP
```

I had to manually install the following:

```
sudo pip install matplotlib
sudo pip install numpy
sudo pip install scipy
sudo apt-get install python3-tk
```

The installation was then successful. 

However, when I run `mn --wifi` I get:

```
*** Creating network
*** Adding controller
*** Adding stations:
sta1 sta2 
*** Adding access points:
ap1 
*** Configuring wifi nodes...
insmod: ERROR: could not load module None: No such file or directory
find: ‘/sys/kernel/debug/ieee80211’: No such file or directory
Warning! Error when loading mac80211_hwsim. Please run sudo 'mn -c' before running your code.
Further information available at /tmp/mininetwifi-mac80211_hwsim.log.
```

The contents of the log file mentioned is:

```
root@instance-2:/tmp# cat mininetwifi-mac80211_hwsim.log 
2018-08-04 13:44:34,259 - ERROR - Warning:
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/mininet_wifi-2.2.1d1-py3.6.egg/mn_wifi/module.py", line 251, in assign_iface
    '| tr -d ":"' % phys[0],
IndexError: list index out of range
```

I get the same error when I run `sudo python examples/position.py`.

Other than falling back to python2, I am out of ideas.

**Comment by tterranigma** [comment]
Also, the python module now is located under `/usr/local/lib/python3.6`.

I also had to install `linux-image-extra-$(uname -r)`. Then, I rebooted. These were all the steps I have taken I think.

**Comment by ramonfontes** [comment]
Strange.. it works with python2 and with the following error?

insmod: ERROR: could not load module None: No such file or directory
find: ‘/sys/kernel/debug/ieee80211’: No such file or directory

It seems that you don't have ieee80211 installed. Are you sure you have mac80211_hwsim?

**Comment by ramonfontes** [comment]
Yes, `-P` should do everything with python3. Have you tried `-PWlnfv`? In fact, I think `-WlnfvP` doesn't work. The order of the flags makes difference.

Please try the latest commit and let me know if it works..

**Comment by tterranigma** [comment]
It installs without problems with a fresh git clone. Thanks for the great support!

**Comment by tterranigma** [comment]
I am sorry to re-open this, but sth still is off. I am using Ubuntu 18.04 now on Google Cloud. Python 2 is not installed there by default. 

What I do is check that Python 3 is installed, symlink `/usr/bin/python` to `/usr/bin/python3`, install `python3-pip` and symlink `/usr/bin/pip` to `/usr/bin/pip3`. 

Then, I run `util/install.sh -Wlnfv` and wait. The install fails consistently with:

```
Installed /usr/local/lib/python2.7/dist-packages/mininet-2.3.0d2-py2.7.egg
Processing dependencies for mininet===2.3.0d2
Searching for setuptools==39.0.1
Best match: setuptools 39.0.1
Adding setuptools 39.0.1 to easy-install.pth file
Installing easy_install script to /usr/local/bin
Using /usr/lib/python2.7/dist-packages
Finished processing dependencies for mininet===2.3.0d2
/home/tterranigma/mininet-wifi /home/tterranigma /home/tterranigma /home/tterranigma/mininet-wifi /home/tterranigma/mininet-wifi/hostap/wpa_supplicant /home/tterranigma/mininet-wifi/hostap/hostapd /home/tterranigma/mininet-wifi/hostap /home
/tterranigma/mininet-wifi /home/tterranigma/mininet-wifi
Installing Mininet-wifi core
/home/tterranigma/mininet-wifi /home/tterranigma/mininet-wifi /home/tterranigma /home/tterranigma /home/tterranigma/mininet-wifi /home/tterranigma/mininet-wifi/hostap/wpa_supplicant /home/tterranigma/mininet-wifi/hostap/hostapd /home/tterra
nigma/mininet-wifi/hostap /home/tterranigma/mininet-wifi /home/tterranigma/mininet-wifi
cc -Wall -Wextra  -DVERSION=\"`PYTHONPATH=. python -B bin/mn --version`\" mnexec.c -o mnexec
Traceback (most recent call last):
  File "bin/mn", line 45, in <module>
    from mn_wifi.net import MininetWithControlNet
  File "./mn_wifi/net.py", line 37, in <module>
    from mn_wifi.mobility import mobility
  File "./mn_wifi/mobility.py", line 13, in <module>
    from mn_wifi.plot import plot2d, plot3d, plotGraph
  File "./mn_wifi/plot.py", line 11, in <module>
    import matplotlib.patches as patches
ImportError: No module named matplotlib.patches
install -D mnexec /usr/bin/mnexec
PYTHONPATH=. help2man -N -n "create a Mininet network." \
--no-discard-stderr "python -B bin/mn" -o mn.1
help2man -N -n "execution utility for Mininet." \
-h "-h" -v "-v" --no-discard-stderr ./mnexec -o mnexec.1
install -D -t /usr/share/man/man1 mn.1 mnexec.1
python setup.py install
Traceback (most recent call last):
  File "setup.py", line 11, in <module>
    from mn_wifi.net import VERSION
  File "/home/tterranigma/mininet-wifi/mn_wifi/net.py", line 37, in <module>
    from mn_wifi.mobility import mobility
  File "/home/tterranigma/mininet-wifi/mn_wifi/mobility.py", line 13, in <module>
    from mn_wifi.plot import plot2d, plot3d, plotGraph
  File "/home/tterranigma/mininet-wifi/mn_wifi/plot.py", line 11, in <module>
    import matplotlib.patches as patches
ImportError: No module named matplotlib.patches
Makefile:58: recipe for target 'install' failed
make: *** [install] Error 1
```

For some reason, Python 2 is installed by the script and then used as default. What could be wrong here?

**Comment by tterranigma** [comment]
I used the `alternatives` program to set Python3 as the default version instead of creating the symlinks manually and it worked. Previously, some python2 packages that are installed during the install process would set the system-wide python version to python2 overwriting the symlinks I had created.

**Comment by ramonfontes** [comment]
Yes, you're right. Some Python3 modules seem to require Python2 that in turn is set to default one after being installed. I'll try to find a way to resolve it.

**Comment by ramonfontes** [comment]
Since I couldn't find any better solution to make it work, I'd recommend using `update-alternatives` as well.

**Comment by MahanteshMise** [comment]
Sir I am having the same issue "No module named 'mininet' .I have my mininet installed in the home directory and the project folder in the same directory. Some help is highly appreciated.

**Comment by ramonfontes** [comment]
How can I reproduce the error? Can you find `mininet` directory into `mininet-wifi/`?

**Comment by MahanteshMise** [comment]
> How can I reproduce the error? Can you find `mininet` directory into `mininet-wifi/`?

I tried adding /home/mininet to the sys.path and then execute. I can execute it on the terminal while if I try to execute it on PyCharm IDE installed in Ubuntu.Its throwing the error!
![Screenshot from 2019-09-15 16-43-42](https://user-images.githubusercontent.com/41672689/64929220-21b61680-d7d8-11e9-8ec1-bbd49c9be65a.png)

**Comment by ramonfontes** [comment]
So, the problem isn't with Mininet-WiFi. You may need to set environmental variables in Pycharm's run configurations menu

**Comment by MahanteshMise** [comment]
Can you please tell me how to do that?
