### ISSUE TITLE
RTNETLINK error on Ubuntu 18.04

### ISSUE THREAD

**Issue by tterranigma** [intrig-unicamp/mininet-wifi#185]
I have installed mininet_wifi on Ubuntu 18.04 using Python 3 as the default. The system is fully updated. 

Both my custom scripts and some of the examples that come with mininet-wifi produce the following error:

```
*** Error: RTNETLINK answers: No such file or directory
```

This happens when the `net.addLink` method is called. I run strace with the `simplewifitopology.py` script and the error seems to happen when `tc` is called at some point by mininet-wifi:

```
write(2, "Associating sta1-wlan0 to ap1\n", 30Associating sta1-wlan0 to ap1
) = 30
write(3, "ip link set sta1-wlan0 up\n", 26) = 26
poll([{fd=3, events=POLLIN|POLLPRI|POLLOUT}], 1, -1) = 1 ([{fd=3, revents=POLLOUT}])
read(3, "\177", 1024)                   = 1
write(3, "ethtool -K sta1-wlan0 gro off\n", 30) = 30
poll([{fd=3, events=POLLIN|POLLPRI|POLLOUT}], 1, -1) = 1 ([{fd=3, revents=POLLOUT}])
read(3, "\177", 1024)                   = 1
write(3, "tc qdisc show dev sta1-wlan0\n", 29) = 29
poll([{fd=3, events=POLLIN|POLLPRI|POLLOUT}], 1, -1) = 1 ([{fd=3, revents=POLLOUT}])
read(3, "qdisc mq 0: root \r\nqdisc fq_code"..., 1024) = 495
poll([{fd=3, events=POLLIN|POLLPRI|POLLOUT}], 1, -1) = 1 ([{fd=3, revents=POLLOUT}])
read(3, "\177", 1024)                   = 1
write(3, "tc qdisc del dev sta1-wlan0 root"..., 33) = 33
poll([{fd=3, events=POLLIN|POLLPRI|POLLOUT}], 1, -1) = 1 ([{fd=3, revents=POLLOUT}])
read(3, "RTNETLINK answers: No such file "..., 1024) = 46
poll([{fd=3, events=POLLIN|POLLPRI|POLLOUT}], 1, -1) = 1 ([{fd=3, revents=POLLOUT}])
read(3, "\177", 1024)                   = 1
write(3, "tc qdisc add dev sta1-wlan0 root"..., 58) = 58
poll([{fd=3, events=POLLIN|POLLPRI|POLLOUT}], 1, -1) = 1 ([{fd=3, revents=POLLOUT}])
read(3, "\177", 1024)                   = 1
write(3, "tc class add dev sta1-wlan0 pare"..., 84) = 84
poll([{fd=3, events=POLLIN|POLLPRI|POLLOUT}], 1, -1) = 1 ([{fd=3, revents=POLLOUT}])
read(3, "\177", 1024)                   = 1
getpid()                                = 16714
write(2, "*** Error: RTNETLINK answers: No"..., 57*** Error: RTNETLINK answers: No such file or directory
) = 57
```

This seems similar to [an older `mininet` issue](https://github.com/mininet/mininet/issues/629). `mininet` examples seem to run fine though.

**Comment by ramonfontes** [comment]
How can I reproduce the issue? Which kernel version do you have?

**Comment by ramonfontes** [comment]
Can you install and use `4.15.0-15-generic`? If so please let me know about the result.

**Comment by ramonfontes** [comment]
This [commit](https://github.com/intrig-unicamp/mininet-wifi/commit/f5e5db6809dd3c023331383f9d236b10ee9f95c0) fixes the issue.

**Comment by tterranigma** [comment]
I can confirm this is solved! Thanks @ramonfontes for the great support!

**Comment by ramonfontes** [comment]
Hi,

Could you run the code in debug mode and share the outcome? Lines throwing the error are enough.

**Comment by hdm0511** [comment]
Hi Ramonfontes,

Thank you very much for prompt reply.
Here is "adding links" in debug mode
++++++++++++++++++++++
sudo mn --wifi --test pingall --topo linear,2
...
...
*** Adding link(s):
*** ap2 : ('ip link add name ap2-eth2 address 6e:c8:48:55:53:d2 type veth peer name ap1-eth2 address 76:70:7a:ef:15:85 netns 7712',)

added intf ap2-eth2 (2) to node ap2
*** ap2 : ('ifconfig', 'ap2-eth2', 'up')
*** ap2 : ('ethtool -K', <TCIntf ap2-eth2>, 'gro', 'off', 'tx', 'on', 'rx', 'on')

added intf ap1-eth2 (2) to node ap1
*** ap1 : ('ifconfig', 'ap1-eth2', 'up')
*** ap1 : ('ethtool -K', <TCIntf ap1-eth2>, 'gro', 'off', 'tx', 'on', 'rx', 'on')
(ap2, ap1) iwconfig sta1-wlan0 essid ssid_ap1 ap 02:00:00:00:02:00
*** sta1 : ('ip link set', 'sta1-wlan0', 'up')
*** sta1 : ('ethtool -K', <TCWirelessLink sta1-wlan0>, 'gro', 'off')
 *** executing command: tc qdisc show dev sta1-wlan0
*** sta1 : ('tc qdisc show dev sta1-wlan0',)
qdisc mq 0: root 
qdisc fq 0: parent :4 limit 10000p flow_limit 100p buckets 1024 orphan_mask 1023 quantum 3028 initial_quantum 15140 low_rate_threshold 550Kbit refill_delay 40.0ms 
qdisc fq 0: parent :3 limit 10000p flow_limit 100p buckets 1024 orphan_mask 1023 quantum 3028 initial_quantum 15140 low_rate_threshold 550Kbit refill_delay 40.0ms 
qdisc fq 0: parent :2 limit 10000p flow_limit 100p buckets 1024 orphan_mask 1023 quantum 3028 initial_quantum 15140 low_rate_threshold 550Kbit refill_delay 40.0ms 
qdisc fq 0: parent :1 limit 10000p flow_limit 100p buckets 1024 orphan_mask 1023 quantum 3028 initial_quantum 15140 low_rate_threshold 550Kbit refill_delay 40.0ms 
at map stage w/cmds: ['%s qdisc del dev %s root', '%s qdisc add dev %s root handle 5:0 htb default 1', '%s class add dev %s parent 5:0 classid 5:1 htb rate 11.000000Mbit burst 15k']
 *** executing command: tc qdisc del dev sta1-wlan0 root
*** sta1 : ('tc qdisc del dev sta1-wlan0 root',)
RTNETLINK answers: No such file or directory
 *** executing command: tc qdisc add dev sta1-wlan0 root handle 5:0 htb default 1
*** sta1 : ('tc qdisc add dev sta1-wlan0 root handle 5:0 htb default 1',)
 *** executing command: tc class add dev sta1-wlan0 parent 5:0 classid 5:1 htb rate 11.000000Mbit burst 15k
*** sta1 : ('tc class add dev sta1-wlan0 parent 5:0 classid 5:1 htb rate 11.000000Mbit burst 15k',)
*** Error: RTNETLINK answers: No such file or directory
cmds: ['%s qdisc del dev %s root', '%s qdisc add dev %s root handle 5:0 htb default 1', '%s class add dev %s parent 5:0 classid 5:1 htb rate 11.000000Mbit burst 15k'] 
outputs: ['RTNETLINK answers: No such file or directory\r\n', '', ''] 
(sta1, ap1) iwconfig sta2-wlan0 essid ssid_ap2 ap 02:00:00:00:03:00
*** sta2 : ('ip link set', 'sta2-wlan0', 'up')
*** sta2 : ('ethtool -K', <TCWirelessLink sta2-wlan0>, 'gro', 'off')
 *** executing command: tc qdisc show dev sta2-wlan0
*** sta2 : ('tc qdisc show dev sta2-wlan0',)
qdisc mq 0: root 
qdisc fq 0: parent :4 limit 10000p flow_limit 100p buckets 1024 orphan_mask 1023 quantum 3028 initial_quantum 15140 low_rate_threshold 550Kbit refill_delay 40.0ms 
qdisc fq 0: parent :3 limit 10000p flow_limit 100p buckets 1024 orphan_mask 1023 quantum 3028 initial_quantum 15140 low_rate_threshold 550Kbit refill_delay 40.0ms 
qdisc fq 0: parent :2 limit 10000p flow_limit 100p buckets 1024 orphan_mask 1023 quantum 3028 initial_quantum 15140 low_rate_threshold 550Kbit refill_delay 40.0ms 
qdisc fq 0: parent :1 limit 10000p flow_limit 100p buckets 1024 orphan_mask 1023 quantum 3028 initial_quantum 15140 low_rate_threshold 550Kbit refill_delay 40.0ms 
at map stage w/cmds: ['%s qdisc del dev %s root', '%s qdisc add dev %s root handle 5:0 htb default 1', '%s class add dev %s parent 5:0 classid 5:1 htb rate 11.000000Mbit burst 15k']
 *** executing command: tc qdisc del dev sta2-wlan0 root
*** sta2 : ('tc qdisc del dev sta2-wlan0 root',)
RTNETLINK answers: No such file or directory
 *** executing command: tc qdisc add dev sta2-wlan0 root handle 5:0 htb default 1
*** sta2 : ('tc qdisc add dev sta2-wlan0 root handle 5:0 htb default 1',)
 *** executing command: tc class add dev sta2-wlan0 parent 5:0 classid 5:1 htb rate 11.000000Mbit burst 15k
*** sta2 : ('tc class add dev sta2-wlan0 parent 5:0 classid 5:1 htb rate 11.000000Mbit burst 15k',)
*** Error: RTNETLINK answers: No such file or directory
cmds: ['%s qdisc del dev %s root', '%s qdisc add dev %s root handle 5:0 htb default 1', '%s class add dev %s parent 5:0 classid 5:1 htb rate 11.000000Mbit burst 15k'] 
outputs: ['RTNETLINK answers: No such file or directory\r\n', '', ''] 
(sta2, ap2) 
*** Configuring nodes
...
++++++++++++++++++++++
thanks
Hoang

**Comment by ramonfontes** [comment]
What if you run `sudo mn` and then `h1 tc qdisc`?

**Comment by hdm0511** [comment]
Hi Ramonfontes,
+++++++++++++++Here is the output without debug+++++++++++++++++
mininet-wifi> h1 tc qdisc
qdisc noqueue 0: dev lo root refcnt 2 
qdisc noqueue 0: dev h1-eth0 root refcnt 2 
+++++++++++++++++++++++++++++++++++++++++++++++++++++++++

++++++++++++++++Here is the output with debug+++++++++++++++++++
mininet-wifi> h1 tc qdisc
*** errRun: ['stty', '-icanon', 'min', '1'] 
  0qdisc noqueue 0: dev lo root refcnt 2 
qdisc noqueue 0: dev h1-eth0 root refcnt 2 
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

++++++++++++++sudo mn -v debug+++++++++++++++++++
....
*** Adding links:
*** h1 : ('ip link add name h1-eth0 address 7a:b1:d2:4c:47:1d type veth peer name s1-eth1 address 82:98:2b:ea:21:aa netns 20360',)

added intf h1-eth0 (0) to node h1
moving h1-eth0 into namespace for h1 
*** h1 : ('ifconfig', 'h1-eth0', 'up')

added intf s1-eth1 (1) to node s1
*** s1 : ('ifconfig', 's1-eth1', 'up')
(h1, s1) *** h2 : ('ip link add name h2-eth0 address c2:ed:d4:a6:f3:9e type veth peer name s1-eth2 address a2:d7:3d:59:05:ee netns 20360',)

added intf h2-eth0 (0) to node h2
moving h2-eth0 into namespace for h2 
*** h2 : ('ifconfig', 'h2-eth0', 'up')

added intf s1-eth2 (2) to node s1
*** s1 : ('ifconfig', 's1-eth2', 'up')
(h2, s1) 
.....
++++++++++++++++++++++++++++++++++++++++++

Thank you
Hoang

**Comment by ramonfontes** [comment]
Thank you Hoang.

Let me ask you one more favor. Could you please run `tc qdisc` on your host?

**Comment by hdm0511** [comment]
Hi Ramontontes,
I installed virtualbox, VMware and Docker
here is the tc qdisc on my host
++++++++tc qdisc++++++++
qdisc noqueue 0: dev lo root refcnt 2 
qdisc mq 0: dev wlp58s0 root 
qdisc fq 0: dev wlp58s0 parent :4 limit 10000p flow_limit 100p buckets 1024 orphan_mask 1023 quantum 3028 initial_quantum 15140 low_rate_threshold 550Kbit refill_delay 40.0ms 
qdisc fq 0: dev wlp58s0 parent :3 limit 10000p flow_limit 100p buckets 1024 orphan_mask 1023 quantum 3028 initial_quantum 15140 low_rate_threshold 550Kbit refill_delay 40.0ms 
qdisc fq 0: dev wlp58s0 parent :2 limit 10000p flow_limit 100p buckets 1024 orphan_mask 1023 quantum 3028 initial_quantum 15140 low_rate_threshold 550Kbit refill_delay 40.0ms 
qdisc fq 0: dev wlp58s0 parent :1 limit 10000p flow_limit 100p buckets 1024 orphan_mask 1023 quantum 3028 initial_quantum 15140 low_rate_threshold 550Kbit refill_delay 40.0ms 
qdisc noqueue 0: dev virbr0 root refcnt 2 
qdisc fq 0: dev virbr0-nic root refcnt 2 limit 10000p flow_limit 100p buckets 1024 orphan_mask 1023 quantum 3028 initial_quantum 15140 low_rate_threshold 550Kbit refill_delay 40.0ms 
qdisc noqueue 0: dev docker0 root refcnt 2 
qdisc fq 0: dev vmnet1 root refcnt 2 limit 10000p flow_limit 100p buckets 1024 orphan_mask 1023 quantum 3028 initial_quantum 15140 low_rate_threshold 550Kbit refill_delay 40.0ms 
qdisc fq 0: dev vmnet8 root refcnt 2 limit 10000p flow_limit 100p buckets 1024 orphan_mask 1023 quantum 3028 initial_quantum 15140 low_rate_threshold 550Kbit refill_delay 40.0ms 
++++++++++++++++

Thank you very much
Hoang

**Comment by ramonfontes** [comment]
Please try a new `git pull` and then run `sudo make install`.

**Comment by hdm0511** [comment]
Hi Ramonfontes,

I did: `git full` then `sudo make install`. However the errors still persist
I run mn -wifi --topo=linear,3 -v debug and the result as following
++++++git full++++++
git pull https://github.com/intrig-unicamp/mininet-wifi
From https://github.com/intrig-unicamp/mininet-wifi
 * branch              HEAD       -> FETCH_HEAD
Updating f8373044..2b353c47
Fast-forward
 examples/adhoc.py                |   9 +-
 examples/handover_bgscan.py      |   2 +-
 examples/mesh.py                 |  12 ++-
 mn_wifi/link.py                  | 192 +++++++++++++++++++++++++++++++--------
 mn_wifi/node.py                  |  71 +--------------
 mn_wifi/test/test_walkthrough.py |   4 +-
 util/hostap-patches/config.patch |  31 +++++--
 7 files changed, 199 insertions(+), 122 deletions(-)
++++++++++++++++++++++++++++++++++++++

++++++++++++sudo make install+++++++++++++
...
++++++++++++++++++++++++++++++++++++++++

+++++++++++++mn -wifi --topo=linear,3 -v debug+++
*** Adding link(s):
*** ap2 : ('ip link add name ap2-eth2 address 9a:b7:0e:2b:fc:50 type veth peer name ap1-eth2 address 62:32:38:c8:eb:74 netns 5282',)

added intf ap2-eth2 (2) to node ap2
*** ap2 : ('ifconfig', 'ap2-eth2', 'up')
*** ap2 : ('ethtool -K', <TCIntf ap2-eth2>, 'gro', 'off', 'tx', 'on', 'rx', 'on')

added intf ap1-eth2 (2) to node ap1
*** ap1 : ('ifconfig', 'ap1-eth2', 'up')
*** ap1 : ('ethtool -K', <TCIntf ap1-eth2>, 'gro', 'off', 'tx', 'on', 'rx', 'on')
(ap2, ap1) *** ap3 : ('ip link add name ap3-eth2 address da:49:56:bc:b6:2d type veth peer name ap2-eth3 address 9a:be:58:95:7b:21 netns 5285',)

added intf ap3-eth2 (2) to node ap3
*** ap3 : ('ifconfig', 'ap3-eth2', 'up')
*** ap3 : ('ethtool -K', <TCIntf ap3-eth2>, 'gro', 'off', 'tx', 'on', 'rx', 'on')

added intf ap2-eth3 (3) to node ap2
*** ap2 : ('ifconfig', 'ap2-eth3', 'up')
*** ap2 : ('ethtool -K', <TCIntf ap2-eth3>, 'gro', 'off', 'tx', 'on', 'rx', 'on')
(ap3, ap2) iwconfig sta1-wlan0 essid ssid_ap1 ap 02:00:00:00:03:00
*** sta1 : ('ip link set', 'sta1-wlan0', 'up')
*** sta1 : ('ethtool -K', <TCWirelessLink sta1-wlan0>, 'gro', 'off')
 *** executing command: tc qdisc show dev sta1-wlan0
*** sta1 : ('tc qdisc show dev sta1-wlan0',)
qdisc mq 0: root 
qdisc fq 0: parent :4 limit 10000p flow_limit 100p buckets 1024 orphan_mask 1023 quantum 3028 initial_quantum 15140 low_rate_threshold 550Kbit refill_delay 40.0ms 
qdisc fq 0: parent :3 limit 10000p flow_limit 100p buckets 1024 orphan_mask 1023 quantum 3028 initial_quantum 15140 low_rate_threshold 550Kbit refill_delay 40.0ms 
qdisc fq 0: parent :2 limit 10000p flow_limit 100p buckets 1024 orphan_mask 1023 quantum 3028 initial_quantum 15140 low_rate_threshold 550Kbit refill_delay 40.0ms 
qdisc fq 0: parent :1 limit 10000p flow_limit 100p buckets 1024 orphan_mask 1023 quantum 3028 initial_quantum 15140 low_rate_threshold 550Kbit refill_delay 40.0ms 
at map stage w/cmds: ['%s qdisc del dev %s root', '%s qdisc add dev %s root handle 5:0 htb default 1', '%s class add dev %s parent 5:0 classid 5:1 htb rate 11.000000Mbit burst 15k']
 *** executing command: tc qdisc del dev sta1-wlan0 root
*** sta1 : ('tc qdisc del dev sta1-wlan0 root',)
RTNETLINK answers: No such file or directory
 *** executing command: tc qdisc add dev sta1-wlan0 root handle 5:0 htb default 1
*** sta1 : ('tc qdisc add dev sta1-wlan0 root handle 5:0 htb default 1',)
 *** executing command: tc class add dev sta1-wlan0 parent 5:0 classid 5:1 htb rate 11.000000Mbit burst 15k
*** sta1 : ('tc class add dev sta1-wlan0 parent 5:0 classid 5:1 htb rate 11.000000Mbit burst 15k',)
*** Error: RTNETLINK answers: No such file or directory
cmds: ['%s qdisc del dev %s root', '%s qdisc add dev %s root handle 5:0 htb default 1', '%s class add dev %s parent 5:0 classid 5:1 htb rate 11.000000Mbit burst 15k'] 
outputs: ['RTNETLINK answers: No such file or directory\r\n', '', ''] 
(sta1, ap1) iwconfig sta2-wlan0 essid ssid_ap2 ap 02:00:00:00:04:00
*** sta2 : ('ip link set', 'sta2-wlan0', 'up')
*** sta2 : ('ethtool -K', <TCWirelessLink sta2-wlan0>, 'gro', 'off')
 *** executing command: tc qdisc show dev sta2-wlan0
*** sta2 : ('tc qdisc show dev sta2-wlan0',)
qdisc mq 0: root 
qdisc fq 0: parent :4 limit 10000p flow_limit 100p buckets 1024 orphan_mask 1023 quantum 3028 initial_quantum 15140 low_rate_threshold 550Kbit refill_delay 40.0ms 
qdisc fq 0: parent :3 limit 10000p flow_limit 100p buckets 1024 orphan_mask 1023 quantum 3028 initial_quantum 15140 low_rate_threshold 550Kbit refill_delay 40.0ms 
qdisc fq 0: parent :2 limit 10000p flow_limit 100p buckets 1024 orphan_mask 1023 quantum 3028 initial_quantum 15140 low_rate_threshold 550Kbit refill_delay 40.0ms 
qdisc fq 0: parent :1 limit 10000p flow_limit 100p buckets 1024 orphan_mask 1023 quantum 3028 initial_quantum 15140 low_rate_threshold 550Kbit refill_delay 40.0ms 
at map stage w/cmds: ['%s qdisc del dev %s root', '%s qdisc add dev %s root handle 5:0 htb default 1', '%s class add dev %s parent 5:0 classid 5:1 htb rate 11.000000Mbit burst 15k']
 *** executing command: tc qdisc del dev sta2-wlan0 root
*** sta2 : ('tc qdisc del dev sta2-wlan0 root',)
RTNETLINK answers: No such file or directory
 *** executing command: tc qdisc add dev sta2-wlan0 root handle 5:0 htb default 1
*** sta2 : ('tc qdisc add dev sta2-wlan0 root handle 5:0 htb default 1',)
 *** executing command: tc class add dev sta2-wlan0 parent 5:0 classid 5:1 htb rate 11.000000Mbit burst 15k
*** sta2 : ('tc class add dev sta2-wlan0 parent 5:0 classid 5:1 htb rate 11.000000Mbit burst 15k',)
*** Error: RTNETLINK answers: No such file or directory
cmds: ['%s qdisc del dev %s root', '%s qdisc add dev %s root handle 5:0 htb default 1', '%s class add dev %s parent 5:0 classid 5:1 htb rate 11.000000Mbit burst 15k'] 
outputs: ['RTNETLINK answers: No such file or directory\r\n', '', ''] 
(sta2, ap2) iwconfig sta3-wlan0 essid ssid_ap3 ap 02:00:00:00:05:00
*** sta3 : ('ip link set', 'sta3-wlan0', 'up')
*** sta3 : ('ethtool -K', <TCWirelessLink sta3-wlan0>, 'gro', 'off')
 *** executing command: tc qdisc show dev sta3-wlan0
*** sta3 : ('tc qdisc show dev sta3-wlan0',)
qdisc mq 0: root 
qdisc fq 0: parent :4 limit 10000p flow_limit 100p buckets 1024 orphan_mask 1023 quantum 3028 initial_quantum 15140 low_rate_threshold 550Kbit refill_delay 40.0ms 
qdisc fq 0: parent :3 limit 10000p flow_limit 100p buckets 1024 orphan_mask 1023 quantum 3028 initial_quantum 15140 low_rate_threshold 550Kbit refill_delay 40.0ms 
qdisc fq 0: parent :2 limit 10000p flow_limit 100p buckets 1024 orphan_mask 1023 quantum 3028 initial_quantum 15140 low_rate_threshold 550Kbit refill_delay 40.0ms 
qdisc fq 0: parent :1 limit 10000p flow_limit 100p buckets 1024 orphan_mask 1023 quantum 3028 initial_quantum 15140 low_rate_threshold 550Kbit refill_delay 40.0ms 
at map stage w/cmds: ['%s qdisc del dev %s root', '%s qdisc add dev %s root handle 5:0 htb default 1', '%s class add dev %s parent 5:0 classid 5:1 htb rate 11.000000Mbit burst 15k']
 *** executing command: tc qdisc del dev sta3-wlan0 root
*** sta3 : ('tc qdisc del dev sta3-wlan0 root',)
RTNETLINK answers: No such file or directory
 *** executing command: tc qdisc add dev sta3-wlan0 root handle 5:0 htb default 1
*** sta3 : ('tc qdisc add dev sta3-wlan0 root handle 5:0 htb default 1',)
 *** executing command: tc class add dev sta3-wlan0 parent 5:0 classid 5:1 htb rate 11.000000Mbit burst 15k
*** sta3 : ('tc class add dev sta3-wlan0 parent 5:0 classid 5:1 htb rate 11.000000Mbit burst 15k',)
*** Error: RTNETLINK answers: No such file or directory
cmds: ['%s qdisc del dev %s root', '%s qdisc add dev %s root handle 5:0 htb default 1', '%s class add dev %s parent 5:0 classid 5:1 htb rate 11.000000Mbit burst 15k'] 
outputs: ['RTNETLINK answers: No such file or directory\r\n', '', ''] 
(sta3, ap3) 
++++++++++++++++++++++++++++++++++++++

Thank you
Hoang

**Comment by hdm0511** [comment]
Hi Ramonfontes,
You are my hero!, It works without RTNETLINK errors.
Thank you very much for your help and time
Hoang
