### ISSUE TITLE
How can I solve mininet wifi problem: cannot find executable ifconfig if i run sudo mn --wifi

### ISSUE THREAD

**Issue by harualhassan** [intrig-unicamp/mininet-wifi#186]
haru@haru-HP-Laptop-15-bs0xx:~/mininet-wifi$ sudo mn --wifi
[sudo] password for haru: 
*** Creating network
*** Adding controller
Cannot find required executable ifconfig.
Please make sure that Mininet is installed and available in your $PATH:
(/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin)

**Comment by ramonfontes** [comment]
Installing net-tools solves the issue (sudo apt-get install net-tools).
