### ISSUE TITLE
 could not execute rssi-threshold.py on mininet

### ISSUE THREAD

**Issue by harualhassan** [intrig-unicamp/mininet-wifi#187]
Traceback (most recent call last):
  File "rssi-threshold.py", line 6, in <module>
    from mininet.node import RemoteController, OVSKernelAP
ImportError: cannot import name OVSKernelAP

kindly advise on the solution

**Comment by ramonfontes** [comment]
Hi. Where is the code?

**Comment by harualhassan** [comment]
Pls find attached the code:

   On Tuesday, 4 September 2018, 00:34:38 GMT+1, Ramon Fontes <notifications@github.com> wrote:  
 
 
Hi. Where is the code?

**Comment by harualhassan** [comment]
#!/usr/bin/python

'RSSI THRESHOLD'

from mininet.net import Mininet
from mininet.node import RemoteController , OVSkernelAP
from mininet.link import TCLink
from mininet.cli import CLI
from mininet.log import setLogLevel

def topology():

    "Create a network."
    net = Mininet(controller=RemoteController, link=TCLink, accessPoint=OVSKernelAP, enable_wmediumd=True, enable_interference=True)

    print "*** Creating nodes"
    sta1 = net.addStation('sta1', mac='00:00:00:00:00:01', ip='10.0.0.1/8')
    h1 = net.addHost('h1', mac='00:00:00:00:00:02', ip='10.0.0.2/8')
    ap1 = net.addAccessPoint('ap1', ssid='ap1', mode='g', channel='1', position='45,40,0')
    ap2 = net.addAccessPoint('ap2', ssid='ap2', mode='g', channel='6', position='100,40,0')
    c1 = net.addController('c1', controller=RemoteController)

    print "*** Configuring Propagation Model"
    net.propagationModel("logDistancePropagationLossModel", exp=4)

    print "*** Configuring wifi nodes"
    net.configureWifiNodes()

    net.addLink(ap1, h1)
    net.addLink(ap1, ap2)

    print "*** Starting network"
    net.build()
    c1.start()
    ap1.start([c1])
    ap2.start([c1])

    """plotting graph"""
    net.plotGraph(max_x=150, max_y=150)

    sta1.cmd('iw dev %s interface add mon0 type monitor' % sta1.params['wlan'][0])
    sta1.cmd('ifconfig mon0 up')
    sta1.cmd('wireshark -i mon0 &')

    #ap1.cmd('ovs-ofctl add-flow "ap1" in_port=1,actions=normal')
    #ap1.cmd('ovs-ofctl add-flow "ap1" in_port=2,actions=normal')
    #ap2.cmd('ovs-ofctl add-flow "ap2" in_port=1,actions=normal')
    #ap2.cmd('ovs-ofctl add-flow "ap2" in_port=2,actions=normal')

    net.startMobility(time=0)
    net.mobility(sta1, 'start', time=10, position='45.0,30.0,0.0')
    net.mobility(sta1, 'stop', time=50, position='140.0,30.0,0.0')
    net.stopMobility(time=51)

    print "*** Running CLI"
    CLI(net)

    print "*** Stopping network"
    net.stop()

if __name__ == '__main__':
    setLogLevel('info')
topology()

**Comment by ramonfontes** [comment]
You may want to modify your script in order to run with the current mininet-wifi. This is straightforward and you can take the scripts at /examples as support.
