### ISSUE TITLE
Issue running VANET.py on mininet-wifi

### ISSUE THREAD

**Issue by ibrahimmayar** [intrig-unicamp/mininet-wifi#191]
I am facing problem relating to running vanet.py on mininet-wifi. The example run successfully however, I face the following problem.

custom        examples  Makefile  mnexec.1               TODO.md
debian        hostap    mininet   mnexec.c               util
root@mininet-vm:~/mininet-new/mininet-wifi# cd examples/
root@mininet-vm:~/mininet-new/mininet-wifi/examples# ls
4address.py            ieee80211p.py          propagationModel.py
6LoWPan.py             __init__.py            radius
active_scan.py         iot.py                 replaying
adhoc.py               meshAP.py              simplewifitopology.py
associationControl.py  mesh.py                sta_ap_mode.py
authentication.py      miniedit.py            vanet.py
capwap-wtp.py          mobilityModel.py       vanet-sumo.py
clustercli.py          mobility.py            wifiDirect.py
cluster.py             multipleWlan.py        wmediumd_error_prob.py
forwardingBySSID.py    physicalMesh.py        wmediumd_interference.py
handover_bgscan.py     physicalWifiDirect.py  wmediumd_mobility.py
handover.py            position.py
root@mininet-vm:~/mininet-new/mininet-wifi/examples# sudo gedit vanet.py
root@mininet-vm:~/mininet-new/mininet-wifi/examples# sudo python vanet.py
*** Creating nodes
*** Configuring Propagation Model
*** Configuring wifi nodes
*** Connecting to wmediumd server /var/run/wmediumd.sock
*** Associating and Creating links
*** Starting network
*** Configuring nodes
*** Running CLI
*** Starting CLI:
mininet-wifi> Exception in thread vanet:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/local/lib/python2.7/dist-packages/mininet_wifi-2.2.2d1-py2.7.egg/mn_wifi/vanet.py", line 66, in start
    self.display_grid(params['aps'], params['conn'], params['nroads'])
  File "/usr/local/lib/python2.7/dist-packages/mininet_wifi-2.2.2d1-py2.7.egg/mn_wifi/vanet.py", line 132, in display_grid
    self.points[n] = self.get_line(int(x1[0]), int(y1[0]),
IndexError: list index out of range

![image](https://user-images.githubusercontent.com/20687965/46453903-44b10b80-c7bd-11e8-9454-88c612c8ae66.png)

Kindly provide solution to this problem.

**Comment by ibrahimmayar** [comment]
No I didnt made any change...!

**Comment by ibrahimmayar** [comment]
Secondly while running the sumo example the map.sumocfg is not running!

**Comment by ibrahimmayar** [comment]
The problem is that sumo-gui is not opened and secondly the sumocfg file is not opened

**Comment by ibrahimmayar** [comment]
I send you request on skype, Kindly accept the request from my skype ID

ibrahimmayar

**Comment by ramonfontes** [comment]
Can you open `sumo-gui` via terminal - by typing `sudo sumo-gui`? Which sumo version do you have?

**Comment by ibrahimmayar** [comment]
sumo-0.28 version i installed..

**Comment by ibrahimmayar** [comment]
Where to set the path.. Because when I run sumo-gui from terminal using command sumo-gui, It runs. However, when i run the vanet-sumo.py example, it doesnt find it..

**Comment by ramonfontes** [comment]
Please try 0.32.

**Comment by ibrahimmayar** [comment]
okay dear... and how to set path of 0.32..

**Comment by ramonfontes** [comment]
Path? Which path? There is no need of any path.

**Comment by ibrahimmayar** [comment]
suppose i download the 0.32 then where should i extract it and what to do then

**Comment by ramonfontes** [comment]
I suppose this question isn't about Mininet-WiFi. This is about Sumo.

**Comment by ibrahimmayar** [comment]
yes but to vanet-sumo.py example to run the sumo need to run that example then the mininet-wifi example with execute.. do u have teamviewer.. i can show u the running status

**Comment by ibrahimmayar** [comment]
I wil install 0.32... can u take screenshot of where sumo is located on ur system... mean path of sumo...

**Comment by ramonfontes** [comment]
Dear,

Everything you need are SUMO and Mininet-WiFi. Then `vanet-sumo.py` should work. I have Sumo 0.32 and everything is working as expected. That's why I recommend you to install 0.32.

**Comment by ibrahimmayar** [comment]
ok.. but u type command which sumo and send me the path which it show.

**Comment by ibrahimmayar** [comment]
my path is usr/local/bin/sumo

**Comment by ramonfontes** [comment]
Dear,

This isn't a chat. So please be concise. Again, if you have everything installed, `vanet-sumo.py` should work.

**Comment by ibrahimmayar** [comment]
Thank you dear for your quick answers.. I appreciate.. I try myself and will let u know..

**Comment by ibrahimmayar** [comment]
Dear I am thankful Issue resolved

**Comment by ibrahimmayar** [comment]
I have another question. Can we included our own scenario of sumo within this example.

**Comment by ramonfontes** [comment]
Yes. To do so, you need to put your map into https://github.com/intrig-unicamp/mininet-wifi/tree/master/mn_wifi/sumo/data and recompile mn-wifi with `sudo make install`.

**Comment by ibrahimmayar** [comment]
Dear Ramon Fontes,
How can we get the information about the vehicles that are in range of a specific vehicle. For example Vehicle 2 and Vehicle 3 are in range of Vehicle 1.
Thanks M.Ibrahim MayarContact #03149110018 

    On Wednesday, November 21, 2018 5:33 AM, Ramon Fontes <notifications@github.com> wrote:
 

 Closed #191.—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread. 

   

|  | Virus-free. www.avg.com  |

**Comment by ramonfontes** [comment]
Use iw tool.

**Comment by ibrahimmayar** [comment]
How to use iw tool. For example during running simulation, I want to get the information about the neighbours of a certain Vehicle sy Vehicle 1 and then display this information or send this information to the RSU or other vehicle. I am talking about the code of the paper title ::Cooperative Mobile Edge Computing System for VANET-Based Software Defined Content Delivery. 
Please guide me accordingly

**Comment by ibrahimmayar** [comment]
Changing this code:

https://github.com/jafar-albadarneh/SDS-Mininet-WiFi/blob/27f098d9edf29f82bc2afb384f9e7c55bb855b2f/SDCD/sdcd-experimental.py

**Comment by rpurkait** [comment]
Sir, I am facing problem, when I am going to execute the python sdcd-experimental.py code at the latest mininet-wifi version 2.6 with sumo-1.18. 
vanet-sumo.py is executing properly.  

ubuntu20@ubuntu20-VirtualBox:~/mininet-wifi/examples/SDS-Mininet-WiFi/SDCD$ sudo python sdcd-experimental.py 

Traceback (most recent call last):

  File "/home/ubuntu20/mininet-wifi/examples/SDS-Mininet-WiFi/SDCD/sdcd-experimental.py", line 9, in <module>

    from Components.SDS_C_Car import SD_C_Car

  File "/home/ubuntu20/mininet-wifi/examples/SDS-Mininet-WiFi/SDCD/../Components/SDS_C_Car.py", line 4, in <module>

    from mininet.node import Car

ImportError: cannot import name 'Car' from 'mininet.node' (/usr/local/lib/python3.10/dist-packages/mininet/node.py)
