### ISSUE TITLE
Error when trying to run 6lowpan example

### ISSUE THREAD

**Issue by brunobcfum** [intrig-unicamp/mininet-wifi#193]
Hi,

I get this error when running the mininet-wifi virtual machine:

**Warning! Error when loading fakelb. Please run sudo 'mn -c' before running your code.
Further information available at /tmp/mininetwifi-fakelb.log.**

I have tried with and without updating the ubuntu and also tried git pull to get latest mininet-wifi code.
The mentioned log life doesn't exist inside /tmp and when running manually modprobe fakelb, the modules gets loaded with not problem.

Thanks

**Comment by brunobcfum** [comment]
OBS.: When installing mininet-wifi from scratch on a Ubuntu 16 it works fine. So I guess there is something wrong with the VM.

**Comment by ramonfontes** [comment]
It was missing _wpan tools_. `sudo util/install.sh -6` solves the problem. I'm going to upload a new VM anyway.

**Comment by ramonfontes** [comment]
A new VM is avalable.
