### ISSUE TITLE
can not ping from station to host (staX ping hY)

### ISSUE THREAD

**Issue by hdm0511** [intrig-unicamp/mininet-wifi#194]
Hi,
Please help me with the following issue. Thank you very much
I have this scenario built with the help of VND: 
sta5<------wirelessChannel------>AP2<-------utp----->Switch3<--------utp-------->h4
                                                        \                              /
                                                          \                          /
                                                           |_____C1_____| 
I can not ping from sta5 to h4, or from h4 to sta5.
++++++++++
*** Creating nodes
*** Creating links
*** Starting network
*** Configuring nodes
*** Running CLI
*** Starting CLI:
mininet-wifi> nodes
available nodes are: 
ap2 c1 h4 s3 sta5
mininet-wifi> sta5 ping h4
PING 10.0.0.4 (10.0.0.4) 56(84) bytes of data.
From 10.0.0.5 icmp_seq=1 Destination Host Unreachable
From 10.0.0.5 icmp_seq=2 Destination Host Unreachable
From 10.0.0.5 icmp_seq=3 Destination Host Unreachable
From 10.0.0.5 icmp_seq=4 Destination Host Unreachable
From 10.0.0.5 icmp_seq=5 Destination Host Unreachable
From 10.0.0.5 icmp_seq=6 Destination Host Unreachable
^C
++++++++++

+++++++++++here is ifconfig:++++++++++++
~/myApps$ ifconfig
ap2-eth1: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet6 fe80::54cd:dfff:feb7:434f  prefixlen 64  scopeid 0x20<link>
        ether 56:cd:df:b7:43:4f  txqueuelen 1000  (Ethernet)
        RX packets 342  bytes 18704 (18.7 KB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 327  bytes 26443 (26.4 KB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

ap2-wlan1: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet6 fe80::ff:fe00:100  prefixlen 64  scopeid 0x20<link>
        ether 02:00:00:00:01:00  txqueuelen 1000  (Ethernet)
        RX packets 23  bytes 1454 (1.4 KB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 65  bytes 8817 (8.8 KB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

docker0: flags=4099<UP,BROADCAST,MULTICAST>  mtu 1500
        inet 172.17.0.1  netmask 255.255.0.0  broadcast 172.17.255.255
        ether 02:42:2a:e9:33:a7  txqueuelen 0  (Ethernet)
        RX packets 0  bytes 0 (0.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 0  bytes 0 (0.0 B)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

lo: flags=73<UP,LOOPBACK,RUNNING>  mtu 65536
        inet 127.0.0.1  netmask 255.0.0.0
        inet6 ::1  prefixlen 128  scopeid 0x10<host>
        loop  txqueuelen 1000  (Local Loopback)
        RX packets 99420  bytes 12091372 (12.0 MB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 99420  bytes 12091372 (12.0 MB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

s3-eth1: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet6 fe80::4000:57ff:fe02:ab2a  prefixlen 64  scopeid 0x20<link>
        ether 42:00:57:02:ab:2a  txqueuelen 1000  (Ethernet)
        RX packets 327  bytes 26443 (26.4 KB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 342  bytes 18704 (18.7 KB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

s3-eth2: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet6 fe80::e875:62ff:fe5a:68b5  prefixlen 64  scopeid 0x20<link>
        ether ea:75:62:5a:68:b5  txqueuelen 1000  (Ethernet)
        RX packets 29  bytes 1794 (1.7 KB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 357  bytes 21030 (21.0 KB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

virbr0: flags=4099<UP,BROADCAST,MULTICAST>  mtu 1500
        inet 192.168.123.1  netmask 255.255.255.0  broadcast 192.168.123.255
        ether 52:54:00:64:a7:ef  txqueuelen 1000  (Ethernet)
        RX packets 0  bytes 0 (0.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 0  bytes 0 (0.0 B)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

vmnet1: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 192.168.255.1  netmask 255.255.255.0  broadcast 192.168.255.255
        inet6 fe80::250:56ff:fec0:1  prefixlen 64  scopeid 0x20<link>
        ether 00:50:56:c0:00:01  txqueuelen 1000  (Ethernet)
        RX packets 0  bytes 0 (0.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 1916  bytes 0 (0.0 B)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

vmnet8: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 172.16.149.1  netmask 255.255.255.0  broadcast 172.16.149.255
        inet6 fe80::250:56ff:fec0:8  prefixlen 64  scopeid 0x20<link>
        ether 00:50:56:c0:00:08  txqueuelen 1000  (Ethernet)
        RX packets 0  bytes 0 (0.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 1910  bytes 0 (0.0 B)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

wlp58s0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 192.168.1.10  netmask 255.255.255.0  broadcast 192.168.1.255
        inet6 fe80::bbc7:1da4:8d30:eee0  prefixlen 64  scopeid 0x20<link>
        inet6 fdc8:5195:5353:2c00:b238:20b8:964c:b98f  prefixlen 64  scopeid 0x0<global>
        ether a0:88:69:eb:68:d3  txqueuelen 1000  (Ethernet)
        RX packets 144922  bytes 138235099 (138.2 MB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 104857  bytes 23278438 (23.2 MB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
++++++++++++++++++++++++++++++++++

++++++here are the code++++
`from mn_wifi.net import Mininet_wifi
from mn_wifi.cli import CLI_wifi
from mininet.node import RemoteController
from mininet.log import setLogLevel, info

def topology():
    "Create a network."
    net = Mininet_wifi( controller=RemoteController )

    info("*** Creating nodes\n")
    c1 = net.addController( 'c1', ip='127.0.0.1', port=6633 )
    ap2 = net.addAccessPoint( 'ap2', ssid='new-ssid2', mode='g', channel='1', 
        position='216.2,141,0', range=100, protocols='OpenFlow10' )
    s3 = net.addSwitch( 's3', protocols='OpenFlow10', listenPort=6674, mac='00:00:00:00:00:03' )
    h4 = net.addHost( 'h4', mac='00:00:00:00:00:04', ip='10.0.0.4/8' )
    sta5 = net.addStation( 'sta5', wlans=1, mac='00:00:00:00:00:05', ip='10.0.0.5/8', 
        position='165.25,141,0', range=18 )

    info("*** Creating links\n")
    net.addLink(ap2, s3)
    net.addLink(s3, h4)

    info("*** Starting network\n")
    net.configureWifiNodes()

    net.plotGraph(min_x=50, min_y=50, max_x=599, max_y=599)

    net.build()
    c1.start()
    s3.start( [c1] )
    ap2.start( [c1] )

    info("*** Running CLI\n")
    CLI_wifi( net )

    info("*** Stopping network\n")
    net.stop()

if __name__ == '__main__':
    setLogLevel( 'info' )
    topology()
`
++++++++++

**Comment by ramonfontes** [comment]
Which OF Controller are you using?

**Comment by ramonfontes** [comment]
So you are using pox on port `5533` and try to connect on port `6633`?

Could you give details about the flow table? Have you checked it?
BTW, is `sta5` associated with `ap3`?

**Comment by hdm0511** [comment]
sorry it was 6633 not 5533 (typing mistake)
sta5 is in the coverage of ap2, and associated with ap2
topo: sta5<------wirelessChannel------>ap2<-------utp----->s3<--------utp-------->h4
in this topo, i use only one wireless access point ap2. The switch3 (s3) is a normal ofswitch. Both ap2 and s3 are controlled by Pox (c1) on port 6633; ap2 has connection over utp link with s3.

**Comment by ramonfontes** [comment]
You didn't provide any comments about the flow table :(. Which troubleshooting steps did you try to identify the reason of the issue?

**Comment by hdm0511** [comment]
here you are:
sudo ovs-ofctl dump-flows s3
 cookie=0x0, duration=649.261s, table=0, n_packets=128, n_bytes=9088, priority=65000,dl_dst=01:23:20:00:00:01,dl_type=0x88cc actions=CONTROLLER:65535
 cookie=0x0, duration=649.219s, table=0, n_packets=3, n_bytes=126, priority=32769,arp,dl_dst=02:00:00:00:be:ef actions=CONTROLLER:65535

sudo ovs-ofctl dump-flows ap2
 cookie=0x0, duration=659.131s, table=0, n_packets=131, n_bytes=5371, priority=65000,dl_dst=01:23:20:00:00:01,dl_type=0x88cc actions=CONTROLLER:65535
 cookie=0x0, duration=659.087s, table=0, n_packets=0, n_bytes=0, priority=32769,arp,dl_dst=02:00:00:00:be:ef actions=CONTROLLER:65535

**Comment by hdm0511** [comment]
here is what POX said when: h4 ping sta5
[dump:00-00-00-00-00-02|4096] [ethernet][arp]
[dump:00-00-00-00-00-03 ] [ethernet][arp]
[dump:00-00-00-00-00-02|4096] [ethernet][arp]
[dump:00-00-00-00-00-03 ] [ethernet][arp]
[dump:00-00-00-00-00-02|4096] [ethernet][arp]
[dump:00-00-00-00-00-03 ] [ethernet][arp]
[dump:00-00-00-00-00-02|4096] [ethernet][arp]
[dump:00-00-00-00-00-03 ] [ethernet][arp]
[dump:00-00-00-00-00-02|4096] [ethernet][arp]
[dump:00-00-00-00-00-03 ] [ethernet][arp]
[dump:00-00-00-00-00-02|4096] [ethernet][arp]
[dump:00-00-00-00-00-03 ] [ethernet][arp]
[dump:00-00-00-00-00-02|4096] [ethernet][arp]
[dump:00-00-00-00-00-03 ] [ethernet][arp]
[dump:00-00-00-00-00-02|4096] [ethernet][arp]
[dump:00-00-00-00-00-03 ] [ethernet][arp]
[dump:00-00-00-00-00-02|4096] [ethernet][arp]
[dump:00-00-00-00-00-03 ] [ethernet][arp]
[dump:00-00-00-00-00-02|4096] [ethernet][arp]
[dump:00-00-00-00-00-03 ] [ethernet][arp]
[dump:00-00-00-00-00-02|4096] [ethernet][arp]
[dump:00-00-00-00-00-03 ] [ethernet][arp]
[dump:00-00-00-00-00-02|4096] [ethernet][arp]
[dump:00-00-00-00-00-03 ] [ethernet][arp]
[dump:00-00-00-00-00-02|4096] [ethernet][arp]
[dump:00-00-00-00-00-03 ] [ethernet][arp]
[dump:00-00-00-00-00-02|4096] [ethernet][arp]
[dump:00-00-00-00-00-03 ] [ethernet][ipv6][icmpv6][NDRouterSolicitation]
[dump:00-00-00-00-00-02|4096] [ethernet][ipv6][icmpv6][NDRouterSolicitation]
[dump:00-00-00-00-00-03 ] [ethernet][arp]
[dump:00-00-00-00-00-02|4096] [ethernet][arp]
[dump:00-00-00-00-00-03 ] [ethernet][arp]
[dump:00-00-00-00-00-02|4096] [ethernet][arp]
[dump:00-00-00-00-00-03 ] [ethernet][arp]
[dump:00-00-00-00-00-02|4096] [ethernet][arp]
[dump:00-00-00-00-00-03 ] [ethernet][arp]
[dump:00-00-00-00-00-02|4096] [ethernet][arp]
[dump:00-00-00-00-00-03 ] [ethernet][ipv6][icmpv6][NDRouterSolicitation]

**Comment by ramonfontes** [comment]
So, what is your conclusion about that? And again, which troubleshooting steps did you try to identify the reason of the problem?

**Comment by hdm0511** [comment]
I think the switch and AP don't have rules in it flow table to forward the packages.
i am total new with this and i am trying to find the way telling POX to install forwarding rules to switch and ap.
honestly, i dont know any steps to identify the reason of the problem :(. 
when i built the same network topo but replace the ap2 with another normal ofswitch (s4), the sta5 is replaced by another host (h6). I can ping from host to host
i.e: i can ping h6 to h4 without any modification of c1.
s4<---------->c1 (pox)<------------->s3
h6<------------>s1<--------------->s2------------------>h4

**Comment by hdm0511** [comment]
it seems pox dont install forwarding rules automatically when i change the node h6--->sta5; s1--->ap2

**Comment by ramonfontes** [comment]
First of all I'd appreciate if you be more concise. You told me that sta5 is associated with the ap. Could you give me more details about this?

**Comment by hdm0511** [comment]
is that what you want?
mininet-wifi> links
ap2-eth1<->s3-eth1 (OK OK) 
s3-eth2<->h4-eth0 (OK OK) 
sta5-wlan0<->wifi (OK wifi) 
mininet-wifi> nodes
available nodes are: 
ap2 c1 h4 s3 sta5
mininet-wifi>

**Comment by hdm0511** [comment]
i am reading about it, by the way, here is iw from sta5
sta5-wlan0  IEEE 802.11  ESSID:"new-ssid2"  
          Mode:Managed  Frequency:2.412 GHz  Access Point: 02:00:00:00:01:00   
          Bit Rate:36 Mb/s   Tx-Power=1 dBm   
          Retry short limit:7   RTS thr:off   Fragment thr:off
          Encryption key:off
          Power Management:off
          Link Quality=60/70  Signal level=-50 dBm  
          Rx invalid nwid:0  Rx invalid crypt:0  Rx invalid frag:0
          Tx excessive retries:0  Invalid misc:13   Missed beacon:0
