### ISSUE TITLE
How to generate tracing?

### ISSUE THREAD

**Issue by EngKhaled91** [intrig-unicamp/mininet-wifi#195]
Hello Everybody:
I'm trying to use mininet-wifi to emulate vanets networks and evaluate performance of some network management protocols like (snmp, netconf,..).
before my main question is there any explanation how vanets.py works or how to change some parameters or write my own example?
and is there any thing I should do to generate a trace file like some simulators (NS2, NS3, ..) ?
thanks for your time reading this
Khaled

**Comment by ramonfontes** [comment]
Sorry, could you clarify your question, please? Which explanation, parameters did you mean?

**Comment by EngKhaled91** [comment]
the parameters like mobility, number of cars, propagation model

**Comment by ramonfontes** [comment]
Please consider to read scripts at /examples as well as the user manual. This isn't an issue at all.
