### ISSUE TITLE
problem in using map.cfg file in mininet wifi

### ISSUE THREAD

**Issue by SuhaibKhan7** [intrig-unicamp/mininet-wifi#196]
sir i installed  mininet-wifi in home directory.For selecting my sumo map i have to place files in 
"usr/local/lib/python2.7/dist-packages/mininet_wifi-2.2.2d1-py2.7.egg/mn_wifi/data "    directory 
but it doesnot work if i place my files -->.      /mininet-wifi/mn_wifi/sumo/data
.Now i am not sure whether to modify code present in mininet-wifi/mn_wifi or in  usr/local/lib/python2.7/dist-packages/mininet_wifi-2.2.2d1-py2.7.egg/mn_wifi

**Comment by ramonfontes** [comment]
Did you run `sudo make install`?

**Comment by ramonfontes** [comment]
The only thing you need to do is to run `sudo make install`. So I suggest you to verify what is going wrong there.

**Comment by SuhaibKhan7** [comment]
#FIRST HALF 
$ sudo make install
cc -Wall -Wextra  -DVERSION=\"`PYTHONPATH=. python -B bin/mn --version`\" mnexec.c -o mnexec
2.2.2d1
install -D mnexec /usr/bin/mnexec
help2man -N -n "execution utility for Mininet." \
-h "-h" -v "-v" --no-discard-stderr ./mnexec -o mnexec.1
install -D -t /usr/share/man/man1 mn.1 mnexec.1
python setup.py install
/usr/lib/python2.7/dist-packages/setuptools/dist.py:406: UserWarning: The version specified ('2.2.2d1') is an invalid version, this may not work as expected with newer versions of setuptools, pip, and PyPI. Please see PEP 440 for more details.
  "details." % self.metadata.version
running install
running bdist_egg
running egg_info
writing requirements to mininet_wifi.egg-info/requires.txt
writing mininet_wifi.egg-info/PKG-INFO
writing top-level names to mininet_wifi.egg-info/top_level.txt
writing dependency_links to mininet_wifi.egg-info/dependency_links.txt
package init file 'mn_wifi/data/__init__.py' not found (or not a regular file)
reading manifest file 'mininet_wifi.egg-info/SOURCES.txt'
writing manifest file 'mininet_wifi.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_py
copying mn_wifi/net.py -> build/lib.linux-x86_64-2.7/mn_wifi
copying mn_wifi/examples/test4v.py -> build/lib.linux-x86_64-2.7/mn_wifi/examples
copying mn_wifi/examples/vanet-sumotest4v.py -> build/lib.linux-x86_64-2.7/mn_wifi/examples
>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
#I HAVE SKIPPED POSTING SOME COMMANDS
>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
copying mininet_wifi.egg-info/top_level.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
zip_safe flag not set; analyzing archive contents...
mn_wifi.sumo.runner: module references __file__
mn_wifi.sumo.sumolib.sumulib: module references __file__
mn_wifi.sumo.traci.rebuildConstants: module references __file__
creating 'dist/mininet_wifi-2.2.2d1-py2.7.egg' and adding 'build/bdist.linux-x86_64/egg' to it
removing 'build/bdist.linux-x86_64/egg' (and everything under it)
Processing mininet_wifi-2.2.2d1-py2.7.egg
removing '/usr/local/lib/python2.7/dist-packages/mininet_wifi-2.2.2d1-py2.7.egg' (and everything under it)
creating /usr/local/lib/python2.7/dist-packages/mininet_wifi-2.2.2d1-py2.7.egg
Extracting mininet_wifi-2.2.2d1-py2.7.egg to /usr/local/lib/python2.7/dist-packages
mininet-wifi 2.2.2d1 is already the active version in easy-install.pth
Installing mn script to /usr/local/bin

Installed /usr/local/lib/python2.7/dist-packages/mininet_wifi-2.2.2d1-py2.7.egg
Processing dependencies for mininet-wifi===2.2.2d1
Searching for setuptools==39.0.1
Best match: setuptools 39.0.1
Adding setuptools 39.0.1 to easy-install.pth file
Installing easy_install script to /usr/local/bin

Using /usr/lib/python2.7/dist-packages
Finished processing dependencies for mininet-wifi===2.2.2d1
>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
EVERYTHING WORKS FINE , I TRIED TO RUN SOME PYTHON FILE AND SOME COMMANDS IT WORKS ,BUT THE PROBLEM ARISE WITH SUMO MAP AS MENTIONED ABOVE

**Comment by ramonfontes** [comment]
Dear,

As I told you it works only with `sudo make install`. I just tested and everything is ok. Please double check your system. Check the build directory. Maybe you have problem with permission.
