### ISSUE TITLE
replayingMobility.py error

### ISSUE THREAD

**Issue by Suzan911** [intrig-unicamp/mininet-wifi#203]
Hi Ramon,

When I try to run the file replayingMobility.py

I got an error :  `IOError: [Errno 2] No such file or directory: 'examples/replaying/replayingMobility/node1.dat'`

how could I fix it please?

**Comment by ramonfontes** [comment]
[Fixed](https://github.com/intrig-unicamp/mininet-wifi/commit/ebd3ce7592adb7ece8d565b7d23b642e6dd3ee2e)!
