### ISSUE TITLE
errors with running vanet.py file 

### ISSUE THREAD

**Issue by yiyacom** [intrig-unicamp/mininet-wifi#205]
Hi,
When I tried to run the vanet.py file from the reproducible-research/mininet-wifi/IEEE-Access-2017/ directory. There are errors for NOT finding "carsSW" and "carsSTA". 

As looked into the mininet-wifi/mn_wifi/net.py file, these variables are not defined.

Should they be defined in net.py or other places?

Thanks.
Best Regards
yiya

**Comment by ramonfontes** [comment]
Hi,

There is a new script at the branch beta where it works. However, some minor changes at L3 are still required.
