### ISSUE TITLE
twoRayGround

### ISSUE THREAD

**Issue by harualhassan** [intrig-unicamp/mininet-wifi#206]
Hi Romonpontes
Thank you for your prompt response yesterday on Friis Propagation Model.

As a beginner kindly guide me how to solve the second issue of twoRayGround. When I said I always got constant RSSI if a station moves away from an access point.

Regards

**Comment by ramonfontes** [comment]
It will work fine if we calculate the signal range (`d`) and txpower (`txpower`) from [L95](https://github.com/intrig-unicamp/mininet-wifi/blob/master/mn_wifi/propagationModels.py#L95).

**Comment by harualhassan** [comment]
Thanks much I will try that.

Regards
