### ISSUE TITLE
Installation issues

### ISSUE THREAD

**Issue by SvetlomirPetrov** [intrig-unicamp/mininet-wifi#207]
Since the last month I have different issues when try to install mininet-wifi.
The first one is:

![image](https://user-images.githubusercontent.com/2814912/49592736-2fe62500-f972-11e8-9eec-dd4ff519a476.png)

The second is:
![image](https://user-images.githubusercontent.com/2814912/49592778-4ee4b700-f972-11e8-8331-41992d3d89b8.png)

I have tried on multiple instances from scratch I get both of them kinda randomly but mainly the first one.
I am using Ubuntu 18.04.

Would appreciate any help.

**Comment by ramonfontes** [comment]
It seems that there are some missing dependencies in your system.

**Comment by SvetlomirPetrov** [comment]
Well there is no `iproute` in the repos but `iproute2` which is already in place. Regarding the `openvswitch` it seems that I have newer versions of the packages. Am I correct?

**Comment by ramonfontes** [comment]
As you can see [here](https://github.com/intrig-unicamp/mininet-wifi/blob/master/util/install.sh#L146), it requires `iproute2`. Regarding `ovs` the error says: `openvswitch-testcontroller` requires `2.9.0`. This isn't about `mn-wifi`, right?

**Comment by SvetlomirPetrov** [comment]
I saw that it requires `iproute2` for all non-Fedora/SUSE distros but for some reason, it is required by the installation sometimes.

As per `ovs` I get this almost at the end of the installation which I do with `util/install.sh -Wlnfv`.

**Comment by ramonfontes** [comment]
Please try this [commit](https://github.com/intrig-unicamp/mininet-wifi/commit/fae094196f15a0c0de5a047952c0967b48fc53ac). Perhaps it solves the issue. Otherwise, I still think that that's a problem of dependencies.

**Comment by SvetlomirPetrov** [comment]
Thanks! You might be right, the "ground" below my setup is slippery and I cannot do anything about the dependencies. But it seems very weird why sometimes it says that there is a problem with this software ovs/iproute when it is always the same (or at least I think so).
