### ISSUE TITLE
select.error: (4, 'Interrupted system call')

### ISSUE THREAD

**Issue by moyeen52** [intrig-unicamp/mininet-wifi#211]
CLI_wifi(net)
  File "/usr/local/lib/python2.7/dist-packages/mininet_wifi-2.3-py2.7.egg/mn_wifi/cli.py", line 11, in __init__
    CLI.__init__(self, mn_wifi, stdin=sys.stdin, script=None)
  File "build/bdist.linux-x86_64/egg/mininet/cli.py", line 68, in __init__
  File "build/bdist.linux-x86_64/egg/mininet/cli.py", line 103, in run
  File "/usr/lib/python2.7/cmd.py", line 142, in cmdloop
    stop = self.onecmd(line)
  File "/usr/lib/python2.7/cmd.py", line 220, in onecmd
    return self.default(line)
  File "build/bdist.linux-x86_64/egg/mininet/cli.py", line 423, in default
  File "build/bdist.linux-x86_64/egg/mininet/cli.py", line 441, in waitForNode
select.error: (4, 'Interrupted system call')

I have a topology with 4 Access point connected as wired. I have assigned 10 hosts at each access point whose are connected through wifi. My program suddenly stops and gives me this error.  I know this is a interruption from OS. But what could be the fix for this issue. I have gone through several online resources but not sure about the possible solution.

**Comment by ramonfontes** [comment]
Hi, could you share your code?

**Comment by moyeen52** [comment]
[gitshared.zip](https://github.com/intrig-unicamp/mininet-wifi/files/2804044/gitshared.zip)
Here is the source code. Thanks for quick reply.

**Comment by ramonfontes** [comment]
Could you please put its content here?

**Comment by moyeen52** [comment]
`
import networkx as nx
from mininet.link import TCLink
from mininet.node import Controller, RemoteController
from mininet.cli import CLI
from mininet.log import setLogLevel
import re,random,time
from networkx.utils import pairwise
from mn_wifi.link import wmediumd, mesh, physicalMesh
from mn_wifi.cli import CLI_wifi
from mn_wifi.net import Mininet_wifi
from mn_wifi.wmediumdConnector import interference
from mininet.node import UserSwitch, OVSSwitch
from mininet.log import setLogLevel, info


def topobuild(n_host=4):
        net = Mininet_wifi(
                   controller=None,link=TCLink, switch=OVSSwitch, waitConnected=True,autoSetMacs=True)
        c0 = net.addController('c0', controller=RemoteController, ip='127.0.0.1', 
                           port=6633)
                       
        net.start()
        graph=nx.DiGraph()
        ap_links=[(0,1),(0,2),(1,2)]
        graph.add_edges_from(ap_links)
        total_node=len(graph.nodes)
        aps={}
        for node in range(total_node):
            aps['ap%s'%(node + 1)] = net.addAccessPoint('ap%s'%(node+1), ssid='ssid%s'%(node+1))
            for host in range(1,n_host+1):
                sta_suffix=str(node+1)+str(host)
                net.addStation('sta%s'%sta_suffix,cpu=.5/total_node)
        net.configureWifiNodes()
        for node in range(total_node):
            for host in range(1,n_host+1):
                sta_suffix=str(node+1)+str(host)
                net.addLink('sta%s'%sta_suffix, 'ap%s'%(node + 1))
        for (sw1, sw2) in ap_links:
            sw1=int(sw1)+1
            sw2=int(sw2)+1
            net.addLink("ap%d" % sw1, "ap%d" % sw2)
  
        net.build()
        c0.start()
        for node in range(total_node):
            aps['ap%s'%(node+1)].start([c0])
            
        return net
     
def runner():
    net = topobuild(10)
    CLI_wifi(net)

if __name__ == '__main__':
    setLogLevel( 'info' )
    runner()  

`

**Comment by moyeen52** [comment]
`mininet-wifi> sta210 ping sta310
PING 10.0.0.30 (10.0.0.30) 56(84) bytes of data.
64 bytes from 10.0.0.30: icmp_seq=1 ttl=62 time=18.8 ms
64 bytes from 10.0.0.30: icmp_seq=2 ttl=62 time=0.839 ms
64 bytes from 10.0.0.30: icmp_seq=3 ttl=62 time=0.223 ms
64 bytes from 10.0.0.30: icmp_seq=4 ttl=62 time=0.250 ms
64 bytes from 10.0.0.30: icmp_seq=5 ttl=62 time=0.412 ms
Traceback (most recent call last):
  File "bfdtopowiredapradiostation.py", line 56, in <module>
    runner()  
  File "bfdtopowiredapradiostation.py", line 52, in runner
    CLI_wifi(net)
  File "/usr/local/lib/python2.7/dist-packages/mininet_wifi-2.3-py2.7.egg/mn_wifi/cli.py", line 11, in __init__
    CLI.__init__(self, mn_wifi, stdin=sys.stdin, script=None)
  File "build/bdist.linux-x86_64/egg/mininet/cli.py", line 68, in __init__
  File "build/bdist.linux-x86_64/egg/mininet/cli.py", line 103, in run
  File "/usr/lib/python2.7/cmd.py", line 142, in cmdloop
    stop = self.onecmd(line)
  File "/usr/lib/python2.7/cmd.py", line 220, in onecmd
    return self.default(line)
  File "build/bdist.linux-x86_64/egg/mininet/cli.py", line 423, in default
  File "build/bdist.linux-x86_64/egg/mininet/cli.py", line 441, in waitForNode
select.error: (4, 'Interrupted system call')
`

**Comment by moyeen52** [comment]
Thanks for asking. 
1. I'm running ryu on 6633 because the other port 6553 is sometimes occupied by reference controller. 
2. If I'm wrong please correct me( I'm starting net at first after adding controller. Then I'm adding access points and stations. Also I have added connections between them. in that stage I might need to rebuild the net. then I can start controller and bind it to access points)
3. Sorry about the import. I did not used that. 
4. That's a good finding about using switch=OVSSWitch I have changed it to OVSAP.  But problem still persists. But this time I had to send lots of ping from several xterminal. 
Thanks for your kind help. Please let me know if you find anything around this,

**Comment by ramonfontes** [comment]
How can I run the script? I'm unable to import `pairwise` and if I don't import it, graph.nodes() seems to be empty.

```
total_node=len(graph.nodes)
TypeError: object of type 'instancemethod' has no len()
```

Is there any relation between that package and `add_edges_from()`?

**Comment by moyeen52** [comment]
`pip install networkx` this will fix it. Its a part of networkx.

**Comment by ramonfontes** [comment]
I have networkx. Please test the code without networkx just to be sure that the issue isn't related to networkx.

**Comment by moyeen52** [comment]
not sure. The error comes all of a sudden. Removed Networkx but nothing helps much. Tthe error came after a long time of execution this time.
