### ISSUE TITLE
Adding Odin option

### ISSUE THREAD

**Issue by uhlik1889** [intrig-unicamp/mininet-wifi#214]
Hi,

I created new option --odin, and now I want to check it with opts.odin and do something in node.py. Any advice?
I don't want to do something big right now, just to change behavior of APConfigFile() to do something different of this option is selected.

Further I would like, when --odin is selected, to run some commands on access points. Like when Mininet is running, using "xterm ap1" and then running some scripts. Similar to cmd() in APConfigFile(), but on access points.

Regards,
Matej.

**Comment by ramonfontes** [comment]
You can take the value of --odin in `net.py`, specially when you add the node (e.g. addAccessPoint()).

**Comment by uhlik1889** [comment]
YES "omg" thank you very much Ramon, I haven't thought that it would go so easily, but with your hint everything is clear now.

So far I successfully tested adding new option, and adding some new functionality into APConfigFile(). Next task would be to run custom commands on APs, and open terminal to run controller there.

**Comment by ramonfontes** [comment]
Cool! Which features have you implemented? Is your code public?

**Comment by uhlik1889** [comment]
I wish to merge it afterwards the publication in my master thesis. The code
is not yet public, but I'll contact you afterwards.

Matej
