### ISSUE TITLE
the roles of station and accesstpoint

### ISSUE THREAD

**Issue by jindengyun** [intrig-unicamp/mininet-wifi#217]
hi, ramon!
i have read the manual(mininet-wifi-draft-manual.pdf), but i still have some questions:
1. if i use the classes of addStation, addAccessPoint in my code to define a sta and an ap, and who plays a SDN switch in my network? or none of them. and what's their role? what's the diffirence among station, accesspoint, host and switch?

2. i find some codes based on mininet-wifi in github(https://github.com/geokal94/Mininet-Wifi/blob/master/Mininet-Wifi/experiment.py#L527),but i have found that already unexecutable. for example, i did not find any information about vehicles and vehiclesSTA in the line 531 and 545...

thanks a lot!

**Comment by ramonfontes** [comment]
Hi,

Please find the answers below:

**1**. APs play the role of SDN switches. Station is a node equipped with wifi interface working on managed mode. On the other hand, hosts don't have wifi interface. Stations were extended from Mininet's hosts. APs are switches equipped with wifi interface working on master mode. Switches don't have wifi interface. APs were extended from Mininet's switches.

**2**. You have two options here:
a) consider the commit from 12/16/2017.
b) consider the new approach available at `https://github.com/intrig-unicamp/mininet-wifi/blob/master/examples/vanet-sumo.py`.

**Comment by jindengyun** [comment]
thanks for ur kindly help!
1. So the stations play  the role of mobile host, and APs play the role of mobile switch, is that right?

2. Sorry , i don't understand the mean of "the commit from 12/16/2017 (or earlier)". And can i find the alternatives to these method?

**Comment by ramonfontes** [comment]
1. Yes.
2. By tracking commits from this repository.

**Comment by jindengyun** [comment]
Thanks. i'll try it.
Best Regards
jdy
