### ISSUE TITLE
ping between stations connected to different ap

### ISSUE THREAD

**Issue by catherinenayer** [intrig-unicamp/mininet-wifi#218]
i need help please this is my code it is very simple but when sta1 ping sta2 the result is 100% losses and destination host unreachable

#!/usr/bin/python

from mininet.node import Controller
from mininet.log import setLogLevel, info
from mn_wifi.net import Mininet_wifi
from mn_wifi.node import Station, OVSKernelAP
from mn_wifi.cli import CLI_wifi
from mn_wifi.link import wmediumd
from mn_wifi.wmediumdConnector import interference
from subprocess import call

def myNetwork():

    net = Mininet_wifi( topo=None, build=False, link=wmediumd,wmediumd_mode=interference, ipBase='10.0.0.0/8')

    info( '*** Adding controller\n' )
    c0=net.addController(name='c0',controller=Controller, protocol='tcp', port=6633)

    info( '*** Add switches/APs\n')
    ap1 = net.addAccessPoint('ap1', cls=OVSKernelAP, ssid='ap1-ssid',channel='1', mode='g', position='562.0,392.0,0')
    ap2 = net.addAccessPoint('ap2', cls=OVSKernelAP, ssid='ap2-ssid',channel='1', mode='g', position='881.0,385.0,0')

    info( '*** Add hosts/stations\n')
    sta2 = net.addStation('sta2', ip='10.0.0.2', position='892.0,557.0,0')
    sta1 = net.addStation('sta1', ip='10.0.0.1', position='513.0,564.0,0')

    info("*** Configuring Propagation Model\n")
    net.setPropagationModel(model="logDistance", exp=3)

    info("*** Configuring wifi nodes\n")
    net.configureWifiNodes()

    info( '*** Add links\n')
    net.addLink(ap2, ap1)
    net.addLink(ap1, sta1)
    net.addLink(ap2, sta2)

    net.plotGraph(max_x=1000, max_y=1000)

    info( '*** Starting network\n')
    net.build()
    info( '*** Starting controllers\n')
    for controller in net.controllers:
        controller.start()

    info( '*** Starting switches/APs\n')
    net.get('ap1').start([c0])
    net.get('ap2').start([c0])

    info( '*** Post configure nodes\n')

    CLI_wifi(net)
    net.stop()

if __name__ == '__main__':
    setLogLevel( 'info' )
    myNetwork()

**Comment by ramonfontes** [comment]
I made some changes in your code. Please consider the code below.

```#!/usr/bin/python

from mininet.node import Controller
from mininet.log import setLogLevel, info
from mn_wifi.net import Mininet_wifi
from mn_wifi.cli import CLI_wifi
from mn_wifi.link import wmediumd
from mn_wifi.wmediumdConnector import interference


def myNetwork():

    net = Mininet_wifi( link=wmediumd, wmediumd_mode=interference)

    info( '*** Adding controller\n' )
    c0 = net.addController(name='c0', controller=Controller, protocol='tcp', port=6653)

    info( '*** Add switches/APs\n')
    ap1 = net.addAccessPoint('ap1',  ssid='ap1-ssid',
                             channel='1', mode='g', position='562.0,392.0,0')
    ap2 = net.addAccessPoint('ap2',  ssid='ap2-ssid',
                             channel='1', mode='g', position='881.0,385.0,0')

    info( '*** Add hosts/stations\n')
    sta2 = net.addStation('sta2', ip='10.0.0.2',
                           position='892.0,557.0,0')
    sta1 = net.addStation('sta1', ip='10.0.0.1',
                           position='513.0,564.0,0')

    info("*** Configuring Propagation Model\n")
    net.setPropagationModel(model="logDistance", exp=3)

    info("*** Configuring wifi nodes\n")
    net.configureWifiNodes()

    info( '*** Add links\n')
    net.addLink(ap1, sta1)
    net.addLink(ap2, sta2)
    net.addLink(ap2, ap1)

    net.plotGraph(max_x=1000, max_y=1000)

    info( '*** Starting network\n')
    net.build()

    info( '*** Starting controllers\n')
    for controller in net.controllers:
        controller.start()

    info( '*** Starting switches/APs\n')
    net.get('ap1').start([c0])
    net.get('ap2').start([c0])

    info( '*** Post configure nodes\n')
    info("*** Running CLI\n")
    CLI_wifi(net)

    info("*** Stopping network\n")
    net.stop()


if __name__ == '__main__':
    setLogLevel( 'info' )
    myNetwork()
```

**Comment by catherinenayer** [comment]
thank you i will check and get you back

**Comment by catherinenayer** [comment]
it works good but when adding switches on top of the access point the ping stop again and here is the modified code and thanks in advance

#!/usr/bin/python

from mininet.node import Controller, OVSKernelSwitch
from mininet.log import setLogLevel, info
from mn_wifi.net import Mininet_wifi
from mn_wifi.cli import CLI_wifi
from mn_wifi.link import wmediumd
from mn_wifi.wmediumdConnector import interference


def myNetwork():

    net = Mininet_wifi( link=wmediumd,wmediumd_mode=interference)

    info( '*** Adding controller\n' )
    c0=net.addController(name='c0',
                      controller=Controller,
                      protocol='tcp',
                      port=6653)

    info( '*** Add switches/APs\n')
    ap2 = net.addAccessPoint('ap2',  ssid='ap2-ssid',
                             channel='1', mode='g', position='549.0,383.0,0')
    s2 = net.addSwitch('s2', cls=OVSKernelSwitch)
    s1 = net.addSwitch('s1', cls=OVSKernelSwitch)
    ap1 = net.addAccessPoint('ap1', ssid='ap1-ssid',
                             channel='1', mode='g', position='278.0,368.0,0')

    info( '*** Add hosts/stations\n')
    sta1 = net.addStation('sta1', ip='10.0.0.1',
                           position='292.0,484.0,0')
    sta2 = net.addStation('sta2', ip='10.0.0.2',
                           position='578.0,487.0,0')

    info("*** Configuring Propagation Model\n")
    net.setPropagationModel(model="logDistance", exp=3)

    info("*** Configuring wifi nodes\n")
    net.configureWifiNodes()

    info( '*** Add links\n')
    net.addLink(ap1, s1)
    net.addLink(s2, ap2)
    net.addLink(ap2, sta2)
    net.addLink(ap1, sta1)
    net.addLink(ap1, ap2)

    net.plotGraph(max_x=1000, max_y=1000)

    info( '*** Starting network\n')
    net.build()
    info( '*** Starting controllers\n')
    for controller in net.controllers:
        controller.start()

    info( '*** Starting switches/APs\n')
    net.get('ap2').start([])
    net.get('s2').start([c0])
    net.get('s1').start([c0])
    net.get('ap1').start([])

    info( '*** Post configure nodes\n')

    CLI_wifi(net)
    net.stop()

if __name__ == '__main__':
    setLogLevel( 'info' )
    myNetwork()

**Comment by ramonfontes** [comment]
You didn't start both `ap1` and `ap2` with `c0`.

**Comment by catherinenayer** [comment]
ok thank you so much it works
