### ISSUE TITLE
how to run application on SDN controller

### ISSUE THREAD

**Issue by catherinenayer** [intrig-unicamp/mininet-wifi#219]
how to run an application (like http or any other) on top of SDN controller in the following code or in other word how to run different traffic in such scenario

#!/usr/bin/python

from mininet.node import Controller, OVSKernelSwitch
from mininet.log import setLogLevel, info
from mn_wifi.net import Mininet_wifi
from mn_wifi.node import Station
from mn_wifi.cli import CLI_wifi
from mn_wifi.link import wmediumd
from mn_wifi.wmediumdConnector import interference

def myNetwork():

    net = Mininet_wifi( link=wmediumd,wmediumd_mode=interference)

    info( '*** Adding controller\n' )
    c0=net.addController(name='c0',
                      controller=Controller,
                      protocol='tcp',
                      port=6653)

    info( '*** Add switches/APs\n')
    ap2 = net.addAccessPoint('ap2', ssid='ap2-ssid',
                             channel='1', mode='g', position='549.0,383.0,0')
    s2 = net.addSwitch('s2', cls=OVSKernelSwitch)
    ap3 = net.addAccessPoint('ap3', ssid='ap3-ssid',
                             channel='1', mode='g', position='697.0,383.0,0')
    ap4 = net.addAccessPoint('ap4', ssid='ap4-ssid',
                             channel='1', mode='g', position='903.0,374.0,0')
    s1 = net.addSwitch('s1', cls=OVSKernelSwitch)
    s4 = net.addSwitch('s4', cls=OVSKernelSwitch)
    ap1 = net.addAccessPoint('ap1', ssid='ap1-ssid',
                             channel='1', mode='g', position='278.0,368.0,0')
    s3 = net.addSwitch('s3', cls=OVSKernelSwitch)

    info( '*** Add hosts/stations\n')
    sta4 = net.addStation('sta4', ip='10.0.0.4',
                           position='935.0,504.0,0')
    sta3 = net.addStation('sta3', ip='10.0.0.3',
                           position='725.0,493.0,0')
    sta1 = net.addStation('sta1', ip='10.0.0.1',
                           position='292.0,484.0,0')
    sta2 = net.addStation('sta2', ip='10.0.0.2',
                           position='578.0,487.0,0')

    info("*** Configuring Propagation Model\n")
    net.setPropagationModel(model="logDistance", exp=3)

    info("*** Configuring wifi nodes\n")
    net.configureWifiNodes()

    info( '*** Add links\n')
    net.addLink(ap3, sta3)
    net.addLink(s3, ap3)
    net.addLink(ap1, s1)
    net.addLink(s2, ap2)
    net.addLink(ap2, sta2)
    net.addLink(ap1, sta1)
    net.addLink(s4, ap4)
    net.addLink(ap4, sta4)
    net.addLink(ap1, ap2)
    net.addLink(ap1, ap3)
    net.addLink(ap1, ap4)

    net.plotGraph(max_x=1000, max_y=1000)

    info( '*** Starting network\n')
    net.build()
    info( '*** Starting controllers\n')
    for controller in net.controllers:
        controller.start()

    info( '*** Starting switches/APs\n')
    net.get('ap2').start([c0])
    net.get('s2').start([c0])
    net.get('ap3').start([c0])
    net.get('ap4').start([c0])
    net.get('s1').start([c0])
    net.get('s4').start([c0])
    net.get('ap1').start([c0])
    net.get('s3').start([c0])

    info( '*** Post configure nodes\n')

    CLI_wifi(net)
    net.stop()

if __name__ == '__main__':
    setLogLevel( 'info' )
    myNetwork()

**Comment by ramonfontes** [comment]
This isn't an issue and I suppose your question is more related to SDN controllers than Mininet-WiFi. Thus, I suppose you will find a response through the controller community you are using.
