### ISSUE TITLE
why ping between sta connected to different ap isn't working

### ISSUE THREAD

**Issue by catherinenayer** [intrig-unicamp/mininet-wifi#220]
when sta1 ping sta8 or other that belongs to other ap the result is destination host unreachable

#!/usr/bin/python

from mininet.node import Controller, OVSKernelSwitch, Node
from mininet.log import setLogLevel, info
from mininet.wifi.net import Mininet_wifi
from mininet.wifi.node import Station
from mininet.wifi.cli import CLI_wifi
from mininet.wifi.link import wmediumd
from mininet.wifi.wmediumdConnector import interference

def myNetwork():

    net = Mininet_wifi( link=wmediumd,wmediumd_mode=interference)

    info( '*** Adding controller\n' )
    c0=net.addController(name='c0',
                      controller=Controller,
                      protocol='tcp',
                      port=6653)

    info( '*** Add switches/APs\n')
    s1 = net.addSwitch('s1', cls=OVSKernelSwitch)
    s2 = net.addSwitch('s2', cls=OVSKernelSwitch)
    s3 = net.addSwitch('s3', cls=OVSKernelSwitch)
    s4 = net.addSwitch('s4', cls=OVSKernelSwitch)

    r6 = net.addHost('r6', cls=Node, ip='0.0.0.0')
    r6.cmd('sysctl -w net.ipv4.ip_forward=1')

    ap1 = net.addAccessPoint('ap1',  ssid='ap1-ssid',channel='1', mode='g', position='191.0,482.0,0')
    ap2 = net.addAccessPoint('ap2', ssid='ap2-ssid',channel='1', mode='g', position='337.0,479.0,0')
    ap3 = net.addAccessPoint('ap3', ssid='ap3-ssid',channel='1', mode='g', position='502.0,481.0,0')
    ap4 = net.addAccessPoint('ap4',  ssid='ap4-ssid',channel='1', mode='g', position='776.0,480.0,0')

    info( '*** Add hosts/stations\n')
    sta1 = net.addStation('sta1', ip='10.0.0.1',position='173.0,487.0,0')
    sta2 = net.addStation('sta2', ip='10.0.0.2',position='233.0,575.0,0')
    sta3 = net.addStation('sta3', ip='10.0.0.3',position='227.0,596.0,0')
    sta4 = net.addStation('sta4', ip='10.0.0.4',position='291.0,495.0,0')
    sta5 = net.addStation('sta5', ip='10.0.0.5',position='346.0,478.0,0')
    sta6 = net.addStation('sta6', ip='10.0.0.6',position='375.0,575.0,0')
    sta7 = net.addStation('sta7', ip='10.0.0.7',position='371.0,582.0,0')
    sta8 = net.addStation('sta8', ip='10.0.0.8',position='330.0,479.0,0')
    sta9 = net.addStation('sta9', ip='10.0.0.9',position='569.0,472.0,0')
    sta10 = net.addStation('sta10', ip='10.0.0.10',position='529.0,570.0,0')
    sta11 = net.addStation('sta11', ip='10.0.0.11',position='518.0,587.0,0')
    sta12 = net.addStation('sta12', ip='10.0.0.12',position='592.0,466.0,0')
    sta13 = net.addStation('sta13', ip='10.0.0.13',position='760.0,474.0,0')
    sta14 = net.addStation('sta14', ip='10.0.0.14',position='708.0,564.0,0')
    sta15 = net.addStation('sta15', ip='10.0.0.15',position='814.0,568.0,0')
    sta16 = net.addStation('sta16', ip='10.0.0.16',position='876.0,458.0,0')

    info("*** Configuring Propagation Model\n")
    net.propagationModel(model="logDistance", exp=3)

    info("*** Configuring wifi nodes\n")
    net.configureWifiNodes()

    info( '*** Add links\n')
    net.addLink(s1, ap1)
    net.addLink(s2, ap2)
    net.addLink(s3, ap3)
    net.addLink(s4, ap4)
    net.addLink(ap1, sta1)
    net.addLink(ap1, sta2)
    net.addLink(ap1, sta3)
    net.addLink(ap1, sta4)
    net.addLink(ap2, sta6)
    net.addLink(ap2, sta7)
    net.addLink(ap2, sta8)
    net.addLink(ap2, sta5)
    net.addLink(ap3, sta9)
    net.addLink(ap3, sta10)
    net.addLink(ap3, sta11)
    net.addLink(ap3, sta12)
    net.addLink(ap4, sta13)
    net.addLink(ap4, sta14)
    net.addLink(ap4, sta15)
    net.addLink(ap4, sta16)
    net.addLink(s1, r6)
    net.addLink(s4, r6)
    net.addLink(s3, r6)
    net.addLink(s2, r6)
    net.addLink(ap1, ap2)
    net.addLink(ap1, ap3)
    net.addLink(ap1, ap4)
    net.addLink(ap3, ap4)
    net.addLink(ap2, ap3)

    net.plotGraph(max_x=1000, max_y=1000)

    info( '*** Starting network\n')
    net.build()
    info( '*** Starting controllers\n')
    for controller in net.controllers:
        controller.start()

    print "*** Starting HTTP server on sta1"
    sta1.cmdPrint('python -m SimpleHTTPServer 80 &')
    print "*** Starting HTTP server on sta2"
    sta2.cmdPrint('python -m SimpleHTTPServer 80 &')
    print "*** Starting HTTP server on sta3"
    sta3.cmdPrint('python -m SimpleHTTPServer 80 &')
    print "*** Starting HTTP server on sta4"
    sta4.cmdPrint('python -m SimpleHTTPServer 80 &')
    print "*** Starting HTTP server on sta5"
    sta5.cmdPrint('python -m SimpleHTTPServer 80 &')
    print "*** Starting HTTP server on sta6"
    sta6.cmdPrint('python -m SimpleHTTPServer 80 &')
    print "*** Starting HTTP server on sta7"
    sta7.cmdPrint('python -m SimpleHTTPServer 80 &')
    print "*** Starting HTTP server on sta8"
    sta8.cmdPrint('python -m SimpleHTTPServer 80 &')
    print "*** Starting HTTP server on sta9"
    sta9.cmdPrint('python -m SimpleHTTPServer 80 &')
    print "*** Starting HTTP server on sta10"
    sta10.cmdPrint('python -m SimpleHTTPServer 80 &')
    print "*** Starting HTTP server on sta11"
    sta11.cmdPrint('python -m SimpleHTTPServer 80 &')
    print "*** Starting HTTP server on sta12"
    sta12.cmdPrint('python -m SimpleHTTPServer 80 &')
    print "*** Starting HTTP server on sta13"
    sta13.cmdPrint('python -m SimpleHTTPServer 80 &')
    print "*** Starting HTTP server on sta14"
    sta14.cmdPrint('python -m SimpleHTTPServer 80 &')
    print "*** Starting HTTP server on sta15"
    sta15.cmdPrint('python -m SimpleHTTPServer 80 &')
    print "*** Starting HTTP server on sta16"
    sta16.cmdPrint('python -m SimpleHTTPServer 80 &')

    info( '*** Starting switches/APs\n')
    net.get('s3').start([c0])
    net.get('ap1').start([c0])
    net.get('s4').start([c0])
    net.get('ap2').start([c0])
    net.get('s1').start([c0])
    net.get('ap3').start([c0])
    net.get('ap4').start([c0])
    net.get('s2').start([c0])

    info( '*** Post configure nodes\n')

    CLI_wifi(net)
    net.stop()

if __name__ == '__main__':
    setLogLevel( 'info' )
    myNetwork()

**Comment by ramonfontes** [comment]
Is there loop in your network topology? Is your controller handling with loops?

**Comment by catherinenayer** [comment]
no

**Comment by ramonfontes** [comment]
No? No for which question? I can see loop in the network tolology. So, can I assume "no" for the last question, am I right? And of course, this explains the lack of communication.

**Comment by catherinenayer** [comment]
there is no loop in my network topology and i don't know if my controller can handle loop or not
ping between sta connected to same ap is working but for other connected to different ap isn't working

**Comment by ramonfontes** [comment]
Dear,

If stations are associated with aps and there is no communication, it means that you have problems at the control plane.

**Comment by catherinenayer** [comment]
so is there any solution for this or i should change the controller type i am using openFlow controller should i use other controller like opendaylight.

**Comment by ramonfontes** [comment]
According your code, `ap1` is attached with both `ap2` and `ap3`, and `ap2` is attached with `ap3`. Isn't this a loop? If you don't know the topology you have and whether your controller is handling with loops, then you should take care with this.

**Comment by catherinenayer** [comment]
ok thank you so much it works

**Comment by catherinenayer** [comment]
but what if we use many controller instead of only one is this may cause a loop?

**Comment by ramonfontes** [comment]
No, you're talking about the control plane. Why would it cause loops? Could you elaborate on that?

Ps. Your question isn't an issue. Please consider to use the mailing list for such questions.
