### ISSUE TITLE
why stations connected to ap1 cannot communicate with stations connected to ap2 or 3 or 4

### ISSUE THREAD

**Issue by catadros** [intrig-unicamp/mininet-wifi#221]
why stations connected to ap1 cannot communicate(ping) with stations connected to ap2 or 3 or 4 

#!/usr/bin/python

from mininet.node import Controller, OVSKernelSwitch, Node
from mininet.log import setLogLevel, info
from mininet.wifi.net import Mininet_wifi
from mininet.wifi.node import Station
from mininet.wifi.cli import CLI_wifi
from mininet.wifi.link import wmediumd
from mininet.wifi.wmediumdConnector import interference

def myNetwork():

    net = Mininet_wifi(link=wmediumd,wmediumd_mode=interference)

    info( '*** Adding controller\n' )
    c0=net.addController(name='c0',controller=Controller,protocol='tcp',port=6653)
    c1=net.addController(name='c1',controller=Controller,protocol='tcp',port=6653)
    c2=net.addController(name='c2',controller=Controller,protocol='tcp',port=6653)
    c3=net.addController(name='c3',controller=Controller,protocol='tcp',port=6653)

    info( '*** Add switches/APs\n')
    s1 = net.addSwitch('s1', cls=OVSKernelSwitch)
    s2 = net.addSwitch('s2', cls=OVSKernelSwitch)
    s3 = net.addSwitch('s3', cls=OVSKernelSwitch)
    s4 = net.addSwitch('s4', cls=OVSKernelSwitch)

    ap1 = net.addAccessPoint('ap1', ssid='ap1-ssid',channel='1', mode='g', position='92.0,431.0,0')
    ap2 = net.addAccessPoint('ap2', ssid='ap2-ssid',channel='1', mode='g', position='385.0,453.0,0')
    ap3 = net.addAccessPoint('ap3', ssid='ap3-ssid',channel='1', mode='g', position='536.0,448.0,0')
    ap4 = net.addAccessPoint('ap4', ssid='ap4-ssid',channel='1', mode='g', position='755.0,439.0,0')

    r5 = net.addHost('r5', cls=Node, ip='0.0.0.0')
    r5.cmd('sysctl -w net.ipv4.ip_forward=1')

    info( '*** Add hosts/stations\n')
    sta1 = net.addStation('sta1', ip='10.0.0.1',position='22.0,401.0,0')
    sta2 = net.addStation('sta2', ip='10.0.0.2',position='23.0,463.0,0')
    sta3 = net.addStation('sta3', ip='10.0.0.3', position='21.0,532.0,0')
    sta4 = net.addStation('sta4', ip='10.0.0.4',position='60.0,561.0,0')
    sta5 = net.addStation('sta5', ip='10.0.0.5', position='100.0,568.0,0')
    sta6 = net.addStation('sta6', ip='10.0.0.6',position='90.0,536.0,0')
    sta7 = net.addStation('sta7', ip='10.0.0.7',position='80.0,497.0,0')
    sta8 = net.addStation('sta8', ip='10.0.0.8',position='72.0,459.0,0')
    sta9 = net.addStation('sta9', ip='10.0.0.9',position='50.0,416.0,0')
    sta10 = net.addStation('sta10', ip='10.0.0.10',position='105.0,352.0,0')

    sta11 = net.addStation('sta11', ip='10.0.0.11',position='401.0,392.0,0')
    sta12 = net.addStation('sta12', ip='10.0.0.12',position='270.0,445.0,0')
    sta13 = net.addStation('sta13', ip='10.0.0.13',position='295.0,502.0,0')
    sta14 = net.addStation('sta14', ip='10.0.0.14',position='336.0,552.0,0')
    sta15 = net.addStation('sta15', ip='10.0.0.15',position='316.0,594.0,0')
    sta16 = net.addStation('sta16', ip='10.0.0.16',position='389.0,608.0,0')
    sta17 = net.addStation('sta17', ip='10.0.0.17',position='432.0,567.0,0')
    sta18 = net.addStation('sta18', ip='10.0.0.18',position='371.0,526.0,0')
    sta19 = net.addStation('sta19', ip='10.0.0.19',position='400.0,468.0,0')
    sta20 = net.addStation('sta20', ip='10.0.0.20',position='466.0,418.0,0')

    sta21 = net.addStation('sta21', ip='10.0.0.21',position='655.0,420.0,0')
    sta22 = net.addStation('sta22', ip='10.0.0.22',position='660.0,472.0,0')
    sta23 = net.addStation('sta23', ip='10.0.0.23',position='619.0,518.0,0')
    sta24 = net.addStation('sta24', ip='10.0.0.24',position='691.0,532.0,0')
    sta25 = net.addStation('sta25', ip='10.0.0.25',position='703.0,579.0,0')
    sta26 = net.addStation('sta26', ip='10.0.0.26',position='765.0,585.0,0')
    sta27 = net.addStation('sta27', ip='10.0.0.27',position='521.0,528.0,0')
    sta28 = net.addStation('sta28', ip='10.0.0.28',position='609.0,461.0,0')
    sta29 = net.addStation('sta29', ip='10.0.0.29',position='645.0,426.0,0')
    sta30 = net.addStation('sta30', ip='10.0.0.30',position='538.0,407.0,0')

    sta31 = net.addStation('sta31', ip='10.0.0.31',position='674.0,406.0,0')
    sta32 = net.addStation('sta32', ip='10.0.0.32',position='646.0,458.0,0')
    sta33 = net.addStation('sta33', ip='10.0.0.33',position='753.0,507.0,0')
    sta34 = net.addStation('sta34', ip='10.0.0.34',position='840.0,598.0,0')
    sta35 = net.addStation('sta35', ip='10.0.0.35',position='709.0,559.0,0')
    sta36 = net.addStation('sta36', ip='10.0.0.36',position='772.0,568.0,0')
    sta37 = net.addStation('sta37', ip='10.0.0.37',position='718.0,553.0,0')
    sta38 = net.addStation('sta38', ip='10.0.0.38',position='818.0,500.0,0')
    sta39 = net.addStation('sta39', ip='10.0.0.39',position='948.0,454.0,0')
    sta40 = net.addStation('sta40', ip='10.0.0.40',position='960.0,367.0,0')

    info("*** Configuring Propagation Model\n")
    net.propagationModel(model="logDistance", exp=3)

    info("*** Configuring wifi nodes\n")
    net.configureWifiNodes()

    info( '*** Add links\n')
    net.addLink(ap1, sta1)
    net.addLink(ap1, sta2)
    net.addLink(ap1, sta3)
    net.addLink(ap1, sta4)
    net.addLink(ap1, sta5)
    net.addLink(ap1, sta6)
    net.addLink(ap1, sta7)
    net.addLink(ap1, sta8)
    net.addLink(ap1, sta9)
    net.addLink(ap1, sta10)

    net.addLink(ap2, sta11)
    net.addLink(ap2, sta12)
    net.addLink(ap2, sta13)
    net.addLink(ap2, sta14)
    net.addLink(ap2, sta15)
    net.addLink(ap2, sta16)
    net.addLink(ap2, sta17)
    net.addLink(ap2, sta18)
    net.addLink(ap2, sta19)
    net.addLink(ap2, sta20)

    net.addLink(ap3, sta21)
    net.addLink(ap3, sta22)
    net.addLink(ap3, sta23)
    net.addLink(ap3, sta24)
    net.addLink(ap3, sta25)
    net.addLink(ap3, sta26)
    net.addLink(ap3, sta27)
    net.addLink(ap3, sta28)
    net.addLink(ap3, sta29)
    net.addLink(ap3, sta30)

    net.addLink(ap4, sta31)
    net.addLink(ap4, sta32)
    net.addLink(ap4, sta33)
    net.addLink(ap4, sta34)
    net.addLink(ap4, sta35)
    net.addLink(ap4, sta36)
    net.addLink(ap4, sta37)
    net.addLink(ap4, sta38)
    net.addLink(ap4, sta39)
    net.addLink(ap4, sta40)

    net.addLink(ap1, ap2)
    net.addLink(ap1, ap3)
    net.addLink(ap1, ap4)

    net.addLink(s1, c0)
    net.addLink(s1, c1)
    net.addLink(s1, c2)
    net.addLink(s1, c3)

    net.addLink(s2, c0)
    net.addLink(s2, c1)
    net.addLink(s2, c2)
    net.addLink(s2, c3)

    net.addLink(s3, c0)
    net.addLink(s3, c1)
    net.addLink(s3, c2)
    net.addLink(s3, c3)

    net.addLink(s4, c0)
    net.addLink(s4, c1)
    net.addLink(s4, c2)
    net.addLink(s4, c3)

    net.addLink(s4, r5)
    net.addLink(s3, r5)
    net.addLink(s2, r5)
    net.addLink(s1, r5)

    net.addLink(s1, ap1)
    net.addLink(s2, ap2)
    net.addLink(s3, ap3)
    net.addLink(s4, ap4)

    net.plotGraph(max_x=1000, max_y=1000)

    info( '*** Starting network\n')
    net.build()
    info( '*** Starting controllers\n')
    for controller in net.controllers:
        controller.start()

    print "*** Starting HTTP server on sta1"
    sta1.cmdPrint('python -m SimpleHTTPServer 80 &')
    print "*** Starting HTTP server on sta2"
    sta2.cmdPrint('python -m SimpleHTTPServer 80 &')
    print "*** Starting HTTP server on sta3"
    sta3.cmdPrint('python -m SimpleHTTPServer 80 &')
    print "*** Starting HTTP server on sta4"
    sta4.cmdPrint('python -m SimpleHTTPServer 80 &')
    print "*** Starting HTTP server on sta5"
    sta5.cmdPrint('python -m SimpleHTTPServer 80 &')
    print "*** Starting HTTP server on sta6"
    sta6.cmdPrint('python -m SimpleHTTPServer 80 &')
    print "*** Starting HTTP server on sta7"
    sta7.cmdPrint('python -m SimpleHTTPServer 80 &')
    print "*** Starting HTTP server on sta8"
    sta8.cmdPrint('python -m SimpleHTTPServer 80 &')
    print "*** Starting HTTP server on sta9"
    sta9.cmdPrint('python -m SimpleHTTPServer 80 &')
    print "*** Starting HTTP server on sta10"
    sta10.cmdPrint('python -m SimpleHTTPServer 80 &')
    print "*** Starting HTTP server on sta11"
    sta11.cmdPrint('python -m SimpleHTTPServer 80 &')
    print "*** Starting HTTP server on sta12"
    sta12.cmdPrint('python -m SimpleHTTPServer 80 &')
    print "*** Starting HTTP server on sta13"
    sta13.cmdPrint('python -m SimpleHTTPServer 80 &')
    print "*** Starting HTTP server on sta14"
    sta14.cmdPrint('python -m SimpleHTTPServer 80 &')
    print "*** Starting HTTP server on sta15"
    sta15.cmdPrint('python -m SimpleHTTPServer 80 &')
    print "*** Starting HTTP server on sta16"
    sta16.cmdPrint('python -m SimpleHTTPServer 80 &')
    print "*** Starting HTTP server on sta17"
    sta17.cmdPrint('python -m SimpleHTTPServer 80 &')
    print "*** Starting HTTP server on sta18"
    sta18.cmdPrint('python -m SimpleHTTPServer 80 &')
    print "*** Starting HTTP server on sta19"
    sta19.cmdPrint('python -m SimpleHTTPServer 80 &')
    print "*** Starting HTTP server on sta20"
    sta20.cmdPrint('python -m SimpleHTTPServer 80 &')
    print "*** Starting HTTP server on sta21"
    sta21.cmdPrint('python -m SimpleHTTPServer 80 &')
    print "*** Starting HTTP server on sta22"
    sta22.cmdPrint('python -m SimpleHTTPServer 80 &')
    print "*** Starting HTTP server on sta23"
    sta23.cmdPrint('python -m SimpleHTTPServer 80 &')
    print "*** Starting HTTP server on sta24"
    sta24.cmdPrint('python -m SimpleHTTPServer 80 &')
    print "*** Starting HTTP server on sta25"
    sta25.cmdPrint('python -m SimpleHTTPServer 80 &')
    print "*** Starting HTTP server on sta26"
    sta26.cmdPrint('python -m SimpleHTTPServer 80 &')
    print "*** Starting HTTP server on sta27"
    sta27.cmdPrint('python -m SimpleHTTPServer 80 &')
    print "*** Starting HTTP server on sta28"
    sta28.cmdPrint('python -m SimpleHTTPServer 80 &')
    print "*** Starting HTTP server on sta29"
    sta29.cmdPrint('python -m SimpleHTTPServer 80 &')
    print "*** Starting HTTP server on sta30"
    sta30.cmdPrint('python -m SimpleHTTPServer 80 &')
    print "*** Starting HTTP server on sta31"
    sta31.cmdPrint('python -m SimpleHTTPServer 80 &')
    print "*** Starting HTTP server on sta32"
    sta32.cmdPrint('python -m SimpleHTTPServer 80 &')
    print "*** Starting HTTP server on sta33"
    sta33.cmdPrint('python -m SimpleHTTPServer 80 &')
    print "*** Starting HTTP server on sta34"
    sta34.cmdPrint('python -m SimpleHTTPServer 80 &')
    print "*** Starting HTTP server on sta35"
    sta35.cmdPrint('python -m SimpleHTTPServer 80 &')
    print "*** Starting HTTP server on sta36"
    sta36.cmdPrint('python -m SimpleHTTPServer 80 &')
    print "*** Starting HTTP server on sta37"
    sta37.cmdPrint('python -m SimpleHTTPServer 80 &')
    print "*** Starting HTTP server on sta38"
    sta38.cmdPrint('python -m SimpleHTTPServer 80 &')
    print "*** Starting HTTP server on sta39"
    sta39.cmdPrint('python -m SimpleHTTPServer 80 &')
    print "*** Starting HTTP server on sta40"
    sta40.cmdPrint('python -m SimpleHTTPServer 80 &')

    info( '*** Starting switches/APs\n')
    net.get('s3').start([c0,c1,c2,c3])
    net.get('ap4').start([c0,c1,c2,c3])
    net.get('s4').start([c0,c1,c2,c3])
    net.get('ap3').start([c0,c1,c2,c3])
    net.get('s1').start([c0,c1,c2,c3])
    net.get('ap1').start([c0,c1,c2,c3])
    net.get('s2').start([c0,c1,c2,c3])
    net.get('ap2').start([c0,c1,c2,c3])

    info( '*** Post configure nodes\n')

    CLI_wifi(net)
    net.stop()

if __name__ == '__main__':
    setLogLevel( 'info' )
    myNetwork()

**Comment by ramonfontes** [comment]
This is not an issue! :( please use the mailing list for such questions. BTW, you cannot connect aps/switches with controllers through addLink().
