### ISSUE TITLE
the handover questions

### ISSUE THREAD

**Issue by jindengyun** [intrig-unicamp/mininet-wifi#223]
hello, ramon, sorry to bother u again. i meet some questions in my experiments.

1.i modified the handover.py followed:

#!/usr/bin/python

'Example for Handover'

from mininet.node import Controller
from mininet.log import setLogLevel, info
from mn_wifi.cli import CLI_wifi
from mn_wifi.node import OVSKernelAP
from mn_wifi.net import Mininet_wifi

def topology():
    "Create a network."
    net = Mininet_wifi(controller=Controller, accessPoint=OVSKernelAP)

    info("*** Creating nodes\n")
    sta1 = net.addStation('sta1', mac='00:00:00:00:00:02', ip='10.0.0.2/8',
                          range=60)
    sta2 = net.addStation('sta2', mac='00:00:00:00:00:03', ip='10.0.0.3/8',
                          range=60)
    ap1 = net.addAccessPoint('ap1', ssid='ssid-ap1', mode='g', channel='1',
                             position='15,30,0', range=30)
    ap2 = net.addAccessPoint('ap2', ssid='ssid-ap2', mode='g', channel='6',
                             position='55,30,0', range=30)
    ap3 = net.addAccessPoint('ap3', ssid='ssid-ap3', mode='g', channel='8',######################
                             position='125,200,0', range=30)#########################
    ap4 = net.addAccessPoint('ap4', ssid='ssid-ap4', mode='g', channel='11',######################
                             position='150,30,0', range=30)#########################

    c1 = net.addController('c1')

    net.setPropagationModel(model="logDistance", exp=5)

    info("*** Configuring wifi nodes\n")
    net.configureWifiNodes()

    info("*** Creating links\n")
    net.addLink(ap1, ap2)
    net.addLink(ap2, ap3)
    net.addLink(ap3, ap4)

    net.plotGraph(max_x=250, max_y=250)

    net.startMobility(time=0)
    net.mobility(sta1, 'start', time=1, position='10,30,0')
    net.mobility(sta2, 'start', time=2, position='0,40,0')
    net.mobility(sta1, 'stop', time=40, position='160,30,0')
    net.mobility(sta2, 'stop', time=40, position='20,40,0')
    net.stopMobility(time=41)

    info("*** Starting network\n")
    net.build()
    c1.start()
    ap1.start([c1])
    ap2.start([c1])
    ap3.start([c1])
    ap4.start([c1])

    info("*** Running CLI\n")
    CLI_wifi(net)

    info("*** Stopping network\n")
    net.stop()

if __name__ == '__main__':
    setLogLevel('info')
    topology()

but i found that sta1 is unable to ping sta2 when sta1 moves out of range of ap2, even though sta1 moves into the range of ap4(sta1 cannot ping sta2 successfully). i don't know why is that.
![捕获22](https://user-images.githubusercontent.com/31470319/57229523-e563f400-7048-11e9-82ed-e1d25cb87e5d.PNG)

2. i found that when i move aps, the connection lines is still in the original location like:
![捕获](https://user-images.githubusercontent.com/31470319/57229142-f6603580-7047-11e9-933f-4c9f85770768.PNG)

so how can i fix that? is ap3 and ap4 still have a connection relationship?
thank u very much

**Comment by ramonfontes** [comment]
Dear,

Did you check the flow table of ap1, ap2, ap3 and ap4? Did you observe any inconsistency?

**Comment by jindengyun** [comment]
oh,  i didn't try to check the flow table of aps, i check like that:

is that all right? 

![捕获365](https://user-images.githubusercontent.com/31470319/57231991-49d58200-704e-11e9-879e-e1f81e1772ae.PNG)

dear, the problem is that i didn't write the flow table for my aps? sorry, i still do not know how to do with that, and why sta1 can ping sta2 successfully in the beginning.

**Comment by ramonfontes** [comment]
My thoughts is that sta1 cannot ping sta2 due to inconsistencies with the flow table. That said, I suggest you to take care about this. If you don't know on how to work with flow tables, I recommend you to read more about the OpenFlow protocol. This issue doesn't seem to be related to Mininet-WiFi at all.

**Comment by jindengyun** [comment]
thank you for your kindly suggestion, sir. i'll read more about the OpenFlow protocol.
