### ISSUE TITLE
A question about llf in associationControl

### ISSUE THREAD

**Issue by juliancastillom** [intrig-unicamp/mininet-wifi#224]
Hi Ramon,
How are you?

I am working with the association control methods in Mininet-wifi. I was checking the script associationControl.py and I'm trying understand the 'llf' mechanism but I got a question about this line of code: 

if len(ap.params['associatedStations']) + 2 < ref_llf:

My question is: why is 2 added to the new AP instead of 1 ?. Also, why is the condition < and not <= ?

**Comment by ramonfontes** [comment]
There is no specific reason for that. Actually, if you consider 1 the client will try to associate to a new AP all the time.

**Comment by juliancastillom** [comment]
Thank you very much for your quick reply
