### ISSUE TITLE
problems with mobility

### ISSUE THREAD

**Issue by CarlottaTagliaro** [intrig-unicamp/mininet-wifi#225]
Good morning,
I would like to know if it was possible to move an AP with the net.setMobilityModel() function..
Also, how can I make a station move in a straight line and then back to its origin within the same script? I tried with the net.mobility() function but the parameters 'start' and 'stop' overrides each other so, if i have a "fragmented" path like this: 
- net.mobility(ap1, 'start', time=11, position='55.0,30.0,0.0')
- net.mobility(ap1, 'stop', time=13, position='200.0,30.0,0.0')
- net.mobility(ap1, 'start', time=21, position='200.0,30.0,0.0')
- net.mobility(ap1, 'stop', time=30, position='55.0,30.0,0.0')

I'm only able to do the second part of it.. Am I doing sth wrong?
Thanks in advance for your help

**Comment by ramonfontes** [comment]
Hi,

Yes, you can move APs with `setMobilityModel()`.

Regarding the last question, first you need to make a `git pull` and run `sudo make install`. Then, you can try something like:
`net.startMobility(time=0, repetitions=3, reverse=True)`

**Comment by CarlottaTagliaro** [comment]
Thanks a lot! Your suggestion worked perfectly!

**Comment by ramonfontes** [comment]
Thank you for your feedback! ;)
