### ISSUE TITLE
Bad documentation API Python: associationControl() method 

### ISSUE THREAD

**Issue by davidcawork** [intrig-unicamp/mininet-wifi#226]
Hi all 😄,

I come from the manual of [Mininet-Wifi](https://github.com/ramonfontes/manual-mininet-wifi/raw/master/mininet-wifi-draft-manual.pdf), I was testing the python API implemented.

I had a problem when implementing the first script with the Mininet-Wifi API. And I think the documentation on the API and really are disparate at this point. I come from Test 3, it proposes a topology of two access points and two Wi-Fi stations, where it is necessary to add a ssf association criterion, in the manual it makes use of the method called ```associationControl()``` and in truth the existing method is called ```setAssociationCtrl()```.

I consider that I should update the documentation or put a note, since it can be a small obstacle for someone who starts using the tool.

- [Actual method](https://github.com/intrig-unicamp/mininet-wifi/blob/master/mn_wifi/net.py#L1620)
- Bad doc:
  * Page 44
  * Page 45 (Exmple 4.5.4)

**Comment by ramonfontes** [comment]
Hello! Where did you take the manual? Pages 44 and 45 are correct. It is worth to mention that the user manual is available at the source code page.

**Comment by davidcawork** [comment]
Right, I have an old version, excuse me! Even so, in this version(actual) the example (pag45) is with the old method, it was good to modify it. Thank you very much your quick response :smile: 


Best,
