### ISSUE TITLE
how to add flow tables between aps

### ISSUE THREAD

**Issue by jindengyun** [intrig-unicamp/mininet-wifi#227]
hello ramon!
i tried to add flow tables between ap1 and ap2  manually, Is this possible?
![pa](https://user-images.githubusercontent.com/31470319/58763050-e5440f00-8588-11e9-99c8-ac93d1e0a29d.jpg)

if so, my code follows:

#!/usr/bin/python
from mininet.node import Controller
from mininet.log import setLogLevel, info
from mn_wifi.net import Mininet_wifi
from mn_wifi.node import OVSKernelAP
from mn_wifi.cli import CLI_wifi

def topology():
    net  = Mininet_wifi(controller=Controller, accessPoint=OVSKernelAP)
    info("*** Creating Nodes\n")
    mov = net.addStation("mov", mac="00:00:00:00:00:02", ip="10.0.0.7/8", range=20, position="30,50,0")
    sta1 = net.addStation("sta1", mac="00:00:00:00:00:06", ip="10.0.0.2/8", range=20, position="30,60,0")
    ap1 = net.addAccessPoint("ap1", ssid="ap1-ssid", mode="g", channel="1", position="30,50,0", range=30)
    ap2 = net.addAccessPoint("ap2", ssid="ap2-ssid", mode="g", channel="6", position="90,50,0", range=30)
    c1 = net.addController("c1", controller=Controller)
    
    info("*** Configuring wifi nodes\n")
    net.configureWifiNodes()
    
    info("*** Associating and Creating links \n")
    net.addLink(ap1, sta1)
    net.addLink(ap1, ap2)

    os.system('ovs-ofctl add-flows "ap1" in_port=1,actions=output:2')
    os.system('ovs-ofctl add-flows "ap1" in_port=2,actions=output:1')

    net.plotGraph(max_x=160, max_y=100)
    
    
    net.startMobility(time=0, AC="ssf")
    net.mobility(mov, "start", time=1, position="30,50,0")
    net.mobility(mov, "stop",  time=31, position="90,50,0")
    net.stopMobility(time=32)
    
    
    info("*** Starting Network\n")
    net.build()
    c1.start()
    ap1.start([c1])
    ap2.start([c1])

    info("*** Running CLI\n")
    CLI_wifi(net)

    info("*** Stopping Network\n")
    net.stop()
    

if __name__ == "__main__":
    setLogLevel("info")
    topology()
    #os.system('sudo mn -c')

but i get
![p2](https://user-images.githubusercontent.com/31470319/58763007-7ebef100-8588-11e9-862e-a698e4e1bb84.jpg)

so how can i add flow tables between ap1 and ap2 correctly？
Thanks in advance for your kindly help!

**Comment by ramonfontes** [comment]
1. Yes, you can add flow tables
