### ISSUE TITLE
MAC layer retransmissions

### ISSUE THREAD

**Issue by niloysh** [intrig-unicamp/mininet-wifi#234]
In the [Mininet WiFi paper (2017)](https://hal.inria.fr/hal-01480973/document), it is mentioned that MAC layer re-transmissions are not supported.

Since then, a lot has changed, especially with wmediumd support. So, presently, does Mininet WiFi support MAC layer re-transmissions? If so, how would I go about capturing it? This is what I have tried so far.

1. Modify ```examples/wmediumd_interference.py``` and set up a monitoring interface on the AP.
2. Send traffic from two STAs to a host (wired) attached to the AP.
3. Capture traffic on the monitoring interface using tcpdump.

However, all packets have the 802.11 wlan.fc.retry set to 0.
I want to capture how many retries there are.

Thanks for your help.

**Comment by ramonfontes** [comment]
As far as I understood MAC layer re-transmissions are supported by wmediumd (see [this pointer](https://github.com/ramonfontes/wmediumd/blob/4ff3652b763cb4c6f2c9c1ec879ddffc4f1557b7/wmediumd/wmediumd.c#L374)), however, we need to mark the frame as a re-transmitted frame. You may want to consider [L406](https://github.com/ramonfontes/wmediumd/blob/4ff3652b763cb4c6f2c9c1ec879ddffc4f1557b7/wmediumd/wmediumd.c#L406) for an easy understanding. I send the RSSI value to the node interface [here](https://github.com/ramonfontes/wmediumd/blob/4ff3652b763cb4c6f2c9c1ec879ddffc4f1557b7/wmediumd/wmediumd.c#L457) and we can basically send any information we want to the node interface.

Not sure, but I think that some changes are needed in mac80211_hwsim as well. For example, mac80211_hwsim checks no ack frames in [L1083](https://github.com/torvalds/linux/blob/v5.2/drivers/net/wireless/mac80211_hwsim.c#L1083). Would we consider [IEEE80211_TX_STAT_NOACK_TRANSMITTED](https://github.com/torvalds/linux/blob/db54615e21419c3cb4d699a0b0aa16cc44d0e9da/include/net/mac80211.h#L792)? I don't know... 

The good news is that we can easily change mac80211_hwsim, recompile it and use it with Mininet-WiFi. You can find a Mininet-WiFi script in [here](https://www.dropbox.com/sh/x33ah2fhw1j8jaz/AABSOH4rIZYBWh7sfa93rebda?dl=0). It works fine with kernel version 5.0, but you can replace mac80211_hwsim.c and mac80211_hwsim.h according your kernel version.
