### ISSUE TITLE
Adhoc Nodes with IPv6

### ISSUE THREAD

**Issue by Diggensag** [intrig-unicamp/mininet-wifi#235]
Hi Ramon, hope you´re fine!

After a long time spend with Omnet++, I am so happy, that finally I found a project that suits my needs for testing a realworld programm in virtual Wifi.

I wondered if I can somehow make IPv6 work with Wifi. IPv6lowpan is nice, but I need classic Wifi with IPv6. Is there a way that I can enable Hosts/"Cars" getting a link-local address?

Greetings

*edit* I have a ubuntu 18.04 VM installed with the install.sh script.

**Comment by ramonfontes** [comment]
Hi,

Please try node.setIPv6() and let me know whether it works.

**Comment by Diggensag** [comment]
Thanks for the quick reply!

Oddly, it seems that sta1-3 have now their IPv6 address, but only some of them bind to that correctly. Maybe I made some mistake?
I also restartet the whole VM, just to be sure to have no garbage around. But it looks like it´s reproducible on my VM:

I modified your example/adhoc.py and added the setIPv6() after net.build(), like it´s done for IPv4 adresses in some other examples:

>  info("*** Addressing...\n")
    sta1.setIPv6('fe80::ff:fe00:100', intf="sta1-wlan0")
    sta2.setIPv6('fe80::ff:fe00:200', intf="sta2-wlan0")
    sta3.setIPv6('fe80::ff:fe00:300', intf="sta3-wlan0")

every node get´s their address assigned:
> mininet-wifi> sta1 ifconfig
lo: flags=73<UP,LOOPBACK,RUNNING>  mtu 65536
        inet 127.0.0.1  netmask 255.0.0.0
        inet6 ::1  prefixlen 128  scopeid 0x10<host>
        loop  txqueuelen 1000  (Lokale Schleife)
        RX packets 0  bytes 0 (0.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 0  bytes 0 (0.0 B)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

        sta1-wlan0: flags=4099<UP,BROADCAST,MULTICAST>  mtu 1500
        inet 10.0.0.1  netmask 255.0.0.0  broadcast 0.0.0.0
        inet6 fe80::ff:fe00:100  prefixlen 64  scopeid 0x20<link>
        ether 02:00:00:00:00:00  txqueuelen 1000  (Ethernet)
        RX packets 44  bytes 3756 (3.7 KB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 6  bytes 574 (574.0 B)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0



sta1 can´t ping itself via v6:

> mininet-wifi> sta1 ping fe80::ff:fe00:100%sta1-wlan0
   connect: the requested address can´t be assigned

sta1 can´t ping it´s neighbor sta2 via v6:
> mininet-wifi> sta1 ping fe80::ff:fe00:200%sta1-wlan0
   connect:  the requested address can´t be assigned

but sta1 can ping sta2 via IPv4:
> mininet-wifi> sta1 ping sta2
   PING 10.0.0.2 (10.0.0.2) 56(84) bytes of data.
   64 bytes from 10.0.0.2: icmp_seq=1 ttl=64 time=0.490 ms
   64 bytes from 10.0.0.2: icmp_seq=2 ttl=64 time=0.615 ms

and sta2 can ping sta3 and vice versa:
> mininet-wifi> sta3 ping fe80::ff:fe00:200%sta3-wlan0
   PING fe80::ff:fe00:200%sta3-wlan0(fe80::ff:fe00:200%sta3-wlan0) 56 data bytes
   64 bytes from fe80::ff:fe00:200%sta3-wlan0: icmp_seq=1 ttl=64 time=1.90 ms
   64 bytes from fe80::ff:fe00:200%sta3-wlan0: icmp_seq=2 ttl=64 time=0.834 ms

when I add more hosts, it seems like every third host or so, is complety unable to use the displayed IPv6 address.




connect: Die angeforderte Adresse kann nicht zugewiesen werden

**Comment by ramonfontes** [comment]
Thank you for detailed explanation about the problem.

I just tested `adhoc.py` with the changes mentioned by you and it worked. Can you try `ping6` instead of `ping`? I've updated [adhoc.py](https://github.com/intrig-unicamp/mininet-wifi/blob/master/examples/adhoc.py) by adding `setIPv6()` and added a [simple test](https://github.com/intrig-unicamp/mininet-wifi/blob/ffae38cd36292dd78722a06b479066ba131f16f0/mn_wifi/test/test_walkthrough.py#L520) for IPv6. It worked with [Travis](https://travis-ci.org/intrig-unicamp/mininet-wifi/jobs/557898484#L3523) too.

**Comment by Diggensag** [comment]
Hi Ramon,
I can confirm, your example is running fine over here, too. It seem´s that it has something to do with the address range given to the interfaces. In your example you use 2001::x and everything works as expected.
By switching back to the link local range fe80::x/10 in the extended example I start to get those problems again.

Normally I would use 2001::x then, but I have this experiment already set up with some RasperryPIs, where they self obtain a IPv6 link local address, then start to communicate with each other over a python programm. 

E.g. from one of my real world raspberrys:
> wlan0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1560
   inet6 fe80::76da:38ff:fe8b:d648  prefixlen 64  scopeid 0x20<link>

So I am not sure about it. What happens if you´re trying
>    info("*** Addressing...\n")
    sta1.setIPv6('fe80::1/10', intf="sta1-wlan0")
    sta2.setIPv6('fe80::2/10', intf="sta2-wlan0")
    sta3.setIPv6('fe80::3/10', intf="sta3-wlan0")

is your sta1 able to ping itself or a neighbor?

Don´t get me wrong, I´m just wondering if this really isn´t a bug and someone isn´t stumbling over it after me - so I want to help to fix it (if it is one and not a layer8 problem :-) ).

Thanks again for your efforts to help me!

**Comment by ramonfontes** [comment]
Yeah, It might be a Layer8 problem. I really enjoy this kind of discussion. :) Ok, let's try to find the reason of the problem, I have an idea though.

If we try the setup below:
`sta1: fe80::ff:fe00:100`
`sta2: fe80::ff:fe00:200`
`sta3: fe80::ff:fe00:300`

In addition to have those IP addresses, they will have the IPs below:
`sta1: fe80::ff:fe00:0`
`sta2: fe80::ff:fe00:100`
`sta3: fe80::ff:fe00:200`

For example:
> sta1-wlan0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 10.0.0.1  netmask 255.0.0.0  broadcast 0.0.0.0
        inet6 fe80::ff:fe00:100  prefixlen 64  scopeid 0x20<link>
        inet6 fe80::ff:fe00:0  prefixlen 64  scopeid 0x20<link>
        ether 02:00:00:00:00:00  txqueuelen 1000  (Ethernet)
        RX packets 8  bytes 680 (680.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 11  bytes 1160 (1.1 KiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

**Conclusion**: both sta1 and sta2 will have fe80::ff:fe00:100; and sta2 and sta3 will have fe80::ff:fe00:200.
 
However, if we try:
`sta1: fe80::ff:fe00:300`
`sta2: fe80::ff:fe00:400`
`sta3: fe80::ff:fe00:500`

Then everything works as expected. I confess I still need to read more about IPv6 Link-local address, but it seems to work because there is no duplicate IP address.

**Comment by Diggensag** [comment]
I was really hoping it´s me, but trying to replay that I found that I have a really strange behavior over here. I even forked your repo, so you can see, which file I am using.

At first try, it did not go as you wrote.
Second try, it did exactly go as you wrote.
Third try, broken.
Then > mn -c
Fourth try, still

It seem´s that it is random, if sta1 gets assigned fe80::ff:fe00:00 or not. If it gets it, it works as expected. But in 9 out of 10 trys I´ll have this error.

I´ll push a logfile to my repo.

**Comment by Diggensag** [comment]
I think I found it now!

Turning mininet´s logging to "debug" while simultaniously watching VMlogs "journalctl -f" on the Ubuntu Host it turned out, that the wlan0 interface (that gets renamed to sta1-wlan0 by mininet) didn´t come up properly. Diving a bit deeper showed that Networkmanager was somehow still alive (even though I disabled it via systemctl) fiddling around with wlan0, but leaving the others untouched. So it turns out NetworkManager can even f*** up your Mininet instance not only at start, while mininet is looking good, no it still can bite you while you think it was turned off...

AND it seems that now I can achieve what I wanted with config like:
> sta1.setIPv6('', intf="sta1-wlan0")
sta2.setIPv6('', intf="sta2-wlan0")
sta3.setIPv6('', intf="sta3-wlan0")

Starts up the interface with no address, then somehow the linklocal (from mininet?) mechanism is kicking in.

Anyway, I am happy now.

Thank you for your great support!

**Comment by ramonfontes** [comment]
_Or maybe, is there a way, to let wmediumd/mininet-wifi automatically assign a IPv6 link-local address? I mean, where do the "fe80::ff:fe00:0"," fe80::ff:fe00:100" come from, if we didn´t specify them in the config file?_
**Answer**: By now, I have no idea where they come from. I also noticed that sometimes the node doesn't get assigned the other IPv6 link-local address. It only gets assigned after trying a simple ping to any other node. >This seems to be a Linux networking issue<.

Anyway, I'm happy that it is working now too.

Thank you for the detailed description of the problem.
