### ISSUE TITLE
6LoWPAN Limitation

### ISSUE THREAD

**Issue by brunobcfum** [intrig-unicamp/mininet-wifi#236]
Is there any limitation when running 6LoWPAN nodes? I can only add up to 10 nodes, after that I have issues starting fakelb:

> Warning! Error when loading fakelb. Please run sudo 'mn -c' before running your code.
> Further information available at /tmp/mininetwifi-fakelb.log.

There isn't any /tmp/mininetwifi-fakelb.log.

I can however run: sudo modprobe fakelb numlbs=30 with no problem.

BR,
Bruno

**Comment by ramonfontes** [comment]
Fixed with https://github.com/intrig-unicamp/mininet-wifi/commit/b61bb7bf7c74dea9c2a7cde5c6dd122798042a5e!

**Comment by chesteve** [comment]
Nice!

**Comment by brunobcfum** [comment]
Thanks!
