### ISSUE TITLE
No. Everything you need is to issue `sudo util/install.sh -Wlnfv`.

### ISSUE THREAD

**Issue by FT-199** [intrig-unicamp/mininet-wifi#238]
No. Everything you need is to issue `sudo util/install.sh -Wlnfv`.

_Originally posted by @ramonfontes in https://github.com/intrig-unicamp/mininet-wifi/issues/210#issuecomment-457914041_

---------------------------------------------------------------------------------------------------
I did all that @ramonfontes said. But the problem still exists. 

Traceback (most recent call last):
  File "./vanet_eNodeB.py", line 14, in <module>
    from mininet.wifi.node import OVSKernelAP
ImportError: No module named wifi.node
root@Latitude:~/mininet-wifi/examples# 

First I uninstall minnet and then I installed only mininet-wifi without any error.

**Comment by ramonfontes** [comment]
Where did you find `wifi.node`? Shouldn't the module be `mn_wifi.node`?

**Comment by FT-199** [comment]
When I run the sample code for VANET:
-----------------------------------------------------------
#!/usr/bin/python

"""This code illustrates a single case about Vehicular Ad-Hoc Networks.
More detail about VANET implementation can be found at the paper titled
From Theory to Experimental Evaluation: Resource Management
in Software-Defined Vehicular Networks
url: http://ieeexplore.ieee.org/document/7859348/
Video clip available at: https://www.youtube.com/watch?v=kO3O9EwrP_s
"""

import os
import time
import matplotlib.pyplot as plt
from mininet.wifi.node import OVSKernelAP
from mininet.log import setLogLevel
from mininet.wifi.net import Mininet_wifi
from mininet.wifi.cli import CLI_wifi

**Comment by ramonfontes** [comment]
You should consider a commit of Mininet-Wifi from 2017 if you want to reproduce such work.

**Comment by FT-199** [comment]
Thanks!
