### ISSUE TITLE
Logging position, RSSI, speed for mobile station in mininet-wifi

### ISSUE THREAD

**Issue by salubinseid** [intrig-unicamp/mininet-wifi#244]
I'm new for mininet. How do I log the position, rssi while the station are in mobile state? 
I can use py sta1.params['rssi'] but it only display single instance. I need to get all rssi value while the station move aware from one access point to another?

**Comment by ramonfontes** [comment]
You can add your own code in https://github.com/intrig-unicamp/mininet-wifi/blob/09b377186d037664c4764da0b1fcf62fafb30ac0/mn_wifi/mobility.py#L86 and send both position and rssi to a file.

**Comment by salubinseid** [comment]
Thanks for reply. I'm new for mininet wifi. Here bellow my code. I don't know how to integrate mobility.py with my code. If you don't mind will you show me a simple example. Thanks 

#!/usr/bin/python
import sys
from mininet.node import Controller, OVSKernelSwitch
from mininet.log import setLogLevel, info
from mn_wifi.node import UserAP
from mn_wifi.cli import CLI_wifi
from mn_wifi.net import Mininet_wifi
from mn_wifi.sumo.runner import sumo
from mn_wifi.link import wmediumd, mesh
from mn_wifi.wmediumdConnector import interference

def mobility_test():
    "A simple test of mobility"
    info( '* Simple mobility test\n' )

    net = Mininet_wifi( controller=Controller, link=wmediumd, switch=OVSKernelSwitch )

    print "*** Creating nodes"
    h1 = net.addHost( 'edge1', mac='00:00:00:00:00:01', ip='10.0.0.1/8')
    h2 = net.addHost( 'edge2', mac='00:00:00:00:00:02', ip='10.0.0.2/8')

    gateway = net.addSwitch('s1')
    
    ap1 = net.addAccessPoint( 'ap1', ssid= 'ssid-ap', mode= 'g', channel= '1', position='50,500,0', range='30' )
    ap2 = net.addAccessPoint( 'ap2', ssid= 'ssid-ap', mode= 'g', channel= '6', position='100,500,0', range='30' )
    ap3 = net.addAccessPoint( 'ap3', ssid= 'ssid-ap', mode= 'g', channel= '6', position='150,500,0', range='30' )
    ap4 = net.addAccessPoint( 'ap4', ssid= 'ssid-ap', mode= 'g', channel= '6', position='200,500,0', range='30' )
    ap5 = net.addAccessPoint( 'ap5', ssid= 'ssid-ap', mode= 'g', channel= '6', position='250,500,0', range='30' )
    ap6 = net.addAccessPoint( 'ap6', ssid= 'ssid-ap', mode= 'g', channel= '6', position='300,500,0', range='30' )
    ap7 = net.addAccessPoint( 'ap7', ssid= 'ssid-ap', mode= 'g', channel= '6', position='350,500,0', range='30' )
    ap8 = net.addAccessPoint( 'ap8', ssid= 'ssid-ap', mode= 'g', channel= '6', position='400,500,0', range='30' )
    ap9 = net.addAccessPoint( 'ap9', ssid= 'ssid-ap', mode= 'g', channel= '6', position='450,500,0', range='30' )
    ap10 = net.addAccessPoint( 'ap10', ssid= 'ssid-ap', mode= 'g', channel= '6', position='500,500,0', range='30' )

    ap11 = net.addAccessPoint( 'ap11', ssid= 'ssid-ap', mode= 'g', channel= '6', position='550,500,0', range='30' )
    ap12 = net.addAccessPoint( 'ap12', ssid= 'ssid-ap', mode= 'g', channel= '6', position='600,500,0', range='30' )
    ap13 = net.addAccessPoint( 'ap13', ssid= 'ssid-ap', mode= 'g', channel= '6', position='650,500,0', range='30' )
    ap14 = net.addAccessPoint( 'ap14', ssid= 'ssid-ap', mode= 'g', channel= '6', position='700,500,0', range='30' )
    ap15 = net.addAccessPoint( 'ap15', ssid= 'ssid-ap', mode= 'g', channel= '6', position='750,500,0', range='30' )
    ap16 = net.addAccessPoint( 'ap16', ssid= 'ssid-ap', mode= 'g', channel= '6', position='800,500,0', range='30' )
    ap17 = net.addAccessPoint( 'ap17', ssid= 'ssid-ap', mode= 'g', channel= '6', position='850,500,0', range='30' )
    ap18 = net.addAccessPoint( 'ap18', ssid= 'ssid-ap', mode= 'g', channel= '6', position='900,500,0', range='30' )
    ap19 = net.addAccessPoint( 'ap19', ssid= 'ssid-ap', mode= 'g', channel= '6', position='950,500,0', range='30' )
    ap20 = net.addAccessPoint( 'ap20', ssid= 'ssid-ap', mode= 'g', channel= '6', position='1000,500,0', range='30' )
    
    #sta1 = net.addStation( 'sta1', mac='00:00:00:00:00:02', ip='10.0.0.1/8', position='60,50,0', range='20' )
    sta1 = net.addStation( 'sta1', mac='00:00:00:00:00:03', ip='10.0.0.3/8', position='60,500,0', range='150')
    sta2 = net.addStation( 'sta2', mac='00:00:00:00:00:04', ip='10.0.0.4/8', position='50,500,0' )

    info("*** Creating nodes\n")
    cars = []
    for id in range(0, 10):
        cars.append(net.addCar('car%s' % (id+1), wlans=2,
                               bgscan_threshold=-60,
                               s_inverval=5,
                               l_interval=10
                               ))


    c1 = net.addController( 'c1', controller=Controller )

    info("*** Configuring Propagation Model\n")
    net.setPropagationModel(model="logDistance", exp=2)


    """plot graph"""
    net.plotGraph(max_x=1000, max_y=1000)

    # Comment out the following two lines to disable AP
    print "*** Enabling association control (AP)"
    #net.associationControl( 'ssf' )
    net.configureWifiNodes()       

    print "*** Creating links and associations"
    #net.addLink(ap1, h1)
    net.addLink(h1, ap1)
    net.addLink(h1, h2)
    #net.addLink( ap1, ap2 )
    #net.addLink( ap2, ap3 )
    net.addLink( ap1, sta1 )
    net.addLink( ap2, sta2 )

    net.startMobility(time=0, repetitions=1, AC='ssf') # ssf (Strongest-Signal-First) or llf (Least-Loaded-First)
    net.mobility(sta1, 'start', time=1, position='1.0,490.0,0.0')
    net.mobility(sta1, 'stop', time=119, position='1000.0,490.0,0.0') # which means 61.2 kilo meter per hour 

    net.mobility(sta2, 'start', time=10, position='1.0,490.0,0.0')
    net.mobility(sta2, 'stop', time=129, position='1000.0,490.0,0.0')

    for car in cars:
        net.mobility(car, 'start', time=5, position='1.0,490.0,0.0')
        net.mobility(car, 'stop', time=79, position='1000.0,490.0,0.0')

    for car in cars:
        net.addLink(car, intf=car.params['wlan'][1],
                    cls=mesh, ssid='mesh-ssid', channel=5)

    net.stopMobility(time=180)


    #net.useExternalProgram(program=sumo, port=8813, config_file='map.sumocfg')



    print "*** Starting network"
    net.build()
    c1.start()
    ap1.start( [c1] )
    ap2.start( [c1] )
    ap3.start( [c1] )
    ap4.start( [c1] )
    ap5.start( [c1] )
    
    ap6.start( [c1] )
    ap7.start( [c1] )
    ap8.start( [c1] )
    ap9.start( [c1] )
    ap10.start( [c1] )


    ap11.start( [c1] )
    ap12.start( [c1] )
    ap13.start( [c1] )
    ap14.start( [c1] )
    ap15.start( [c1] )


    ap16.start( [c1] )
    ap17.start( [c1] )
    ap18.start( [c1] )
    ap19.start( [c1] )
    ap20.start( [c1] )

    sta1.cmd('iw dev %s interface add mon0 type monitor' % sta1.params['wlan'][0])
    sta1.cmd('ifconfig mon0 up')
    #sta1.cmd('wireshark -i mon0 &')

    #info(sta2.params['rssi'][0])
    #info("dBm *** RSSI\n") 

    #info(sta2.params['position'])  


    for car in cars:
        car.setIP('192.168.0.%s/24' % (int(cars.index(car))+1),
                  intf='%s-wlan0' % car)
        car.setIP('192.168.1.%s/24' % (int(cars.index(car))+1),
                  intf='%s-mp1' % car)

    print "*** Running CLI"
    CLI_wifi( net )
    #info (sta1.cmd("echo 1 > /proc/sys/net/ipv4/ip_forward"))
    #net.start()
    #info (sta1.cmd('ping -c1 %s' % sta2.IP()))

    print "*** Stopping network"
    net.stop()

if __name__ == '__main__':
    setLogLevel('info')
    coord = True if '-c' in sys.argv else False
    mobility_test()

**Comment by ramonfontes** [comment]
Dear,

You need to change the code base of Mininet-WiFi. I pointed you out where you need to add your own code. In other words, instructions to send position and rssi to a file.

**Comment by ramonfontes** [comment]
I just added a new sample file (https://github.com/intrig-unicamp/mininet-wifi/tree/master/examples/telemetry.py) where you can get the rssi, among other things.
