### ISSUE TITLE
new socket feature(2/2): server not reachable from within staX / connection refused

### ISSUE THREAD

**Issue by Diggensag** [intrig-unicamp/mininet-wifi#253]
So I used the code mentioned one issue earlier, trying to connect to the server. Works fine for one message as root on the host console.

But if I start it from mn-wifi (examples/socket_server.py) like:
mininet-wifi> sta1 xterm
then inside the lxcontainer:

```
python2 geonode.py --sumocar sta1-wlan0
SUMOCAR MODE
      + INTERFACE ipV6: sta1-wlan0
{'wifiradius': 50, 'coord_y': '-999', 'name': '-999', 'coord_z': '-999', 'longitude': '-999', 'id': -999, 'latitude': '-999', 'class': 'regular', 'coord_x': '-999'}
Traceback (most recent call last):
  File "geonode.py", line 858, in <module>
    main()
  File "geonode.py", line 712, in main
    oslib.getCoordinatesOverSocket(interfaceV6)
  File "/*snip*/lib/oslib.py", line 159, in getCoordinatesOverSocket
    s.connect((host, port))
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
socket.error: [Errno 111] Connection refused
```

Do I have to modify some stuff to give access from the sta1 container to the hostmachine or sth. else?

**Comment by ramonfontes** [comment]
There was a problem in the communication with the server. I use `addNat()` as workaround and the station can talk to the server right now. Please note that you have to define the ip address of your host in `socket_server.py`.

https://github.com/intrig-unicamp/mininet-wifi/commit/221f52dae0c7328ef14c07106d776c43dac99efa

**Comment by Diggensag** [comment]
Works now. But socket_server is running wild on my system ;-) I'll open a new issue on that.
