### ISSUE TITLE
802.11p based access point

### ISSUE THREAD

**Issue by daviddvs** [intrig-unicamp/mininet-wifi#257]
Hi,
I am simulating an ITS scenario based on 802.11p. I am interested in the 802.11p feature that allows the connection between OBU and RSU without authentication nor association (for high-speed scenarios). I have tested the ITSLink between STAs, that allows me to directly send information from one STA to another. Is it possible to establish such link between an STA and an AP?
David

**Comment by daviddvs** [comment]
I tested the following code:
```
net = Mininet_wifi(controller=Controller, link=wmediumd, wmediumd_mode=interference)
    info("*** Creating nodes\n")
    sta1 = net.addStation('sta1', ip='10.0.0.1/24', position='200,120,0', channel='161')
    rsu1 = net.addAccessPoint('rsu1', ssid='rsu1', channel='171', position='200,100,0', range=20)
    h5 = net.addHost('h5', ip='10.0.0.5/24')
    h6 = net.addHost('h6', ip='10.0.0.6/24')
    
    c1 = net.addController('c1')

    info("*** Configuring Propagation Model\n")
    net.setPropagationModel(model="logDistance", exp=3.5)
    
    info("*** Configuring wifi nodes\n")
    net.configureWifiNodes()

    net.plotGraph(max_x=500, max_y=500)

    info("*** Starting WiFi Direct\n")
    net.addLink(sta1, cls=ITSLink)
    net.addLink(rsu1,intf='rsu1-wlan1', cls=ITSLink)
    net.addLink(rsu1, h5)
    net.addLink(rsu1, h6)

    info("*** Starting network\n")
    net.build()
    
    c1.start()
    rsu1.start([c1])

    info("*** Running CLI\n")
    CLI_wifi(net)

    info("*** Stopping network\n")
    net.stop()`
```
Unfortunately, I could not ping sta1 -> h5.

**Comment by ramonfontes** [comment]
`sta1` is working on channel **161**, while `ap1` on channel **171**. How is this supposed to work?

1. Could you confirm that both `sta1` and `ap1` can communicate with each other?
2. How about `h5`. Is it receiving an ARP request, at least?

* I wouldn't manually set the signal range unless you know what you're doing. I'd prefer to modify the propagation model and the exponent.
* If `sta1` can communicate with `rsu1`, and `sta1` cannot communicate with `h5` you may need to set IP address for `rsu1`. You also may need to consider UserAP (ofsoftswitch13) instead of OVS.

**Comment by daviddvs** [comment]
This is my situation when I ping `sta1`-->`h5`, the `ARPresponse` cannot reach the `sta1`, so I suposes that the failure is in the link from `ap1` to `sta1`. I have also tried using UserAP, but the result is the same.

`sta1` --`ARPreq`--> `ap1` --`ARPreq`--> `h5`
`sta1` <--X-- `ap1` <--`ARPres`-- `h5`

**Comment by ramonfontes** [comment]
I successfully run this code: https://gist.github.com/ramonfontes/0eb8f65d4fd803fa29819832d09bc2bd

In this code I had to split the network into subnets to make it work properly. However, I still don't know why 802.11p requires such setup.

**Comment by daviddvs** [comment]
I have tested that code and I cannot ping `sta1`-x->`h5`, however, I can ping:

`sta1` --> `rsu1 (10.0.0.10)`
`sta1` --> `rsu1 (192.168.0.1)`
`h5` --> `rsu1 (10.0.0.10)`
`h5` --> `rsu1 (192.168.0.1)`

I suppose that something goes wrong in rsu1, which is not able to forward packets (even ARPs) between its interfaces. .

**Comment by ramonfontes** [comment]
Did you install `ofsoftswitch13`? `sudo util/install.sh -3f`

**Comment by daviddvs** [comment]
I do now, and it still doesn't work, the rsu1 does not forward any packet.

**Comment by ramonfontes** [comment]
Strange. As I said, that code worked as expected here. Can `sta1` ping `sta2`?

**Comment by daviddvs** [comment]
Yes, `sta1`  can ping `sta2`, same situation as in https://github.com/intrig-unicamp/mininet-wifi/issues/257#issuecomment-541749135.

Do you use any external controller like Ryu or ONOS?

**Comment by ramonfontes** [comment]
No. I only run the code and then it works.

See: https://intrig.dca.fee.unicamp.br:8840/owncloud/index.php/s/G5SRvJieVkHGX6h

**Comment by daviddvs** [comment]
The only way I can get it work is by setting `echo 1 > /proc/sys/net/ipv4/ip_forward` in the `rsu1`. Therefore, I suppose that there is something wrong with the controller, which is not able to send the instructions to the `rsu1` in order to forward packets (`/tmp/c1.log` file does not tell anything).

**Comment by ramonfontes** [comment]
I agree that this is really strange. It would be great if someone run the same code with P4.

**Comment by ramonfontes** [comment]
Please refer to **_Running P4 Tutorials_** from https://mininet-wifi.github.io/

**Comment by ramonfontes** [comment]
`protobuf` is a P4 dependence and. `sudo util/install.sh -Wlnfv` doesn't install `protobuf` and there is no reason for installing it. So, you need to make sure that P4 is working properly.

**Comment by daviddvs** [comment]
The problem is that official P4 tutorials work before instatiilng Mininet-WiFi (`sudo util/install.sh -Wlnfv`). After installing installing Mininet-WiFi it turns up the aforementioned error.

**Comment by ramonfontes** [comment]
I can see no relationship between `sudo util/install.sh -Wlnfv` and the message accusing error with `protobuf`. I just downloaded the P4 VM, followed the steps described in https://mininet-wifi.github.io/ and it worked. Do you have both `python3` and `python2` installed? You may need to check whether you are using python2. I've found many related-topics e.g. https://github.com/p4lang/tutorials/issues/265

**Comment by ramonfontes** [comment]
IEEE 802.11p is officially supported from kernel 5.6.

- https://github.com/torvalds/linux/commit/7dfd8ac327301f302b03072066c66eb32578e940#diff-21081ef83e1374560c2e244926168e49 enables OCB and
- https://github.com/torvalds/linux/commit/b5764696ac409523414f70421c13b7e7a9309454#diff-21081ef83e1374560c2e244926168e49 enables 5.9GHz
