### ISSUE TITLE
Stop the car mobility when running examples/vanet.py

### ISSUE THREAD

**Issue by badDDalways** [intrig-unicamp/mininet-wifi#261]
Hello, I'd like to stop the car mobility when running examples/vanet.py. I've tried "net. stopMobility()" method, and there's no effect. Is there any other way to stop the car on the road? Thank you.

**Comment by ramonfontes** [comment]
Hi,

You can try the `stop` command in the CLI.

**Comment by badDDalways** [comment]
Hi,

 I tried the stop command while running examples/vanet.py, it didn't work, cars are still moving. 
However, when I tried this command in examples/mobility.py, it worked well. I think it's possible that some mobility methods have been rewritten in vanet.py.  Is there any other solutions? 

Thank you.

**Comment by ramonfontes** [comment]
https://github.com/intrig-unicamp/mininet-wifi/commit/c71a17158fd71d3f7f77a66b58f7f5efe8a8c070 enables `stop` command for `vanet.py`

**Comment by badDDalways** [comment]
Thank you very much.
I tried a few more times, the stop command still cannot work.

**Comment by ramonfontes** [comment]
Did you recompile the code with `sudo make install`?

**Comment by badDDalways** [comment]
It works well~~~!!!!
Thank you very much~~~!!!
