### ISSUE TITLE
mininet-wifi

### ISSUE THREAD

**Issue by RAMPRASATH29** [intrig-unicamp/mininet-wifi#263]
Using /usr/lib/python2.7/dist-packages
Finished processing dependencies for mininet===2.3.0d6
~/mininet-wifi ~ ~ ~/mininet-wifi ~/mininet-wifi/hostap/wpa_supplicant ~/mininet-wifi/hostap/hostapd ~/mininet-wifi/hostap ~/mininet-wifi ~/mininet-wifi
Installing Mininet-wifi core
~/mininet-wifi ~/mininet-wifi ~ ~ ~/mininet-wifi ~/mininet-wifi/hostap/wpa_supplicant ~/mininet-wifi/hostap/hostapd ~/mininet-wifi/hostap ~/mininet-wifi ~/mininet-wifi
cc -Wall -Wextra  -DVERSION=\"`PYTHONPATH=. python -B bin/mn --version`\" mnexec.c -o mnexec
Traceback (most recent call last):
  File "bin/mn", line 27, in <module>
    from mn_wifi.net import VERSION
  File "./mn_wifi/net.py", line 29, in <module>
    from mn_wifi.node import AccessPoint, AP, Station, Car, \
  File "./mn_wifi/node.py", line 34, in <module>
    from mininet.util import (quietRun, errRun, errFail, mountCgroups,
ImportError: cannot import name Python3
install -D mnexec /usr/bin/mnexec
PYTHONPATH=. help2man -N -n "create a Mininet network." \
--no-discard-stderr "python -B bin/mn" -o mn.1
help2man -N -n "execution utility for Mininet." \
-h "-h" -v "-v" --no-discard-stderr ./mnexec -o mnexec.1
install -D -t /usr/share/man/man1 mn.1 mnexec.1
python setup.py install
Traceback (most recent call last):
  File "setup.py", line 11, in <module>
    from mn_wifi.net import VERSION
  File "/home/ram/mininet-wifi/mn_wifi/net.py", line 29, in <module>
    from mn_wifi.node import AccessPoint, AP, Station, Car, \
  File "/home/ram/mininet-wifi/mn_wifi/node.py", line 34, in <module>
    from mininet.util import (quietRun, errRun, errFail, mountCgroups,
ImportError: cannot import name Python3
Makefile:59: recipe for target 'install' failed
make: *** [install] Error 1

**Comment by ramonfontes** [comment]
Do you have any question? Or even some useful information you have regarding the error message?

**Comment by RAMPRASATH29** [comment]
I have run your mininet-wifi emulator .
But ,it would not run (it doesn't import python3) .
if you would explain how mininet-wifi to create topology mobile station and how to fetch new station (UAV) to access (bandwidth allocation and capacity).
And i taken base paper has "A software defined multipath offloading system for heterogenous lte-wifi networks". - could you tell procedure for this paper  and if you have created - ubuntu clone file.
In this paper has lte and wifi networks based multipath communication from bandwidth allocation and capacity . If you any future idea for this paper ,

**Comment by ramonfontes** [comment]
How can I reproduce such behavior?

**Comment by husseinali87** [comment]
https://github.com/intrig-unicamp/mininet-wifi/issues/263#issuecomment-545480322

Iam also need the code if available
