### ISSUE TITLE
How to change AP's channel or TxPower?

### ISSUE THREAD

**Issue by tori22** [intrig-unicamp/mininet-wifi#270]
Hi, after reading examples, I found there are almost all codes about how to create a new topology.

### Case1(done):
I want to re-associate  ap and sta after sta moves to another ap's neighborhood.
` cls.update(sta, ap, wlan)`
It works after I figure out some resource code.

### Case 2(still confused):
I want to change one ap's channel and power when I think current channel or TxPower is not good.
but after searching source code in link.py, I can't still find a good way.

### Conclusion:
1. how to solve case2?
2. Can we add some dynamic params change examples?

**Comment by ramonfontes** [comment]
Hi,

Please consider https://mininet-wifi.github.io/part3/ for cases #1 and #2. By now, It works only with the branch dev.

**Comment by tori22** [comment]
Thanks for the [link](https://mininet-wifi.github.io/part3/).
I solved how to change TxPower ;
but it doesn't work when trying to change channel according to the code.

`py ap1.setChannel(2, intf='ap1-wlan1')`

but error shows 
`unbound method setChannel() must be called with IntfWireless instance as first argument (got OVSAP instance instead)`

**Comment by ramonfontes** [comment]
Hi,

Please make sure you have the new compiled version.

I just ran `sudo mn --wifi` and then `py ap1.setChannel(2, intf='ap1-wlan1')` and it worked.

**Comment by tori22** [comment]
Thanks for your reply.

I switch to dev branch and sudo make install.
`git checkout dev
`
`sudo make install`


It works now. 
Thanks again.
