### ISSUE TITLE
ping all cars in vanet

### ISSUE THREAD

**Issue by badDDalways** [intrig-unicamp/mininet-wifi#272]
Hi,

I have some problems in studying vanet and running examples/vanet.py.

1. How can I ping all cars to test their connections like the command pingall in mininet? I tried command pingpair and pingall, they all worked for hosts but not cars, and command ping can only work for two cars.

topology: car10 - car4 - RSU14 - RSU11 - car7
2. I have tested examples/vanet.py. car10 (not covered by RSU14) connected to car4 (covered by RSU14) can successfully ping RSU11, but cannot successfully ping cars that covered by RSU11 such as car7. However, car4 can ping car7 well. I am so confused. Is this related to the car’s connection mode “mesh”?

3. In my test, two cars that connected with each other and not covered by any RSU cannot communicate with each other (ping unsuccessfully). However, the display of the vehicle track always show the connected car link as red lines. I want to know whether my test result was right.

Thank you.

**Comment by ramonfontes** [comment]
Hello,

1. What is the reason of having such command in VANET scenarios?
2. Cars have 2 wireless network interfaces: one working in managed mode and other working in adhoc/mesh mode. That said, my question is: Who is the destination? The node name or its IP address? Moreover, is RSU11 running at root NS? If so, you're actually pinging to 127.0.0.1. In other words you aren't pinging to RSU11.
3. Who is the destination? Node name or its IP address?

Assuming that the node has 2 wireless network interfaces, you cannot use the node name as destination. The system cannot select the IP destination for you in case of having multiple options.

Still regarding 1, you can easily writing your own program in basically any programming language and use util/m for accessing nodes running in Mininet-WiFi: https://mininet-wifi.github.io/faq/#q2

**Comment by badDDalways** [comment]
Hi,

1. I want to consider some impact factor on the connection of vanet. I'll try util/m these days.

topology: **car10** (not covered) **-** **car4** (covered) **- RSU14 - RSU11 - car7** (covered)
2. Thank you very much. I have tried "car10 ping 192.168.1.7" (mesh) and "car10 ping 192.168.0.7" (wlan), all failed. I don't know why.

3. I used node name before. I have tried IP address as destination, it worked.

Thanks again.

  

Thank you very much, you help me a lot.

**Comment by badDDalways** [comment]
Hi,
1.I want to consider some impact factor on the connection of vanet. I'll try util/m these days.

topology: car10 (not covered) - car4 (covered) - RSU14 - RSU11 - car7 (covered)
2. Thank you very much. I have tried "car10 ping 192.168.1.7" (mesh) and "car10 ping 192.168.0.7" (wlan), all failed. I don't know why.

3.I used node name before. I have tried IP address as destination, it worked.

Thanks again.

**Comment by ramonfontes** [comment]
You didn't provide any comment about the network topology.  There is no information about the signal strength as well. So, I cannot say what is going wrong.

**Comment by badDDalways** [comment]
Hi,

I am sorry about it. I want to upload pictures of simulator, but the comment window said "Try again".
I just use the example/vanet.py and do not make any changes.

I did another similar experiment and get similar result.
The topology is like this:
                car1
                  |
RSU12 - RSU11 - RSU13 - car4 - car6 (car6 not covered by RSU14)
                  |
              RSU14


**I use iwconfig to provide more details.**
**For car1:**
car1-mp1  IEEE 802.11abgn  Mode:Auto  Tx-Power=20 dBm   
          Retry short limit:7   RTS thr:off   Fragment thr:off
          Power Management:on
          
car1-wlan0  IEEE 802.11abgn  ESSID:"RSU11"  
          Mode:Managed  Frequency:2.412 GHz  Access Point: 02:00:00:00:14:00   
          Bit Rate:9 Mb/s   Tx-Power=14 dBm   
          Retry short limit:7   RTS thr:off   Fragment thr:off
          Encryption key:off
          Power Management:off
          Link Quality=32/70  Signal level=-78 dBm  
          Rx invalid nwid:0  Rx invalid crypt:0  Rx invalid frag:0
          Tx excessive retries:0  Invalid misc:4   Missed beacon:0

lo        no wireless extensions.

car1-wlan1  IEEE 802.11abgn  ESSID:off/any  
          Mode:Managed  Access Point: Not-Associated   Tx-Power=20 dBm   
          Retry short limit:7   RTS thr:off   Fragment thr:off
          Encryption key:off
          Power Management:off

**For car4:**
lo        no wireless extensions.

car4-wlan1  IEEE 802.11abgn  ESSID:off/any  
          Mode:Managed  Access Point: Not-Associated   Tx-Power=20 dBm   
          Retry short limit:7   RTS thr:off   Fragment thr:off
          Encryption key:off
          Power Management:off
          
car4-mp1  IEEE 802.11abgn  Mode:Auto  Tx-Power=20 dBm   
          Retry short limit:7   RTS thr:off   Fragment thr:off
          Power Management:on
          
car4-wlan0  IEEE 802.11abgn  ESSID:"RSU13"  
          Mode:Managed  Frequency:2.462 GHz  Access Point: 02:00:00:00:16:00   
          Bit Rate:9 Mb/s   Tx-Power=14 dBm   
          Retry short limit:7   RTS thr:off   Fragment thr:off
          Encryption key:off
          Power Management:off
          Link Quality=27/70  Signal level=-83 dBm  
          Rx invalid nwid:0  Rx invalid crypt:0  Rx invalid frag:0
          Tx excessive retries:0  Invalid misc:0   Missed beacon:0

**For car6:**
lo        no wireless extensions.

car6-wlan1  IEEE 802.11abgn  ESSID:off/any  
          Mode:Managed  Access Point: Not-Associated   Tx-Power=20 dBm   
          Retry short limit:7   RTS thr:off   Fragment thr:off
          Encryption key:off
          Power Management:off
          
car6-wlan0  IEEE 802.11abgn  ESSID:off/any  
          Mode:Managed  Access Point: Not-Associated   Tx-Power=20 dBm   
          Retry short limit:7   RTS thr:off   Fragment thr:off
          Encryption key:off
          Power Management:off
          
car6-mp1  IEEE 802.11abgn  Mode:Auto  Tx-Power=20 dBm   
          Retry short limit:7   RTS thr:off   Fragment thr:off
          Power Management:on

**I also get the signal strength.**
mininet-wifi> py car1.params['rssi']
[-78.0, -60]
mininet-wifi> py car4.params['rssi']
[-83.0, -60]
mininet-wifi> py car6.params['rssi']
[0, -60]

**Comment by badDDalways** [comment]
Hi,

I am sorry about it. I want to upload pictures of simulator, but the comment window said "Try again".
I just use the example/vanet.py and do not make any changes.

I did another similar experiment and get similar result.
The topology is like this:
car1        RSU12
|           /
 RSU11 - RSU13 - car4 - car6 (car6 is not covered by RSU14)
|
RSU14

**I use iwconfig to provide more details.**
**For car1:**
car1-mp1  IEEE 802.11abgn  Mode:Auto  Tx-Power=20 dBm   
          Retry short limit:7   RTS thr:off   Fragment thr:off
          Power Management:on
          
car1-wlan0  IEEE 802.11abgn  ESSID:"RSU11"  
          Mode:Managed  Frequency:2.412 GHz  Access Point: 02:00:00:00:14:00   
          Bit Rate:9 Mb/s   Tx-Power=14 dBm   
          Retry short limit:7   RTS thr:off   Fragment thr:off
          Encryption key:off
          Power Management:off
          Link Quality=32/70  Signal level=-78 dBm  
          Rx invalid nwid:0  Rx invalid crypt:0  Rx invalid frag:0
          Tx excessive retries:0  Invalid misc:4   Missed beacon:0

lo        no wireless extensions.

car1-wlan1  IEEE 802.11abgn  ESSID:off/any  
          Mode:Managed  Access Point: Not-Associated   Tx-Power=20 dBm   
          Retry short limit:7   RTS thr:off   Fragment thr:off
          Encryption key:off
          Power Management:off

**For car4:**
lo        no wireless extensions.

car4-wlan1  IEEE 802.11abgn  ESSID:off/any  
          Mode:Managed  Access Point: Not-Associated   Tx-Power=20 dBm   
          Retry short limit:7   RTS thr:off   Fragment thr:off
          Encryption key:off
          Power Management:off
          
car4-mp1  IEEE 802.11abgn  Mode:Auto  Tx-Power=20 dBm   
          Retry short limit:7   RTS thr:off   Fragment thr:off
          Power Management:on
          
car4-wlan0  IEEE 802.11abgn  ESSID:"RSU13"  
          Mode:Managed  Frequency:2.462 GHz  Access Point: 02:00:00:00:16:00   
          Bit Rate:9 Mb/s   Tx-Power=14 dBm   
          Retry short limit:7   RTS thr:off   Fragment thr:off
          Encryption key:off
          Power Management:off
          Link Quality=27/70  Signal level=-83 dBm  
          Rx invalid nwid:0  Rx invalid crypt:0  Rx invalid frag:0
          Tx excessive retries:0  Invalid misc:0   Missed beacon:0

**For car6:**
lo        no wireless extensions.

car6-wlan1  IEEE 802.11abgn  ESSID:off/any  
          Mode:Managed  Access Point: Not-Associated   Tx-Power=20 dBm   
          Retry short limit:7   RTS thr:off   Fragment thr:off
          Encryption key:off
          Power Management:off
          
car6-wlan0  IEEE 802.11abgn  ESSID:off/any  
          Mode:Managed  Access Point: Not-Associated   Tx-Power=20 dBm   
          Retry short limit:7   RTS thr:off   Fragment thr:off
          Encryption key:off
          Power Management:off
          
car6-mp1  IEEE 802.11abgn  Mode:Auto  Tx-Power=20 dBm   
          Retry short limit:7   RTS thr:off   Fragment thr:off
          Power Management:on

**I also get the signal strength.**
mininet-wifi> py car1.params['rssi']
[-78.0, -60]
mininet-wifi> py car4.params['rssi']
[-83.0, -60]
mininet-wifi> py car6.params['rssi']
[0, -60]

Thank you very much.

**Comment by badDDalways** [comment]
The experiment result above is car6 cannot ping car1 and car1 cannot ping car6 successfully.

**Comment by ramonfontes** [comment]
Please try only iw/iwconfig if you are using wmediumd - I cannot see the signal strength between car4 and car6. You also didn't provide any comment about ip forwarding as well as ip routing. Did you configure static/dynamic ip routing?

**Comment by badDDalways** [comment]
Hi,

car1 RSU12
| /
RSU11 - RSU13 - car4 - car6 (car6 is not covered by RSU14)
|
RSU14

Could you tell me which mode does car1 or car6 need when communicate with each other?
That is, if everything goes well, I should use the command "car1 ping 192.168.1.6" (mesh) or "car1 ping 192.168.0.6" (wlan)? or the command "car6 ping 192.168.1.1" (mesh) or "car6 ping 192.168.0.1" (wlan)? 
car6 accessed car4 using mesh mode, car4 accessed car1 using wlan mode, the above problems puzzled me a lot.

**Comment by badDDalways** [comment]
Hi，

Today I tried some “ping” related tests and another two problems appeared.

1. When I first started running vanet.py in mininet-WiFi, all links (car-car, car-RSU) goes well except for the case I mentioned above: car-car-RSU-car. However, after I using “ping” to test the network connections several times and the cars moving for a few minutes, sometimes the cars cannot successfully ping other cars. 
I've been through the relevant issues and found a similar issue, [.](https://github.com/intrig-unicamp/mininet-wifi/issues/190). It seems that this is a problem with flow rules caused by cars communicating through cables and then wireless channel. Is there any solutions for this situation besides adding flow rules manually?

2. I add one host to the network. When I use command "carx ping h1" or "carx ping 10.0.0.1", all failed with “connect: Network is unreachable”.

Here is the code I used.

`from random import randint

from mininet.node import Controller, RemoteController
from mininet.log import setLogLevel, info
from mn_wifi.cli import CLI_wifi
from mn_wifi.net import Mininet_wifi
from mn_wifi.link import wmediumd, mesh
from mn_wifi.wmediumdConnector import interference


def topology():

    "Create a network."
    net = Mininet_wifi(controller=None,
                       link=wmediumd,
                       wmediumd_mode=interference)

    info("*** Creating nodes\n")
    cars = []
    for id in range(0, 10):
        min_ = randint(1, 4)
        max_ = randint(11, 30)
        cars.append(net.addCar('car%s' % (id+1), wlans=2,
                               min_speed=min_,
                               max_speed=max_))

    rsu11 = net.addAccessPoint('RSU11', ssid='RSU11', mode='g',
                               channel='1', failMode="standalone")
    rsu12 = net.addAccessPoint('RSU12', ssid='RSU12', mode='g',
                               channel='6', failMode="standalone")
    rsu13 = net.addAccessPoint('RSU13', ssid='RSU13', mode='g',
                               channel='11', failMode="standalone")
    rsu14 = net.addAccessPoint('RSU14', ssid='RSU14', mode='g',
                               channel='11', failMode="standalone")
    h1 = net.addHost('h1', mac='00:00:00:00:00:01', ip='10.0.0.1/8' )
    
    c1 = net.addController('c1', controller=RemoteController, ip='127.0.0.1', port=6653)

    info("*** Configuring Propagation Model\n")
    net.setPropagationModel(model="logDistance", exp=4.5)

    info("*** Configuring wifi nodes\n")
    net.configureWifiNodes()

    info("*** Associating and Creating links\n")
    net.addLink(rsu11, rsu12)
    net.addLink(rsu11, rsu13)
    net.addLink(rsu11, rsu14)
    net.addLink(rsu11, h1)    

    for car in cars:
        net.addLink(car, intf=car.params['wlan'][1],
                    cls=mesh, ssid='mesh-ssid', channel=5)

    net.plotGraph(max_x=500, max_y=500)

    net.roads(3)

    net.startMobility(time=0)

    info("*** Starting network\n")
    net.build()
    c1.start()
    rsu11.start([c1])
    rsu12.start([c1])
    rsu13.start([c1])
    rsu14.start([c1])

    for car in cars:
        car.setIP('192.168.0.%s/24' % (int(cars.index(car))+1),
                  intf='%s-wlan0' % car)
        car.setIP('192.168.1.%s/24' % (int(cars.index(car))+1),
                  intf='%s-mp1' % car)

    info("*** Running CLI\n")
    CLI_wifi(net)

    info("*** Stopping network\n")
    net.stop()


if __name__ == '__main__':
    setLogLevel('info')
    topology()`

Thank you very much!

**Comment by ramonfontes** [comment]
You didn't answer my question. :(

Please solve the problem with the L3. I think there are basic computer networking concepts being ignored here. I am closing this issue because it does not seem to be an issue related to mn-wifi at all.
