### ISSUE TITLE
Does mininet-wifi support aps' cascade connection?

### ISSUE THREAD

**Issue by tori22** [intrig-unicamp/mininet-wifi#273]
ap1
   |        |        
ap2   ap3         
   |         |   
ap4   ap5       

I want to create a topology where there are 3 levels' aps and all aps can connect stations. 
ap1 have control about ap2, ap3, ap4, ap5.
But it seems cascade connection never appear in mininet-wifi examples?

**Comment by ramonfontes** [comment]
Yes, you can create such topology.
