### ISSUE TITLE
Problem when running vanet-sumo.py

### ISSUE THREAD

**Issue by badDDalways** [intrig-unicamp/mininet-wifi#280]
Hi,

When I run vanet-sumo.py, it always goes wrong and can't call the SUMO program.  
Here is the error:
*** Configuring nodes
sh: 1: sumo-gui: not found
*** Running CLI

 I have installed SUMO-1.1.0 and SUMO-GUI successfully, and also added the environment variable SUMO_HOME. I don't know why this problem always happens.

Thank you.

**Comment by ramonfontes** [comment]
Dear,

The warning message is clear: _sumo-gui not found_. This means that you haven't installed sumo-gui. This isn't a mn-wifi issue.
