### ISSUE TITLE
mn : error : no such option: --wifi

### ISSUE THREAD

**Issue by kebim** [intrig-unicamp/mininet-wifi#281]

**Comment by kebim** [comment]
Hello, 
Could you please help me with the issue,
mn : error : no such option: --wifi
![Capture](https://user-images.githubusercontent.com/39697035/74097277-6b5e1f80-4b32-11ea-8d48-2f5ff611ce24.JPG)


Though, sudo mn , works fine. And yes i have installed mininet wifi also

**Comment by ramonfontes** [comment]
I don't know what do you mean with "i have installed mininet wifi also", but you cannot install Mininet-WiFi and then install Mininet. However, if you install Mininet-WiFi you also have Mininet. The error mentioned by you means that you don't have Mininet-WiFi installed. Sudo make install in the Mininet-WiFi's root directory may solve the issue.

**Comment by kebim** [comment]
thank u for your reply.
I have mininet-wifi installed
but the issue is when I run sudo mn --wifi, it shows mn: error : no such option: --wifi

but when I run sudo mn, it works fine

**Comment by ramonfontes** [comment]
Dear,

You haven't successfully installed Mininet-WiFi.
