### ISSUE TITLE
Can I limit the up/download speed of wireless network by CLI?

### ISSUE THREAD

**Issue by u284976** [intrig-unicamp/mininet-wifi#283]
Hi,
I'm a beginner , i want to implement a multi-hop ad-hoc network with automatic re-routing, when the network environment is disturbed.

I know in the Linux system can use like `tc` or `iptables` command to limit the bandwidth, but I think this unrealistic.

In original mininet, I can use openvswitch command like:
`mininet>sh ovs-vsctl set interface s1-eth1 ingress_policing_rate=5000`
to simulate more realistic network situation.

Is there any method like open vswitch command to achieve similar effect?

Thank you.

**Comment by ramonfontes** [comment]
Hi,

Could you please tell me why `ingress_policing_rate` is more realistic than `TC` or `iptables`

**Comment by u284976** [comment]
Hi, 
I just think when I verify application, modifying parameters other than host (such as open vswitch) is more strict than modifying by iptable
because application running on the host cannot directly obtain this changed information. It must through measurement the routing path

Thank you for your reply

**Comment by ramonfontes** [comment]
I think the correct answer for this question depends of the network topology as well as the nodes the topology have. For example: if you are considering only other nodes than switches; if the nodes are switches equipped with wireless interfaces working in adhoc mode, etc. However, most of the cases do not involve a central device. So how would you expect to make it work with physical devices?

**Comment by u284976** [comment]
Sorry, my English may not be good enough, I will try my best to explain my question
```
    /----sta2----sta3---\
sta1                      sta5
    \---------sta4------/
```
Above is an ad-hoc network, links between stations means wireless range can communication,
These five stations are running application(four SDN clients, one SDN servcer and client simultaneously), the application can determines the route in the Application Layer to send and forward packets

Without change any settings, the best routing path of `sta1` to `sta5` is:
sta1---->sta4---->sta5   (shortest)

But I want to consider that `sta4` might need carrying heavy transfer tasks for another sub-net, 
And when the SDN server observes a decrease in network speed, it can actively choose another link to complete job.

1.That's why I want to ask if there is any method to control the network speed of the sta4.

In addition, I want to demonstrate that the SDN client does not read `iptable` etc. Re-routing is triggered by end-to-end device detection.
2. So I ask how to modifying parameters other than host(sta4)

Thank you for your reply

**Comment by ramonfontes** [comment]
If we think in the real world, I can see some options: you can set the link parameters with tools like TC; you can send data traffic through `sta4`; or you can set the data rate of `sta4` with `iw`.

**Comment by u284976** [comment]
Thanks for the explanation,
I will try this after setting up my application
