### ISSUE TITLE
Installation problem about patch

### ISSUE THREAD

**Issue by Icarus1994** [intrig-unicamp/mininet-wifi#286]
When I install mininet-wifi from github in Ubuntu16.04 VM, I tried the instruction:
**sudo util/install.sh -Wlnfv**
there is error like this:
<img width="737" alt="issue1" src="https://user-images.githubusercontent.com/25322847/76502127-76cc9f80-647e-11ea-8464-ee31da3d8079.png">
and I used **wget** instruction to download the "python-lazy-object-proxy-build_amd.deb" file
then I tried **sudo apt-get update** and **sudo util/install.sh -Wlnfy --fix-missing**
then there are some patch problem:
<img width="702" alt="patch_issue" src="https://user-images.githubusercontent.com/25322847/76502602-42a5ae80-647f-11ea-8eef-ca4e6f429b40.png">

I find some ways to solve the patch problem from this: 
https://stackoverflow.com/questions/14282617/hunk-1-failed-at-1-whats-that-mean/14282775#14282775

I tried the instruction:
patch --verbose --dry-run --ignore-whitespace --fuzz 3 < wpa_supplicant/p2p_supplicant.c.rej
in mininet-wifi directory, but it shows that "No such file or directory."

So I don't know how to solve this problem.
Thanks for answer!

**Comment by ramonfontes** [comment]
Sorry, what is the lazy-object-proxy package? Mininet-WiFi doesn't require such package. I cannot confirm the problem with the installation steps. It seems that you have to solve a particular problem in your machine.

**Comment by Icarus1994** [comment]
> Sorry, what is the lazy-object-proxy package? Mininet-WiFi doesn't require such package. I cannot confirm the problem with the installation steps. It seems that you have to solve a particular problem in your machine.

Thanks for replying so fast!
 Well, I have no idea about this lazy-object-proxy package, but in the seconde pic, the patch files **hostapd/deconfig** and **wpa_supplicant/p2p_supplicant.c** seems like are files in mininet-wifi. Everything is normal except when installing it.
Do you have any idea about how to deal with those patch files?  If they have nothing to do with mininet-wifi , I gonna remove them if I can.

**Comment by ramonfontes** [comment]
You have installed both hostapd and wpa_supplicant and the system wishes to know whether you want to keep the previous installation or not. I suggest you to remove the hostap directory and reinstall it with install.sh.

**Comment by Icarus1994** [comment]
Great. It does work. I'll recommend this emulator with others.

For anyone who may face the same problem:
The first error occurred because I used Aliyun source instead of ubuntu source. However, 500 http error always happen in Aliyun source these days.Thus, I have to reinstall mininet-wifi and some files already exist.
