### ISSUE TITLE
wps_auth.py fails to run

### ISSUE THREAD

**Issue by Soundofsnow** [intrig-unicamp/mininet-wifi#287]
I am trying to recreate the Reaver attack on WPS which you have created a youtube video for. However, when I run **wps_auth.py** a series of errors is produced:
![wps_auth_errors](https://user-images.githubusercontent.com/48861278/77076707-78551500-69f4-11ea-8308-4eae36fb2c1a.jpg)

**Comment by ramonfontes** [comment]
Fixed https://github.com/intrig-unicamp/mininet-wifi/commit/3f447f7bad27ee4d8923e89ffe8c5ba11a9e3bce!

**Comment by Soundofsnow** [comment]
That worked perfectly. Thanks for fixing the issue so quickly!
