### ISSUE TITLE
wps_auth.py - when running the reaver command it produces multiple "receive timeout occurred" messages.

### ISSUE THREAD

**Issue by Soundofsnow** [intrig-unicamp/mininet-wifi#288]
**wps_auth.py** - when running the reaver command it produces multiple "receive timeout occurred" messages.
![image](https://user-images.githubusercontent.com/48861278/77103996-8f5b2d80-6a1b-11ea-8fa8-00911c745335.png)

If I run **sudo python wps_auth.py -a** and then use mon0 in the reaver command it produces the same result:
![image](https://user-images.githubusercontent.com/48861278/77104857-fa593400-6a1c-11ea-9e09-61b8b230e964.png)

**Comment by ramonfontes** [comment]
The problem may be similar to https://github.com/intrig-unicamp/mininet-wifi/issues/278

**Comment by Soundofsnow** [comment]
Thanks again. I juist ran the reaver command without first being in monitor mode and it has worked.
