### ISSUE TITLE
Nodes stopped pinging each other when there is more than 20 nodes.

### ISSUE THREAD

**Issue by khulan8824** [intrig-unicamp/mininet-wifi#289]
Hi all,

I was creating Wifi direct communication with 20 nodes. With 15 nodes they can able to ping. But as soon as I increase the number of nodes, it stopped pinging each other.

Could anyone help me with this?

`

def topology():
    addresses = ['10.0.0.1', '10.0.0.2', '10.0.0.3', '10.0.0.4', '10.0.0.5', '10.0.0.6', '10.0.0.7', '10.0.0.8', '10.0.0.9', '10.0.0.10', '10.0.0.11', '10.0.0.12', '10.0.0.13', '10.0.0.14', '10.0.0.15']
    gateways = ['10.0.1.1', '10.0.1.2', '10.0.1.3', '10.0.1.4', '10.0.1.5']
    net = Mininet_wifi(link=wmediumd, wmediumd_mode=interference)
    info("*** Creating Nodes\n")
    nodes = []
    gws = [] 
    cnt =1 
    c1 = net.addController('c1')
    c1.start()
            
    for gw in gateways:
        gw = net.addStation('gw'+str(cnt), ip=gw+"/8", position=str(random.randint(0,300))+','+str(random.randint(0,300))+','+str(random.randint(0,300)))
        gws.append(gw)
        cnt+=1    
    
    cnt = 1
    for addr in addresses:
        sta = net.addStation('n'+str(cnt), ip=addr+"/8", position=str(random.randint(0,300))+','+str(random.randint(0,300))+','+str(random.randint(0,300)))
        nodes.append(sta)
        cnt+=1
        
    net.setPropagationModel(model="logDistance", exp=3)
    
    info("*** Configuring wifi nodes\n")
    net.configureWifiNodes()    
    
    info("*** Creating links\n")
    for gw in gws:
        net.addLink(gw, cls=mesh, ssid='meshNet', channel=5, ht_cap='HT40+')
    
    
    for node in nodes:
        net.addLink(node, cls=mesh, ssid='meshNet', channel=5, ht_cap='HT40+')
        
    net.plotGraph(max_x=300, max_y=300)    
    info("*** Starting network\n")
    net.build()

    info("*** Running CLI\n")
    CLI_wifi(net)
    info("*** Stopping network\n")
    net.stop()   

`

**Comment by ramonfontes** [comment]
Hi,

I can see no WiFi-Direct configuration in your code. Could please explain why you're using 802.11s? Moreover, are you considering the limit on the number of hops imposed by 802.11s? Lastly, how can I reproduce the behaviour mentioned by you?
