### ISSUE TITLE
Graph doesn't work after the last update

### ISSUE THREAD

**Issue by JAHorcajo** [intrig-unicamp/mininet-wifi#293]
Hi,
when I try to put the mobility on with the following commands
    info('*** with mobility ***\n')
     net.setMobilityModel(time=0, model='RandomDirection', max_x=1000, max_y=1000, min_v=1, seed=20)
the system gives me the following error:

Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/local/lib/python2.7/dist-packages/mininet_wifi-2.4.3-py2.7.egg/mn_wifi/mobility.py", line 337, in models
    self.start_mob_mod(mob, mob_nodes, draw)
  File "/usr/local/lib/python2.7/dist-packages/mininet_wifi-2.4.3-py2.7.egg/mn_wifi/mobility.py", line 344, in start_mob_mod
    for xy in mob:
  File "/usr/local/lib/python2.7/dist-packages/mininet_wifi-2.4.3-py2.7.egg/mn_wifi/mobility.py", line 895, in __iter__
    xy = U(0, MAX_X[self.b], np.dstack((NODES, NODES))[0])
IndexError: index 0 is out of bounds for axis 1 with size 0

can you help me, please??
thanks
JAHUAH

**Comment by ramonfontes** [comment]
How can I reproduce such behavior? I just tried `mobilityModel.py` and it works.

**Comment by JAHorcajo** [comment]
Hi

I use this script

#!/usr/bin/python

from mininet.node import RemoteController
from mininet.log import setLogLevel, info
from mn_wifi.net import Mininet_wifi
from mn_wifi.node import Station, OVSKernelAP
from mn_wifi.cli import CLI
from mn_wifi.link import *
from mn_wifi.wmediumdConnector import interference, snr
from subprocess import call
import os

import sys

def myNetwork():

    #net = Mininet_wifi(topo=None, build=False, link=wmediumd, wmediumd_mode=interference)#, ipBase='10.0.0.0/8')
    net = Mininet_wifi()

    info( '*** Adding controller ***\n' )
    c0 = net.addController(name='c0', controller=RemoteController, ip='127.0.0.1', protocol='tcp', port=6633)

    info( '*** Add switches/APs ***\n')
    ap1 = net.addAccessPoint('ap1',  dpid='1', ssid='ssid_1', failMode="standalone", range=50, position='0.0,250.0,0',
        mode='g', channel='1')

    info( '*** Add hosts/stations ***\n')
    sta1 = net.addStation('sta1', mac='00:00:00:00:00:01', range=50, wlans=2, position='100.0,250.0,0')
    sta2 = net.addStation('sta2', mac='00:00:00:00:00:02', range=50, wlans=2, position='200.0,250.0,0')
    sta3 = net.addStation('sta3', mac='00:00:00:00:00:03', range=50, wlans=2, position='300.0,250.0,0')
    sta4 = net.addStation('sta4', mac='00:00:00:00:00:04', range=50, wlans=2, position='400.0,250.0,0')
    sta5 = net.addStation('sta5', mac='00:00:00:00:00:05', range=50, wlans=2, position='500.0,250.0,0')
    sta6 = net.addStation('sta6', mac='00:00:00:00:00:06', range=50, wlans=2, position='600.0,250.0,0')
    sta7 = net.addStation('sta7', mac='00:00:00:00:00:07', range=50, wlans=1, position='700.0,250.0,0')

    info("*** Configuring wifi nodes ***\n")
    net.configureWifiNodes()
    net.plotGraph(max_x=800, max_y=500)

    info("*** Configuring Propagation Model ***\n")
    #net.setPropagationModel(model="logDistance", exp=3)
    #net.setPropagationModel()

    info( '*** Add links ***\n')
    net.addLink(ap1, sta1, mode='g', channel=1)
    net.addLink(sta1, intf='sta1-wlan1', cls=adhoc, ssid='adhocNet12', mode='g', channel=5, ibss="aa:bb:00:00:00:01")
    net.addLink(sta2, intf='sta2-wlan0', cls=adhoc, ssid='adhocNet12', mode='g', channel=5, ibss="aa:bb:00:00:00:01")
    net.addLink(sta2, intf='sta2-wlan1', cls=adhoc, ssid='adhocNet23', mode='g', channel=9, ibss="aa:bb:00:00:00:02")
    net.addLink(sta3, intf='sta3-wlan0', cls=adhoc, ssid='adhocNet23', mode='g', channel=9, ibss="aa:bb:00:00:00:02")
    net.addLink(sta3, intf='sta3-wlan1', cls=adhoc, ssid='adhocNet34', mode='g', channel=11, ibss="aa:bb:00:00:00:03")
    net.addLink(sta4, intf='sta4-wlan0', cls=adhoc, ssid='adhocNet34', mode='g', channel=11, ibss="aa:bb:00:00:00:03")
    net.addLink(sta4, intf='sta4-wlan1', cls=adhoc, ssid='adhocNet45', mode='g', channel=7, ibss="aa:bb:00:00:00:04")
    net.addLink(sta5, intf='sta5-wlan0', cls=adhoc, ssid='adhocNet45', mode='g', channel=7, ibss="aa:bb:00:00:00:04")
    net.addLink(sta5, intf='sta5-wlan1', cls=adhoc, ssid='adhocNet56', mode='g', channel=3, ibss="aa:bb:00:00:00:05")
    net.addLink(sta6, intf='sta6-wlan0', cls=adhoc, ssid='adhocNet56', mode='g', channel=3, ibss="aa:bb:00:00:00:05")
    net.addLink(sta6, intf='sta6-wlan1', cls=adhoc, ssid='adhocNet67', mode='g', channel=10, ibss="aa:bb:00:00:00:06")
    net.addLink(sta7, intf='sta7-wlan0', cls=adhoc, ssid='adhocNet67', mode='g', channel=10, ibss="aa:bb:00:00:00:06")
    
    info('*** with mobility  ***\n')
    net.setMobilityModel(time=1, model='RandomDirection', max_x=1000, max_y=1000, min_v=1, seed=20)

    info( '*** Starting network ***\n')
    net.build()

    info( '*** Starting controllers ***\n')
    for controller in net.controllers:
        controller.start()

    info( '*** Starting and configuration switches/APs ***\n')
    ap1.start([c0])
   

    info("*** Addressing ***\n")
    #ap1.setIP('11.0.0.1/24', intf="ap1-wlan1")
    #sta1.setIP('11.0.0.2/24', intf="sta1-wlan0")
    sta1.setIP('10.0.0.1/24', intf="sta1-wlan1")
    sta2.setIP('10.0.0.2/24', intf="sta2-wlan0")
    sta2.setIP('10.0.1.2/24', intf="sta2-wlan1")
    sta3.setIP('10.0.1.3/24', intf="sta3-wlan0")
    sta3.setIP('10.0.2.3/24', intf="sta3-wlan1")
    sta4.setIP('10.0.2.4/24', intf="sta4-wlan0")
    sta4.setIP('10.0.3.4/24', intf="sta4-wlan1")
    sta5.setIP('10.0.3.5/24', intf="sta5-wlan0")
    sta5.setIP('10.0.4.5/24', intf="sta5-wlan1")
    sta6.setIP('10.0.4.6/24', intf="sta6-wlan0")
    sta6.setIP('10.0.5.6/24', intf="sta6-wlan1")
    sta7.setIP('10.0.5.7/24', intf="sta7-wlan0")

    info( '*** see hwsim0 ***\n')
    os.system('sudo ifconfig hwsim0 up')

    info('*** start sniffer hddp ***\n')

    CLI(net)
    net.stop()

if __name__ == '__main__':
    setLogLevel( 'info' )
    myNetwork()

**Comment by ramonfontes** [comment]
Well, it seems that nodes sta1-sta7 have static position and then you set the mobility model. Since they have static position, which node do you expect to have mobility?

**Comment by JAHorcajo** [comment]
i will want to set a initial position, and later move all stations
"No creas en todo lo que veas. Sólo haz caso a tu intuición"

**Comment by ramonfontes** [comment]
You cannot set initial position when you configure a mobility model. You may want to modify the seed, instead.
