### ISSUE TITLE
problem in miniedit

### ISSUE THREAD

**Issue by u284976** [intrig-unicamp/mininet-wifi#298]
I have problem using miniedit in these two days,
![image](https://user-images.githubusercontent.com/44360629/79738341-31c64380-832f-11ea-96fb-50182e691eb5.png)

I checked your recent update, I think it is because the module name has not been unified yet.

Bmv2Switch->ONOSBmv2Switch

**Comment by ramonfontes** [comment]
Yes, you're right. https://github.com/intrig-unicamp/mininet-wifi/commit/6ed57be3bc968fb5902f76be07e7201be965e395 fixes the issue.

**Comment by u284976** [comment]
Thank a lot.
