### ISSUE TITLE
opendaylight 

### ISSUE THREAD

**Issue by llaftsis** [intrig-unicamp/mininet-wifi#299]
hi, when i use mininet with odl and run sudo mn --topo linear,3 --mac --controller=remote,ip=192.168.56.101,port=6633 --switch ovs,protocols=OpenFlow13 everything works fine and i get to see my topology via http://192.168.56.101:8181/index.html#/topology . When i try to run mininet-wifi topo and give a command like this sudo mn --wifi --controller=remote,ip=192.168.56.191,port=6633 everything goes according to plan but i dont see my topology i dont get any representation of it (with and without pingall)  . I use virtual machines in windows10 mininet-wifi works fine . Question is do i have to install extra features for odl? Mininet-wifi connects to odl with no problem.
![Screenshot (23)](https://user-images.githubusercontent.com/61693731/79759497-6b934c00-8327-11ea-8c83-1d07b411daf3.png)

**Comment by ramonfontes** [comment]
My guess is that as there is no client isolation, there is no need to install OF rules. As consequence, you cannot see the network topology. 

You can enable the client isolation with `--no-bridge`. However, the OpenFlow spec mentions that the default behavior of sending out the incoming port is to drop the packet. That said, you need to check how ODL manages this scenario.

**Comment by llaftsis** [comment]
with "--no-bridge" added after the --wifi , i ping sta2 from sta1 and i get destination host unreachable . Else everything runs as expected except the representation in the odl .(I'm trying to bridge the odl with the mininet-wifi and when i run this sudo ovs-vsctl set-controller br0 tcp: ${198.168.56.101}:6633 where 198.168.56.101 is the odl controller and i get " bad substitution" ) .Can mininet-wifi be represented accurately in odl ? should i learn about sumo omnet ?

**Comment by ramonfontes** [comment]
> with "--no-bridge" added after the --wifi , i ping sta2 from sta1 and i get destination host unreachable . Else everything runs as expected(when i run the comand sudo mn --wifi --controller=remote,ip=192.168.56.101,port=6633 --switch ovs,protocols=OpenFlow13) except the representation in the odl .

APs have one wireless interface where multiple stations can be connected. This means that only one interface is used for incoming and outgoing data traffic.

The OpenFlow spec is clear:
**B.6.3 IN PORT Virtual Port**
The behavior of sending out the incoming port was not clearly defined in earlier versions of the specification. It is now forbidden unless the output port is explicitly set to OFPP_IN_PORT virtual port (0xfff8) is set. The primary place where this is used is for wireless links, where a packet is received over the wireless interface and needs to be sent to another host through the same interface. For example, if a packet needed to be sent to all interfaces on the switch, two actions would need to be specified: ”actions=output:ALL,output:IN PORT”.
source: https://www.opennetworking.org/wp-content/uploads/2014/10/openflow-switch-v1.5.1.pdf

As I said, you need to check how ODL manages such scenario. You also need to think about how much a GUI is relevant for your work.

**Comment by llaftsis** [comment]
But even with some of the examples like mobilityModel, mobility i get the moving graphs with the X server but still no response from odl (i ran the  commands sudo python examples/mobility.py --controller=remote,ip=192.168.56.101,port=6633 --switch ovs,protocols=OpenFlow13) .Can these examples be represented in odl?  I should search how mininet-wifi and odl interact at length i just haven't found a better place to ask these things. Maybe 0.5.4 Boron has the problem and should try newer version

**Comment by ramonfontes** [comment]
> But even with some of the examples like mobilityModel, mobility i get the moving graphs with the X server but still no response from odl (i ran the commands sudo python examples/mobility.py --controller=remote,ip=192.168.56.101,port=6633 --switch ovs,protocols=OpenFlow13) .

Why are you using port 6633? OpenFlow 1.3 and port 6633? Have you changed the default port number in ODL?

> Can these examples be represented in odl? 

The OF protocol works. Not sure about the GUI though.

**Comment by llaftsis** [comment]
odl is listening to connections on port 6633 and 6640 (tried both with the above command) 

the graphs are correct and have movement if you are referring to them

**Comment by ramonfontes** [comment]
ODL with OpenFlow 1.3 working on port 6633 and 6640?? Shouldn't it be 6653?

**Comment by llaftsis** [comment]
tried sudo mn --controller=remote,ip=192.168.56.101,port=6633 --switch ovs,protocols=OpenFlow13  (a simple mininet topo) 
with 6653 6633 as ports and it has the same results , i guess its listening to both ports and odl respresents them (6640 not working)

**Comment by llaftsis** [comment]
Update : I downloaded and imported the pre-configured vm (followed the tutorials form brianlinkletter as did for previous machines didnt even need to assign ip addresses) installed the -Wlnfv6 and when i ran commands like : sudo mn --wifi -topo linear,3 --controller=remote,ip=192.168.56.101,port=6633 --switch ovs,protocols=OpenFlow13 it finally shows up to the OpenDaylight controller . Also in the above topology i associated sta1 with ap2 ,assign ip addresses to them then pingall and i get these results, i think everything works just fine
![Screenshot (24)](https://user-images.githubusercontent.com/61693731/79969631-6d315100-849a-11ea-9a0d-6b390612a47a.png)

**Comment by ramonfontes** [comment]
Cool. Thank you for the feedback. Can you close the issue?

**Comment by ctsahn** [comment]
I'm having the same issue with this; however, I followed exactly what @llaftsis did, but there is still no topology being shown. Does anyone have ideas?
