### ISSUE TITLE
AttributeError: 'Mininet' object has no attribute 'addStation'

### ISSUE THREAD

**Issue by maganiss** [intrig-unicamp/mininet-wifi#3]
I successfully installed mininet wifi, and "sudo mn --wifi --ssid=new_ssid" command works perfectly for me. But when I want to run the examples, e.g."sudo python examples/2AccessPoints.py", I get the error below:

AttributeError: 'Mininet' object has no attribute 'addStation'

What is the problem?

**Comment by ramonfontes** [comment]
Hi,

Probably there is something wrong in your installation. Have you run "make install" inside of Mininet-WiFi's root directory? Which version do you have installed (mn --version)?

**Comment by maganiss** [comment]
No I had not run "make install" but now I did it and nothing changed.
sudo mn --version output was:

1.6r3

**Comment by ramonfontes** [comment]
It is weird. You should be able to run any example. This error normally occurs when you do not have it properly installed. (if you look at https://github.com/intrig-unicamp/mininet-wifi/blob/master/mininet/net.py, the attribute addStation is there). Do you still have the same error?

**Comment by maganiss** [comment]
Yes, I have the attribute addStation in my net.py, and I have the same error.

**Comment by maganiss** [comment]
I have an earlier installation of mininet (not the wifi version) in another directory. 
Do they have conflict with each other?

**Comment by ramonfontes** [comment]
No no.. they do not have conflict, but it is not possible use both together. If you have run make install in Mininet-WiFi, you will use only Mininet-WiFi (but it has the same properties of Mininet). On the other hand, if you run make install in Mininet you will use only Mininet. You can see the difference with mn --version. Although I do not believe it has any error, I am going to install it from scratch in a new machine and let you know about the results.

**Comment by ramonfontes** [comment]
Hi,

I've just installed it and it is working properly. :( I am curious about this problem.

**Comment by maganiss** [comment]
I'm now installing it on my ubutun 15.10 machine which is a fresh OS without anything installed.

**Comment by maganiss** [comment]
I installed mininet wifi in a fresh Ubuntu 15.10 machine without any other installations on it. 
Again, the default topology runs (with  sudo mn --wifi --ssid=new_ssid), but by running "sudo python examples/wifiPosition.py" or any other examples, I face the following error :


me@ubuntu:~/mininet-wifi$ sudo python examples/wifiPosition.py 
*** Creating nodes
*** Creating links
wlan2: ERROR while getting interface flags: No such device
Cannot find device "wlan2"
ap1-wlan0: ERROR while getting interface flags: No such device
Traceback (most recent call last):
  File "examples/wifiPosition.py", line 44, in <module>
    topology()
  File "examples/wifiPosition.py", line 28, in topology
    net.addLink(ap1, sta1)
  File "build/bdist.linux-i686/egg/mininet/net.py", line 776, in addLink
  File "build/bdist.linux-i686/egg/mininet/net.py", line 758, in configureWifiNodes
  File "build/bdist.linux-i686/egg/mininet/net.py", line 645, in configureAP
  File "build/bdist.linux-i686/egg/mininet/wifi.py", line 74, in getMacAddress
IOError: [Errno 19] No such device

**Comment by ramonfontes** [comment]
Run mn -c, and then your scenario.

-- Sent from my android
Em 14/12/2015 03:50, "Aniss" <notifications@github.com> escreveu:

**Comment by maganiss** [comment]
sudo mn -c worked for me in my fresh ubuntu 15.10 .
(although ubuntu 14.10 still fails).

Thanks a lot.

**Comment by ramonfontes** [comment]
If the error says: Cannot find device "wlan", sudo mn -c should works in any case and any Ubuntu distro. But if the error message is "AttributeError: 'Mininet' object has no attribute 'addStation'", something is wrong in the installation process or there is something strange that I did not know until now. I will continue to investigate to comprehend what is happening.

**Comment by sahilabro** [comment]
Hi, did you ever get the solution to this issue?  "AttributeError: 'Mininet' object has no attribute 'addStation'"

I am getting the same issue. I have run make install in the mininet-wifi directory, and then run it again but it still gives me the same error.

**Comment by sahilabro** [comment]
FYI

mn --version

2.2.0d1

**Comment by sahilabro** [comment]
It does not this give me the error if i remove stations and APs, it works for Controller and Host, so perhaps it's an issue with it using Mininet not mininet-wifi?

**Comment by ramonfontes** [comment]
Please try:
mininet-wifi$ sudo rm -r /usr/local/lib/python2.7/dist-packages/mininet*

Then run:
mininet-wifi$ sudo make install

**Comment by sahilabro** [comment]
Hi, it still gives me the same error after removing the directory and reinstalling from within the mininet-wifi folder.
 
mininet-wifi$ python test1.py
mininet-wifi$ Traceback... 
                      .....
                      AttributeError: 'Mininet' object has no attribute 'addStation'

**Comment by ramonfontes** [comment]
According your version (2.2.0d1), you have Mininet and not Mininet-WiFi. I
suggest you to review the installation process.

Sent from my android

On 4 Mar 2018 20:14, "sahilabro" <notifications@github.com> wrote:

Hi, it still gives me the same error after removing the directory and
reinstalling from within the mininet-wifi folder.

mininet-wifi$ python test1.py
mininet-wifi$ Traceback...
.....

AttributeError: 'Mininet' object has no attribute 'addStation'

—

You are receiving this because you modified the open/close state.
Reply to this email directly, view it on GitHub
<https://github.com/intrig-unicamp/mininet-wifi/issues/3#issuecomment-370273608>,
or mute the thread

**Comment by sahilabro** [comment]
Hi,

I see. When I run 
$sudo mn --wifi

It works fully well, with two stations and one AP. Does this still mean I have mininet not mininet wifi? 

Nevertheless, I tried again by removing instances of mininet and reinstalling mininet-wifi: 

i.e

sudo rm -r /usr/local/lib/python2.7/dist-packages/mininet*
sudo rm -r /usr/local/bin/mn
sudo apt-get autoremove mininet
sudo apt-get autoremove mn
sudo rm -r mininet-wifi
git clone https://github.com/intrig-unicamp/mininet-wifi
cd mininet-wifi
sudo util/install.sh -Wlnfv

However, at this point the log script indicates the mn version as 2.2.0d1:
mininet.sumo.traci.rebuildConstants: module references __file__
creating 'dist/mininet_wifi-2.2.0d1-py2.7.egg' and adding 'build/bdist.linux-x86_64/egg' to it
removing 'build/bdist.linux-x86_64/egg' (and everything under it)
Processing mininet_wifi-2.2.0d1-py2.7.egg
removing '/usr/local/lib/python2.7/dist-packages/mininet_wifi-2.2.0d1-py2.7.egg' (and everything under it)
creating /usr/local/lib/python2.7/dist-packages/mininet_wifi-2.2.0d1-py2.7.egg
Extracting mininet_wifi-2.2.0d1-py2.7.egg to /usr/local/lib/python2.7/dist-packages
mininet-wifi 2.2.0d1 is already the active version in easy-install.pth
Installing mn script to /usr/local/bin

Installed /usr/local/lib/python2.7/dist-packages/mininet_wifi-2.2.0d1-py2.7.egg
Processing dependencies for mininet-wifi===2.2.0d1
Searching for setuptools==20.7.0
Best match: setuptools 20.7.0
setuptools 20.7.0 is already the active version in easy-install.pth
Installing easy_install script to /usr/local/bin

Using /usr/lib/python2.7/dist-packages
Finished processing dependencies for mininet-wifi===**2.2.0d1**


and even when i check:
$mn --version
2.2.0d1





and then

mininet-wifi$ sudo make install

$sudo python topology.py
$....
$AttributeError: 'Mininet' object has no attribute 'addStation'

**Comment by ramonfontes** [comment]
Yes, it's mininet-wifi. Are you importing Mininet_wifi from wifi.net and
using it (net = Mininet_wifi(...))? Please refer sample files at /examples.

**Comment by sahilabro** [comment]
Thank you.

I was using net = mininet(..) instead of mininet-wifi. I apologise for the inconvenience.

**Comment by amigos03** [comment]
hi, I am getting git not found error while installing mininet wifi in ubuntu terminal. I am using the commands that are mentioned in github for installation

**Comment by ramonfontes** [comment]
I suggest you to double check it. There is no problem with the installation steps.

**Comment by amigos03** [comment]
Hi,  sir  i am working on a project..  I want to make a delay efficient
architecture for sdn using mininet wifi.  Considering the effects due to
contention delay, transmission delay,  propagation delay,  queueing delay,
processing delay and controller placement..  Could you please help me
regarding this?

**Comment by ramonfontes** [comment]
What is the issue?

**Comment by amigos03** [comment]
I have no idea,  i have to start it from the scratch about making delay
efficient architecture for sdn..  Please guide me how i can proceed using
mininet wifi

**Comment by ramonfontes** [comment]
Are you commenting in this issue and you have no idea? Please refer to the user manual, mailing list as well as publications for more information about Mininet-WiFi.

**Comment by CharlieAx10** [comment]
Hi, i'm currently working with propagation models using mininet-wifi, im using the file propagationModel.py as a starting point located at the examples folder, my problem is that whenever i try using the two Ray Ground Popagation Loss Model i get the following error: 
AttributeError: 'managed' has no attribute 'bandChannel' 
is there a way to fix this ? 
i'm working with the pre-configured VM from github by the way: 
https://github.com/intrig-unicamp/mininet-wifi
Any help would be truly appreciated, thanks.

**Comment by ramonfontes** [comment]
Fixed https://github.com/intrig-unicamp/mininet-wifi/commit/0c44803686be4cf27644797b7a703dd1300fe7cc

**Comment by CharlieAx10** [comment]
> Fixed [0c44803](https://github.com/intrig-unicamp/mininet-wifi/commit/0c44803686be4cf27644797b7a703dd1300fe7cc)

Thank you for the modification, it seems that the error got fixed but now every time I run the script my computer gets stuck completely, the mininet WiFi CLI appears but I can’t write any commands as the computer gets stuck. 
I’ve to power it off from the button in order to restart it. 
Does that have to do with my particular system?

**Comment by CharlieAx10** [comment]
Also, the mobility animation doesn’t appear  either, the computer gets stuck as soon as I run the script.

**Comment by ramonfontes** [comment]
I suggest you to take a look at the log files in your system.

**Comment by CharlieAx10** [comment]
> I suggest you to take a look at the log files in your system.

Thank you for the suggestion, i was able to fix the issue. I've a final question regarding the height of the transmitter antenna. 
The theory about propagation models says that there's a transmitter antenna and a receiver antenna with a certain distance in between, when calculating path loss on the two ray model i have to use the height of both antennas. 
My question would be; ¿What height is mininet-wifi using for the transmitter antenna ?, in this case the transmitter would be the access point i believe. 
To calculate path loss im assuming a larger antenna than the receiver antenna since i don't know the real value for the transmitter, maybe i'm missing on something. 
Once again, i'd really appreciate any help.

**Comment by ramonfontes** [comment]
1.0 is the default value: https://github.com/intrig-unicamp/mininet-wifi/blob/master/mn_wifi/link.py#L1083

**Comment by CharlieAx10** [comment]
> 1.0 is the default value: https://github.com/intrig-unicamp/mininet-wifi/blob/master/mn_wifi/link.py#L1083

i see, so the only way to change that value is by modifying it on that particular script or is there a particular command for the CLI ? 
Thank you.

**Comment by ramonfontes** [comment]
You can pass `antennaHeigh` as a node parameter.

Please create a new issue if you have a question about a different topic.

**Comment by CharlieAx10** [comment]
Thank you, i will.
