### ISSUE TITLE
remote controller cannot detect normal OVSSwitch when there are aps

### ISSUE THREAD

**Issue by zhangzee** [intrig-unicamp/mininet-wifi#30]
I programe a python script that hava normal OVSSwitchs and aps based on examples/handover.py .But the remote controller just can detect aps and cannot detect the normal switch through addSwitch('s1') method .     what's more ,when I replace all the switchs to aps ,the ping ttl time between two hosts under one ap  is up to more than 10ms rather than less 0.05ms under one normal OVSSwitch .......

**Comment by zhangzee** [comment]
the mobilityDemo.py is like this: the remote controller(onos) cannot detect the s1 and s2 .so sta1 cannot ping h1 successfully.

#!/usr/bin/python

from mininet.net import Mininet
from mininet.node import Controller
from mininet.cli import CLI
from mininet.log import setLogLevel, info

#from mininet.node import OVSKernelSwitch, Controller ,OVSSwitch
#from mininet.link import TCLink

def emptyNet():

    "Create an empty network and add nodes to it."

    net = Mininet( controller=Controller )

    info( '*** Adding controller\n' )
    net.addController( 'c0' )

    info( '*** Adding hosts\n' )
    h1 = net.addHost( 'h1', ip='192.168.0.6/24' )
    h2 = net.addHost( 'h2', ip='192.168.0.5/24' )

    info( '*** Adding switch\n' )
    s1 = net.addSwitch( 's1' )
    s2 = net.addSwitch( 's2' )

    sta1 = net.addStation( 'sta1', mac='00:00:00:00:00:02', ip="192.168.0.1/24" ,range='20' )
    ap1 = net.addAccessPoint( 'ap1', ssid= 'ap1-ssid', mode= 'g', channel= '1', position='30,50,0', range='30' )
    ap2 = net.addAccessPoint( 'ap2', ssid= 'ap2-ssid', mode= 'g', channel= '1', position='90,50,0', range='30' )
    ap3 = net.addAccessPoint( 'ap3', ssid= 'ap3-ssid', mode= 'g', channel= '1', position='130,50,0', range='30' )

    print "*** Configuring wifi nodes"
    net.configureWifiNodes()

    net.addLink(s1, s2)
    net.addLink(s1, h1)
    net.addLink(s2, h2)
    net.addLink(s1, ap1)
    net.addLink(s1, ap2)
    net.addLink(s2, ap3)

    net.plotGraph(max_x=160, max_y=160)

    net.startMobility(startTime=0, AC='ssf')
    net.mobility(sta1, 'start', time=20, position='1,50,0')
    net.mobility(sta1, 'stop', time=79, position='159,50,0')
    net.stopMobility(stopTime=80) 

    info( '*** Starting network\n')
    net.start()

    info( '*** Running CLI\n' )
    CLI( net )

    info( '*** Stopping network' )
    net.stop()

if __name__ == '__main__':
    setLogLevel( 'info' )
    emptyNet()

**Comment by zhangzee** [comment]
![image](https://cloud.githubusercontent.com/assets/22088840/21757035/df1a2d0c-d663-11e6-906d-3a152754e257.png)
![image](https://cloud.githubusercontent.com/assets/22088840/21757042/f6849586-d663-11e6-8704-555bb050de60.png)

**Comment by ramonfontes** [comment]
Dear,

Both switch and AP have the same ID number and consequently the same DPID
(s1, s2, ap1 and ap2). Try to change the ID of APs to ap3 and ap4, and let
me know if it works please.

**Comment by zhangzee** [comment]
thank for you help @ramonfontes
when I changed the ap1 ,ap2,ap3 to ap3 ap4 ap5, the remote controller can indeed detect the s1 and s2. But there is  no diffrent with define s1 to ap in this way.   I want to know if I use the method **net.addSwitch('s1')** cannot add a normal  switch not an ap ?? As we konw the method is add a normal OVSSwitch in mininet. if the mininet-wifi change the method??

**Comment by ramonfontes** [comment]
net.addSwitch('s1') adds the same switch as Mininet does. So, we didn't change net.addSwitch(). 

You can add the parameter dpid when add switch and ap. For example:
**net.addSwitch('s1',dpid='0000000100000001')
net.addAccessPoint('ap1',dpid='0000000100000002')**

should work fine.

**Comment by zhangzee** [comment]
thank you for you help . It works.  
But when sta1 ping h1 , the ttl time (more than 10ms like the up picture ) is correct or normal to simulate the real wireless network? when h1 ping h2 ,the ttl time is less than 0.05ms.   can I change the wireless link rodio  to decreate the ttl time . Thank you .

**Comment by ramonfontes** [comment]
You may change the formula for bw, loss, latency and delay. Please take a
look at the section "Customizing Equations" in the Mininet-WiFi's manual.

2017-01-09 23:16 GMT-03:00 zhangze <notifications@github.com>:

**Comment by zhangzee** [comment]
Is this manual ? But there is no this section "Customizing Equations" . And when I set the link bw to 100M It doesn't works.  
![image](https://cloud.githubusercontent.com/assets/22088840/21839850/017a4c26-d815-11e6-8c9b-9c3e5a481f43.png)

**Comment by ramonfontes** [comment]
Dear,

You can find that section at page 15.


2017-01-11 4:48 GMT-03:00 zhangze <notifications@github.com>:

**Comment by ramonfontes** [comment]
Hello,

Did you solve the problem?

**Comment by zhangzee** [comment]
sorry, I can't find the method to setbw, loss, latency and delay. And I didn't get help from examples/wifiPropagationModel.py refered at page 15 . So can you give me a example to change these parameters ? Thank you .

**Comment by ramonfontes** [comment]
I don't know where did you get the manual, but from
https://www.dropbox.com/s/jgkhsdrz736e4q2/mininet-wifi-draft-manual.pdf?dl=0
(URL available at the source code page) you can find that subsection at
page 15. By calling net.setChannelEquation() you'll be able to change the
formula for bw, loss, latency and delay. BTW, does your scenario has
mobility?

2017-01-13 1:38 GMT-03:00 zhangze <notifications@github.com>:

**Comment by zhangzee** [comment]
perfect ! Thank you very much .
And my scenario can support mobility .  
haha

**Comment by ramonfontes** [comment]
Good. Please close the issue if it is solved.
