### ISSUE TITLE
sudo mn --wifi --no-bridge is not an option in mininet-wifi? I got this error

### ISSUE THREAD

**Issue by alic-antunez** [intrig-unicamp/mininet-wifi#309]
Hello guys. I was testing mininet wifi. When I want to implement the OpenFlow protocol with this parameter (--no-bridge) I get this error (attached image).. Do I need to install something previously? or what could it be? Thanks

![--no-bridge](https://user-images.githubusercontent.com/68139074/87216995-574d6280-c30a-11ea-8913-3ddf8a2a6562.JPG)

**Comment by ramonfontes** [comment]
Use `--client-isolation` instead https://mininet-wifi.github.io/advanced/#clientisolation

**Comment by alic-antunez** [comment]
Thanks, It works now
