### ISSUE TITLE
How could I change the channel of an AP once mininet-wifi is running?

### ISSUE THREAD

**Issue by alic-antunez** [intrig-unicamp/mininet-wifi#310]
Hello. Is there a command which I could change the channel of an AP once mininet-wifi is running? Is it possible do that inside mininet running o maybe from a remote controller (ex: OpenDayLight) ???
 I would appretiate the support. Thanks

**Comment by ramonfontes** [comment]
Hello,

Have you ever tried `hostapd_cli`?

**Comment by alic-antunez** [comment]
No. Give me more info about that please.

**Comment by ramonfontes** [comment]
Dear,

You can find vast information about `hostapd_cli` on the Net.
