### ISSUE TITLE
Setting Circle Color not working?

### ISSUE THREAD

**Issue by ckampi** [intrig-unicamp/mininet-wifi#311]
Hello, I'm trying to chanage the range color from the APs and the Stations following this guide https://mininet-wifi.github.io/part3/#setcirclecolor , but when I tryed the code this message showed up: AttributeError: 'Station' object has no attribute 'setCircleColor'. 

I tryed again on the cli using 
sta1.setCircleColor('r')
or
py sta1.setCircleColor('r')

But none of them work. How can I use properly this command?

**Comment by ramonfontes** [comment]
Please try `set_circle_color()` instead.

**Comment by ckampi** [comment]
Excellent, not it works, thank you for beign so fast Ramon.
