### ISSUE TITLE
Help with socket_server and socket_client

### ISSUE THREAD

**Issue by alic-antunez** [intrig-unicamp/mininet-wifi#312]
I copied the code (from https://github.com/intrig-unicamp/mininet-wifi/blob/master/examples/socket_client.py) to socket_client.py
and I also copied the code (from https://github.com/intrig-unicamp/mininet-wifi/blob/master/examples/socket_server.py) to socket_server.py, but I can't get the parameters correctly inside the client.

![socket_client_error](https://user-images.githubusercontent.com/68139074/88339445-a8445a00-ccff-11ea-954e-6514101acfd8.JPG)

**Comment by ramonfontes** [comment]
Please (always) refer to https://mininet-wifi.github.io. You can find answer for your question at https://mininet-wifi.github.io/advanced/#socket

**Comment by alic-antunez** [comment]
Thanks. It works
