### ISSUE TITLE
Issue in running vanet-sumo.py file 

### ISSUE THREAD

**Issue by janiceHappy** [intrig-unicamp/mininet-wifi#314]
Hi Ramon,
I have some problems in running vanet-sumo.py file.

After the program automatically opens sumo-gui, I set the delay to 500ms, and then click start.
I pingall in the mininet-wifi CLI, and I expected to see that the cars could ping each other, but the results were as follows:

mininet-wifi> pingall
*** Ping: testing ping reachability
*** Warning: No packets sent

In addition, in sumo, I can see that the cars are in coverage of each other

Any help will be appreciated!

Regards,
Junjng

**Comment by ramonfontes** [comment]
`pingall` doesn't work with vehicles because they have two interfaces.

**Comment by janiceHappy** [comment]
Thanks for you help!

**Comment by janiceHappy** [comment]
Thanks for your help！

Another small question:
Is it that vehicles cannot use car-wlan addresses to ping each other, but can only use car-mp?
And what does "mp" mean?

Regards,
Junjng

**Comment by ramonfontes** [comment]
Is Network Manager running? Is there a link among APs? Mp is acronym for Mesh Point - the code configures a mesh interface for the second wireless interface, right?

Please consider to use the mailing list for such questions.
