### ISSUE TITLE
How to determine no of work station(sta) devices connected in an access point(ap)?

### ISSUE THREAD

**Issue by arghasen10** [intrig-unicamp/mininet-wifi#315]
I would like to know if it is possible to determine the number of sta devices connected in an ap and also their name, IP or mac?
I know from the station with a command like **>sta1 iw dev sta1-wlan0 link** I can get details like on which ap the sta is connected. Is there any possible commands or any functions for the ap that will help to get details of connected sta.

**Comment by ramonfontes** [comment]
You can use `hostapd_cli`

**Comment by arghasen10** [comment]
Thank you Sir for your quick response.
With a command like this, I can get the numbers of sta connected to a particular access point
```bash
ap_name hostapd_cli all_sta | grep ^..: | wc -l
 ```
sta MAC can also be found as follows
```bash
ap_name hostapd_cli all_sta | grep ^..:
```
