### ISSUE TITLE
changing the band to 5ghz in mesh

### ISSUE THREAD

**Issue by tagoresrinivas** [intrig-unicamp/mininet-wifi#317]
Hello

I had tried to simulate the 5Ghz network in mesh mode using mininet-wifi/examples/mesh.py and I had added the band='5' parameter to the .addLink() and passed it. But once after running the dump I see that the mesh is only running 2.4Ghz even the band is set to 5Ghz any fix for this?

Thanks

**Comment by ramonfontes** [comment]
Hello,

In the mesh scenario you only have to set the channel (e.g. 36).

**Comment by tagoresrinivas** [comment]
`def topology(mobility):
    "Create a network."
    net = Mininet_wifi(link=wmediumd, wmediumd_mode=interference)

    info("*** Creating nodes\n")
    if mobility:
        sta1 = net.addStation('sta1')
        sta2 = net.addStation('sta2')
        sta3 = net.addStation('sta3')
    else:
        sta1 = net.addStation('sta1', position='10,10,0')
        sta2 = net.addStation('sta2', position='50,10,0')
        sta3 = net.addStation('sta3', position='90,10,0')

    info("*** Configuring Propagation Model\n")
    net.setPropagationModel(model="logDistance", exp=4)

    info("*** Configuring wifi nodes\n")
    net.configureWifiNodes()

    info("*** Creating links\n")
    net.addLink(sta1, cls=mesh, ssid='meshNet',
                intf='sta1-wlan0',band='5',channel='36', ht_cap='HT40+')  #, passwd='thisisreallysecret')
    net.addLink(sta2, cls=mesh, ssid='meshNet',
                intf='sta2-wlan0', band='5',channel='36', ht_cap='HT40+')  #, passwd='thisisreallysecret')
    net.addLink(sta3, cls=mesh, ssid='meshNet',
                intf='sta3-wlan0',band='5',channel='36', ht_cap='HT40+')  #, passwd='thisisreallysecret')

`
If I add the channel the stations are not pinging each other and the command "sta1 iw dev sta1-mp0 info" is not showing the channel/band/width on the mesh is operating.

**Comment by ramonfontes** [comment]
When you set the channel to 36 you're already using 5GHz. What would be the purpose of the `band` parameter?

**Comment by tagoresrinivas** [comment]
Yeah I had remove band param and only setting the channel to 36. But this has same problem. stations are not pinging each other.

**Comment by ramonfontes** [comment]
Can you please run the code in debug mode and put the outcome here?

**Comment by tagoresrinivas** [comment]
Hello ramon

Please find the attached debug from dmesg.
[https://drive.google.com/file/d/1swchH-F9fMu8PR_-BY7aGby_t4nAj3kS/view?usp=sharing](url)

**Comment by ramonfontes** [comment]
Sorry.. you should run the code in debug mode `setLogLevel('debug')`

**Comment by tagoresrinivas** [comment]
Hello ramon,

here it is [https://drive.google.com/file/d/1ATlSukf1lkiNVhYsgbJx_vxGfw59t3EV/view?usp=sharing](url)

**Comment by ramonfontes** [comment]
Which regulatory domain are you using? Can you try `iw reg set US`?

**Comment by tagoresrinivas** [comment]
its already set to US i think
`0mininet-wifi> sta1 iw reg get
*** errRun: ['stty', '-icanon', 'min', '1'] 
  0global
country US: DFS-FCC
	(2402 - 2472 @ 40), (N/A, 30), (N/A)
	(5170 - 5250 @ 80), (N/A, 23), (N/A), AUTO-BW
	(5250 - 5330 @ 80), (N/A, 23), (0 ms), DFS, AUTO-BW
	(5490 - 5730 @ 160), (N/A, 23), (0 ms), DFS
	(5735 - 5835 @ 80), (N/A, 30), (N/A)
	(57240 - 63720 @ 2160), (N/A, 40), (N/A)

mininet-wifi> 
`

**Comment by ramonfontes** [comment]
Well, the command is correct:
`iw dev sta1-mp0 mesh join meshNet freq 5180 HT40`

Please note that the message error says:
`command failed: Invalid argument (-22)`

I know of no other reason for this error than the regulatory domain.

**Comment by tagoresrinivas** [comment]
Hello Ramon

how can I use VHT to set 80mhz channel width in 5ghz band? I saw one of links you suggested in other issues (https://w1.fi/cgit/hostap/plain/hostapd/hostapd.conf) .I tried using vht_capab='SHORT-GI-80' but when I run it was going back in 20mhz. Any help here?

**Comment by ramonfontes** [comment]
Hi,

I suggest you to use `iw`.

**Comment by tagoresrinivas** [comment]
Getting this below error while using iw command to set 80mhz channel width
`mininet-wifi> sta1 iw dev sta1-mp0 set freq 5200 80 5210
*** errRun: ['stty', '-icanon', 'min', '1'] 
  0command failed: Device or resource busy (-16)
mininet-wifi> `
any help is appreciated.

**Comment by ramonfontes** [comment]
Is the interface up?

**Comment by tagoresrinivas** [comment]
Thanks Ramon that worked.

**Comment by ramonfontes** [comment]
The network interface was UP!
