### ISSUE TITLE
Ubuntu 20.04 Installation Issue

### ISSUE THREAD

**Issue by jrandallclark** [intrig-unicamp/mininet-wifi#318]
Installation on Ubuntu 20.04 fails due to [L596](https://github.com/intrig-unicamp/mininet-wifi/blob/master/util/install.sh#L596) trying to install python-pip, which is no longer available through apt-get.

**Comment by ramonfontes** [comment]
Hi,

Are you trying to install Ryu? `python-pip` is installed if you use the flag `-y`.

**Comment by jrandallclark** [comment]
Hi. I was installing Ryu. I just discussed it with someone else who was having the same issue and the problem can be fixed by installing python-is-python3 first.

**Comment by ramonfontes** [comment]
humm..

Please try a `git pull` and let me know if it works now.

**Comment by jrandallclark** [comment]
Your latest commit is missing the '$' before each 'install' but that seems to fix it. There are still issues with python-is-python3 still being necessary for the mininet installer and ifconfig being depreciated, but I think those are more mininet issues.
