### ISSUE TITLE
Installation issue on ubuntu 16.04

### ISSUE THREAD

**Issue by jamesrenxiangyu** [intrig-unicamp/mininet-wifi#320]
Hi, I was installing mininet wifi on my machine but had this issue while installing:
Installing Mininet-wifi core
~/mininet-wifi ~/mininet-wifi ~ ~ ~/mininet-wifi ~/mininet-wifi/hostap/wpa_supplicant ~/mininet-wifi/hostap/hostapd ~/mininet-wifi/hostap ~/mininet-wifi ~/mininet-wifi
cc -Wall -Wextra  -DVERSION=\"`PYTHONPATH=. python -B bin/mn --version`\" mnexec.c -o mnexec
Traceback (most recent call last):
  File "bin/mn", line 27, in <module>
    from mn_wifi.net import VERSION
  File "./mn_wifi/net.py", line 23, in <module>
    from mn_wifi.node import AP, Station, Car, \
  File "./mn_wifi/node.py", line 171
    def setBand(self, *args, intf=None):
                                ^
SyntaxError: invalid syntax
install -D mnexec /usr/bin/mnexec
PYTHONPATH=. help2man -N -n "create a Mininet network." \
--no-discard-stderr "python -B bin/mn" -o mn.1
help2man -N -n "execution utility for Mininet." \
-h "-h" -v "-v" --no-discard-stderr ./mnexec -o mnexec.1
install -D -t /usr/share/man/man1 mn.1 mnexec.1
python setup.py install
Traceback (most recent call last):
  File "setup.py", line 11, in <module>
    from mn_wifi.net import VERSION
  File "/home/renxiangyu/mininet-wifi/mn_wifi/net.py", line 23, in <module>
    from mn_wifi.node import AP, Station, Car, \
  File "/home/renxiangyu/mininet-wifi/mn_wifi/node.py", line 171
    def setBand(self, *args, intf=None):
                                ^
SyntaxError: invalid syntax

Does any one have any idea how to solve this? Much appreciated! Thank you.

**Comment by ramonfontes** [comment]
Fixed!
