### ISSUE TITLE
problem with pre-defined virtual machine

### ISSUE THREAD

**Issue by yiyacom** [intrig-unicamp/mininet-wifi#325]
Hi, 
I downloaded the pre-defined virtual machine (3.3G). After importing into the virtualbox, there is no internet connection. 

After running the commands either sudo systemctl stop network-manager or sudo service network-manager stop.
The error message is: 
"Failed to stop network-manager.serivce: Unit network-manager.service not loaded."

Could you please help to check the VM image? 

Best Regards
Ying

**Comment by ramonfontes** [comment]
Hi,

You can manually install `Network Manager` if you wish to use it.

**Comment by yiyacom** [comment]
Thanks. It is now fine with the network connection and network manager. :)
