### ISSUE TITLE
Changing plot2d and plot3d in plot.py in VM has no impact

### ISSUE THREAD

**Issue by masad8** [intrig-unicamp/mininet-wifi#326]
I'm using the provided Mininet Wifi VM. When I change the plot2d and plot3d functions in mn_wifi/plot.py to change title of plotted graph, it doesn't reflect on the graph shown when I create a network. It still says the same title. Why is it so?

**Comment by ramonfontes** [comment]
Did you recompile the code (`sudo make install`)?

**Comment by masad8** [comment]
No, do I need to do that in the main mininet-wifi directory, or inside the mn_wifi directory?

**Comment by ramonfontes** [comment]
`~/mininet-wifi$`
