### ISSUE TITLE
Is it possible run a python script inside the mininet-wifi´s prompt? I mean during runtime.

### ISSUE THREAD

**Issue by alic-antunez** [intrig-unicamp/mininet-wifi#328]
Hello guys.
Is it possible run a python script inside the mininet-wifi´s prompt? I mean during runtime.
Thanks

**Comment by ramonfontes** [comment]
You can use sh e.g. `mininet-wifi> sh file.py`

**Comment by alic-antunez** [comment]
Where I can find some documentation about sh file.py?

**Comment by ramonfontes** [comment]
Mininet-WiFi extends `sh` from Mininet. I think you can easily find some information about it in the Mininet doc.
