### ISSUE TITLE
How could I store the values of the "py" command in a variable or in a dictionary?

### ISSUE THREAD

**Issue by alic-antunez** [intrig-unicamp/mininet-wifi#331]
Hi

For example I would like to know how to store  all the frequencies of the deployed APs (of a certain topology in mininet-wifi) in a dictionary?
Or How to store any py comand (like distance, range, channel, txpower, etc) in a variable or external file.

Regards

**Comment by ramonfontes** [comment]
Do you want to use the CLI to store data in a dictionary (python dictionary)?? This doesn't make sense to me.  What would be the reason? Anyway, the code is open and you are free to change it according to your needs.

By the way, I'd suggest you to take a look at https://mininet-wifi.github.io/advanced/#socket.

**Comment by alic-antunez** [comment]
Not exactly in the CLI but in the script of creation of the topology or maybe you could suggest me something else. The reason is, let's say I want to deploy a topology with 10 APs with its default frequency channel, I want to make an algorithm to reassign automatically  the channels in order to reduce cochannel interference (change them to orthogonal channels) and then test the scenarios. 
The idea is to get all the APs freq channels and pass it to an algorithm which automatically reassigns the APs channels.

**Comment by ramonfontes** [comment]
Socket does the work
