### ISSUE TITLE
Voltage parameter in battery.py not working?

### ISSUE THREAD

**Issue by Takarossa** [intrig-unicamp/mininet-wifi#334]
I'm trying to run the battery example from the mininet-wifi examples but it seems like I'm able to ping no matter what value I set the voltage to. It is not clear to me if the voltage parameter refers to the remaining voltage in the battery or the consumption per unit time/byte etc. 
So I tried to test it by using both high and low values but no matter what it seems like I'm always able to ping the access point with the sensors. Since the example does not provide a graph I have made some slight alterations to the script, this is what I'm running:
[batteryModified.txt](https://github.com/intrig-unicamp/mininet-wifi/files/5301148/batteryModified.txt)

Do you have any ideas what the issue is?
Or am I misunderstanding the voltage parameter entirely?
On a small side note, is there a command to fetch the remaining battery charge on a unit? I can't find any such command.

With best regards, 
-Takarossa.

**Comment by ramonfontes** [comment]
Please refer to https://mininet-wifi.github.io/advanced/#battery for more information about the battery example.
