### ISSUE TITLE
Multi hop mesh network in mininet-wifi

### ISSUE THREAD

**Issue by bhatramya** [intrig-unicamp/mininet-wifi#341]
Is it possible to create a multi-hop mesh network in mininet-wifi? I have checked the example mesh.py, all the stations are connected to each other. I would like to have at least one hop between two stations. 
Also, can I use a routing protocol in mesh network (like in adhoc.py), since it is using 802.11s?

Thanks and regards,
Ramya

**Comment by ramonfontes** [comment]
> Is it possible to create a multi-hop mesh network in mininet-wifi? I have checked the example mesh.py, all the stations are connected to each other. I would like to have at least one hop between two stations.

Yes, it is possible. This is managed by the routing protocol you are using and not mn-wifi.

> Also, can I use a routing protocol in mesh network (like in adhoc.py), since it is using 802.11s?

You can use any routing protocol supported by 802.11s.

**Comment by bhatramya** [comment]
Thanks for the quick reply!
Can I pass the routing protocol as parameter ex: "proto=olsr"?

**Comment by ramonfontes** [comment]
> Can I pass the routing protocol as parameter ex: "proto=olsr"?

Yes. However, you may want to do a `git pull` and recompile the code with `sudo make install` before.

**Comment by bhatramya** [comment]
Okay, Thanks again!
