### ISSUE TITLE
INTEGERATING MININET WIFI WITH 5G CORE

### ISSUE THREAD

**Issue by mimo123-code** [intrig-unicamp/mininet-wifi#347]
hello i want to integrate mininet wifi with a opensource 5G core open5gs for my research purpose can anyone help me regarding  these

**Comment by ramonfontes** [comment]
Hello,

Which help do you need?

**Comment by mimo123-code** [comment]
I am using open5gs which is 5G core I want to integrate mininet wifi with 5G core . Can you help me in integrating it with 5G core

**Comment by ramonfontes** [comment]
I didn't find an issue in your question. So please consider using the mailing for such questions.
