### ISSUE TITLE
Using threading with net.plotGraph

### ISSUE THREAD

**Issue by phantomxe** [intrig-unicamp/mininet-wifi#348]
I need to change a station position from a running code at another thread. If i use setPosition method on station, it fails like;

```
....
    self._idle_callback = self._tkcanvas.after_idle(idle_draw)
  File "/usr/lib/python2.7/lib-tk/Tkinter.py", line 614, in after_idle
    return self.after('idle', func, *args)
  File "/usr/lib/python2.7/lib-tk/Tkinter.py", line 606, in after
    name = self._register(callit)
  File "/usr/lib/python2.7/lib-tk/Tkinter.py", line 1228, in _register
    self.tk.createcommand(name, f)
RuntimeError: main thread is not in main loop
```

I tried also just set position tuple and i got no error but this time the graph is not changed. There is no effect. I called update graph method from after setting position then i got same error message.

**Comment by ramonfontes** [comment]
Have you ever tried sockets?

https://mininet-wifi.github.io/advanced/#socket

**Comment by phantomxe** [comment]
@ramonfontes i will try now.

**Comment by phantomxe** [comment]
@ramonfontes why client need to kill the socket after sending each command? I try to send lots of commands and it crashes the mininet.

**Comment by ramonfontes** [comment]
I don't remember exactly but I had experienced some issues. However, you are free to do without stopping it if you can.
