### ISSUE TITLE
Error when link down in "normal" swicthes

### ISSUE THREAD

**Issue by MarianaCruz** [intrig-unicamp/mininet-wifi#350]
Hi, 

I need to test the network in terms of performance when a link failure occurs. But with no success. I have a pretty big network topology but only with one ap1 and one station sta1, I want to simulate a link crash in other switches. But an error saying: AttributeError: 'OVSSwitch' object has no attribute 'wintfs' is shown (see screenshot). In mininet wifi is not possible to turn "normal" links down? Or there is other way to do it?
![Captura de ecrã 2020-12-16, às 17 25 28](https://user-images.githubusercontent.com/17406099/102385317-9d97a380-3fc5-11eb-8e6e-0063e1276c29.png)

I really could use your help. Thanks in advance,
Mariana

**Comment by ramonfontes** [comment]
Fixed! https://github.com/intrig-unicamp/mininet-wifi/commit/fedfb91dc4f32bb08095ece9c4e83c83f25fd5ab

**Comment by MarianaCruz** [comment]
Fixed, thank you!
