### ISSUE TITLE
WBAN (wireless Body area network) Simulation

### ISSUE THREAD

**Issue by catherinenayer** [intrig-unicamp/mininet-wifi#354]
Can we use Mininet-WIFI in emulating the wireless Body area network? and if yes how we can do this??

**Comment by ramonfontes** [comment]
Unfortunately, IEEE 802.15.6 is not supported by the Linux system. You can only simulate the wireless connection by choosing a propagation model that fits your needs.

Ps. Please consider using the mailing for such question.

**Comment by catherinenayer** [comment]
thank you
