### ISSUE TITLE
routers connections

### ISSUE THREAD

**Issue by catherinenayer** [intrig-unicamp/mininet-wifi#355]
How can I make a wireless link connection between the router and the access point in mIninet-WIFI?

**Comment by ramonfontes** [comment]
Which wireless technology would you use in the real world? 

Ps. Please consider using the mailing for such question.

**Comment by catherinenayer** [comment]
I ask about how to make a wireless link between a router and access point in Mininet-WIFI if possible and in real-world I will use any of the following 
Intra-Body Communication (IEEE 802.11ax, IEEE-802.16n, IEEE 802.16.1a, Zigbee healthcare 1.0)
Inter-Body Communication (UMTS, 4G, 4.5G, 5G and beyond)

**Comment by ramonfontes** [comment]
Ok. Let me be more specific: you have a physical router and access point in your hands. How would you make a wireless connection between them? How can they communicate wirelessly? Which steps would you take?

**Comment by catherinenayer** [comment]
to make a connection between them i have to connect them to a network cable

**Comment by ramonfontes** [comment]
So we connect them to a network cable and then we have a wireless link connection??

**Comment by catherinenayer** [comment]
ok thank you
