### ISSUE TITLE
LTE emulation

### ISSUE THREAD

**Issue by mtahrawi** [intrig-unicamp/mininet-wifi#357]
Hi developer,
can I implement LTE emulation using MiniNet-WiFi?
Tq

**Comment by ramonfontes** [comment]
You can find some answers in this recent publication and its open source repository:

Raza Ul Mustafa, Md Tariqul Islam, Christian Esteve Rothenberg, Simone Ferlin, Darijo Raca, and Jason J. Quinlan. "DASH QoE performance evaluation framework with 5G datasets".  In IEEE CNSM AnServApp. Nov. 2020.

https://intrig.dca.fee.unicamp.br/wp-content/papercite-data/pdf/ul2020supervised.pdf
https://github.com/razaulmustafa852/5G/ 

Please use the mailing list for questions like that.
