### ISSUE TITLE
Mininet-WIFI installation issue

### ISSUE THREAD

**Issue by catherinenayer** [intrig-unicamp/mininet-wifi#358]
When opening my Mininet-Wifi virtual machine (on Vmware workstation 11) I received the following figure with kernel error
![image](https://user-images.githubusercontent.com/40392417/105578581-ff4bea00-5d89-11eb-8a5b-478af8f01714.png)

and when trying to use the old kernel from ubuntu advanced options I got the following image
![image](https://user-images.githubusercontent.com/40392417/105578616-302c1f00-5d8a-11eb-946c-90d264073138.png)

so I have tried to install Mininet-Wifi on a new VM using Ubuntu 14.04 using the following steps 
sudo apt-get update
sudo apt-get install git
git clone https://github.com/intrig-unicamp/mininet-wifi
cd mininet-wifi
sudo util/install.sh -Wlnfv
and I  get the following error 
Cloning into 'iw'...
fatal: unable to access 'https://git.kernel.org/pub/scm/linux/kernel/git/jberg/iw.git/': server certificate verification failed. CAfile: /etc/ssl/certs/ca-certificates.crt CRLfile: none
Thanks in advance

**Comment by ramonfontes** [comment]
When opening my Mininet-Wifi virtual machine (on Vmware workstation 11) I received the following figure with kernel error
> 1. Please try VirtualBox instead.

2. so I have tried to install Mininet-Wifi on a new VM using Ubuntu 14.04 using the following steps
sudo apt-get update
sudo apt-get install git
git clone https://github.com/intrig-unicamp/mininet-wifi
cd mininet-wifi
sudo util/install.sh -Wlnfv
and I get the following error
Cloning into 'iw'...
fatal: unable to access 'https://git.kernel.org/pub/scm/linux/kernel/git/jberg/iw.git/': server certificate verification failed. CAfile: /etc/ssl/certs/ca-certificates.crt CRLfile: none
> The error is not related to Mininet-WiFi. You can find the answer by googling for the error message. This might help you: https://stackoverflow.com/questions/35821245/github-server-certificate-verification-failed
