### ISSUE TITLE
install of mininet-wifi

### ISSUE THREAD

**Issue by NovicecoderCrisis** [intrig-unicamp/mininet-wifi#362]
Hello, I'm a beginner of P4 + mininet. Now I have a little problem. I have installed P4 and mininet according to the installation steps of P4 [tutorial](https://github.com/p4lang/tutorials).  Now I want to install mininet-wifi. Do I need to uninstall the mininet that has been installed? Is the optional - P of the installation command `sudo util/install.sh -Wlnfv ` still needed?

**Comment by ramonfontes** [comment]
The P4 you have installed should work. I have never tried that version with Mininet-WiFi though.

**Comment by NovicecoderCrisis** [comment]
Thanks for your response! Yeah，I run the P4 tutorial such as basic forwarding successfully. Now I want to try to change its topology to WiFi version. So do I just need to install mininet -wifi directly without uninstalling the original mininet?

**Comment by NovicecoderCrisis** [comment]
OK! Thank you!
