### ISSUE TITLE
installation failed

### ISSUE THREAD

**Issue by srikrishna3118** [intrig-unicamp/mininet-wifi#364]
I have already installed the previous version of mininet-wifi and I was trying to update the latest version, resulting in this error

Cloning into 'mininet'...
remote: Enumerating objects: 158, done.
remote: Counting objects: 100% (158/158), done.
remote: Compressing objects: 100% (146/146), done.
remote: Total 158 (delta 7), reused 40 (delta 0), pack-reused 0
Receiving objects: 100% (158/158), 268.90 KiB | 494.00 KiB/s, done.
Resolving deltas: 100% (7/7), done.
~/simulation/mininet-wifi/mininet ~/simulation/mininet-wifi ~/simulation ~/simulation ~/simulation/mininet-wifi ~/simulation/mininet-wifi/hostap/wpa_supplicant ~/simulation/mininet-wifi/hostap/hostapd ~/simulation/mininet-wifi/hostap ~/simulation/mininet-wifi ~/simulation/mininet-wifi
cc -Wall -Wextra  -DVERSION=\"`PYTHONPATH=. python -B bin/mn --version`\" mnexec.c -o mnexec
install -D mnexec /usr/bin/mnexec
PYTHONPATH=. help2man -N -n "create a Mininet network." \
--no-discard-stderr "python -B bin/mn" -o mn.1
help2man: can't get `--version' info from python -B bin/mn
Makefile:73: recipe for target 'mn.1' failed
make: *** [mn.1] Error 2

**Comment by ramonfontes** [comment]
`git pull` and `sudo make install` do the work
