### ISSUE TITLE
wmediumdConnector.py signal table selection

### ISSUE THREAD

**Issue by Onurklngc** [intrig-unicamp/mininet-wifi#367]
Hi Dr.Ramon,

From [this method](https://github.com/intrig-unicamp/mininet-wifi/blob/b43cbc11b3803593a8536e81e35c9df9b4612aee/mn_wifi/wmediumdConnector.py#L330), the following command is called:
`['wmediumd', '-l', '0', '-s', '-c', '/tmp/mn_wmd_config_AwWFSv.cfg', '-x', '/usr/local/lib/python2.7/dist-packages/mininet_wifi-2.5-py2.7.egg/mn_wifi/data/signal_table_ieee80211']
`

When I check wmediumd log file, only the next line is logged:
_Input packet error rate file: /usr/local/lib/python2.7/dist-packages/mininet_wifi-2.5-py2.7.egg/mn_wifi/data/signal_table_ieee80211_

In mn_wifi/data/ path there are files with 'signal_table_ieee80211' prefix. I duplicated one of the these files with 'signal_table_ieee80211' name, but it still prints the same error log. I was trying to figure out which one is used in wmediumd.

Best regards,
Onur

**Comment by ramonfontes** [comment]
`signal_table_ieee80211ax` is the default one: https://github.com/ramonfontes/wmediumd/blob/mininet-wifi/wmediumd/per.c#L315

**Comment by Onurklngc** [comment]
Thank you!
