### ISSUE TITLE
Why does VANET-SUMO not support V2V communication

### ISSUE THREAD

**Issue by fansky666** [intrig-unicamp/mininet-wifi#374]
mininet-wifi/example/vanet-sumo 
V2V communication cannot be achieved

**Comment by ramonfontes** [comment]
What????

**Comment by fansky666** [comment]
I have just run example/vanet-sumo.py and found that the vehicles cannot communicate with each other.
Because cls=ITS?

**Comment by ramonfontes** [comment]
Please provide as much as information you can. I cannot confirm this issue.

**Comment by fansky666** [comment]
Sorry, do you know mininet-wifi/example/vanet-sumo.py?I just run this file, but I found that there is no communication between vehicles. I can't find the cause of the problem. Can you help me?

**Comment by ramonfontes** [comment]
How can I reproduce the issue???

**Comment by fansky666** [comment]
You can run mininet-wifi/example/vanet-sumo.py and then car1 ping car2

**Comment by fansky666** [comment]
I am sorry that I am weak in programming of Mininet-WiFi. I would like to ask whether there is an API about programming of Mininet-WiFi.

**Comment by ramonfontes** [comment]
Who is car2? It has 2 network interfaces, right? How would the system by aware about the destination?? Would it use the first or the second one?

**Comment by fansky666** [comment]
I tried 192.168.0.1 ping 192.168.0.2, but there is an error.
How do I ping it

**Comment by ramonfontes** [comment]
`192.168.0.1 ping 192.168.0.2` ??

**Comment by fansky666** [comment]
Sorry, I did it wrong, the vehicle has two ports how do I get them
communication

**Comment by ramonfontes** [comment]
Dear, are you new to computer networking too?

**Comment by fansky666** [comment]
Yeah, I'm a high school student, and I'm very interested in your Mininet-WiFi

**Comment by fansky666** [comment]
yeah

**Comment by fansky666** [comment]
Sorry to have taken up your time, because of my ignorance.
Thanks for your help
