### ISSUE TITLE
Missing bridge-utils in VM

### ISSUE THREAD

**Issue by yanosz** [intrig-unicamp/mininet-wifi#388]
Btw. sorry, forgot that one the in beginning. I created my own VM now - this is not urgent. Not having other reports on this, I don't think that's needed to create a new VM becaus of this.

https://drive.google.com/file/d/1gRqGmkyPcw1waBlwfSGnOcucvXsHvATx/view?usp=sharing does not include bridge-utils.

This breaks mininet from emulating a non of-switch. I.e. 
```python
from mininet.nodelib import LinuxBridge
s1 = net.addSwitch("s1", cls=LinuxBridge)
```
In the VM, newly created bridges use iptables / ip6tables / arbtable that break forwarding in mininet. To tackle this, I have:
### /etc/modules-load.d/bridge.conf
```
br_netfilter
```
### /etc/sysctl.d/bridge.conf 
```
net.bridge.bridge-nf-call-ip6tables = 0
net.bridge.bridge-nf-call-iptables = 0
net.bridge.bridge-nf-call-arptables = 0

```

**Comment by ramonfontes** [comment]
`bridge-utils` added in the VM. ;)
