### ISSUE TITLE
is it possible to program a node on mininet-wifi?

### ISSUE THREAD

**Issue by aceylan** [intrig-unicamp/mininet-wifi#392]
Hi. I am new on mininet-wifi. I looked at examples. 
But I am curious about programming in nodes. For example, I want to add some nodes and want to make some spesific programming on nodes. is it possible and is there an example for it?
Thanks.

**Comment by ramonfontes** [comment]
What do you mean with "program a node"??? Please use the mailing list for questions like this. This is not an issue at all.
