### ISSUE TITLE
why ovs queue setting no working on wireless interface??

### ISSUE THREAD

**Issue by Sean861026** [intrig-unicamp/mininet-wifi#395]
<img width="481" alt="截圖 2021-07-03 19 05 30" src="https://user-images.githubusercontent.com/38836267/124352202-a3876600-dc31-11eb-8e35-d3d467ce5c9c.png">

**Comment by ramonfontes** [comment]
This is due to the values added from TC to bw, loss and delay to the wlan interface. You can confirm this by running `examples/wmediumd_interference.py` cause this code uses wmediumd instead of tc.

You can also delete the rules with `ap1 tc qdisc del dev ap1-wlan1 root` and then `queue-stats` will work.

**Comment by Sean861026** [comment]
if i use wmediumd, can i set the link bw and delay?

**Comment by ramonfontes** [comment]
You cannot set link parameters when using wmediumd because they are defined by the propagation model.
You cannot use TC and OVS queues together too.

**Comment by Sean861026** [comment]
ok, got it. thank you!
i'll close this issue after this.

**Comment by Sean861026** [comment]
sorry, i use  `tc qdisc del dev ap1-wlan1` root and then create ovs queue. But it always on default queue, is this situation normal? 
<img width="557" alt="截圖 2021-07-04 06 50 26" src="https://user-images.githubusercontent.com/38836267/124368491-1e816880-dc94-11eb-9a19-564564dbb4cd.png">

**Comment by ramonfontes** [comment]
I suggest you to check the ovs doc.

**Comment by Sean861026** [comment]
sorry for bother again. 
i try to use tc directly but i got nothing after i add a filter.

```
sudo tc qdisc del dev ap2-wlan1 root handle 1:0 htb
sudo tc qdisc add dev ap2-wlan1 root handle 1:0 htb
sudo tc class add dev ap2-wlan1 parent 1:0 classid 1:1 htb rate 75mbps ceil 75mbps
sudo tc class add dev ap2-wlan1 parent 1:1 classid 1:11 htb rate 20mbps ceil 20mbps
sudo tc filter add dev ap2-wlan1 protocol ip parent 1:1 prio 1 u32 match ip dst 192.168.2.2 flowid 1:11
sudo tc filter show dev ap2-wlan1
```

**Comment by ramonfontes** [comment]
Please read the tc doc!! This is not a mn-wifi issue.

Have you ever tried  `tc filter show dev s1-eth1 parent 1:1`??

**Comment by Sean861026** [comment]
ok, thank you
