### ISSUE TITLE
name of the host limited to <=8 chars

### ISSUE THREAD

**Issue by srikrishna3118** [intrig-unicamp/mininet-wifi#399]
I was naming the stations (name_robo2)
    ap1 = net.addAccessPoint('ap1', ssid='new-ssid', mode='g', channel='1',
                             failMode="standalone", mac='00:00:00:00:00:01',
                             position='400,600,0')
    net.addStation('name_robo1', mac='00:00:00:00:00:02', ip='10.0.0.1/8',
                   position='400,400,0')

as soon as the number of characters exceeds the limit (<=8) the add intf function results in error. I have posted the error log.

added intf name_robo1-wlan0 (0) to node name_robo1
DEBUG:mininet:added intf name_robo1-wlan0 (0) to node name_robo1

*** name_robo1 : ('ip link set', 'name_robo1-wlan0', 'up')
DEBUG:mininet:*** name_robo1 : ('ip link set', 'name_robo1-wlan0', 'up')

Error: argument "name_robo1-wlan0" is wrong: "dev" not a valid ifname
DEBUG:mininet:Error: argument "name_robo1-wlan0" is wrong: "dev" not a valid ifname

**Comment by ramonfontes** [comment]
You are reporting a known issue, since the interface name must be [less than 16 characters](https://git.kernel.org/pub/scm/network/iproute2/iproute2.git/tree/lib/utils.c?id=1f420318bda3cc62156e89e1b56d60cc744b48ad#n832). As you can see this is a limit imposed by `iproute2`.

**Comment by srikrishna3118** [comment]
Ok -wlan0 also part of that interface potentially further limiting the name.. I missed that thank you
