### ISSUE TITLE
Has it support dynamic reconfiguration of link parameters?

### ISSUE THREAD

**Issue by codetime2015** [intrig-unicamp/mininet-wifi#4]
The latest version supported dynamic reconfiguration of link parameters?

**Comment by ramonfontes** [comment]
Hi,

What do you mean with *dynamic reconfiguration of link parameters*? If you
are talking about bw, loss and delay, yes. You also can use two propagation
models (free space loss and friis loss).

2015-12-15 9:09 GMT-03:00 codetime2015 <notifications@github.com>:
