### ISSUE TITLE
Some bugs found in MiniEdit

### ISSUE THREAD

**Issue by andredemori** [intrig-unicamp/mininet-wifi#401]
When I run the network in MiniEdit I can't LInkDown any topology link. Another bug I found is that I can't activate the Host Options or Switch Options. Is it recommended not to use MiniEdit or are these problems not common to appear? I'm starting to use Mininet now so I'm making use of MiniEdit in this initial step to learn.

I'm using a virtual machine downloaded from GitHub.

**Comment by ramonfontes** [comment]
Some features may not be implemented in miniedit and I won't be able to update it until some time in the future. In this way, PR are most than welcome. :)
