### ISSUE TITLE
mininet-wifi & containernet - nested docker deployment option 

### ISSUE THREAD

**Issue by andreasdotzler** [intrig-unicamp/mininet-wifi#402]
I would like to use the mininet-wifi and containernet and I prefer the nested docker deployment option. I tried https://github.com/ramonfontes/containernet and noticed the nested docker deployment option was removed from the README.md . As with the original containernet, I tried building the container image, but it fails. 

Is there a general problem that prevents mininet-wifi and containernet from being deployed in a nested docker deployment? Or is there a chance it will work if I fix the build of the docker image?

**Comment by ramonfontes** [comment]
Well, I confess that I do not remember. Which error did you find?

**Comment by andreasdotzler** [comment]
I am seeing errors with the ansible-playbook, I believe those might be related to ubuntu version, ansible version, and python version. If you can not remember a general problem, I will make an attempt to fix them and report back

```
Step 6/12 : RUN ansible-playbook -i "localhost," -c local --skip-tags "notindocker" install.yml
 ---> Running in 7443853e49c2

PLAY ***************************************************************************

TASK [setup] *******************************************************************
ok: [localhost]

TASK [updates apt] *************************************************************
fatal: [localhost]: FAILED! => {"changed": false, "failed": true, "msg": "No package matching 'apt-get update' is available"}

PLAY RECAP *********************************************************************
localhost                  : ok=1    changed=0    unreachable=0    failed=1   

The command '/bin/sh -c ansible-playbook -i "localhost," -c local --skip-tags "notindocker" install.yml' returned a non-zero code: 2
```
