### ISSUE TITLE
How can I specify the device used in devices.py in Python program 

### ISSUE THREAD

**Issue by wulas09763** [intrig-unicamp/mininet-wifi#403]
Hello, how can I specify the device used in devices.py in Python program and give the corresponding mode to limit the bandwidth?
 For example, if I want to use the di524 device in devices.py and specify mode = n, how should my Python specify it?
 I use ap1 = net. Addaccesspoint ('ap1 ', MAC ='02:00:00:00:00:01', protocols ='openflow13 ', SSID =' AP1 SSID ', model ='di524', mode = 'n', channel = '1', position ='40,60,0 ', range = 200) without any effect. Its bandwidth limit is still def getrate (self): the value of the default mode in link.py. Thank you

**Comment by ramonfontes** [comment]
You have defined the `model` and `range` params. You cannot have both because we assume the signal range provided by the device model. Moreover, you cannot use wmediumd because it works only with tc.

**Comment by wulas09763** [comment]
I want to use model in device.py , what should I do ?

**Comment by ramonfontes** [comment]
Please apply this patch https://github.com/intrig-unicamp/mininet-wifi/commit/4bdc36ac9824d632540f879fb85676f816c92bc2 and then you can try the `model` param.

**Comment by wulas09763** [comment]
It's works ! Thank you~
