### ISSUE TITLE
Cannot find device "hwsim0"

### ISSUE THREAD

**Issue by amirmirzaeinia** [intrig-unicamp/mininet-wifi#404]
Hello, 
I am trying to capture some traces on wireshark but I get error message as 
hwsim0: ERROR while getting interface flags: No such device
I was able to run and capture for the first time and then stop  working.  running the "hcxdumptool -I" gives me the following.
wlan interfaces:
34c93d00e97a wlp4s0 (iwlwifi)
warning: NetworkManager is running with pid 776
warning: wpa_supplicant is running with pid 800
any help on how to fix this issue?
thank you

**Comment by ramonfontes** [comment]
Honestly, I don't know why some prefer to use hwsim0 instead of creating a monitor interface for a particular node. Well, you probably didn't bring the network interface up.

**Comment by amirmirzaeinia** [comment]
Ramon , thank you for your prompt reply. I can capture on server node and guess that is fine in my scenarios.  I guess the main reason for hwsim0 is the following page  
https://hackmd.io/@pmanzoni/rkMF11rIH
have a look . thank you

**Comment by ramonfontes** [comment]
Sorry, I didn't get you. Can you clarify that please?

**Comment by amirmirzaeinia** [comment]
Ramon
there is another issues with high number of requests. I have client server in my mininet wifi and trying to test a wide range of experiments. But it stuck after 400 different try of different request. I guess at this point it reaches to some hardware limits (RAM, etc). Is there any way to fix this issues?
thank you

**Comment by ramonfontes** [comment]
Dear,

You have created an issue for hwsim0. Could please answer the question I made? Also, what was the problem and how did you get it solved??

By the way, I didn't comprehend the last question either.

**Comment by amirmirzaeinia** [comment]
> Sorry, I didn't get you. Can you clarify that please?

Ramon
I mean, if you just google "mininet wifi wireshark" the first page that comes up in my region is, https://hackmd.io/@pmanzoni/rkMF11rIH , which is focused on hwsim0. that is the reason I was confused to use hwsim0 rather than creating monitor interface for my server.
now that I started capturing the trace on my server node , I see another problem to extend number of flow experiments. I just have two mobile stations that are connecting to a host server through AP and requesting for services but after ~450 requests it just stuck and I have to ^C to stop the process. any solution to increase the capabilities?
thank you

**Comment by ramonfontes** [comment]
Please use the mailing list for such question and provide as much information as you can.
