### ISSUE TITLE
scalability

### ISSUE THREAD

**Issue by amirmirzaeinia** [intrig-unicamp/mininet-wifi#405]
Hello, thank you for this wonderful simulator. 
I am running a simple scenario with two mobile stations that send some requests to server (host node) that is connecting through AP. however I can just capture 450 requests and then the whole simulator stop responding. is there any help on how to fix this and make it more scalable? I have Ubuntu 20 running on my computer with 64Gbyte RAM.
thank you
Amir

**Comment by ramonfontes** [comment]
How can I reproduce the issue?

**Comment by amirmirzaeinia** [comment]
found the issue with my server. change to HTTP server on python3 and it is fixed now.
 thank you.
