### ISSUE TITLE
V2.2.0 Preconfigured VM Image Link

### ISSUE THREAD

**Issue by mufaawan** [intrig-unicamp/mininet-wifi#412]
I am trying to test following repo. 
https://github.com/jafar-albadarneh/SDS-Mininet-WiFi

It requires 2.2 version (exactly as below)
https://github.com/intrig-unicamp/mininet-wifi/tree/c97b35398d985e02eaf8a33b92406ad8bbb59973

Where can I find the link to VM for the version above in the link?

**Comment by ramonfontes** [comment]
You can try
https://github.com/intrig-unicamp/mininet-wifi/releases/tag/2.2.1

>

**Comment by mufaawan** [comment]
@ramonfontes  thank you for response. 

I have tried this version. It requires packages to import like `from mn_wifi.net import ClassName` [Python]. The repo I want to use which I mentioned in above comment uses `from mininet.wifi.net import ClassName.`.

**Comment by ramonfontes** [comment]
You can also try https://github.com/intrig-unicamp/mininet-wifi/commit/a135fccec49b8f81e99588ae2eedf9850ba2cb3c.

**Comment by mufaawan** [comment]
![image](https://user-images.githubusercontent.com/17979287/141294194-2cd476dc-4634-4b26-8893-fe2ef90232df.png)

There's no preconfigured VM min the mentioned commit.

**Comment by mufaawan** [comment]
It would be nice if you can provide me link to preconfigured VM. If it's not available and I have to configure myself. Please guide me with these:
1. which version of Ubuntu should I select?
2. Should I choose VM or native installation?

I have already tried to setup the commit you mentioned on my native installation of ubuntu 16.04. It didn't go successful.

**Comment by ramonfontes** [comment]
> which version of Ubuntu should I select?
A: >= 16.04

> Should I choose VM or native installation?
Native

> I have already tried to setup the commit you mentioned on my native installation of ubuntu 16.04. It didn't go successful.
Why?

**Comment by mufaawan** [comment]
> > which version of Ubuntu should I select?
> 
> A: >= 16.04
> 
> > Should I choose VM or native installation?
> 
> A: Native
> 
> > I have already tried to setup the commit you mentioned on my native installation of ubuntu 16.04. It didn't go successful.
> 
> A: Why?

Thank you for response. 
It finishes the installation but when I try to import package in python like `from mininet.wifi.net import *` I get error saying `no module found named mininet.wifi`

**Comment by mufaawan** [comment]
Is there any way I can get the pre-configured VM link for the version I have mentioned?
https://github.com/intrig-unicamp/mininet-wifi/tree/c97b35398d985e02eaf8a33b92406ad8bbb59973

**Comment by ramonfontes** [comment]
> Is there any way I can get the pre-configured VM link for the version I have mentioned?

No.

> It finishes the installation but when I try to import package in python like from mininet.wifi.net import * I get error saying no module found named mininet.wifi

Why don't you reproduce the code with the latest version? You can simply import `mn_wifi.net` instead of `mininet.wifi.net`

**Comment by mufaawan** [comment]
On the mentioned commit below, the VM download link is broke. Can it be fixed please? It would help me alot.

https://github.com/intrig-unicamp/mininet-wifi/tree/c97b35398d985e02eaf8a33b92406ad8bbb59973
