### ISSUE TITLE
AssertionError while pinging station that gets out of range

### ISSUE THREAD

**Issue by rrehlert** [intrig-unicamp/mininet-wifi#413]
Hello,
I am getting an issue while constatly pinging a station that gets out of the range of the Access point.
What is happening is: the ping works while in range, but if it is pinging when the station exits range it gives me an AssertionError in the console and the ping still occurs fine (no packet loss) even out of range of the AP. The same does not occur if I ping while in range, stop the ping, then resume it while out of range, then it gives me packet losses as expected.

I'll attach some prints to help the explanation 

If the ping keeps going:
![image](https://user-images.githubusercontent.com/63610519/144262129-c5f16984-d635-4150-ab7f-e72a2cb31f0d.png)

If I stop and resume it:
![image](https://user-images.githubusercontent.com/63610519/144262419-d338402f-e9cd-4db8-acb1-6d77da09559e.png)

**Comment by ramonfontes** [comment]
You can overcome this issue by running the ping command through xterm instead of the `mn-wifi` terminal.

**Comment by rrehlert** [comment]
That worked fine, thank you!
