### ISSUE TITLE
Why I am getting network is unreachable?

### ISSUE THREAD

**Issue by Varadarajreddy** [intrig-unicamp/mininet-wifi#416]
H Ramon, 

I have configured 8 switches 1 server and 12 hosts, the issue is I am unable to ping between the server and the hosts. when I try to ping I am getting network unreachable. below is my network configuration. so please help me how to achieve the successful connection between the server and the hosts?
This is my network topology.
![Screenshot (124)](https://user-images.githubusercontent.com/86453166/144710432-01883df7-7f62-4d3a-91b0-ca65f2e3e054.png)

Hosts      IP Address                  Mac Adderess
H1        147.197.129.1/24       00:00:00:00:00:01
H2        147.197.129.2/24      00:00:00:00:00:02
H3        147.197.129.3/24      00:00:00:00:00:03
H4        147.197.129.4/24      00:00:00:00:00:04
H5        147.197.129.5/24      00:00:00:00:00:05
H6        147.197.129.6/24      00:00:00:00:00:06
H7        147.197.129.7/24      00:00:00:00:00:07
H8        147.197.129.8/24      00:00:00:00:00:08
H9        147.197.129.9/24      00:00:00:00:00:09
H10      147.197.129.10/24    00:00:00:10:10:01
H11      147.197.129.11/24    00:00:00:10:10:02
H12      147.197.129.12/24    00:00:00:10:10:03
Server   10.10.10.1/8              00:00:00:10:10:04

**Comment by ramonfontes** [comment]
There is a switching loop in your network topology! :( :( this is not a mn-wifi issue at all!
