### ISSUE TITLE
setBGScan function replacement.

### ISSUE THREAD

**Issue by mufaawan** [intrig-unicamp/mininet-wifi#417]
I have been trying to convert code from following link which was supposed to work on with mininet-wifi 2.2.  But I am converting it to work with latest mininet-wifi.
https://github.com/jafar-albadarneh/SDS-Mininet-WiFi/blob/master/SDCD/sdcd-experimental.py

On line number 96 there is an statement:
`net.setBgscan(signal=-45, s_inverval=5, l_interval=10)`

I found that there is no setBgscan function anymore in net.py. How am I supposed to handle this change?

**Comment by ramonfontes** [comment]
Hi,

You can take [handover_bgscan.py ](https://github.com/intrig-unicamp/mininet-wifi/blob/master/examples/handover_bgscan.py#L33) as reference.

**Comment by mufaawan** [comment]
I fixed the issue by suggested solution. 
Simulation started, when I click 'Locate Vehicles'.  I see no vehicles list. 

Just for the sake of confirmation I executed `vanet-sumo.py` from examples. Even with that example file without any change I see no vehicles list under 'Locate Vehicles'. Please suggest me if I need to do anything. 

I am using preconfigured VM. And I confirmed that there is data folder inside mn_wifi/sumo. This folder has all files.

**Comment by ramonfontes** [comment]
Which SUMO version do you have??

**Comment by mufaawan** [comment]
I have following version.
![Uploading image.png…]()

**Comment by mufaawan** [comment]
![image](https://user-images.githubusercontent.com/17979287/145069770-bfd6ba6f-17fd-4864-bd46-f2ddaf331e6c.png)

I have this version.

**Comment by ramonfontes** [comment]
Have you ever read the requirements??

https://github.com/intrig-unicamp/mininet-wifi/blob/37785e5dbd3d62cb33284af201a18b83c5ec38a9/examples/vanet-sumo.py

**Comment by mufaawan** [comment]
So I updated to v1.11. Still can't see any vehicle in the list.

**Comment by ramonfontes** [comment]
How can I reproduce the issue?

**Comment by mufaawan** [comment]
You can reproduce by loading pre-configured VM(latest:without p4). And just execute `vanet-sumo.py` from examples.

**Comment by ramonfontes** [comment]
Okay. You are using the VM. Can you please do a `git pull`, run `sudo make install` and then run the code one more time?

**Comment by mufaawan** [comment]
It worked this time.  
Thank you so much. 

I am sorry for asking too much. But I have one  more question. Actually I am upgrading the repo to   work  with latest Mininet wifi. 

https://github.com/jafar-albadarneh/SDS-Mininet-WiFi/blob/master/SDCD/sdcd-experimental.py
On line 146 and 155  there is an array accessed from net object like `net.carsSTA` which was part of v2.2. I have been struggling to find the same array in latest version.

One parallel request is to please provide the link to preconfigured VM for version 2.2.  It must be somewhere in your google  drive. It would make alot of  things easy for me.  
Thank you.

**Comment by mufaawan** [comment]
@ramonfontes  I am waiting for kind response.

**Comment by ramonfontes** [comment]
> On line 146 and 155 there is an array accessed from net object like net.carsSTA which was part of v2.2. I have been struggling to find the same array in latest version

There is no carsSTA anymore. However, you can easily reproduce the same setup by connecting a switch to the vehicle.

> One parallel request is to please provide the link to preconfigured VM for version 2.2. It must be somewhere in your google drive. It would make alot of things easy for me.

There is no VM for old releases.
