### ISSUE TITLE
Dual Band Configuration

### ISSUE THREAD

**Issue by Saydemr** [intrig-unicamp/mininet-wifi#418]
Hello,

I would like to broadcast two SSIDs, one in 5GHz and another in 2.4GHz, from one AP in Miniedit. However, though I can change the Wlans parameter, I cannot add another SSID. Is there any delimiter that allows this?

![image](https://user-images.githubusercontent.com/37012364/146162009-12a079e5-a5ff-4971-9237-00673790a686.png)
![image](https://user-images.githubusercontent.com/37012364/146162277-3d080a97-0293-46a8-878a-754e416543b8.png)

If not, how should I change the python script to achieve this configuration? 

Thanks.
Abdullah

**Comment by ramonfontes** [comment]
You can try ssid=['ssid_1', 'ssid_2']

**Comment by Saydemr** [comment]
Thanks!
