### ISSUE TITLE
Issue with EAP TLS Example 

### ISSUE THREAD

**Issue by rali0** [intrig-unicamp/mininet-wifi#420]
hello All 

i had made the changes mentioned in the TLS EAP code and ran it it works fine without any error however 

sta1 ping sta2 does not work 

also there are no debug file being created 

cat /var/log/syslog | grep hostap shows that the stations are authenticated. 

Regards

**Comment by ramonfontes** [comment]
What??? What is the purpose of this issue??

**Comment by rali0** [comment]
Hello Ramon

I guess i did not do a good job of explaining. The purpose for the example
as far as I understand is to have the CA certify the Ap and stations after
the connection is successfull i should be able to ping between them which i
cannot as the readme suggested so are there any other changes we need to
make or am i missing something?

Regards

Rizwan

**Comment by ramonfontes** [comment]
Closing this issue, as the author was unable to explain it in detail. Also, it is not clear how this issue is related to mn-wifi.
