### ISSUE TITLE
Cannot load backend ‘TkAgg’ which requires the ‘tk’

### ISSUE THREAD

**Issue by andredemori** [intrig-unicamp/mininet-wifi#422]
I'm facing the following issue:

I have a Django project that imports some libraries from mn_wifi and that django project is running with python3.

When installing Mininet Wi-Fi it installs along with python 2.7.

But I need to install Mininet Wi-Fi with python3 for the project to be able to import mn_wifi.

I tried to install as follows:

sudo PYTHON=python3 util/install.sh -Wlnfv6

`sudo mn --> works`

`sudo mn --wifi`

output:

```
Usage: mn [options]
(type mn -h for details)

mn: error: no option: --wifi
```

I receive the following error during installation process:

`Cannot load backend ‘TkAgg’ which requires the ‘tk’`

Are there any restrictions for using Mininet Wi-Fi with python3 or a different thing to do in installation process?

**Comment by ramonfontes** [comment]
Please see https://github.com/intrig-unicamp/mininet-wifi/issues/415

**Comment by andredemori** [comment]
Solution:

export DISPLAY=":0.0"

Thanks.
