### ISSUE TITLE
[Error] Installation method install.sh have failed

### ISSUE THREAD

**Issue by VictoriaNoci** [intrig-unicamp/mininet-wifi#425]
Hi!

I have found an error at the moment of the installation of Wifi Dependences. I'm using Ubuntu 20.04 VM.

Here is the error:

![imagen](https://user-images.githubusercontent.com/48250726/155516768-4c36d4b6-3636-412c-8fdb-4fc01e0464fd.png)

Thank you! :smile:

**Comment by ramonfontes** [comment]
Hi, this is not a mn-wifi issue. You can easily find answer for this question on google.
