### ISSUE TITLE
How to make the connection between the switch and the controller multi-hop？

### ISSUE THREAD

**Issue by longmao121** [intrig-unicamp/mininet-wifi#428]
My current situation is：controllers defalut work in root namespace,  and connect UserAPs which running into their own namespace by domian socket. So,  I cannot I can't make the controllers multi-hop.

How to make the connection between the switch and the controller multi-hop？
Is it okay to put the controllers in their own namespace? How?

**Comment by ramonfontes** [comment]
Create a node (e.g. host) and run the controller in it.

**Comment by longmao121** [comment]
> Create a node (e.g. host) and run the controller in it.

But the controller and switch cannot be connected, if run the controller in a host. 
h1 :10.0.0.1 、ap1 ：10.0.0.6,  I can ping h1 in ap1 (xterm ap1)
Is it because the controller(node c0, not ryu or nox) is still running in root namespce?

**Comment by ramonfontes** [comment]
> But the controller and switch cannot be connected, if run the controller in a host.

Why not? We can help you if you provide further details.

> Is it because the controller(node c0, not ryu or nox) is still running in root namespce?

Sorry, I don't know what do you mean.

**Comment by longmao121** [comment]
> Sorry, I don't know what do you mean.

![image](https://user-images.githubusercontent.com/55868895/160620027-8f66e2c3-c2dc-49d0-9827-53bf1ecebe6e.png)
The controller is still in root namespace, but I run ryu in h1, is that ok？
Thank you~

**Comment by ramonfontes** [comment]
Do you need two controllers or only one??

**Comment by longmao121** [comment]
> Do you need two controllers or only one??
![image](https://user-images.githubusercontent.com/55868895/160624795-b5ede064-5477-446e-b178-a1a39cecf95a.png)

For exmaple, c1 in the range of ap1. If I run ryu in root namespce, and change ap3 loss 100% by TC,  c1 will disconnect with ap3，but ap4 and ap5 have no effect

**Comment by ramonfontes** [comment]
> For exmaple, c1 in the range of ap1. If I run ryu in root namespce, and change ap3 loss 100% by TC, c1 will disconnect with ap3，but ap4 and ap5 have no effect

Which effect do you expect in ap4 and ap5 other than have no effect?? Didn't you set loss only in ap3? I'm getting too confused.

**Comment by longmao121** [comment]
> 

c1 only in the range of ap1, if ap3 loss all packects, ap4 ap5 should disconnect with c1, but not

**Comment by longmao121** [comment]
> Which effect do you expect in ap4 and ap5 other than have no effect?? Didn't you set loss only in ap3? I'm getting too confused.
c1 only in the range of ap1, if ap3 loss all packects, ap4 ap5 should disconnect with c1, but not

**Comment by longmao121** [comment]
> You can try containernet https://github.com/ramonfontes/containernet
Thanks for your response!
