### ISSUE TITLE
802.11ax (WiFi 6) didn't work for me

### ISSUE THREAD

**Issue by ygoramaral** [intrig-unicamp/mininet-wifi#429]
Is it possible to use 802.11ax? The topic of [supported wireless modes](https://mn-wifi.readthedocs.io/en/latest/usage.html#supported-wireless-modes) and examples/6GHz.py makes me believe so.

However, I am having trouble creating a topology with 802.11ax on Mininet-WiFi. Follow the screenshot:
![802 11ax](https://user-images.githubusercontent.com/1597361/160623553-a065671f-edf5-4b24-b8f1-c0d425e48cd9.png)

mn-wifi returns the following warning:
- `Bandwidth limit 2000 is outside supported range 0..1000 - ignoring`

When trying to run examples/6GHz.py, no warning is returned, but it does not work either. Follow the screenshot:
![802 11ax_6GHz](https://user-images.githubusercontent.com/1597361/160626773-253a27bf-d3d2-47cc-ae00-7bd0de526969.png)

With 802.11ac (WiFi 5) it works. Follow the screenshot:
![802 11ac](https://user-images.githubusercontent.com/1597361/160623977-b5f1e9f5-a1c8-4da2-916c-148da30c6e4c.png)

I do not need 802.11ax at 6GHz. If 6Ghz is available it will be a bonus for me.

My kernel linux is: 
- `Linux amaral 5.13.0-37-generic #42~20.04.1-Ubuntu SMP Tue Mar 15 15:44:28 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux`

The version of Mininet-WiFi in use is the latest clone with the March 26, 2022 commit. My python is 3.8.10.

**Comment by ramonfontes** [comment]
> Bandwidth limit 2000 is outside supported range 0..1000 - ignoring

I will take a look and give you a feedback asap.

> When trying to run examples/6GHz.py, no warning is returned, but it does not work either.

Kernel version is OK but it is not clear to me if you have enabled 6GHz channels in your system. Have you modified the regulatory domain to support 6GHz. 

Regarding channel 36, honestly I don't remember if 11ax supports it. If so, we need to check the Linux kernel too.

**Comment by ygoramaral** [comment]
> Fixed in https://github.com/intrig-unicamp/mininet-wifi/commit/081537c54d80be8f20347522dd4cb123fa00d970

Thanks for fixing the warning quickly.

> Kernel version is OK but it is not clear to me if you have enabled 6GHz channels in your system. Have you modified the regulatory domain to support 6GHz?

I did not know about this need. What must be done to allow 6 GHz channels on my system?

When I run the commands:
`mininet-wifi> ap1 iw phy`
`mininet-wifi> sta1 iw phy`

Really only 2.4GHz and 5GHz network capabilities appear. No 6 GHz capabilities are shown.

Also only appears 2.4GHz and 5GHz with the commands:
`mininet-wifi> ap1 iwlist ap1-wlan1 frequency`
`mininet-wifi> sta1 iwlist sta1-wlan0 frequency`

However, 802.11ax should also be able to work on the 5 GHz frequency. However, the freq=5 attribute in the Mininet_wifi class constructor seems to be ignored (I just suspect).

I unsuccessfully tested 802.11ax with several 5 GHz channels present in the mac80211_hwsim kernel module (lines 337-383).

**Comment by ramonfontes** [comment]
You have to enable 6GHz channels in the regulatory domain.

Regarding 5Ghz, can you confirm that the system support channel 36?

**Comment by ygoramaral** [comment]
> You have to enable 6GHz channels in the regulatory domain. I did something similar with 11p in https://mininet-wifi.github.io/80211p/

I understand now. I checked the kernel's git and noticed that this was already done last month by Ilan Peer.

This commit should be in the next tag (5.18). So I will wait to test this.

> Regarding 5Ghz, can you confirm that the system support channel 36?

5 GHz - ch 36, it worked here with the modes: 'a', 'n5' and 'ac'. With 'ax' does not work.

I also tested the 'ax' with 2.4 GHz, but without success.

I can not get any feedback on what frequency it's actually running. 

So I have doubts if the mn-wifi is trying to run the 'ax' with 2.4 GHz or 5 GHz; or if under the hood mn-wifi is only trying with 6 GHz.

The 802.11ax standard works with 2.4GHz, 5GHz, and 6GHz.

As it is something new, I will wait for more new kernel versions to check if WiFi 6 works on mininet-wifi.

For now I will continue using ns-3, which already has support for 'ax'.

Thank you Ramon!

**Comment by ramonfontes** [comment]
> This commit should be in the next tag (5.18). So I will wait to test this.

This is not about kernel version. Don't you know regdomain??

> So I have doubts if the mn-wifi is trying to run the 'ax' with 2.4 GHz or 5 GHz; or if under the hood mn-wifi is only trying with 6 GHz.

Well, there is no channel 36 for 2.4GHz, right? I will take a look at it one more time.

**Comment by ygoramaral** [comment]
> This is not about kernel version. Don't you know regdb and cdra??

In the [link](https://mininet-wifi.github.io/80211p/) you gave me, in addition to working with wireless-regdb and crda, you also added reg_rules in the mac80211_hwsim kernel module. What I meant is that there is already a commit of new reg_rules for 6GHz and it should be updated in kernel 5.18.

`REG_RULE(5955 - 10, 7125 + 10, 320, 0, 33, 0),`

> Well, there is no channel 36 for 2.4GHz, right? I will take a look at it one more time.

I tested several channels. In the specific case of 2.4 GHz, I tested values in the range 1-11.

> Could you share some pointer that shows Linux Kernel support 5GHz with 11ax?

I do not know specifically where the kernel provides this support.

However, I looked the source code superficially and found some wireless drivers that appear to support these frequencies with 11ax. 

Drivers:

5.17/drivers/net/wireless

- /ath/atk11k - 2.4, 5, and 6 GHz
- /realtek/rtw89 - 2.4, and 5 GHz
- /mediatek/mt76/mt7915 - 2.4, and 5 GHz
- /mediatek/mt76/mt7921 - 2.4, 5, and 6 GHz
- /intel/iwlwifi - 2.4, 5, and 6 GHz

**Comment by ramonfontes** [comment]
Please try https://github.com/intrig-unicamp/mininet-wifi/commit/17b0b595bce8963883e0de0295e0650ecdecaad9

You can do a `git pull` and `sudo make install`

Then, you can run either (for 2.4GHz):
```
sudo mn --wifi --mode=ax --channel=6 --mode=ax --encrypt=wpa2 --passwd=tests101010
```

or (for 5GHz):
```
sudo mn --wifi --mode=ax --channel=36 --mode=ax --encrypt=wpa2 --passwd=tests101010
```

**Comment by ygoramaral** [comment]
Very cool Ramon! Thanks!

You accidentally added two bugs. Line 798 and line 807 in mn_wifi/link.py (TypeError).

- When the mode is 'ac' or 'ax', the channel will need to be integer. But you often use it as a string. For example: examples/6GHz.py

I have other doubts, but I think they are beyond the issue scope. I will put the doubts here, because they can serve for a future discussion, but I will close the issue, because it's been resolved.

- Channels 1, 5, 9, and 13 exist in both 2.4 and 6 GHz. If using freq explicitly will mn-wifi switch correctly?
- Is there a way to change the MCS index to use different capabilities. Because it seems to me that 'ac' and 'ax' have the same performance at 2.4 GHz and 5 GHz. When I use the command: iw dev \<interface\> link, the MCS of rx and tx does not seem correct to me.

I need to spend some time inspecting and debugging mn-wifi to understand how it works internally.

Thanks again Ramon.

**Comment by ygoramaral** [comment]
Thanks!
