### ISSUE TITLE
error: Your local changes to the following files would be overwritten by checkout

### ISSUE THREAD

**Issue by elhachi** [intrig-unicamp/mininet-wifi#431]
Hello, I got this error when installing mininet-wifi using "sudo util/install.sh -Wlnfv" command:

~/mininet-wifi ~/mininet-wifi
error: Your local changes to the following files would be overwritten by checkout:
hostapd/defconfig
wpa_supplicant/defconfig
wpa_supplicant/p2p_supplicant.c
Please, commit your changes or stash them before you can switch branches.
Aborting
Unable to checkout 'f1843376050e787fbcea8eb5f61e617ebd658430' in submodule path 'hostap'

So please could you tell me how to deal with this issue? 
(I'm using ubuntu 14.04 LTS VM)

**Comment by ramonfontes** [comment]
> Please, commit your changes or stash them before you can switch branches

Cannot you do that??

**Comment by elhachi** [comment]
I'm sorry for reopening this issue. But I got a new error when running the "sudo mn --wifi" command and I don't know how to solve it:
mininet@mininet-vm:~/mininet-wifi$ sudo mn --wifi
*** Adding stations:
sta1 sta2
*** Adding access points:
ap1
*** Configuring wifi nodes...
--------------------------------------------------------------------------------
Caught exception. Cleaning up...

IOError: [Errno 2] No such file or directory: '/etc/NetworkManager/conf.d/unmanaged.conf'
--------------------------------------------------------------------------------
*** Removing excess controllers/ofprotocols/ofdatapaths/pings/noxes
killall controller ofprotocol ofdatapath ping nox_corelt-nox_core ovs-openflowd ovs-controllerovs-testcontroller udpbwtest mnexec ivs ryu-manager 2> /dev/null
killall -9 controller ofprotocol ofdatapath ping nox_corelt-nox_core ovs-openflowd ovs-controllerovs-testcontroller udpbwtest mnexec ivs ryu-manager 2> /dev/null
pkill -9 -f "sudo mnexec"
*** Removing junk from /tmp
rm -f /tmp/vconn* /tmp/vlogs* /tmp/*.out /tmp/*.log
*** Removing old X11 tunnels
*** Removing excess kernel datapaths
ps ax | egrep -o 'dp[0-9]+' | sed 's/dp/nl:/'
***  Removing OVS datapaths
ovs-vsctl --timeout=1 list-br
ovs-vsctl --timeout=1 list-br
*** Removing all links of the pattern foo-ethX
ip link show | egrep -o '([-_.[:alnum:]]+-eth[[:digit:]]+)'
ip link show
*** Killing stale mininet node processes
pkill -9 -f mininet:
*** Shutting down stale tunnels
pkill -9 -f Tunnel=Ethernet
pkill -9 -f .ssh/mn
rm -f ~/.ssh/mn/*
*** Cleanup complete.

*** Removing WiFi module and Configurations
*** Killing mac80211_hwsim

**Comment by ramonfontes** [comment]
Can you create `/etc/NetworkManager/conf.d/unmanaged.conf`?

**Comment by elhachi** [comment]
To be honest with you, I have never tried it before but I will try.

**Comment by elhachi** [comment]
Is this the right way to create the /etc/NetworkManager/conf.d/unmanaged.conf file?
I created the conf.d directory and then create the unmanaged.conf using nano and add the following lines:
[main]
plugins=ifupdown,keyfile

[ifupdown]
managed=false

**Comment by ramonfontes** [comment]
There is no correct way. The file just needs to exist - even if it's empty.

**Comment by elhachi** [comment]
I solved the problem, thank you for your help.
