### ISSUE TITLE
802.11p-wireless-regdb not compiling with python3

### ISSUE THREAD

**Issue by alamfaisal654** [intrig-unicamp/mininet-wifi#433]
I am trying to perform some experiments with IEEE802.11p involving cars and accesspoints. I tried to install dependencies for the same as given on the[ web page](https://mininet-wifi.github.io/80211p/) .

I have python3 installed and when I try to build the **802.11p-wireless-regdb,** it gives me issues as the code has been written for python2 and I have python3. The last code commit is in 2014. Is there a corresponding repository that is **compatible with python3**.

Secondly, I am using the vm provided on the mininet-wifi webpage. **Does IEEE802.11p come preinstalled in that vm image** ?

**Comment by ramonfontes** [comment]
> Is there a corresponding repository that is compatible with python3

Honestly, I don't know. However, this is not a problem at all. You can compile with python2 and use python3 once you have the binary.


> Does IEEE802.11p come preinstalled in that vm image ?

No. 802.11p doesn't come in that vm. In general, you don't install 802.11p. You only have to enable the frequency supported by 802.11p in the regulatory domain.
