### ISSUE TITLE
Some problems of mininet-wifi

### ISSUE THREAD

**Issue by KeyiJJJ** [intrig-unicamp/mininet-wifi#434]
When I run the example of mininet-wifi，I face this problem.
And I followed the prompts, but it didn't work.
Could you please help me？
Thanks！
![RY}N2UNW%IJ_7WO}HDMI`ER](https://user-images.githubusercontent.com/60995838/164282573-f8b28077-741a-4c29-bb6d-44f9c76cc172.png)

**Comment by KeyiJJJ** [comment]
I ‘m a new to mininet-wifi and I also want to know can i put two wifi adapter（e.g: staX-wlan0） in one station？
Thank u.

**Comment by ramonfontes** [comment]
> When I run the example of mininet-wifi

Does the system have mac80211_hwsim?

> I also want to know can i put two wifi adapter（e.g: staX-wlan0) in one station？

https://mininet-wifi.github.io/advanced/#multipleifaces

**Comment by KeyiJJJ** [comment]
> mac80211_hwsim

yes.. I think it has.
![HZ1I3YUP 9VUZZ(U{ GBML0](https://user-images.githubusercontent.com/60995838/164375582-4f956aa1-b92e-40e7-a6c1-c5236000e21f.png)
And after I  download it again, it is ok now.
Thanks fot your reply.
