### ISSUE TITLE
Run $ sudo mn --wifi, in the CLI, run >sta1 ping sta2, soon became unreachable.

### ISSUE THREAD

**Issue by Flash-Tang** [intrig-unicamp/mininet-wifi#439]
sudo mn --wifi
*** Adding stations:
sta1 sta2 
*** Adding access points:
ap1 
*** Configuring wifi nodes...
*** Creating network
*** Adding controller
*** Adding hosts:

*** Adding switches:

*** Adding links:
(sta1, ap1) (sta2, ap1) 
*** Starting controller(s)
c0 
*** Starting L2 nodes
ap1 ...
*** Starting CLI:
mininet-wifi> sta1 ping sta2
PING 10.0.0.2 (10.0.0.2) 56(84) bytes of data.
64 bytes from 10.0.0.2: icmp_seq=1 ttl=64 time=4.46 ms
64 bytes from 10.0.0.2: icmp_seq=2 ttl=64 time=2.44 ms
64 bytes from 10.0.0.2: icmp_seq=3 ttl=64 time=2.37 ms
From 10.0.0.1 icmp_seq=38 Destination Host Unreachable
From 10.0.0.1 icmp_seq=39 Destination Host Unreachable
From 10.0.0.1 icmp_seq=40 Destination Host Unreachable
From 10.0.0.1 icmp_seq=41 Destination Host Unreachable
From 10.0.0.1 icmp_seq=42 Destination Host Unreachable
From 10.0.0.1 icmp_seq=43 Destination Host Unreachable

**Comment by ramonfontes** [comment]
Did you stop network manager??

**Comment by Flash-Tang** [comment]
Oh, I didn't notice this Note in readme,
It works, thank you so much :)
