### ISSUE TITLE
Matplotlib issue

### ISSUE THREAD

**Issue by Rahi63** [intrig-unicamp/mininet-wifi#440]
Hello, I am new to SDN and Mininet. Could you please guide me on how to solve this problem?
Thank you

sudo mn --wifi 
[sudo] password for lab1: 

Bad key "lines.markeredgecolor" on line 12 in
/usr/share/matplotlib/mpl-data/stylelib/classic.mplstyle.
You probably need to get an updated matplotlibrc file from
http://github.com/matplotlib/matplotlib/blob/master/matplotlibrc.template
or from the matplotlib source distribution

Bad key "lines.markerfacecolor" on line 11 in
/usr/share/matplotlib/mpl-data/stylelib/classic.mplstyle.
You probably need to get an updated matplotlibrc file from
http://github.com/matplotlib/matplotlib/blob/master/matplotlibrc.template
or from the matplotlib source distribution
*** Adding stations:
sta1 sta2 sta3 sta4 
*** Adding access points:
ap1 ap2 ap3 ap4 
*** Configuring wifi nodes...
Warning! If you already had Mininet-WiFi installed please run util/install.sh -W and then sudo make install.
Warning! Error when loading mac80211_hwsim. Please run sudo 'mn -c' before running your code.
Further information available at /tmp/mn-wifi-mac80211_hwsim.log.

**Comment by ramonfontes** [comment]
This is not a mn-wifi issue. One of the messages say: 
```
You probably need to get an updated matplotlibrc file from
[http://github.com/matplotlib/matplotlib/blob/master/matplotlibrc.template](https://github.com/matplotlib/matplotlib/blob/master/matplotlibrc.template)
or from the matplotlib source distribution
```

What should you do??

**Comment by Rahi63** [comment]
Thank you for your response. I executed this command first:
sudo apt-get install linux-image-extra-`uname -r`

but I got an error:

sudo apt-get install linux-image-extra-$(uname -r)
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package linux-image-extra-5.13.0-41-generic
E: Couldn't find any package by glob 'linux-image-extra-5.13.0-41-generic'
E: Couldn't find any package by regex 'linux-image-extra-5.13.0-41-generic'

and then, according to another topic (error in loading mac80211_hwsim #169), I applied the commends, but the problem was not solved.

**Comment by ramonfontes** [comment]
Did you solve the problem with matplotlib??

**Comment by Rahi63** [comment]
Not yet. I don't know how should I update matplotlibrc file because the link that you sent me doesn't work.

**Comment by ramonfontes** [comment]
Pardon, which link I sent to you? Wasn't it issued by your system??

**Comment by Rahi63** [comment]
sorry I meant this command:
sudo apt-get update http://github.com/matplotlib/matplotlib/blob/master/matplotlibrc.template

it didn't work for me

**Comment by Rahi63** [comment]
I updated matplotlibrc file but I got an error when I ran my topology:

Warning! If you already had Mininet-WiFi installed please run util/install.sh -W and then sudo make install.
Warning! Error when loading mac80211_hwsim. Please run sudo 'mn -c' before running your code.
Further information available at /tmp/mn-wifi-mac80211_hwsim.log.

**Comment by ramonfontes** [comment]
What is the result for `sudo modprobe mac80211_hwsim`?

**Comment by Rahi63** [comment]
nothing. 
lab1@ubuntu:~$ sudo modprobe mac80211_hwsim
lab1@ubuntu:~$

after that when I run: sudo mn --wifi I get the same error
arning! Error when loading mac80211_hwsim. Please run sudo 'mn -c' before running your code

**Comment by Rahi63** [comment]
lab1@ubuntu:~$ sudo mn --wifi -v debug

Bad key "lines.markeredgecolor" on line 12 in
/usr/share/matplotlib/mpl-data/stylelib/classic.mplstyle.
You probably need to get an updated matplotlibrc file from
http://github.com/matplotlib/matplotlib/blob/master/matplotlibrc.template
or from the matplotlib source distribution

Bad key "lines.markerfacecolor" on line 11 in
/usr/share/matplotlib/mpl-data/stylelib/classic.mplstyle.
You probably need to get an updated matplotlibrc file from
http://github.com/matplotlib/matplotlib/blob/master/matplotlibrc.template
or from the matplotlib source distribution
*** errRun: ['which', 'controller'] 
/usr/local/bin/controller
  0*** errRun: ['grep', '-c', 'processor', '/proc/cpuinfo'] 
4
  0*** Setting resource limits
*** Adding stations:
*** errRun: ['which', 'mnexec'] 
/usr/bin/mnexec
  0*** errRun: ['which', 'ip', 'addr'] 
/usr/sbin/ip
  1_popen ['mnexec', '-cdn', 'env', 'PS1=\x7f', 'bash', '--norc', '--noediting', '-is', 'mininet:sta1'] 47986*** sta1 : ('unset HISTFILE; stty -echo; set +m',)
unset HISTFILE; stty -echo; set +m
sta1 _popen ['mnexec', '-cdn', 'env', 'PS1=\x7f', 'bash', '--norc', '--noediting', '-is', 'mininet:sta2'] 47988*** sta2 : ('unset HISTFILE; stty -echo; set +m',)
unset HISTFILE; stty -echo; set +m
sta2 
*** Adding access points:
*** errRun: ['which', 'ovs-vsctl'] 
/usr/bin/ovs-vsctl
  0*** errRun: ['ovs-vsctl', '-t', '1', 'show'] 
7c54e88d-6551-455c-b4fd-920b7675e79c
    ovs_version: "2.13.5"
  0*** errRun: ['ovs-vsctl', '--version'] 
ovs-vsctl (Open vSwitch) 2.13.5
DB Schema 8.2.0
  0_popen ['mnexec', '-cd', 'env', 'PS1=\x7f', 'bash', '--norc', '--noediting', '-is', 'mininet:ap1'] 47993*** ap1 : ('unset HISTFILE; stty -echo; set +m',)
unset HISTFILE; stty -echo; set +m

added intf lo (0) to node ap1
*** ap1 : ('ifconfig', 'lo', 'up')
ap1 
*** Configuring wifi nodes...
Loading 3 virtual wifi interfaces
Warning! If you already had Mininet-WiFi installed please run util/install.sh -W and then sudo make install.
Warning! Error when loading mac80211_hwsim. Please run sudo 'mn -c' before running your code.
Further information available at /tmp/mn-wifi-mac80211_hwsim.log.
