### ISSUE TITLE
sta1 iw dev sta1-wlan0 link  -  "Not connected".

### ISSUE THREAD

**Issue by Liliana060618** [intrig-unicamp/mininet-wifi#441]
Hello,

I installed mininet-wifi some time ago, everything was working. I had a problem on my computer, I reinstalled everything again. I ran some of the examples and everything was working, 
When I do **_sta1 iw dev sta1-wlan0 link_** the answer is: "Not connected".

Please, a need your help.

Thank you

**Comment by Liliana060618** [comment]
> Hello,
> 
> I installed mininet-wifi some time ago, everything was working. I had a problem on my computer, I reinstalled everything again. I ran some of the examples and everything was working, I didn't make any changes and at the moment I can't ping between the sta, even in the simple topology. But it doesn't give any error. Also when I do **_sta1 iw dev sta1-wlan0 link_** the answer is: "Not connected".
> 
> Please, a need your help.
> 
> Thank you

**Comment by ramonfontes** [comment]
Is network manager running??

**Comment by Liliana060618** [comment]
Pois, era esse o problema. Já está resolvido.
Muito Obrigada.
Liliana
