### ISSUE TITLE
falha no ping no static-routing.py 

### ISSUE THREAD

**Issue by Liliana060618** [intrig-unicamp/mininet-wifi#442]
Olá Ramon,

Estou a ter problemas na conexão entre a sta1 e a sta2 no script static-routing.py. 
Coloquei as rotas, como explicado no livro, mesmo assim não pinga.

Consegue me ajudar?

Obrigada.

Liliana

**Comment by ramonfontes** [comment]
Olá,

Então, será melhor que utilizes o [repositório do livro](https://github.com/ramonfontes/mn-wifi-ebook) para questões sobre o livro. Além disso, é muito importante que você explique em detalhes o comportamento observado e indicações de resoluções de problemas que você tentou/observou.
