### ISSUE TITLE
I can't install mininet-wifi

### ISSUE THREAD

**Issue by Rahi63** [intrig-unicamp/mininet-wifi#443]
Hello,
I installed mininet and it works fine but I can not install minify-wifi.
I did the following steps:
1- sudo apt-get install git
2- git clone https://github.com/intrig-unicamp/mininet-wifi
3- cd mininet-wifi/util/
4- sudo ./install.sh -Wlnfv

Please help if you can.

![3](https://user-images.githubusercontent.com/36030289/173368671-a2e6cf03-ca05-4779-abda-817f1d5425f5.png)
![2](https://user-images.githubusercontent.com/36030289/173368675-d90c6473-5562-4332-af34-d768cb09b5f9.png)
![1](https://user-images.githubusercontent.com/36030289/173368677-2449963f-3176-4514-a8a8-932fb3a8b7d9.png)

**Comment by ramonfontes** [comment]
Please don't create multiple issues for the same subject. According to the message error you have a problem of permissions in your system and there is nothing we can do for that.
