### ISSUE TITLE
stations cant communicate with each other in mininet-wifi

### ISSUE THREAD

**Issue by Rahi63** [intrig-unicamp/mininet-wifi#444]
Hello,
I have Opendaylight controller and mininet-wifi on Ubuntu 20.
when I run simple mininet, all my hosts can ping each other, and the network works properly. but when I run mininet-wifi the stations can't ping each other.
Also, I can run some examples like mesh.py without any problem. could you please help me?

![1](https://user-images.githubusercontent.com/36030289/173787683-b4eefb0b-5c81-4a99-8e92-b59f511409a8.jpg)
![2](https://user-images.githubusercontent.com/36030289/173787686-1d1ef807-1266-440f-96f2-89fd15c96aa4.jpg)

**Comment by ramonfontes** [comment]
Is network manager running? Are stations associated with APs. If you confirm associations, this means that you have a problem with the control plane.

**Comment by Rahi63** [comment]
Thank you for your answer, but I don't think the stations are associated with APs.

![3](https://user-images.githubusercontent.com/36030289/173820962-da6010e7-0746-4558-ba56-5b8f8fe32b2f.jpg)

**Comment by ramonfontes** [comment]
You didn't answer the question about network manager.. :(

**Comment by Rahi63** [comment]
could you please guide me on how to check if the network manager is running or not?

**Comment by Rahi63** [comment]
I stopped the network manager with: sudo systemctl stop network-manager
but in the end, the problem remains

**Comment by ramonfontes** [comment]
Any issues with `sudo mn --wifi -v debug`?

**Comment by Rahi63** [comment]
I have run this command before but unfortunately, I could not understand anything from it to fix the problem

![5](https://user-images.githubusercontent.com/36030289/173834306-fee598e5-ca8f-4757-a1ca-fa36fd536cc0.jpg)

**Comment by Rahi63** [comment]
I could solve the problem by resetting the network manager.
Thank you for your help
