### ISSUE TITLE
How to connect two hosts or stations via SSH

### ISSUE THREAD

**Issue by andredemori** [intrig-unicamp/mininet-wifi#445]
I created a simple topology using miniedit. I have a controller, a switch and two hosts. I can ping between the two hosts using terminal. But I can't make a ssh connection, because of the error **_port 22: connection refused._**

I'm trying to make the connection as follows:

`ssh -l h2 10.0.0.2`

Any suggestions on how to get this connection done?

**Comment by andredemori** [comment]
I saw that in mininet there is a way to run the sshd.py script and make this connection between hosts. Is there a way to do this on mininet-WiFi between stations?

**Comment by ramonfontes** [comment]
As you can see in https://github.com/mininet/mininet/blob/master/examples/sshd.py#L40 a node in root NS is created. Of course, you can do the same with stations.

**Comment by andredemori** [comment]
I thought there was a way to ssh through the terminal without changing the code, like something already native. But it looks like I'm going to have to implement sshd in my code. Correct? Thanks.

**Comment by ramonfontes** [comment]
No, that is not correct. As I said, a node in NS has been created and you can do the same with stations.

**Comment by andredemori** [comment]
For example:

I have the follow network:

```
net = Mininet_wifi()

    info("*** Creating nodes\n")
    h1 = net.addHost('h1', mac='00:00:00:00:00:01', ip='10.0.0.1/8')
    sta1 = net.addStation('sta1', mac='00:00:00:00:00:02', ip='10.0.0.2/8')
    sta2 = net.addStation('sta2', mac='00:00:00:00:00:03', ip='10.0.0.3/8')
    ap1 = net.addAccessPoint('ap1', ssid='new-ssid', mode='g', channel='1',
                             position='45,40,0')
    c1 = net.addController('c1')
```

In addition to providing ssh access to sta1 and sta2 I need to do the follow:

```
argvopts = ' '.join(sys.argv[1:]) if len(sys.argv) > 1 else ('-D -o UseDNS=no -u0')
sshd(net, opts=argvopts)
```.
So, I need to implement connectToRootNS and sshd in my code.

Sorry for the difficulty in understanding this.
