### ISSUE TITLE
Some stations get Connected to AP but others do not

### ISSUE THREAD

**Issue by alamfaisal654** [intrig-unicamp/mininet-wifi#446]
I have a topology with one AP and 14 stations . All the stations are spawned in a loop and are set at the same position. Since they are at same position, they are all equidistant from AP.  All ststaions get connected tp AP with SSID as new-ssid. The observation is that  even after waiting for 10 minutes some stations get connected to access point and can ping other connected APs but some stations do not at all get connected.  I need multiple stations connected with single AP for my experiments . Code is attached
[serverwifi_example.py.txt](https://github.com/intrig-unicamp/mininet-wifi/files/9187488/serverwifi_example.py.txt)

Troubleshooting Steps:
1. Tried running with debug and assess the logs, but nothing peculiar was found
2. Tried stopping the network Manager. No change was observed.
3. Keeping less number of stations , close to to 4 or 5 stations makes them all connected. But this is not what is intended. I want higher number of stations connected.
4. Used commands _"iw dev sta1-wlan0 link_ " or equivalent to check if the stations are connected with APs or not.

Debug Logs are also attached
[DebugLogs.txt](https://github.com/intrig-unicamp/mininet-wifi/files/9187518/DebugLogs.txt)
.

**Comment by ramonfontes** [comment]
User is using containernet. This is not a mn-wifi issue at all.
