### ISSUE TITLE
Exception: Error creating interface pair (ap1-eth2,ap2-eth2): RTNETLINK answers: File exists

### ISSUE THREAD

**Issue by andredemori** [intrig-unicamp/mininet-wifi#448]
The following error started to appear after running handover.py

`Exception: Error creating interface pair (ap1-eth2,ap2-eth2): RTNETLINK answers: File exists
`
I've already tried to restart networkmanager, but it didn't work.

handover.py ran perfectly, however, after it was closed it started giving this error and handover.py doesn't run anymore.

**Comment by ramonfontes** [comment]
`sudo mn -c` solves the issue
