### ISSUE TITLE
How to connect a host to an AP and Switch

### ISSUE THREAD

**Issue by andredemori** [intrig-unicamp/mininet-wifi#449]
I'm trying to build a topology where the host has a link with an AP and another link with a switch, as shown in the image below.

![Captura de tela de 2022-08-19 15-49-54](https://user-images.githubusercontent.com/10273317/185687203-f0c47c42-31af-48ef-9c54-d9bc3a91320b.png)

Do you have any example script on how to create two interfaces on the host and connect it on two elements (intf1 - AP1) (intf2, Switch)?

**Comment by ramonfontes** [comment]
```
addLink(h1, ap1)
addLink(h1, s1)
```

**Comment by andredemori** [comment]
I'm trying to build this topology:

![Captura de tela de 2022-08-19 15-56-04](https://user-images.githubusercontent.com/10273317/185688368-8f09446b-ae1e-4efd-842c-db5bc0a6277f.png)

But for some reason h1 can't communicate with h2 and I thought it was because it wasn't linking properly.
```

info("*** Creating links\n")
    net.addLink(h1, ap1)
    net.addLink(h2, ap2)
    net.addLink(h1, s1)
    net.addLink(h2, s1)
```

In this case, all stations that are reached by the AP can talk to each other and can also talk to the host connected to the respective AP, but h1 and h2 cannot talk to each other.

Do you have any suggestions?

**Comment by ramonfontes** [comment]
Please make sure this is an issue before creating a new one. Also, please provide as much information as you can when you describe the issue.

**Comment by andredemori** [comment]
I understood. I think I've now found an example in multipleWlan.py on how to create an IP address for each interface.

info("*** Addressing...\n")
     sta1.setIP('192.168.10.1/24', intf="sta1-wlan1")
     sta2.setIP('192.168.10.2/24', intf="sta2-wlan0")

In this case it seems that I should do the same for h1 and h2

**Comment by ramonfontes** [comment]
I see no relationship between the example above and your network topology :(

**Comment by andredemori** [comment]
In my code I set the IP address as follows:

h1 = net.addHost('h1', mac='00:00:00:00:00:08', ip='10.0.0.6/8')
h2 = net.addHost('h2', mac='00:00:00:00:00:09', ip='10.0.0.7/8')

**Comment by ramonfontes** [comment]
Can you please answer my first question?? what is the ip addr of the second interface of the nodes???

**Comment by andredemori** [comment]
xterm h1 ifconfig output:

![Captura de tela de 2022-08-19 16-23-50](https://user-images.githubusercontent.com/10273317/185692379-de75ea33-6eea-440c-8f6c-410919ec5ee0.png)

**Comment by andredemori** [comment]
Do you recommend any forum to ask questions about mininet-wifi implementation?

![Captura de tela de 2022-08-19 17-18-58](https://user-images.githubusercontent.com/10273317/185700758-b670635b-20c6-414a-8cfa-6e96d1f05f63.png)

I tried another alternative following the book creating two wlans for a station, however the sta1 station can only talk to the stations connected to AP1, although iwconfig confirms that it is connected to both APs. 

I'm really confused about how to use two interfaces on both hosts and stations.

**Comment by ramonfontes** [comment]
Please do not mix network topologies in the same issue :(
