### ISSUE TITLE
Moving nodes

### ISSUE THREAD

**Issue by gauravbatra8** [intrig-unicamp/mininet-wifi#45]
Hello Ramon . I have a doubt, I want to simulate software defined wireless mesh network using mininet-wifi. I see some examples where stations are moving and access points are fixed. In my project , I want to move my nodes which are simple openvswitch/access points. There will be no stations. Is it possible? 
Then I want to use some routing protocol in the controller to optimize path.

Can I do that with mininet-wifi ?

**Comment by gauravbatra8** [comment]
![20170206_132525](https://cloud.githubusercontent.com/assets/25457611/22647090/db7c37ae-ec6f-11e6-846d-9a432f9244a0.jpg)

this will be the topology.

**Comment by ramonfontes** [comment]
Hello. Yes, I think so. I've never try it before though. Please let me know if you face any trouble anyway.

**Comment by gauravbatra8** [comment]
Alright. I'm trying.

**Comment by gauravbatra8** [comment]
Hello Ramon,
I am working with mininet-wifi python script. I see if I use "addLink" to
connect two access points, it creates ethernet link. But I want to use
wireless link between two access points.
How should I do that?


Regards
Gaurav

**Comment by ramonfontes** [comment]
You can do this manually by using iw if your hardware supports wds -
https://wireless.wiki.kernel.org/en/users/documentation/iw. This feature is
not natively supported yet.

2017-02-07 5:21 GMT-03:00 MastERSStudent <notifications@github.com>:
