### ISSUE TITLE
Host unreachable when pinging cars in vanet-sudmo.py!!

### ISSUE THREAD

**Issue by elhachi** [intrig-unicamp/mininet-wifi#450]
Hello,

I'm using the vanet-sumo.py script to generate a vanet environment. I tried to make a ping between car2 and car3, where each of them has two different interfaces, as follows:

$ sudo python vanet-sumo.py
mininet-wifi >> Xterm car2 car3
car2 >> ping 192.168.0.3
ping success.
car2 >> ping 192.168.1.3 
ping failed with the destination host unreachable.
I don't know why it failed even when the routing table was set:
car2 >> route -n
Kernel IP routing table 
Destination   Gateway         Genmask       Flags   Metric     Ref    Use    Iface
192.168.0.0    0.0.0.0      255.255.255.0      U          0             0        0       car2-wlan0  
192.168.1.0    0.0.0.0      255.255.255.0      U          0             0        0       car2-wlan1

Best regards.

**Comment by ramonfontes** [comment]
This is not an issue at all and we've also extensively discussed issues about vehicular networks here and also on the mailing list. Please search related topics and consider using the mailing list for questions like that.

And most importantly: if you are going to open an issue, you need to provide enough technical details and comment on any troubleshooting attempts you have tried.
