### ISSUE TITLE
‘/sys/kernel/debug/ieee80211’: No such file or directory

### ISSUE THREAD

**Issue by panos-ece** [intrig-unicamp/mininet-wifi#451]
Hello,
I came up with the same error as the title, but in my case the modprobe of both mac80211 and mac80211_hwsim works.
This is the error that i get:

```
mn --wifi --mac --arp --ap p4ap --client-isolation
*** Adding stations:
sta1 sta2 
*** Adding access points:
ap1 
*** Configuring wifi nodes...
find: '/sys/kernel/debug/ieee80211': No such file or directory
find: '/sys/kernel/debug/ieee80211': No such file or directory
find: '/sys/kernel/debug/ieee80211': No such file or directory
find: '/sys/kernel/debug/ieee80211': No such file or directory
Warning! Error when loading mac80211_hwsim. Please run sudo 'mn -c' before running your code.
Further information available at /tmp/mn-wifi-mac80211_hwsim.log.

```
Any suggestions?
I use ubuntu 18.04 with kernel version 5.15.0-46-generic.

_Originally posted by @panos-ece in https://github.com/intrig-unicamp/mininet-wifi/issues/421#issuecomment-1239726553_

**Comment by ramonfontes** [comment]
This seems that you don't have all the mac80211 stack in your kernel. I have never seen this before.

**Comment by ramonfontes** [comment]
Closing due to no new interactions.
