### ISSUE TITLE
MAC address of Access point

### ISSUE THREAD

**Issue by CITIZENDOT** [intrig-unicamp/mininet-wifi#458]
I want to implement the de-authentication attack with mininet-wifi. I'm trying to get the MAC address of the gateway node. I created a simple topology with `sudo mn --wifi --mode=g --channel=6`. Topology contains Two hosts `sta1`, `sta2` and one access point `ap1`.

![image](https://user-images.githubusercontent.com/52322531/194750869-16e0b280-9cf8-4aa6-bbf4-480edd7a2e50.png)

I'm thinking `ap1` is the gateway here (Correct me, If I'm wrong). Hence I'm trying to find its MAC address (but it's empty here).
In the de-authentication attack, Which address do I have to set as the gateway MAC? Thank you

**Comment by ramonfontes** [comment]
Cannot you use `ap1 ip addr` or `ap1 ifconfig` ??

**Comment by CITIZENDOT** [comment]
![image](https://user-images.githubusercontent.com/52322531/194752440-72cbbb80-d5af-4c7f-8796-c302e7482add.png)
Thank you, So `02:00:00:00:02:00` is the gateway MAC right?
