### ISSUE TITLE
802.11 standards support

### ISSUE THREAD

**Issue by francozappa** [intrig-unicamp/mininet-wifi#46]
Hi !

I was wondering how you are supporting different 802.11 standards and amendments such as 802.11b or 802.11n. For example, is it possible to emulate a MIMO system?

Thanks

**Comment by ramonfontes** [comment]
Hi!

Hostapd is responsible for virtualizing APs in Mininet-WiFi. Further
information about 802.11 standards are available at
https://wiki.gentoo.org/wiki/Hostapd. Then, we use TC for controlling
the communications at high speeds (and also at low speeds) -
http://tldp.org/HOWTO/Traffic-Control-HOWTO/intro.html. BTW, everything
that is supported by Hostapd and the soft driver mac80211_hwsim (
https://wireless.wiki.kernel.org/en/users/drivers/mac80211_hwsim) is also
supported by Mininet-WiFi.

Regards,
Ramon

2017-02-14 7:50 GMT-03:00 Daniele Antonioli <notifications@github.com>:
