### ISSUE TITLE
Wi-Fi throughput test 

### ISSUE THREAD

**Issue by lhz-1236** [intrig-unicamp/mininet-wifi#461]
When using wifi communication, is the host using half-duplex mode? When I tested, the same topology environment, just replaced the wired connection with the wireless connection, and then tested the bandwidth, and there was no difference in the throughput of the two. But in fact, the throughput of wireless should be lower than that of wired

**Comment by ramonfontes** [comment]
No, the host is not using half duplex. Please consider using the mailing list for questions like this. This is not an issue at all.
