### ISSUE TITLE
Battery.py error

### ISSUE THREAD

**Issue by wassim-ba** [intrig-unicamp/mininet-wifi#464]
Hello ! 

I got an error concerning the example energy topology.

`*** Creating nodes
*** Configuring nodes
Traceback (most recent call last):
  File "battery.py", line 37, in <module>
    topology()
  File "battery.py", line 23, in topology
    net.configureNodes()
AttributeError: 'Mininet_wifi' object has no attribute 'configureNodes'
`

My Mininet WiFi is well installed, and the energy.py script seems to be execute.

Thanks

**Comment by wassim-ba** [comment]
I found the error, I just changed the method to "net.configureWifiNodes()" because my VM is not up to date. However, I always have an error on the execution of the sensor1.wintfs[0].consumption command which is not recognized.

**Comment by ramonfontes** [comment]
`git pull` and `sudo make install` fix the issue.
