### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: '/home/jzy/mininet-wifi/examples/uav/data/dr1.txt'

### ISSUE THREAD

**Issue by zhiyunjiang** [intrig-unicamp/mininet-wifi#468]
Hello,
I ran the UAV example with the error described in the title. What is the reason? 
The missing file should be created manually?
Thank you.

**Comment by Sue147** [comment]
Hello!
I also encountered this problem. 
What's more, when I start the UAV network, I can't even make three drones ping each other.
I don't know if it's related to the missing file"./mininet-wifi/examples/uav/data/dr1.txt".
Looking forward to your response!
Thanks.
