### ISSUE TITLE
How I can connect one station to two different ap in mininet wifi?

### ISSUE THREAD

**Issue by Forceeeeeee** [intrig-unicamp/mininet-wifi#469]
Hello I have two ap in mininet and 3 stations, one of them should connect to both aps while the others connect just only one. Connection to just only one ap is no problem, however, station which should connect to both is hard to do. Can I get help? I used wlans=2 in station parameters to have 2 interfaces and used addLink(ap1, sta2) and addLink(ap2, sta2) at the same time but it did not work, I can't copy past from VM to here the script for some reason, it is another problem, but for now could you please let me know how I can connect to two ap at the same time.

**Comment by ramonfontes** [comment]
https://mn-wifi.readthedocs.io/en/latest/options.html#connecting-stations-to-multiple-aps

**Comment by Forceeeeeee** [comment]
@ramonfontes Thank you for your reply really, however, I added it does not work.
![Screenshot 2022-11-11 145306](https://user-images.githubusercontent.com/117982804/201325755-6823f917-f721-484d-9fb0-34c440cde372.jpg)
here is the script you can see the addLink parts.

and prove
![image](https://user-images.githubusercontent.com/117982804/201325943-d1be5463-8c84-4187-9947-63972ed7637f.png)

**Comment by ramonfontes** [comment]
@Forceeeeeee, I think there are some computer networking basics missing here...

Firstly, what is the ip address of the second interface of sta2??
Did you check the association at L2??


Please make sure you have a correct setup.

**Comment by Forceeeeeee** [comment]
I tried to use setIP for that like this:
![image](https://user-images.githubusercontent.com/117982804/201327457-8191f2af-1f7a-47fc-95b3-96daf625e19b.png)
but I got these errors
![image](https://user-images.githubusercontent.com/117982804/201327519-81cddce7-6763-4be5-b6ab-1f9ceebb2160.png)

I am sorry, I am just a beginner can I cannot find any info properly.

**Comment by ramonfontes** [comment]
`setIP()` must be added after `net.build()`

**Comment by Forceeeeeee** [comment]
![image](https://user-images.githubusercontent.com/117982804/201328349-e2994004-0db3-4d29-aa8e-bbcc1475f36f.png)

now I cant ping both of them.
![image](https://user-images.githubusercontent.com/117982804/201328529-b64bee45-0207-4ee5-afec-74e3fb610232.png)

**Comment by ramonfontes** [comment]
Dear @Forceeeeeee,

This is not a chat. Please make sure you have a correct setup and consider following computer networking troubleshooting steps.

**Comment by Forceeeeeee** [comment]
Okay, I am sorry.
