### ISSUE TITLE
issue when i install mininet-wifi

### ISSUE THREAD

**Issue by Ju5ticeGit** [intrig-unicamp/mininet-wifi#471]
![image](https://user-images.githubusercontent.com/38004564/202910035-eedfb5c3-ba45-439c-bc4e-36eb824d2eb4.png)
it give some issues, and ask me “skip this patch?” ,and i just enter
but when i use "sudo mn --wifi",i found mininet-wifi have not installed
how can i slove that?

**Comment by Ju5ticeGit** [comment]
i just use u-disk copy file to my ubuntu vm,because i can't connet github to download directly in my vm，but it's shouldn't be core of this issue

**Comment by ramonfontes** [comment]
If you are new to git I strongly suggest you to remove mininet-wifi dir and do a new git clone.

**Comment by Ju5ticeGit** [comment]
well,the most confused thing is that i can ping github.com but i can't use git clone command.   :-(
![image](https://user-images.githubusercontent.com/38004564/202959917-d250a630-180c-4f4c-a8ed-8df53f039218.png)

**Comment by Ju5ticeGit** [comment]
> If you are new to git I strongly suggest you to remove mininet-wifi dir and do a new git clone.

well,the most confused thing is that i can ping github.com but i can't use git clone command. :-(
![image](https://user-images.githubusercontent.com/38004564/202960058-0a4a2fd4-36df-49c4-b785-67b7f0f1765b.png)

**Comment by Ju5ticeGit** [comment]
maybe there are some config error in my vm

**Comment by Ju5ticeGit** [comment]
oh,i got it,"git config --global url."https://".insteadOf git://" is useful
