### ISSUE TITLE
mininet wifi installation

### ISSUE THREAD

**Issue by Sai-Vivek-Pidaparthi** [intrig-unicamp/mininet-wifi#472]
after installing mininet wifi and using the command sudo mn --wifi, it says the attribute error: type object 'hostapdconfig' has no attribute 'write_mac'. what needs to be done?

**Comment by ramonfontes** [comment]
Fixed with https://github.com/intrig-unicamp/mininet-wifi/commit/02037093cae715dc38b482020d892958a8c7d70f. Try a `git pull` and then run `sudo make install`

**Comment by Sai-Vivek-Pidaparthi** [comment]
Thank you!! That worked.
