### ISSUE TITLE
mininet wifi not working with onos

### ISSUE THREAD

**Issue by Sai-Vivek-Pidaparthi** [intrig-unicamp/mininet-wifi#473]
this might be a bit out of the topic here but it involves mininet wifi. 
For my project I have to use mininet wifi with ONOS controller. the mininet wifi topology is being created and connected to the onos controller but the controller is not showing the AP or any other devices.

I am getting an error saying that "ofparse error: worng length: expected 40(40), got =32", even If i use the command "sudo mn --wifi --controller remote  --switch=ovs,protocols=OpenFlow13". 

I got the same error with mininet also but when i use openflow=13 in sudo mn command it worked. but it is not working for mininet wifi.

what shall be done?

**Comment by ramonfontes** [comment]
Can you please try `sudo mn --wifi --controller remote --ap=ovs,protocols=OpenFlow13`?

**Comment by Sai-Vivek-Pidaparthi** [comment]
Awesome !! That worked. Thank you so much.
