### ISSUE TITLE
Connecting Mininet-wifi with onos controller

### ISSUE THREAD

**Issue by Sai-Vivek-Pidaparthi** [intrig-unicamp/mininet-wifi#474]
I created a topology in miniedit with 2-AP's, 2-STA's, 1-controller and 1 switch. added the IP address of my ONOS controller in the controller properties in miniedit. my controller is on and working but when I start the topology using sudo python3 example.py (example.py is my level 2 script), I am getting an error asking me to "shutdown the controller which is running on 6653" which is my onos controller!!. So, how do I connect my topology to the controller? 

I have another doubt, how do I create a situation where a station should move from one place to another place like in real world environment in miniedit?

**Comment by ramonfontes** [comment]
Is the controller a `RemoteController`??

Like most of the GUIs miniedit is very limited. I sugest you to program your code by hands if you want to have full control of your code.

**Comment by Sai-Vivek-Pidaparthi** [comment]
1. I think the onos controller is a remote controller, how do I add the Openflow13 and --ap=ovs  in "sudo mn --wifi --ap=ovs,protocol=OpenFlow13" to the code of the topology? 

2. When I enter the sta1 iw dev sta1-wlano scan command it is taking around 20 seconds to show the output. is there any way to speed up this?

**Comment by Sai-Vivek-Pidaparthi** [comment]
I figured out the OpenFlow13 part, but can you tell me is there any way to speed up the scan process?

**Comment by ramonfontes** [comment]
I suggest checking the iw doc. Scanning is not managed by mn-wifi.
