### ISSUE TITLE
Some doubts about ‘delay’ and 'latency'.

### ISSUE THREAD

**Issue by zhiyunjiang** [intrig-unicamp/mininet-wifi#475]
1、The ‘delay’ parameter of the link is the transmission delay. Is the propagation delay calculated by the distance between nodes? 
2、If so, I change the distance between two nodes. Why does the ping delay not change? 
3、Can queuing delay be counted? 
4、The 'latency' refers to the maximum queuing delay?

Looking forward to your help. Thank you.

**Comment by ramonfontes** [comment]
1. Yes.
2. Are you using tc or wmediumd? Wmediumd also relies on the minstrel algorithm. I suggest you to go through it. You can also refer to the tc doc.
3. Is there any way to do so on Linux systems? You can try replicating the same.
4. The same as 2.

**Comment by ramonfontes** [comment]
Closing due to no new interactions.
