### ISSUE TITLE
Best way to get the rssi values.

### ISSUE THREAD

**Issue by Sai-Vivek-Pidaparthi** [intrig-unicamp/mininet-wifi#476]
I need to get the rssi values of every ap in range every 5 seconds. 
1. I tried the iw dev scan command but its taking too long to get the rssi values, 
2. also tried the py sta1.wintfs[0].rssi but it is showing only one instance
3. tried the telemetry thing too, but when i am using net.telemtetry, I cant use net.plotgraph. is there any way to use both?

actually I want to get the RSSI values every 3 seconds and send those to the controller so that the controller can make decisions.

**Comment by ramonfontes** [comment]
Why don't you capture beacons through the monitor interface??

**Comment by Sai-Vivek-Pidaparthi** [comment]
I added two interfaces while setting up the topology and both of them are in managed mode. the sta1-wlan0 is associated to an AP while I try to change the sta1-wlan0 interface to monitor mode it says, device or resource busy.

**Comment by Sai-Vivek-Pidaparthi** [comment]
I created two interfaces while setting up the topology, sta1-wlan0 and sta1-wlan1, wlan0 is associated to an AP, while wlan1 is in monitor mode, when I enter iw sta1-wlan1 scan command it says operation not permitted.

**Comment by ramonfontes** [comment]
Sorry?? Have you been using iw??

**Comment by Sai-Vivek-Pidaparthi** [comment]
while sta1-wlan0 is associated to an ap,  if I set it in monitor mode, It will be in passive mode and disconnects from the ap. so I added two interfaces one for association with ap and another one to be in monitor mode. 
in both the cases if enter "iw interface scan", I am getting the same error as operation not supported.

**Comment by ramonfontes** [comment]
Dear,

I'm not talking about setting interface to monitor mode. I'm talking about creating a virtual interface in monitor mode. I suggest you reading the iw doc. 

I'm not talking about using wireshark neither. I'd suggest you to use scapy. 

Well, this is a well-known topic in the community. If I were you I'd take some time for reading.

**Comment by Sai-Vivek-Pidaparthi** [comment]
Hey thanks for pointing towards the right direction.

I created an interface 'sta1-wlan0', and put it to monitor mode and wrote a program using scapy to sniff the packets and filtered the rssi values. this part is a success. 

but if I create two interfaces and put one of them in monitor mode then I cant see any broadcast frames in wireshark. becuase I need one interface to monitor so that I can capture beacon frames and another one as a managed interface so that it can get associated to an access point.

**Comment by ramonfontes** [comment]
> Note: I dont want to capture the beacon frames in wireshark.
> but if I create two interfaces and put one of them in monitor mode then I cant see any broadcast frames in wireshark. 

I'm getting  confused..

> becuase I need one interface to monitor so that I can capture beacon frames and another one as a managed interface so that it can get associated to an access point.

More confused...

**Comment by Sai-Vivek-Pidaparthi** [comment]
no problem, I figured it out. thanks for helping by the way. you can close this issue.
