### ISSUE TITLE
Matplotlib issue

### ISSUE THREAD

**Issue by nounou23** [intrig-unicamp/mininet-wifi#477]
hi,
First of all thanks for your efforts.
I have changed the map used in the example VANET-SUMO,sumo-gui shows the new map and the cars but the matplotlib doesn't show cars like in the main example(new-york). I tried to ping from terminal but it hows "host unreachable" 
anyone can tell me what is the probleme please ?

**Comment by ramonfontes** [comment]
> sumo-gui shows the new map and the cars but the matplotlib doesn't show cars like in the main example(new-york)

Are the coordinates the same? Unfortunately there is not information about it.

> I tried to ping from terminal but it hows "host unreachable"

It's really hard to help with so poor information. Also, I think this is out-of-topic question if we consider the issue title.

Please provide consistent information about issues.

**Comment by nounou23** [comment]
> > sumo-gui shows the new map and the cars but the matplotlib doesn't show cars like in the main example(new-york)
> 
> Are the coordinates the same? Unfortunately there is not information about it.
I did'nt checked,how can i verify this? But i swiped all the area to check any changes 
> 
> > I tried to ping from terminal but it hows "host unreachable"
> 
> It's really hard to help with so poor information. Also, I think this is out-of-topic question if we consider the issue title.
> 
> Please provide consistent information about issues.
> 
May be the title is bad written but the real issue is about "vanet-sumo" example
