### ISSUE TITLE
Node Connection & WifiDirect Related Question

### ISSUE THREAD

**Issue by struggle47** [intrig-unicamp/mininet-wifi#48]
Hi,

I've just started doing a WifiDirect project in mininet using this code as a basis. First of all, thanks for providing the code!
Now, I would like to connect sta1 and sta2 using WifiDirect. Could you give me a guidance how to do that? Can I do it automatically using python code?
WifiDirect related questions:
I can set the range whatever I want, but wifiDirect range is about 60 meters. Thus, when I set my wifiDirect range I should be within this range, I guess. Am I right?

**Comment by ramonfontes** [comment]
Hi,

Did you change wpa_supplicant in order to support wifi-direct according the
instructions of the manual of Mininet-WiFi?

**Comment by struggle47** [comment]
Hi,

As far as I remember I did, but I'll double check again. In the code, there is net.wifiDirect(sta1) command. The code worked without any error or warning. This means wifiDirect starts without any problem, doesn't it? That's why I assumed I did what you told in section 1.8.1. Nevertheless, I'll double check it. Thank you for your quick response.

**Comment by ramonfontes** [comment]
Actually it doesn't check if there are problems with wifi-direct or if
wpa_supplicant is correctly configured.


Sent from my android

On 21 Feb 2017 18:39, "struggle47" <notifications@github.com> wrote:

Hi,

As far as I remember I did, but I'll double check again. In the code, there
is net.wifiDirect(sta1) command. The code worked without any error or
warning. This means wifiDirect starts without any problem, doesn't it?
That's why I assumed I did what you told in section 1.8.1. Nevertheless,
I'll double check it. Thank you for your quick response.

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/intrig-unicamp/mininet-wifi/issues/48#issuecomment-281489574>,
or mute the thread

**Comment by struggle47** [comment]
Hi,

Yes, I've just changed the wpa_supplicant once again based on the instructions given in section 1.8.1 in the manual. After this point, I would be greatly appreciated if you could give me a guidance to connect two nodes (sta1 and sta2) using WifiDirect.

**Comment by ramonfontes** [comment]
Please search for *define P2P_MGMT_DEVICE_PREFIX          "p2p-dev-" *and
change it to *define P2P_MGMT_DEVICE_PREFIX          "p2p-" *in
p2p_supplicant.c and then compile wpa_supplicant one more time. Then, let
me know if it works for you.

2017-02-21 21:05 GMT-03:00 struggle47 <notifications@github.com>:

**Comment by struggle47** [comment]
Great! Thank you very much for your guidance and fast response! I'll do it right away. Thank you!

**Comment by ramonfontes** [comment]
I just updated the code and manual changes in wpa_supplicant is not
required anymore (there was a problem with wpa and I think that wpa and
wifidirect can work together right now). If you want to update
wpa_supplicant with changes towards wifidirect, please clone mininet-wifi
and run util/install.sh -W. Then, you should be able to run wpa_cli.

**Comment by struggle47** [comment]
Hi,

Thank you very much for your responses and updates. I did what you had told me to do before. I was preparing my questions. I also saw your latest update and I did what you told me to do and both worked perfectly! (p2p_find and p2p_stop_find works; whereas p2p_group_add doesn't fail automatically)Thank you for caring!
However, couple of more questions appeared after this point:
1) When I am in the interactive mode (let's say after I write "sta1 wpa_cli"), the CLI says that my selected interface is "p2p-sta2-wlan0". Even though I specified sta1, it looks like I am in sta2. Is there anything that I misunderstand here?
1.a) Also when I type "sta2 ifconfig -a", the interfaces I see are "lo" and "sta2-wlan0". There isn't interface named "p2p-sta2-wlan0" for sta2. I am not sure if this is a problem or I misunderstand something. 
2) I noticed an issue related to "p2p_group_add" command. p2p_group_add command simply do not create a wifidirect group. Before your update, p2p_group_add command directly gave FAIL message. Now, I do not get FAIL message, but the command doesn't create a group either. CLI displays "P2P-GROUP-STARTED", but when I use command "status" the interface seems to be "DISCONNECTED". It should be "P2P-GO" as far as I know.
3) After I get into interactive mode, when I use "status" command the CLI displays p2p_device_address (I believe this refers to mac address), but it is different than the one displayed without getting into interactive mode. For example, before getting into interactive mode the mac address of sta1: 02:00:00:00:01:00, but in interactive mode p2p_device_address: 42:00:00:00:01:00. 

Sorry, the list is long! but I believe I can provide a good feedback and I would be really really appreciated if you could tell me ways to solve these problems I am having.

**Comment by ramonfontes** [comment]
2017-02-22 1:07 GMT-03:00 struggle47 <notifications@github.com>:

> Hi,
>
> Thank you very much for your responses and updates. I did what you had
> told me to do before. I was preparing my questions. I also saw your latest
> update and I did what you told me to do and both worked perfectly!
> (p2p_find and p2p_stop_find works; whereas p2p_group_add doesn't fail
> automatically)Thank you for caring!
> However, couple of more questions appeared after this point:
>
>    1. When I am in the interactive mode (let's say after I write "sta1
>    wpa_cli"), the CLI says that my selected interface is "p2p-sta2-wlan0".
>    Even though I specified sta1, it looks like I am in sta2. Is there anything
>    that I misunderstand here?
>    1.a) Also when I type "sta2 ifconfig -a", the interfaces I see are
>    "lo" and "sta2-wlan0". There isn't interface named "p2p-sta2-wlan0" for
>    sta2. I am not sure if this is a problem or I misunderstand something.
>
> I recommend you open "xterm sta1" and then run "wpa_cli -i sta1-wlan0"
(alternatively "sta1 wpa_cli -i sta1-wlan0").

>
>    1. I noticed an issue related to "p2p_group_add" command.
>    p2p_group_add command simply do not create a wifidirect group. Before your
>    update, p2p_group_add command directly gave FAIL message. Now, I do not get
>    FAIL message, but the command doesn't create a group either. CLI displays
>    "P2P-GROUP-STARTED", but when I use command "status" the interface seems to
>    be "DISCONNECTED". It should be "P2P-GO" as far as I know.
>
> This I presume you have to discover by yourself. I really don't know
wifidirect at all and I'll appreciate any help to automatize it.
Nevertheless perhaps it works with the correct interface.

>
>    1. After I get into interactive mode, when I use "status" command the
>    CLI displays p2p_device_address (I believe this refers to mac address), but
>    it is different than the one displayed without getting into interactive
>    mode. For example, before getting into interactive mode the mac address of
>    sta1: 02:00:00:00:01:00, but in interactive mode p2p_device_address:
>    42:00:00:00:01:00.
>
> The same as before. ;)

>
>
> Sorry, the list is long! but I believe I can provide a good feedback and I
> would be really really appreciated if you could tell me ways to solve these
> problems I am having.
>
I help you and you help me. :) wifidirect is new for me. I've implemented
wifidirect just to satisfy user needs.
I really appreciate good feedback and tips for improvements.

**Comment by struggle47** [comment]
Hi,

Thank you very much for your response! Even a slightest clue helps me a lot since I am just in the beginning of the process. I'll go over what you've suggested and I'll get back to you as soon as I have some results. Thank you!

**Comment by struggle47** [comment]
Hi,

I guess I have a quick question, which will help me to understand what's going on. Compared to what I had before (mininet-wifi folder) mininet-wifi-master is a bit different. First of all, there isn't any wpa_supplicant folder or p2p_supplicant.c file within mininet-wifi-master. Where are they folder now? Aren't they needed? Did you just gather all the wpa_supplicant codes into one particular file?

**Comment by ramonfontes** [comment]
wpa_supplicant is now part of hostap dir (which is now a submodule).
Although there is nothing into hostap dir from master, the files will be
present into mininet-wifi/hostap after installing mininet-wifi.

2017-02-22 14:23 GMT-03:00 struggle47 <notifications@github.com>:

**Comment by struggle47** [comment]
Hi,

Sorry for bothering you, but I have another question about installation. I guess I could not install mininet using your latest version (mininet-wifi-master). Did you change install.sh file? When I run "util/install.sh -W" on CLI, I see that ".../mininet-wifi/hostap: No such file or directory". I am a bit confused in here. In mininet-wifi-master folder there is a folder named "hostap", but in the old version mininet-wifi there is "hostapd" folder. In install.sh file the code has lines like "pushd $MININET_DIR/mininet-wifi/hostap". I believe, I need to change this line to "pushd $MININET_DIR/mininet-wifi-master/hostap".

**Comment by ramonfontes** [comment]
Install.sh was changed in f11cefc44477280d50fa8cab55af61a89100fefb
<https://github.com/intrig-unicamp/mininet-wifi/commit/f11cefc44477280d50fa8cab55af61a89100fefb>
and
hostapd is retrieved from http://w1.fi/hostap.git - (
https://github.com/intrig-unicamp/mininet-wifi/blob/master/.gitmodules).

2017-02-22 15:36 GMT-03:00 struggle47 <notifications@github.com>:

**Comment by struggle47** [comment]
Hi,

It's been a while, but I solved my issues. Thank you for responding me quickly! To solve my issues, all I did was installing a VM and then installing mininet wifi again.

**Comment by ramonfontes** [comment]
Thanks!
