### ISSUE TITLE
unable to ping between stations

### ISSUE THREAD

**Issue by Sai-Vivek-Pidaparthi** [intrig-unicamp/mininet-wifi#481]
![image](https://user-images.githubusercontent.com/97266227/213811503-ae8289bc-e095-4dba-83d7-70a147baebf8.png)

Hi, 
I am unable to ping from sta1 to sta2 or from sta2 to sta1. 
sta1 ip - 10.0.0.1/8
sta2 ip - 10.0.0.2/8
the connected switch is a legacy switch. I tried troubleshooting, the ping is working from sta1 to ap1, ap1 to ap2 but not from ap2 to sta2. 
please refer to the above image.

**Comment by ramonfontes** [comment]
> the ping is working from sta1 to ap1, ap1 to ap2 but not from ap2

I think you don't know how OVS works. Isn't sta1 pinging to localhost?? Did you check the ip response?

I bet that sta1 isn't associated to ap1.

**Comment by Sai-Vivek-Pidaparthi** [comment]
you are right, I just observed in wireshark that the ping is happening from 127.0.0.1 to 127.0.0.1, but not from 10.0.0.1 to 10.0.0.2. I think sta1 is associated to ap1 because I can see that sta1 is associated to ap1 in the 'iw dev' command.

**Comment by ramonfontes** [comment]
What about sta2? This seems more a computer networking issue. Which troubleshooting steps did you try?

**Comment by Sai-Vivek-Pidaparthi** [comment]
sta1 is associated to ap1 and sta2 is associated to ap2.

for the trouble shooting steps, I did a ping from sta1 to ap1, ap1 to ap2, ap2 to sta2. 

sta1 to ap1 ( from 127.0.0.1 to 127.0.0.1)
ap1 to ap2 ( from 127.0.0.1 to 127.0.0.1)
ap2 to sta2 ( destination host unreachable)

I dont know why its pinging local host. 

note - I am not using a linux virtual machine, I installed linux on my hard drive. does this have anything to do with that?

**Comment by ramonfontes** [comment]
Is ap1 send packets to s1? What is s1 doing with the packet it receive?

**Comment by Sai-Vivek-Pidaparthi** [comment]
no, ap1 is not sending to s1.

**Comment by ramonfontes** [comment]
I suggest you to review your setup.

**Comment by Sai-Vivek-Pidaparthi** [comment]
Hey, I think it had some thing to do with linux on the hard drive thing, I tried the same thing on virtual box and its working fine. thanks for the help though. you can close the discussion now.

**Comment by Sai-Vivek-Pidaparthi** [comment]
https://mail.google.com/mail/u/0?ui=2&ik=a53189812f&attid=0.1&permmsgid=msg-a:r1280563895287252418&th=185d19add4c9ecd7&view=att&disp=safe&realattid=f_ld56hwxf0

this is the .py file generated from the miniedit.
please, can you take a look at this and tell me what is the problem?
