### ISSUE TITLE
plot3d throws error

### ISSUE THREAD

**Issue by scrappylabs** [intrig-unicamp/mininet-wifi#482]
sudo mn --wifi --topo=linear,4 --plot3d --position
mininet-wifi> py sta1.setPosition('100,100,100')

Expected Result:
sta1 moves to 100,100,100

Actual Result:
sta1 does not move to 100,100,100
Terminal Prints: 'Poly3DCollection' object has no attribute 'set_radius'

If I edit examples/mobility.py to plot 3D, it does not return any error and the expected output is shown in the figure:
########
if '-p' not in args:
        net.plotGraph(max_x=200, max_y=200, **max_z=500**)
########

p1, p2, p3, p4 = {}, {}, {}, {}
    if '-c' not in args:
        p1 = {'position': '40.0,30.0,**100.0**'}
        p2 = {'position': '40.0,40.0,0.0'}
        p3 = {'position': '31.0,10.0,**200.0**'}
        p4 = {'position': '55.0,31.0,0.0'}
    net.mobility(sta1, 'start', time=1, **p1)
    net.mobility(sta2, 'start', time=2, **p2)
    net.mobility(sta1, 'stop', time=12, **p3)
    net.mobility(sta2, 'stop', time=22, **p4)
    net.stopMobility(time=23)
##########

**Comment by ramonfontes** [comment]
I cannot confirm the issue. The command works.

Can you please confirm that you have an updated mn-wifi source code?

**Comment by scrappylabs** [comment]
Hi Ramon, for the SDN class I am teaching with your book we are using the latest VM image from the website.

**Comment by ramonfontes** [comment]
The command also works with our Pre-configured Virtual Machine. :/

**Comment by ramonfontes** [comment]
Ok. Let me check it out.

**Comment by scrappylabs** [comment]
It moves the station, but does not update the graphic. I get the same error when changing the range/transmit power using the py command at runtime. 

wifi@wifi-virtualbox:~$ pip3 show matplotlib
Name: matplotlib
Version: 3.1.2
Summary: Python plotting package
Home-page: https://matplotlib.org
Author: John D. Hunter, Michael Droettboom
Author-email: matplotlib-users@python.org
License: PSF
Location: /usr/lib/python3/dist-packages
Requires: 
Required-by: mininet-wifi

wifi@wifi-virtualbox:~$ python --version
Python 3.8.10

**Comment by scrappylabs** [comment]
It's defined in patches.py of matplotlib for the version of matplotlib

https://github.com/matplotlib/matplotlib/blob/v3.1.x/lib/matplotlib/patches.py

But I'm not sure how Poly3DCollection ties in with patches

**Comment by scrappylabs** [comment]
I used git pull from the mininet-wifi directory in the VM. I tried again, it gave the same error.

**Comment by ramonfontes** [comment]
Did you recompile the code with `sudo make install`?

**Comment by scrappylabs** [comment]
yes i did

**Comment by ramonfontes** [comment]
Well, the error seems to be fixed on my side.

**Comment by ramonfontes** [comment]
Closing due to no new interactions.
