### ISSUE TITLE
mininet -W install error

### ISSUE THREAD

**Issue by BLeach386** [intrig-unicamp/mininet-wifi#483]
the "hostap" folder may have some error
when install the mininet -W
it stop at"Cloning into '/home/user/Desktop/mininet-wifi/hostap'...'"

**Comment by ramonfontes** [comment]
This seems a connectivity issue. It's not a mn-wifi issue, definitively.

**Comment by BLeach386** [comment]
Hello

I find the 'hostap @ f184337' folder in the github (https://github.com/intrig-unicamp/mininet-wifi) cannot be opened and has an arrow pointing to the right

Will this cause the installation to fail?

**Comment by ramonfontes** [comment]
It's a git submodule! ;|

**Comment by BLeach386** [comment]
OK. Thank you very much.
