### ISSUE TITLE
Is it possible to automate sending data from sumo vehicles to RSUs in Mininet-WiFi ?

### ISSUE THREAD

**Issue by 14vv1A0516** [intrig-unicamp/mininet-wifi#484]
Hi Sir,

I implement and map sumo scenario in Mininet-WiFi with vehicles and RSUs. I want to write an authentication protocol i.e., RSU authenticates vehicles when they come into transmission range or coverage area of RSU. 

The auth protocol involve vehicle sending data(a few parameters like ID, password etc) to RSU and gets auth session token from RSU. This should work for all the vehicles automatically running in the scenario. Is it possible to simulate this in Mininet-WiFi ?

Thank you.

**Comment by ramonfontes** [comment]
> Is it possible to simulate this in Mininet-WiFi

Why not? Write your code and go ahead.

**Comment by 14vv1A0516** [comment]
How do I send user-defined data ? After building net with 2 stations, 1 RSU controlled by Ryu controller, I tried to use  **sta1.cmd('curl -X POST -d '{"address":"wefwfwef"}' http://10.13.2.193:8080/simpleswitch/hai/0000000000000001')** this. But it doesn't work. 

My use-case is as and when a mobile station enters the transmission range of an RSU, it should send some information to controller using some function call. How to do this ?

I tried with os.system () call also but it haven't worked.

**Comment by ramonfontes** [comment]
Try makeTerm() instead.

**Comment by 14vv1A0516** [comment]
A statement like this works **makeTerm(sta1, cmd = "bash -c 'curl -X PUT -d '{'My_ID':'13242', 'password':'m2386Ff#@'}' http://10.13.2.193:8080/simpleswitch/hai/0000000000000001;'")** . The station is basically sending message to controller. 
How do I capture the response in sta1 from controller ? 
Suppose, I have a some python file which needs to be run in sta1, how do I store it in sta1 and run it as and when sta1 is created from mininet-wifi program ?
This is the use-case I have to implement to authenticate sta1 with controller. Here, the sta1 initiates authentication process.

**Comment by 14vv1A0516** [comment]
I added these steps:

makeTerm (sta1, cmd =  "bash -c 'xterm;'")

makeTerm(sta1, cmd = "bash -c 'python3 samp.py;'")

The xterm console pops up for sta1 but I am not able to realize whether the python file is run or not. The python code  has a few print statements but I don't see them running on xterm terminal.
