### ISSUE TITLE
Station not establishing socket connection with AP during handover.

### ISSUE THREAD

**Issue by 14vv1A0516** [intrig-unicamp/mininet-wifi#490]
Sir,

I am having problem with handover of mobile stations between APs. I have a simple network scenario with 2 mobile stations and 2 APs. 

1) When a station moves into range of AP 1, it establishes a TCP socket connection with AP1 and sends some data.

2) When a station moves from AP1 to range of AP 2, it should establish a TCP socket connection with AP2 and exchange some data.

Step 1 works fine but step 2 always fails. During handover, association happens but socket connection is not established. I am not using any controller in this scenario. All the nodes are in same network i.e., 10.x.x.x/255 subnet. 

IP of sta1: 10.0.0.10/255
IP of sta2: 10.0.0.20/255

IP of AP1: 10.0.0.100/255
IP of AP2: 10.0.0.200/255

The simple codes are in zip file. Can you please help me where I am going wrong.

Please run the file **test_vanet_cars.py**
[Handover Test files.zip](https://github.com/intrig-unicamp/mininet-wifi/files/11166944/Handover.Test.files.zip)
  in **mininet_wifi/examples** directory.

Thank you.

**Comment by ramonfontes** [comment]
What do you can tell me about the flow table?

**Comment by 14vv1A0516** [comment]
Sir, I don't see any flow rules in both APs . 
![image](https://user-images.githubusercontent.com/18321698/230367136-4185b02f-7670-4d77-b10b-3605f6ce6321.png)

Station is associated with AP2 but ping says not reachable.

**Comment by ramonfontes** [comment]
Well, I think you have found the issue.

**Comment by 14vv1A0516** [comment]
1) My doubt is there is no controller to write rules. Is there mininet reference controller running background ? 

2) If there have to be flow rules in APs, AP1 too does not have any rules. How are stations pinging to AP1 but not AP2 ?

3) Now, what should I change in code ? Do I have to manually write flow rules in AP2 ? Is there an example working code for this kind of handover scenario ?

Please help me Sir.

**Comment by ramonfontes** [comment]
Please provide a simple code so that we can reproduce the issue you have mentioned.

**Comment by 14vv1A0516** [comment]
Sir, the sample code is in zip file I uploaded in 1st comment. When you run test_vanet_cars.py, connection establishes with first AP. During handover, socket connection fails. It is very simple code sir. If you need more simplified code, I can write sir.

**Comment by ramonfontes** [comment]
You have attached multiple codes. Please provide a simple code with reproducibility steps.

**Comment by 14vv1A0516** [comment]
Please find the simple code. In this code, we have only 1 station and 2 APs. When station in AP1 region, ping between station and AP1 works. When station moves to AP2, ping to AP2 does not work. However, association happens between station and AP2 during handover. 
[Handover_test.zip](https://github.com/intrig-unicamp/mininet-wifi/files/11176586/Handover_test.zip)

**Comment by ramonfontes** [comment]
Clearly there is a problem related to the ARP table entries. If you are working with OVS as UserAP, all network interfaces of APs will be running in root NS - you can easily check with "ifconfig/ip link". This means that sta1 can also ping ap2 when connected to ap1.

The scenario you want to achieve is only possible with Bofuss and/or [stations working as APs](https://github.com/intrig-unicamp/mininet-wifi/blob/master/examples/sta_ap_mode.py).

**Comment by 14vv1A0516** [comment]
Sorry sir for late reply. The code is working fine  but I have one more doubt. As soon as association happens with AP1 in sta_ap_mode.py, sta ping ap1 does not work. It takes some time and then ping happens. Even though station and AP1 are in same network, it is expected that station should ping AP1 immediately after association, right ? Please clear my doubt sir.
