### ISSUE TITLE
sta1 can ping ap1 but not the other way around

### ISSUE THREAD

**Issue by ldahal** [intrig-unicamp/mininet-wifi#493]
I have been trying to create a mobility model where all stations can easily connect with any nearby aps. Only selected stations can ping to each other but not any stations could ping with any stations.  ap1 ping sta1 or any ap ping sta is not working. However, sta1 ping ap1 works. Wondering what I am missing . Here is my full code 

#!/usr/bin/env python

'Importing Library'
import sys
from mininet.log import setLogLevel, info
from mn_wifi.cli import CLI
from mn_wifi.net import Mininet_wifi

def topology(args):
    "Create a network."
    net = Mininet_wifi()

    info("*** Creating nodes\n")
    sta1 = net.addStation('sta1', mac='00:00:00:00:00:02', ip='10.0.0.2/8',
                   min_x=0, max_x=220, min_y=00, max_y=120, min_v=5, max_v=10, range=60, txpower=30)
    sta2 = net.addStation('sta2', mac='00:00:00:00:00:03', ip='10.0.0.3/8',
                   min_x=0, max_x=220, min_y=0, max_y=120, min_v=5, max_v=20, range=60, txpower=30)
    
    sta3 = net.addStation('sta3', mac='00:00:00:00:00:04', ip='10.0.0.4/8',
                   min_x=0, max_x=220, min_y=00, max_y=120, min_v=5, max_v=10, range=60, txpower=30)
    sta4 = net.addStation('sta4', mac='00:00:00:00:00:05', ip='10.0.0.5/8',
   
                  
    
    ap1 = net.addAccessPoint('ap1', ssid='new-ssid', mode='g', channel='1',
                                 failMode="continue", position='60,65,0', max_stations=20, range=90, txpower=30)
    
    ap2 = net.addAccessPoint('ap2', ssid='new-ssid', mode='g', channel='11',
                                 failMode="continue", position='180,65,0', max_stations=20, range=90, txpower=30)
 
     # Creating a controller.                             
    c1 = net.addController('c1')
    
    #net.addLink(ap1,ap2)
    
    info("*** Configuring propagation model\n")
    net.setPropagationModel(model="logDistance",exp=4) 
                    
     #Node configuration.                                  
    info("*** Configuring nodes\n")
    net.configureNodes()

   # For plotting Mininet-wifi graph
    net.plotGraph()
    
    
    
    
    net.setMobilityModel(time=0, model='RandomDirection',
                         max_x=220, max_y=120, seed=70 , AC='ssf')
                         
    #Network start. 
    info("*** Starting network\n")
    net.build()
    c1.start()
    ap1.start([c1])
    ap2.start([c1])
    
    
    #Launches command line interface (CLI) once the network starts.

    info("*** Running CLI\n")
    CLI(net)
    
    info("*** Stopping network\n")
    net.stop()

    # Start Mininet network topology with loggging level set to info, when the script is ran as the main program. 

if __name__ == '__main__':
    setLogLevel('info')
    topology(sys.argv)

**Comment by ldahal** [comment]
I had not assigned one .  I now assigned it as below 
ap1 = net.addAccessPoint('ap1', ssid='new-ssid',  mode='g',  ip='10.0.0.6/8', channel='1',
                                 failMode="continue", position='60,65,0', max_stations=20, range=90, txpower=30)
    
    ap2 = net.addAccessPoint('ap2', ssid='new-ssid',  mode='g', ip='10.0.0.7/8', channel='11',
                                 failMode="continue", position='180,65,0', max_stations=20, range=90, txpower=30)

I also added the following lines 

net.configureNodes()
    net.addLink(ap1,ap2)
    net.addLink(sta1,ap1)
    net.addLink(sta1,ap2)
    net.addLink(sta2,ap1)
    net.addLink(sta2,ap2)
    net.addLink(sta3,ap1)
    net.addLink(sta3,ap2)
    net.addLink(sta4,ap1)
    net.addLink(sta4,ap2)
Made iptables to ACCEPT for INPUT , FORWARD and OUTPUT. 
My goal is everything connected to everything. Pingall command shows 83 % dropped (2/12 received). I am doing something wrong but couldn't figure. Sorry, pretty new with SDN. Read your book still couldn't find a way to get everything connected.

**Comment by ramonfontes** [comment]
I think you don't know how Mininet-WiFi and OVS work. I strongly suggest you to read the mn-wifi book: https://github.com/ramonfontes/mn-wifi-ebook
