### ISSUE TITLE
AttributeError: 'Mininet_wifi' object has no attribute '_parseIperf'

### ISSUE THREAD

**Issue by Mehdi-Nobakht** [intrig-unicamp/mininet-wifi#497]
I recently installed Mininet-WiFi version 2.6 on Ubuntu. When running the `iperf` command on Mininet, it works fine with the following command:

        sudo mn --switch ovsbr --test iperf

However, when attempting to run iperf on Mininet-WiFi using the command:

      sudo mn --wifi --test iperf

It throws an error and exits Mininet-WiFi. The specific error message is as follows:

       in `net.py` line 1042, in iperf
       result = [self._parseIperf(servout), self._parseIperf(cliout)]
      AttributeError: 'Mininet_wifi' object has no attribute '_parseIperf'

**Comment by ramonfontes** [comment]
Please use xterm instead of the console for commands such as iperf.
