### ISSUE TITLE
About CSMA/CA

### ISSUE THREAD

**Issue by tsukalab-2021** [intrig-unicamp/mininet-wifi#498]
Hello, I am thinking of trying this simulator but there is one thing I am not certain about this simulator.
I know this simulator supports IEEE 802.11a,b,g,b,p,ax,ac etc, but does it also simulate CSMA/CA behavior?
The fact that CSMA/CA behavior can be simulated is very important for what I am trying to do in the future.
Any help would be appreciated.

**Comment by ramonfontes** [comment]
Please refer to wmediumd https://github.com/bcopeland/wmediumd

**Comment by kit-ad** [comment]
Hello, I also wanted to know if Mininet-wifi supports CSMA/CA, so I checked wmediumd, but all I could find is that it can simulate loss and delay. Does this mean that Mininet-wifi does not do any collision avoidance? I would appreciate it if you could tell me
