### ISSUE TITLE
mininet-wifi in debian 11 bullseye , ModuleNotFoundError: No module named 'mn_wifi'

### ISSUE THREAD

**Issue by georkoy** [intrig-unicamp/mininet-wifi#499]
Hi , 

I try to install mininet-wifi in debian 11 bullseye
When i try sudo util/install.sh –Wlnfv i get the following error: 
Detected Linux distribution: Debian 11 bullseye amd64
Debian
sys.version_info(major=3, minor=9, micro=2, releaselevel='final', serial=0)
Detected Python (python) version 3
Installing Mininet dependencies
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
python-is-python3 is already the newest version (3.9.2-1).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Package pep8 is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

Package pyflakes is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source
However the following packages replace it:
  python3-pyflakes pyflakes3

E: Package 'pyflakes' has no installation candidate
E: Package 'pep8' has no installation candidate

I have install pep8 and pyrflake manualy but i get the same error
Then in installation script (util/install.sh ) in install mininet-wifi dependencies  sections i change
Pf=pyrflakes -> pf=pyrflakes3
Ethtool help2man $pf pylint pep8 -> Ethtool help2man $pf pylint pycodestyle or Ethtool help2man $pf pylint pyflakes3

Then the installation script runs , but when i try to run examples (in examples folder) i get 
 ModuleNotFoundError: No module named 'mn_wifi'

any ideas will be helpful..
Thanks in advance!

**Comment by ramonfontes** [comment]
Debian is not officially supported by install.sh.

**Comment by georkoy** [comment]
Hi , 

thanks for your answer...
So , is there any trick i can do , to get it installed properly?
Thanks in advance!
