### ISSUE TITLE
Mininet wifi crashes 

### ISSUE THREAD

**Issue by maganiss** [intrig-unicamp/mininet-wifi#5]
Hi.
Sadly, my mininet-wifi crashes many times.
I run 2AccessPoint.py one time, type exit at the end.
Then I run 2AccessPoint.py (or any other topologies) and it faces an error(index out of range).
I type sudo mn -c, then run the topo again, and it goes till adding link... but suddenly my ubuntu hangs (like there's a loop somewhere), and I have to reset the machine, turns out that I have to run just one topology each time then reset, and then the other.

what should I do?

**Comment by ramonfontes** [comment]
Hi,

Have you stopped Network Manager? In the Readme has: "Mininet-WiFi should work fine in any Ubuntu distribution from 14.04, but in some cases (only if you have problems when start it) you have to stop NetworkManager typing stop network-manager."

**Comment by maganiss** [comment]
I can't. The command gives me the error below.
stop: Unable to connect to Upstart: Failed to connect to socket /com/ubuntu/upstart: Connection refused

**Comment by ramonfontes** [comment]
Try sudo systemctl stop network-manager or service network-manager restart.

**Comment by maganiss** [comment]
Thank you very much.
It worked.

**Comment by ramonfontes** [comment]
Great! ;)
