### ISSUE TITLE
Information pulling from CLI report

### ISSUE THREAD

**Issue by struggle47** [intrig-unicamp/mininet-wifi#50]
Hi,

I have a basic question about how to get information from mininet report on the Ubuntu CLI. I believe describing what I do will be helpful. I use python script to create nodes, start wifi-Direct on the nodes (sta1, sta2, sta3, sta4), declare one of the nodes as group owner (sta1), and then connect remaining nodes (except sta4) to the GO (Group Owner) via wifi-direct. Then, through sta4 I start wpa_cli using the line of "sta4 wpa_cli -ista-lan0" and I find other devices using "p2p_find 20", where 20 refers to time. I got the following output:
<3>P2P-DEVICE-FOUND 00:00:00:00:00:03 p2p_dev_addr=00:00:00:00:00:03 pri_dev_type=1-0050F204-1 name='sta3' config_methods=0x1108 dev_capab=0x27 group_capab=0x0 new=1
<3>P2P-DEVICE-FOUND 00:00:00:00:00:02 p2p_dev_addr=00:00:00:00:00:02 pri_dev_type=1-0050F204-1 name='sta2' config_methods=0x1108 dev_capab=0x27 group_capab=0x0 new=1
<3>P2P-DEVICE-FOUND 00:00:00:00:00:01 p2p_dev_addr=00:00:00:00:00:01 pri_dev_type=1-0050F204-1 name='sta1' config_methods=0x1108 dev_capab=0x25 group_capab=0x9 new=1
Here I would like to be able to select the GO among other devices. I noticed that there are couple of features that GO has different compared to the GM (Group Member), such as "dev_capab" "group_capab". Here my question is: how can I get group_capab=0x9 information using python?

**Comment by ramonfontes** [comment]
Have you ever tried the grep command?

**Comment by struggle47** [comment]
Thank you for quick response! No I haven't. I will take a look at it now. Thanks!

**Comment by struggle47** [comment]
I've been working on this grep command. However, it seems like grep command only works for the (not moving) strings on the CLI. I would like to use grep command for the strings that moves continuously. For example, in wpa_cli mode I discover peers. The CLI displays
<3>CTRL-EVENT-SCAN-STARTED 
<3>CTRL-EVENT-SCAN-STARTED 
<3>CTRL-EVENT-SCAN-STARTED 
<3>CTRL-EVENT-SCAN-STARTED
continuously. When it finds a peer CLI displays:
<3>P2P-DEVICE-FOUND 00:00:00:00:00:03 p2p_dev_addr=00:00:00:00:00:03 pri_dev_type=1-0050F204-1 name='sta3' config_methods=0x1108 dev_capab=0x27 group_capab=0x0 new=1
All in all, my question is when I am in wpa_cli mode, can't I use grep in order to extract information?

**Comment by ramonfontes** [comment]
Please take a look at step 3 from
https://losst.wordpress.com/2011/04/05/monitor-wireless-access-points-with-a-one-line-shell-script/.
They seem to use grep from wpa_cli. The same in
http://stackoverflow.com/questions/27922190/getting-p2p-device-address-from-wpa-cli-status
.

2017-03-07 16:53 GMT-03:00 struggle47 <notifications@github.com>:

**Comment by struggle47** [comment]
Thank you very much, I will take a look at them right away.

**Comment by struggle47** [comment]
As far as I understood, they use grep for non-moving lines. When they use "wpa_cli -i<interfaceName> status", the status information is displayed on the regular Terminal (texts do not move). However, I wanted to use grep for moving texts when I use "wpa_cli -i<interfaceName> p2p_find". In this case no text in shown on the Terminal. In order to be able to see the moving texts I need to go to "wpa_cli -i<interfaceName>", which gives me an interactive mode. I guess I need to use some tricks from the available tools. Maybe like continuously calling status and then checking the information I need. Thanks!
