### ISSUE TITLE
If Mininet-wifi supports CSMA/CA

### ISSUE THREAD

**Issue by kit-ad** [intrig-unicamp/mininet-wifi#500]
Hello, I wanted to know if Mininet-wifi supports CSMA/CA, so I checked  https://github.com/bcopeland/wmediumd, but all I could find is that it can simulate loss and delay. Does this mean that Mininet-wifi does not do any collision avoidance? I would appreciate it if you could tell me

_Originally posted by @kit-ad in https://github.com/intrig-unicamp/mininet-wifi/issues/498#issuecomment-1596107853_

**Comment by ramonfontes** [comment]
Mininet-WiFi doesn't have any collision avoidance method. Features such as CSMA/CA must be implemented in wmediumd.
