### ISSUE TITLE
Set range and antennaGain to Interfaces

### ISSUE THREAD

**Issue by andredemori** [intrig-unicamp/mininet-wifi#501]
Is there any way to set the **range** and **antennaGain** to just one of the interfaces of a node, or just to the node itself?

When I add a station I can set range and antennaGain. But there is a way to do it to only one interface?

ex:

sta1.range(50, intf="sta1-wlan0")

**Comment by ramonfontes** [comment]
https://mn-wifi.readthedocs.io/en/latest/commands.html#confval-node.setRange-10-intf-node-wlan0-or-net.addStation-...-range-10
