### ISSUE TITLE
E : package 'python-matplotlib' has no installation candidate

### ISSUE THREAD

**Issue by renirss** [intrig-unicamp/mininet-wifi#502]
Hi everyone, 
I try to install mininet-Wifi on ubuntu 20.04, but when I try to run "util/install.sh - Wlnfv" I git this error E : package 'python-matplotlib' has no installation candidate, Has anyone ever got the same error and solved it? 

thanks a lot

**Comment by renirss** [comment]
already solved, thank you

**Comment by 12138-czy** [comment]
I have the same question ,so please help me ,how to solve it

**Comment by WangchukSherpa** [comment]
I have the same problem ,so please help me ,how to solve it
