### ISSUE TITLE
Limits of values set in Mininet-WiFi

### ISSUE THREAD

**Issue by andredemori** [intrig-unicamp/mininet-wifi#505]
Is there any documentation about the limits of values that can be set on Mininet-WiFi?

For example, Noise threshold, Antenna Gain, TxPower, etc?

Is there a minimum or maximum value? Or can I set any value even if it doesn't make sense?

Thanks in advance.

**Comment by ramonfontes** [comment]
There is no limit for Noise threshold and Antenna Gain. TxPower depends on the System/Kernel version you have.
