### ISSUE TITLE
Few problems with file replayingRSSI.py in examples/replaying

### ISSUE THREAD

**Issue by floppydrive6** [intrig-unicamp/mininet-wifi#51]
1) path in lines 36 and 37 in function should be changed to: replayingRSSI/node1_rssiData.dat and replayingRSSI/node2_rssiData.dat
2) in line 39 method replayingRSSI() should be call with mininet-object as an argument so in this case I think it should be replayingRSSI(net)
3) in wifiReplaying.py module in line mobility.parameters_() there is a classmethod call without any arg, I go to definition and I think it should be call with sta as a parameter so mobility.parameters_(sta) should work.
After these changes it works fine.
Let me know if I'm wrong or not.

**Comment by ramonfontes** [comment]
Hello,

First of all thank you for opening this issue. Actually only this fixed the problem: https://github.com/intrig-unicamp/mininet-wifi/commit/8ee3616a2996b15ddaca97ff145a5911fe1b82dc#diff-3c16c71baa443da6738ec0bef1834d12R224

**Comment by floppydrive6** [comment]
Hello,
I think that those paths should be modified (in order to avoid more questions) and I'm not sure, if the same problem won't occur with other examples connected with mobility.
Regards,
Greg

**Comment by ramonfontes** [comment]
Changing that path to replayingRSSI/node1_rssiData.dat and replayingRSSI/node2_rssiData.dat, are you able to run the code from any dir?
