### ISSUE TITLE
Unable ping in sdn-vanet when car moving

### ISSUE THREAD

**Issue by nonhetnuoccham** [intrig-unicamp/mininet-wifi#512]
Hi sir,
I am having a project about sdn in vanet and I must simulate it in mininet-wifi . After running code, it is very good and i can ping 2 car in 2 ap, but after a few minute i cannot ping 2 car in 2 ap. This is my code:

import sys
from random import randint

from mininet.node import DefaultController, RemoteController
from mininet.log import setLogLevel, info
from mn_wifi.cli import CLI
from mn_wifi.net import Mininet_wifi
from mn_wifi.link import wmediumd, adhoc,mesh
from mn_wifi.wmediumdConnector import interference

def topology(args):
 "Create a network."
 net = Mininet_wifi(controller=RemoteController, roads=4,
 link=wmediumd, wmediumd_mode=interference)

 info("*** Creating nodes\n")

 for id in range(0, 10):
  min_ = randint(1, 4)
  max_ = randint(11, 30)
  net.addCar('car%s' % (id+1), wlans=2, min_speed=min_, max_speed=max_)

 rsu11 = net.addAccessPoint(
 'RSU11', ssid='vanet-ssid', mode='g', position='2600,3500,0', proto='batmand', channel='1', intf='RSU11-wlan1',
 ht_cap='HT40+')
 rsu12 = net.addAccessPoint(
 'RSU12', ssid='vanet-ssid', mode='g', position='2800,3500,0', proto='batmand', channel='6', intf='RSU12-wlan1',
 ht_cap='HT40+')
 rsu13 = net.addAccessPoint(
 'RSU13', ssid='vanet-ssid', mode='g', position='3000,3500,0', proto='batmand', channel='11', intf='RSU13-wlan1',
 ht_cap='HT40+')
 rsu14 = net.addAccessPoint(
 'RSU14', ssid='vanet-ssid', mode='g', position='3200,3500,0', proto='batmand', channel='11', intf='RSU14-wlan1',
 ht_cap='HT40+')
 c1 = net.addController('c1')
info("*** Configuring Propagation Model\n")
 net.setPropagationModel(model="logDistance", exp=4)

 info("*** Configuring wifi nodes\n")
 net.configureWifiNodes()

 info("*** Associating and Creating links\n")
 net.addLink(rsu11, rsu12)
 net.addLink(rsu11, rsu13)
 net.addLink(rsu11, rsu14)

 for car in net.cars:
  net.addLink(car, cls=mesh, intf='%s-wlan1' % car,
  ssid='adhocNet', proto='batmand', mode='g', channel=5,
  ht_cap='HT40+')

 if '-p' not in args:
  net.plotGraph(max_x=500, max_y=500)

 net.startMobility(time=0)

 info("*** Starting network\n")
 net.build()
 c1.start()
 rsu11.start([c1])
 rsu12.start([c1])
 rsu13.start([c1])
 rsu14.start([c1])
for id, ap in enumerate(net.aps):
  ap.setIP('192.168.1.%s/24' % (id+11), intf='%s-wlan1' % ap)
  ap.setIP('10.0.1.%s/24' % (id+11), intf='%s-eth2' % ap)
info("*** Running CLI\n")
 CLI(net)

 info("*** Stopping network\n")
 net.stop()

if __name__ == '__main__':
 setLogLevel('info')
 topology(sys.argv)

ping result:

![Screenshot (622)](https://github.com/intrig-unicamp/mininet-wifi/assets/149099179/aedff319-97ae-406a-b614-a647835688ba)

![Screenshot (623)](https://github.com/intrig-unicamp/mininet-wifi/assets/149099179/f749ae6d-185b-4672-8f4a-27ae4ba47547)
 
![Screenshot (624)](https://github.com/intrig-unicamp/mininet-wifi/assets/149099179/cf509691-a7a7-4ff0-88bf-d8f7e481d959)

![Screenshot (625)](https://github.com/intrig-unicamp/mininet-wifi/assets/149099179/3b666789-0b4e-49bd-bc54-f38131bee8b0)

**after a few minute, I cannot ping 2 car in 2 ap**

![Screenshot (626)](https://github.com/intrig-unicamp/mininet-wifi/assets/149099179/df2ff109-0fb5-41cd-9ef4-04bd3ba3c703)
![Screenshot (627)](https://github.com/intrig-unicamp/mininet-wifi/assets/149099179/50de943b-2e59-4e8e-8e96-749c42c85bcd)

![Screenshot (628)](https://github.com/intrig-unicamp/mininet-wifi/assets/149099179/6a396398-8f34-4c1e-8177-edd67c27ae1c)

Can you show my problem and how to fix it.

**Comment by ramonfontes** [comment]
Could you please tell us about the flow timeout? How is the controller handling flow timeouts?

**Comment by nonhetnuoccham** [comment]
when I cannot ping and I run dpctl dump-flows it show:
![Screenshot (628)](https://github.com/intrig-unicamp/mininet-wifi/assets/149099179/5cc0f2b6-f160-48a8-a8d1-2771c1f00b4e)

**Comment by ramonfontes** [comment]
You didn't answer my question.. :(

**Comment by nonhetnuoccham** [comment]
How i can show it, i never use controller before and having many thing i donnot know

**Comment by ramonfontes** [comment]
> How i can show it, i never use controller before and having many thing i donnot know

Please don't open a new issue if you don't know exactly what is going wrong. I suggest you to go through related issues since this issue has already been explored in the past.
