### ISSUE TITLE
can I custom the moving path in virtual space 

### ISSUE THREAD

**Issue by zhangzee** [intrig-unicamp/mininet-wifi#52]
hello , I have learned that the mininet-wifi offers two methods(net.mobility and net.startMobility) to support  mobility. And I want to know if it is possible that the station moves according a customized path.
For example , one path is ap1, ap2, ap3, ap2, ap1.....

Thandks

**Comment by ramonfontes** [comment]
It might help you: https://github.com/intrig-unicamp/mininet-wifi/blob/master/examples/replaying/replayingMobility.py

**Comment by zhangzee** [comment]
Thank you for you reply , but when I run the replayingMobility.py , I get the error :
![image](https://cloud.githubusercontent.com/assets/22088840/23612698/59239e6a-02b7-11e7-9fc8-493665352d4e.png) 

If I should do something?

**Comment by ramonfontes** [comment]
Please change replayingMobility() to replayingMobility(net)

2017-03-06 10:55 GMT-03:00 zhangze <notifications@github.com>:

**Comment by zhangzee** [comment]
![image](https://cloud.githubusercontent.com/assets/22088840/23613309/e0629172-02b9-11e7-869a-16c418646404.png)

**Comment by ramonfontes** [comment]
Please clone Mininet-WiFi and then run make install.

2017-03-06 11:11 GMT-03:00 zhangze <notifications@github.com>:

**Comment by ramonfontes** [comment]
Hello! Is the issue solved?

**Comment by zhangzee** [comment]
Thanks , after I clone the new Mininet-WiFi ,the issue is solved.  Thank you !
