### ISSUE TITLE
MININET-WIFI&ONOS 

### ISSUE THREAD

**Issue by Szy520110** [intrig-unicamp/mininet-wifi#521]
Hi, 
Thank you for your answer to my last question.
MININET is able to use ONOS as a controller and visualise topology connections and other data on the ONOS GUI. can the ad-hoc topology of MININET-WIFI be displayed on ONOS?

Best Regards，
Zey

**Comment by ramonfontes** [comment]
Please consider using the mailist list for questions or concerns. This and others have already been answered there.
