### ISSUE TITLE
Combine 2 car is in ap and not in ap

### ISSUE THREAD

**Issue by nonhetnuoccham** [intrig-unicamp/mininet-wifi#522]
Hi sir,
I am learning about vanet and i have a question: In mininet-wifi, i can combine 2 situation: 2 car can communicate while both are in ap; 2 car ping while distance is near enough and they are not in ap. Ihave tried but I only can ping success when i try 2 situation separately . How can I combined them in a topo?

**Comment by ramonfontes** [comment]
Please consider using the mailing list for questions like that. We've discussed this subject a lot there.
