### ISSUE TITLE
vanet.py issue

### ISSUE THREAD

**Issue by mfatihkoc** [intrig-unicamp/mininet-wifi#527]
**Hi,

(Python 3.10.12)

I wanted to run vanet.py example actually I receive various error with following Reproducibility steps:**
- ~/mininet-wifi$ sudo rm -r /usr/local/lib/python2.7/dist-packages/mininet*
- ~/mininet-wifi$ git reset --hard b43af65
- ~/mininet-wifi$ sudo make install
- ~/mininet-wifi$ cd reproducible-research/mininet-wifi/IEEE-Access-2017

**That is why I run sudo su instead. and became root: however I received following error.**

_root@ubuntu:/home/ubuntu/mininet-wifi/reproducible-research/mininet-wifi# cd IEEE-Access-2017/
root@ubuntu:/home/ubuntu/mininet-wifi/reproducible-research/mininet-wifi/IEEE-Access-2017# ls
README.md  vanet.py
root@ubuntu:/home/ubuntu/mininet-wifi/reproducible-research/mininet-wifi/IEEE-Access-2017# python3 vanet.py 
Traceback (most recent call last):
  File "/home/ubuntu/mininet-wifi/reproducible-research/mininet-wifi/IEEE-Access-2017/vanet.py", line 15, in <module>
    from mininet.node import Controller, OVSKernelSwitch, OVSKernelAP, Car
ImportError: cannot import name 'OVSKernelAP' from 'mininet.node' (/usr/local/lib/python3.10/dist-packages/mininet/node.py)_

**Comment by ramonfontes** [comment]
Please make sure you have the mn-wifi code base from 2017.

**Comment by mfatihkoc** [comment]
yes I have downloaded with https://github.com/ramonfontes/reproducible-research/tree/master/mininet-wifi/IEEE-Access-2017

**Comment by ramonfontes** [comment]
> https://github.com/ramonfontes/reproducible-research/tree/master/mininet-wifi/IEEE-Access-2017

This doesn't mean that you have the mininet-wifi code from 2017 :(

**Comment by mfatihkoc** [comment]
I am trying to run the **vanet.py** code in **IEEE-Access-2017**.

**Comment by ramonfontes** [comment]
You are trying to run a script. What about the mn-wifi code base??

**Comment by mfatihkoc** [comment]
sorry but what does it mean (mn-wifi code base), I run ~/mininet-wifi/reproducible-research/mininet-wifi/IEEE-Access-2017$ sudo python vanet.py already. do I need to run another script something else?

**Comment by mfatihkoc** [comment]
It could be nice that you share the video clearly with steps, that you are running already here Video clip available at: https://www.youtube.com/watch?v=kO3O9EwrP_s

**Comment by ramonfontes** [comment]
Which version of mn-wifi do you have?? ;/

**Comment by mfatihkoc** [comment]
wifi@wifi-virtualbox:~/mininet-wifi/reproducible-research/mininet-wifi$ pip show mininet-wifi
DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained. pip 21.0 will drop support for Python 2.7 in January 2021. More details about Python 2 support in pip can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support pip 21.0 will remove support for this functionality.                                                                                         
WARNING: Package(s) not found: mininet-wifi
wifi@wifi-virtualbox:~/mininet-wifi/reproducible-research/mininet-wifi$ python3 --version
Python 3.8.5

**Comment by ramonfontes** [comment]
Closing the issue as the information presented is not consistent.
