### ISSUE TITLE
A question about net.addLink()

### ISSUE THREAD

**Issue by Ericzhang1127** [intrig-unicamp/mininet-wifi#53]
Hello! I want to change the bandwidth, error rate, and delay between a station and an accesss piont .
For examples,net.addLink(sta1, ap1,bw='11Mbps', loss='100%', delay='15ms') and net.addLink(sta2, ap1,bw='11Mbps', loss='100%', delay='15ms').
However,when I input "sta1 ping sta2" in the CLI, it shows that "6 packets transmitted, 6 received, 0% packet loss". I set the loss="100%" and why the packet loss is 0%?
It also shows that “64 bytes from 192.168.0.4: icmp_seq=4 ttl=64 time=0.069 ms”.The delay='15ms' doesn't work at all.
Thanks!

**Comment by ramonfontes** [comment]
Hello,

Please try the most recent code with something like *net.addLink(sta1, ap1,
bw=10, loss=10, delay='15ms').* Please note that it won't work in scenarios
with mobility.

2017-03-06 9:55 GMT-03:00 Ericzhang1127 <notifications@github.com>:

**Comment by Ericzhang1127** [comment]
Thank you！

**Comment by hdm0511** [comment]
Hi Ramonfontes,
I create a network in mininet wifi (code below) with  a given fixed bandwidth (100Mbps), link delay and packet loss. However when i ping from host to host the packet loss results are different from time to time.
For instance:
net.addLink(s2, h3, bw=1000)
net.addLink(s2, h8, bw=100, delay='25ms', loss=2)
packet loss of the command: h8 ping -c 100 h3. the packet loss should be 2. but the actual results are not consistent ( 4, 5, 7...) 
I dont know how to keep the packet loss to a given number.

Thank you,


 
`from mn_wifi.net import Mininet_wifi
from mn_wifi.cli import CLI_wifi
from mininet.node import Controller
from mininet.log import setLogLevel, info

def topology():

    "Create a network."
    net = Mininet_wifi( controller=Controller )

    info("*** Creating nodes\n")
    c1 = net.addController( 'c1')#, ip='127.0.0.1', port=6633 )
    s2 = net.addSwitch( 's2', protocols='OpenFlow10', listenPort=6673, mac='00:00:00:00:00:02' )
    h3 = net.addHost( 'h3', mac='00:00:00:00:00:03', ip='10.0.0.3/8' )
    h4 = net.addHost( 'h4', mac='00:00:00:00:00:04', ip='10.0.0.4/8' )
    h5 = net.addHost( 'h5', mac='00:00:00:00:00:05', ip='10.0.0.5/8' )
    h6 = net.addHost( 'h6', mac='00:00:00:00:00:06', ip='10.0.0.6/8' )
    h7 = net.addHost( 'h7', mac='00:00:00:00:00:07', ip='10.0.0.7/8' )
    h8 = net.addHost( 'h8', mac='00:00:00:00:00:08', ip='10.0.0.8/8' )
    h9 = net.addHost( 'h9', mac='00:00:00:00:00:09', ip='10.0.0.9/8' )
    h10 = net.addHost( 'h10', mac='00:00:00:00:00:0a', ip='10.0.0.10/8' )
    
    info("*** Creating links\n")
    net.addLink(s2, h3, bw=1000)
    net.addLink(s2, h4, bw=100, delay='1ms', loss=2)
    net.addLink(s2, h5, bw=100, delay='2.5ms', loss=2)
    net.addLink(s2, h6, bw=100, delay='5ms', loss=2)
    net.addLink(s2, h7, bw=100, delay='10ms', loss=2)
    net.addLink(s2, h8, bw=100, delay='25ms', loss=2)
    net.addLink(s2, h9, bw=100, delay='35ms', loss=2)
    net.addLink(s2, h10, bw=100, delay='25ms', loss=1)
    
    info("*** Starting network\n")
    net.configureWifiNodes()
    net.build()
    c1.start()
    s2.start( [c1] )


    info("*** Running CLI\n")
    CLI_wifi( net )

    info("*** Stopping network\n")
    net.stop()

if __name__ == '__main__':
    setLogLevel( 'info' )
    topology()`

**Comment by hdm0511** [comment]
could you please copy the code and ping h8 to h3 as above?
here is the code:
+++++++++++++
#!/usr/bin/env python2
# -*- coding: utf-8 -*-
"""

from mn_wifi.net import Mininet_wifi
from mn_wifi.cli import CLI_wifi
from mininet.node import Controller
from mininet.log import setLogLevel, info

def topology():

    "Create a network."
    net = Mininet_wifi( controller=Controller )

    info("*** Creating nodes\n")
    c1 = net.addController( 'c1')#, ip='127.0.0.1', port=6633 )
    s2 = net.addSwitch( 's2', protocols='OpenFlow10', listenPort=6673, mac='00:00:00:00:00:02' )
    h3 = net.addHost( 'h3', mac='00:00:00:00:00:03', ip='10.0.0.3/8' )
    h4 = net.addHost( 'h4', mac='00:00:00:00:00:04', ip='10.0.0.4/8' )
    h5 = net.addHost( 'h5', mac='00:00:00:00:00:05', ip='10.0.0.5/8' )
    h6 = net.addHost( 'h6', mac='00:00:00:00:00:06', ip='10.0.0.6/8' )
    h7 = net.addHost( 'h7', mac='00:00:00:00:00:07', ip='10.0.0.7/8' )
    h8 = net.addHost( 'h8', mac='00:00:00:00:00:08', ip='10.0.0.8/8' )
    h9 = net.addHost( 'h9', mac='00:00:00:00:00:09', ip='10.0.0.9/8' )
    h10 = net.addHost( 'h10', mac='00:00:00:00:00:0a', ip='10.0.0.10/8' )
    
    info("*** Creating links\n")
    net.addLink(s2, h3, bw=1000)
    net.addLink(s2, h4, bw=100, delay='1ms', loss=2)
    net.addLink(s2, h5, bw=100, delay='2.5ms', loss=2)
    net.addLink(s2, h6, bw=100, delay='5ms', loss=2)
    net.addLink(s2, h7, bw=100, delay='10ms', loss=2)
    net.addLink(s2, h8, bw=100, delay='25ms', loss=2)
    net.addLink(s2, h9, bw=100, delay='35ms', loss=2)
    net.addLink(s2, h10, bw=100, delay='25ms', loss=1)
    
    info("*** Starting network\n")
    net.configureWifiNodes()
    net.build()
    c1.start()
    s2.start( [c1] )


    info("*** Running CLI\n")
    CLI_wifi( net )

    info("*** Stopping network\n")
    net.stop()

if __name__ == '__main__':
    setLogLevel( 'info' )
    topology()
+++++++++++++

**Comment by hdm0511** [comment]
Or you can remote login to my system.

**Comment by ramonfontes** [comment]
Sorry, but I didn't notice any problem with the script.

**Comment by hdm0511** [comment]
that is the question. script is ok, but packet loss results are different from time to time. 
is that Link in mininet-wifi add loss automatically according to wireless modelling?

++++++++++h3 ping h8 -c 100++++++++++++
--- 10.0.0.8 ping statistics ---
100 packets transmitted, 93 received, 7% packet loss, time 99226ms
rtt min/avg/max/mdev = 50.063/50.328/58.065/0.853 ms
++++++++++h8 ping h3 -c 100++++++++++++
--- 10.0.0.3 ping statistics ---
100 packets transmitted, 97 received, 3% packet loss, time 99175ms
rtt min/avg/max/mdev = 50.066/50.339/54.715/0.487 ms
++++++++++++++h8 ping h3 -c 100+++++++++++++++++
--- 10.0.0.3 ping statistics ---
100 packets transmitted, 95 received, 5% packet loss, time 99199ms
rtt min/avg/max/mdev = 50.048/50.247/50.538/0.198 ms
