### ISSUE TITLE
mn_wifi error

### ISSUE THREAD

**Issue by Varuni387** [intrig-unicamp/mininet-wifi#543]
After following the steps for installation I am facing the error
varuni@varuni-Inspiron-15-3511:~/mininet-wifi/examples$ sudo python3 mobility.pyTraceback (most recent call last):
  File "/home/varuni/mininet-wifi/examples/mobility.py", line 8, in <module>
    from mn_wifi.cli import CLI
ModuleNotFoundError: No module named 'mn_wifi'

**Comment by ramonfontes** [comment]
This means that you don't have mininet-wifi  insfalled in your system.
