### ISSUE TITLE
Wireless Communication between APs

### ISSUE THREAD

**Issue by michelebarbieri** [intrig-unicamp/mininet-wifi#546]
Hi! Sorry for the question but I'm interested in building a Wireless Network in with Wireless distribution system powered by SDN, and I'm wondering for a wireless connection betweeen APs, but nothing found about; does anyone know something? I'm not able to ping AP2 from AP1 and viceversa, so I'm not able to understand... Thanks in advance

**Comment by ramonfontes** [comment]
Didn't you find 4address??

ps: I see no issue here. Please use the mailing list for such a question.

**Comment by michelebarbieri** [comment]
Hi! yes I found 4address, but works in client-ap fashion but I think they do not fit my needs. I'm trying to build a network with APs which provides both coverage to stations and also are capable to route the packets among the other APs, in a SDN trend, following apath provided by a Controller working with OpenFlow. Probably I'm confusing but what I need is the communication between APs in order to drop or retransmit the packet according to the path defined and the flow rules (if the datapath id of the AP is inside the path retransmit otherwise drop it)
