### ISSUE TITLE
Running a code in separate nodes simultaneously

### ISSUE THREAD

**Issue by struggle47** [intrig-unicamp/mininet-wifi#55]
Hi,

I would like to write a python code and run it in different nodes simultaneously. Is there a way to achieve this? Here's a detailed explanation of the problem I have: Let's say I created two nodes that runs wifi-direct in them. sta1 and sta2. When I run the code:
sta1.cmd('<discover peers for 60 sec.>; sleep 30')
sta2.cmd('<discover peers for 60 sec. >; sleep 10')
First, sta1 starts discovering peers and then waits for 30 seconds. After that 30 seconds sta2 starts discovering. This is not what I want. Instead, I want sta1 and sta2 to start discovering at the same time. I don't want one station (sta2) to wait other station (sta1) in order to start processing. How can I start sta1 and sta2 working simultaneously (I would like to increase the number of stations in the future)? Here sleep is just an example. If there's a process, which takes a bit of time, sta2 waits sta1 to finish the process.

**Comment by ramonfontes** [comment]
Thread is certainly an alternative. See
https://github.com/intrig-unicamp/mininet-wifi/blob/master/mininet/net.py#L1794
as an example.

**Comment by struggle47** [comment]
Thank you! I'll work on it.
