### ISSUE TITLE
mininet-wifi module not found issue

### ISSUE THREAD

**Issue by Subho-Ninja** [intrig-unicamp/mininet-wifi#554]
I am experiencing persistent issues installing and running Mininet-WiFi on Ubuntu. After following the official installation steps and setting the PYTHONPATH, my attempts to import Mininet_wifi consistently result in a ModuleNotFoundError. I’ve tried reinstalling dependencies, configuring PYTHONPATH, and re-cloning the repository. Despite following the instructions, the module remains unrecognized, hindering my ability to run essential scripts. I kindly request guidance or any additional troubleshooting steps to resolve this issue. Any insights would be highly appreciated.

![image](https://github.com/user-attachments/assets/4fa1f005-ce75-4a49-9339-b31f3949e009)

**Comment by ramonfontes** [comment]
The module `mininet_wifi` doesn't exist. You should try `mn_wifi` instead.
