### ISSUE TITLE
The handover recovery latency is so unstable when the sta moving among APs

### ISSUE THREAD

**Issue by zhangzee** [intrig-unicamp/mininet-wifi#56]
hi ，I  choose a controller which support mobility to test the handover latency when a sta moving among APs , of course I use the mininet-wifi to simulate experimental environment.  And I get a strange result : the handover latency is very different .The most handover latency is range between 2s and 5s , but there is also some 14s and 15s ,the unstable result troubled me, and I want to know whether I forget to deploy something at the APs or stas or the wireless links ??  Because I guess the instability may  be associated with  the wifi handover .

**Comment by ramonfontes** [comment]
Hello,

I can help you if you provide more details. The code would be helpful as
well.

2017-03-14 11:28 GMT-03:00 zhangze <notifications@github.com>:

**Comment by zhangzee** [comment]
#!/usr/bin/python

"""
Setting the position of Nodes (only for Stations and Access Points) and providing mobility using mobility models.

"""

from mininet.net import Mininet
from mininet.node import Controller,OVSKernelSwitch
from mininet.link import TCLink
from mininet.cli import CLI
from mininet.log import setLogLevel, info
from mininet.node import Controller, RemoteController, OVSKernelSwitch, OVSSwitch

from mininet.wifiReplaying import replayingMobility

def topology():

    "Create a network."
    net = Mininet( listenPort = 6633,topo=None)
    mycontroller = RemoteController("remoteController",ip="172.21.6.219")
    net.controllers = [mycontroller]
    net.nameToNode["remoteController"] = mycontroller

    info( '*** Adding hosts\n' )
    h1 = net.addHost( 'h1', ip='192.168.0.1/24', mac='00:00:00:00:00:01' )
    h2 = net.addHost( 'h2', ip='192.168.0.2/24', mac='00:00:00:00:00:02' )

    print "*** Creating nodes"
    sta1 = net.addStation( 'sta1', mac='00:00:00:00:00:03', ip='192.168.0.3/24', speed=1 )
    #sta2 = net.addStation( 'sta2', mac='00:00:00:00:00:03', ip='10.0.0.3/8' )
    ap1 = net.addAccessPoint( 'ap1', ssid= 'new-ssid1', dpid='0000000100000001',mode= 'g', channel= '1', position='4,4,0', range='30'  )
    ap2 = net.addAccessPoint( 'ap2', ssid= 'new-ssid2', dpid='0000000100000002',mode= 'g', channel= '1', position='55,17,0', range='30' )
    ap3 = net.addAccessPoint( 'ap3', ssid= 'new-ssid3', dpid='0000000100000003',mode= 'g', channel= '1', position='105,23,0', range='30' )
    ap4 = net.addAccessPoint( 'ap4', ssid= 'new-ssid4', dpid='0000000100000004',mode= 'g', channel= '1', position='20,55,0', range='30' )
    ap5 = net.addAccessPoint( 'ap5', ssid= 'new-ssid5', dpid='0000000100000005', mode= 'g', channel= '1', position='73,65,0', range='30' )
    ap6 = net.addAccessPoint( 'ap6', ssid= 'new-ssid6', dpid='0000000100000006',mode= 'g', channel= '1', position='120,78,0', range='30' )
    ap7 = net.addAccessPoint( 'ap7', ssid= 'new-ssid7', dpid='0000000100000007',mode= 'g', channel= '1', position='0,105,0', range='30' )
    ap8 = net.addAccessPoint( 'ap8', ssid= 'new-ssid8', dpid='0000000100000008',mode= 'g', channel= '1', position='50,102,0', range='30' )
    ap9 = net.addAccessPoint( 'ap9', ssid= 'new-ssid9', dpid='0000000100000009',mode= 'g', channel= '1', position='99,118,0', range='30' )

    info( '*** Adding switch\n' )
    s1 = net.addSwitch('s1',dpid='0000000100000010')
    s2 = net.addSwitch('s2',dpid='0000000100000011')
    s3 = net.addSwitch('s3',dpid='0000000100000012')
    s4 = net.addSwitch('s4',dpid='0000000100000013')
    s5 = net.addSwitch('s5',dpid='0000000100000014')
    s6 = net.addSwitch('s6',dpid='0000000100000015')
    s7 = net.addSwitch('s7',dpid='0000000100000016')

    print "*** Configuring wifi nodes"
    net.configureWifiNodes()
    print "*** Associating and Creating links"
    net.addLink(s1, s2,1 , 1)
    net.addLink(s1, s3,2 , 3)
    net.addLink(s1, s4,3 , 3)
    net.addLink(s1, h1,5 , 1)
    net.addLink(s1, s5,4 , 2)
    net.addLink(s2, s6)
    net.addLink(s2, s7)
    #net.addLink(s2, h2)

    net.addLink(s3, ap1, 1, 2)
    net.addLink(s3, ap2, 2, 2)
    net.addLink(s4, ap3)
    net.addLink(s4, ap6)
    net.addLink(s4, ap5)
    net.addLink(s5, ap8)
    net.addLink(s6, ap4)
    net.addLink(s7, ap7)
    net.addLink(s7, ap9)
    net.addLink(s7, h2)

    #set the bw loss delay and so on 
    net.setChannelEquation(bw='100', loss='0.04', delay='0', latency='0')

    info( '*** Starting network\n')
    net.start()

    """uncomment to plot graph"""
    net.plotGraph(max_x=120, max_y=120)

    getTrace(sta1, '/home/liangjun/mininet-wifi/examples/replaying/replayingMobility/node5.dat')
    #getTrace(sta2, '/home/liangjun/mininet-wifi/examples/replaying/replayingMobility/node2.dat')

    replayingMobility(net)
    print "*** Running CLI"
    CLI( net )

    print "*** Stopping network"
    net.stop()
def getTrace(sta, file):

    file = open(file, 'r')
    raw_data = file.readlines()
    file.close()
    
    sta.position = []

    for data in raw_data:
        line = data.split()
        x = line[0] #First Column
        y = line[1] #Second Column
        sta.position.append('%s,%s,0' % (x, y))

if __name__ == '__main__':
    setLogLevel( 'info' )
    topology()

**Comment by zhangzee** [comment]
this is the experiment topology script , and the node5.dat is self-defined moving path among APs, And the whole network is controlled by the remote controller.

**Comment by ramonfontes** [comment]
What about the content of .dat files? I will ask you one more thing: could
you prepare a video clip showing the behavior mentioned by you?

**Comment by zhangzee** [comment]
did you have a similar experiments? the reply support video clip ?

**Comment by ramonfontes** [comment]
Not yet. The reply doesn't support it, but you can send me the url (from
dropbox?).

Sent from my android

On 14 Mar 2017 12:17, "zhangze" <notifications@github.com> wrote:

did you have a similar experiments? the reply support video clip ?

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/intrig-unicamp/mininet-wifi/issues/56#issuecomment-286454097>,
or mute the thread

**Comment by zhangzee** [comment]
I donn't have dropbox,  I think about this question . Thank you !

**Comment by zhangzee** [comment]
o , I guess the instability may be associated with the wifi access . Every access to wifi aps  produces different access delay , so using the mininet-wifi as my experiment environment may be inappropriate unless I can fix the wifi access delay.

**Comment by ramonfontes** [comment]
What do you mean about wifi access?

Sent from my android

On 14 Mar 2017 14:07, "zhangze" <notifications@github.com> wrote:

o , I guess the instability may be associated with the wifi access . Every
access to wifi aps produces different access delay , so using the
mininet-wifi as my experiment environment may be inappropriate unless I can
fix the wifi access delay.

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/intrig-unicamp/mininet-wifi/issues/56#issuecomment-286491102>,
or mute the thread

**Comment by zhangzee** [comment]
For example , there are three APs(ap1, ap2, ap3) and one mobile node(sta ). The sta handover from ap1 to ap2 and from ap2 to ap3 , I mean the wifi access time from ap1 to ap2  is different from the sta handover from ap2 to ap3 . I just mean the  wireless access time is uncertain. Is it?

**Comment by zhangzee** [comment]
![1111](https://cloud.githubusercontent.com/assets/22088840/23930038/d2aadc7c-0964-11e7-9983-1e60bddb6268.jpg)

the up picture is my test environment ,And the node5.dat is like this 

![image](https://cloud.githubusercontent.com/assets/22088840/23930116/4cfff11a-0965-11e7-9b48-c977bcb67625.png)

**Comment by ramonfontes** [comment]
Are you sure this is not related to the openflow rules? That's why I want
to see a video clip. Typing sta1 iwconfig you can also be sure if the
station is already associated or not.

**Comment by zhangzee** [comment]
Can you give me a email address?  I try to give you a video clip .

**Comment by ramonfontes** [comment]
ramonreisfontes@gmail.com

2017-03-14 23:25 GMT-03:00 zhangze <notifications@github.com>:
