### ISSUE TITLE
A question about changing AP parameters by controller.

### ISSUE THREAD

**Issue by floppydrive6** [intrig-unicamp/mininet-wifi#58]
Hi, 
I have a question as in the title. Is there a possibility to change AP's parameters such a AP range (I mean antenna power level), contention window size, channel etc. by a remote controller? I am afraid that controller supporting OpenFlow protocol (ex. some POX controller) can't do that, so have you got an idea how can I achieve that? I am asking because I want to create a SDN controller which could change AP's amounparameters based on amount of clients connected to AP but I have no idea how can I create that kind of controller and if I can test it using mininet-wifi.
Thanks a lot for answer,
Regards,
Greg

**Comment by ramonfontes** [comment]
Hello Greg,

This is really an interesting/relevant question! As probably you know the
OpenFlow protocol was not designed for wireless networks and changes are
required. In my opinion you should start with the experimenter field (I've
never tried it before, but I think it is great kick-off). On the other
hand, another alternative is CAPWAP. OpenDayLight seems to support CAPWAP (
https://wiki.opendaylight.org/view/CAPWAP:Main), but I've never tried it
before too. BTW I really appreciate if you update me with your future
experience in this field. Please keep in mind that Mininet-WiFi relies in
mac80211_hwsim to create/virtualize wireless interfaces and hostapd to
virtualize Access Points. I know that hostapd works with Radius server and
any solution in this direction should work.

Regards,
Ramon

2017-03-24 12:49 GMT-03:00 floppydrive6 <notifications@github.com>:

**Comment by floppydrive6** [comment]
Hello Ramon,
Thanks for answer. I think that it will be possible to realize using CAPWAP or NETCONF, but do virtual APs emulated using Mininet-WiFi (as they are right now) support these protocols? I am asking because I do not know where could I change it. I know that they are virtualized using hostapd but I have no idea how can it be done. I have read somewhere that it is required to create an IPC between controller and APs but as You know I do not know if I have to change the source-code of Mininet-WiFi on my own (and I also do not what where there change should be) or just controller (ex. POX). I suppose that OpenFlow protocol does not send a information about current power level from AP to POX. Have you got an idea how can it be done?
Regards,
Greg

**Comment by ramonfontes** [comment]
Hello Greg,

I think so. You can try both and see what happen. The manual of
Mininet-WiFi should help you to comprehend how it works and I don't believe
that changes in the source code is required. I'm here to help you if you
need anyway. In my opinion you have to understand how CAPWAP works and how
it manages the AP firstly.

2017-03-25 10:41 GMT-03:00 floppydrive6 <notifications@github.com>:

**Comment by floppydrive6** [comment]
Hi Ramon,
I installed OpenDayLight controller with CAPWAP plugin and ran: sudo mn --controller=remote. Mininet-WiFi connected to that controller (my controller ran at: 127.0.0.1:6633) and all flows were available in controller.  According to instruction available here: https://wiki.opendaylight.org/view/CAPWAP:Lithium:Developer_Guide under "Discovered WTPs" header I tried to find out available APs which I can configure, but ODL displayed only ac-root controller, there were no emulated APs found. Have you got any idea how can I configure parameters like channel, power level etc. using CAPWAP? (I want to set this parameters using remote CAPWAP controller.) Because I am afraid that this feature is not supported by Mininet-WiFi. I know that via hostapd it is possible to configure CAPWAP-client and then you have to enter CAPWAP controller ip-address and it should work.
Regards,
Greg

**Comment by ramonfontes** [comment]
Hi Greg,

I have no idea. Not yet. Did you get it via hostapd? How? I can replicate
the same setup here and improve Mininet-WiFi in order to support capwap if
necessary.

2017-04-04 7:27 GMT-03:00 floppydrive6 <notifications@github.com>:

**Comment by ramonfontes** [comment]
I just found it when googling:
https://github.com/iosifpeterfi/openCAPWAP-OpenWRT/blob/master/hostapd_wrapper/hostapd.conf-ac#L26
Did you use something like that?

2017-04-04 8:47 GMT-03:00 Ramon Fontes <ramonreisfontes@gmail.com>:

**Comment by floppydrive6** [comment]
Hi Ramon,
At this time I have no idea how it can be done, but I have found something like this: https://github.com/iosifpeterfi/openCAPWAP-OpenWRT (and https://github.com/carosio/meta-caros/blob/master/recipes-connectivity/hostapd/hostapd-capwap-ac-1.1/hostapd-capwap.patch) and I suppose it could help. I did not tried it yet.
Regards,
Greg

**Comment by ramonfontes** [comment]
Ok. Let's try to make it work. Tomorrow I'll try to compile hostapd in
order to provide support to capwap according those references. Please let
me know if you have any progress.

2017-04-04 9:14 GMT-03:00 floppydrive6 <notifications@github.com>:

**Comment by ramonfontes** [comment]
Dear Greg,

I found some material that might help you:

(i) http://www.altencalsoftlabs.com/resource-center/whitepapers/vWLC.pdf -
It seems to be proprietary, but take a look on page 4.
(ii)
https://github.com/zqqiang/node-capwap/blob/71cc774f1a8e0940ca703f08c29b7e656a8fa3d4/doc/diagram.md
(iii) https://github.com/ahmedshabib/opencapwap_hostapd_wrapper, specially
https://github.com/ahmedshabib/opencapwap_hostapd_wrapper/blob/master/AC/hostapd/hostapd.conf.
Please note that config file loads the capwap driver.

I really enjoyed the last one. Although it requires some modification in
order to talk with the new hostapd, in my opinion it's feasible.

2017-04-04 10:07 GMT-03:00 Ramon Fontes <ramonreisfontes@gmail.com>:

**Comment by ramonfontes** [comment]
https://github.com/vollero/openCAPWAP/tree/elena.ago

2017-04-04 20:00 GMT-03:00 Ramon Fontes <ramonreisfontes@gmail.com>:

**Comment by ramonfontes** [comment]
Still a first release: https://github.com/ramonfontes/opencapwap-mininet-wifi

**Comment by ramonfontes** [comment]
It's been over a month with no new data, so I'm going to close this. Feel free to reopen if there's new info.
