### ISSUE TITLE
How to put a car in ad hoc mode?

### ISSUE THREAD

**Issue by agawande** [intrig-unicamp/mininet-wifi#59]
Hi
Can you please tell how to put cars in adhoc mode.
I see that in the adhoc example station can be put in adhoc mode.

A car is connected to a station - you can get the station object from the car but cannot use addHoc method on it:
Traceback (most recent call last):
  File "vanet.py", line 114, in <module>
    topology()
  File "vanet.py", line 46, in topology
    net.addHoc(sta, ssid='adhocNet', mode='g')
  File "/usr/local/lib/python2.7/dist-packages/mininet-2.0.post2-py2.7.egg/mininet/net.py", line 755, in addHoc
    sta.func[wlan] = 'adhoc'
IndexError: list assignment index out of range

(After adding cars in the vanet.py, I get the car's station and try pass it in addHoc)

Thanks
Ashlesh

**Comment by ramonfontes** [comment]
Unfortunately you cannot do that by script, but you can change the code of
Mininet-WiFi if you want (
https://github.com/intrig-unicamp/mininet-wifi/blob/master/mininet/net.py#L975
).

2017-03-25 16:04 GMT-03:00 Ashlesh Gawande <notifications@github.com>:

**Comment by ramonfontes** [comment]
It's been over a month with no new data, so I'm going to close this. Feel free to reopen if there's new info.
