### ISSUE TITLE
A question about the ac parameter in net.startMobility

### ISSUE THREAD

**Issue by wucanrui** [intrig-unicamp/mininet-wifi#64]
Hi. 
In the function net.startMobilty, there are only two available value("ssf","llf") for the ac parameter.
Can I add my custom mechanism by adding some code in /mininet/wifiAssociationControl.py ?
Should I remake the project when I change the Source code?
Could you give me some guide? Thank you in advance.

**Comment by ramonfontes** [comment]
Hi,

Yes, of course. You can do that and any pull request is welcome.

**Comment by wucanrui** [comment]
Thank you.
