### ISSUE TITLE
All *.txt and *.conf files are deleted from current directory

### ISSUE THREAD

**Issue by haakjes** [intrig-unicamp/mininet-wifi#7]
Mininet-wifi deletes all *.txt and *.conf files from the current directory. This is implemented in mininet/wifiModule.py:

```python
    @classmethod
    def stop(self):
        """ Stop wireless Module """
        if glob.glob("*.conf"):
            os.system('rm *.conf')

        if glob.glob("*.txt"):
            os.system('rm *.txt')
```

**Comment by ramonfontes** [comment]
Hi,

It creates a conf file in https://github.com/intrig-unicamp/mininet-wifi/blob/master/mininet/wifiAccessPoint.py. but I will change it right now. Thank you for alerting me.

**Comment by ramonfontes** [comment]
Fixed! Now it deletes *.apconf files. ;)
