### ISSUE TITLE
The user manual seems outdated.

### ISSUE THREAD

**Issue by garylavayou** [intrig-unicamp/mininet-wifi#93]
When I follows the tutorial (in Section 5.5.10), I find some API cannot be resolved. For example, 
`mininet-wifi> ap1.range`
`bash: .range: command not found`
According to description of APIs (see Section 1.6.3), the right form should be
`mininet-wifi> py ap1.params['range']`

Furthermore, there is a typo error of the code example (in Section 5.5.11), _i.e._,
`sta1.moveAssociationTo('sta1-wlan0', 'ap1')`,
which should be
`sta1.moveAssociationTo('sta1-wlan0', ap1)`,
since the second argument _ap1_ is an objec of AP, not a string (see Section 1.6.5).

So, I think the user manual is outdated, and should be updated.

**Comment by ramonfontes** [comment]
Fixed! Thanks a lot!

**Comment by garylavayou** [comment]
@ramonfontes Thanks for your work!

I still find another problem, which confuses me a lot. I have followed the example _position-test.py_, and run it on my computer (Ubuntu 16.04 virtual machine).
`gary@NetworkSimulator:~/mnwifi-project$ sudo python position_test.py `
and the simulation is up.
Then I try to use the command _moveNodeTo_, however, it dose not work. The CLI gives the following mistake.
```
mininet-wifi> py sta1.moveNodeTo('40,20,0')
'Station' object has no attribute 'moveNodeTo'
```
I could not figure out why this would happen.

Note: I install the Mininet-WiFi with **-Wnfvl** option as the manual specifies. I doubt if I have some component missing.

**Comment by ramonfontes** [comment]
Try setPosition, instead.

**Comment by garylavayou** [comment]
@ramonfontes Thanks a lot and _setPosition_ will work properly. So, is _moveNodeTo_  a deprecated Method?

**Comment by ramonfontes** [comment]
Yes. I am going to udpate the manual.
