### ISSUE TITLE
A couple of issues

### ISSUE THREAD

**Issue by frencos** [intrig-unicamp/mininet-wifi#98]
Hi.
I am a student that recently started  to work with mininet-wifi. While i was working in the tutorial i found a couple of problems. If this is not the place for this questions just tell me.
1-My main interest is develop some networks to make test on them but i can't find the examples of which the tutorial speaks:
wifiMobilityModel.py at the point 5.5.4
2AccessPoints.py 5.6.1 at the point 5.5.4
wifiAssociationControl.py 5.6.1 at the point 5.5.4

2-At the point 5.5.4 when i try to run the code of position-test.py i get this error (https://gyazo.com/be86d039f8b0a62233b670034c133c87). Is it a problem with the instalation?

Thank you and sorry for my English (it has been a while)

**Comment by chesteve** [comment]
I suggest you place these type of questions to the open mailing list :
mininet-wifi-discuss@googlegroups.com

**Comment by ramonfontes** [comment]
2017-07-18 13:44 GMT-03:00 frencos <notifications@github.com>:

> Hi.
> I am a student that recently started to work with mininet-wifi. While i
> was working in the tutorial i found a couple of problems. If this is not
> the place for this questions just tell me.
> 1-My main interest is develop some networks to make test on them but i
> can't find the examples of which the tutorial speaks:
> wifiMobilityModel.py at the point 5.5.4
>
Try mobilityModel.py

> 2AccessPoints.py 5.6.1 at the point 5.5.4
>
This file isn't available anymore.

> wifiAssociationControl.py 5.6.1 at the point 5.5.4
>
Try associationControl.py

> 2-At the point 5.5.4 when i try to run the code of position-test.py i get
> this error (https://gyazo.com/be86d039f8b0a62233b670034c133c87). Is it a
> problem with the instalation?
>
sudo mn -c should solve the problem
