### ISSUE TITLE
Rate of TP-Link TLWR740N

### ISSUE THREAD

**Issue by floppydrive6** [intrig-unicamp/mininet-wifi#99]
Hi, I've found out, that rate of AP mentioned in title could not be good, idk if 130 - 100, 54 - 43 etc. is okay. According to specification: http://www.tp-link.com.au/products/details/TL-WR740N.html#specifications I am not sure if it should be decreased by these values.
Could you explain me why it is like that?
I have noticed that when I tried different APs in my topos (all in mode "n") and I have much lower rate with TP-Link TLWR740N in comparison to ex. CISCO WRT120N
Regards,
Grzegorz

PS:
below code from repo (mininet/wifiDevices.py)

https://github.com/ramonfontes/mininet-wifi/blob/master/mininet/wifiDevices.py#L108-L144

**Comment by ramonfontes** [comment]
Hi,

That was an error and it's [fixed](https://github.com/intrig-unicamp/mininet-wifi/commit/b9328b5bf6942b0dacf430ec49413891a253bc8c) now.

Thank you!

**Comment by floppydrive6** [comment]
Hi,
I have got one more question.
Is method sta.moveNodeTo() supported in current release?
I am asking because I clone my repo about 7th September and when I want to
run: `py sta1.moveNodeTo('x,y,0') I get: 'Station' object has no attribute
'moveNodeTo'
Regards,
Grzegorz

**Comment by ramonfontes** [comment]
Hi,

Try setPosition() instead.

**Comment by floppydrive6** [comment]
Hi,
Thanks a lot! setPosition() works!
Regards,
Grzegorz
